schema = 1
source_hash = "sha256:6f3f35cc5fa58404f397a65dc65c690dd3c2ccfe516b476beddc74616d24e7b1"
spec_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:edef1d1b3964495faec3766f68bf436301a1b5eb71e68dea14b29a647cf99689"

[[file]]
path = "LICENSE.md"
sha256 = "c0e2a0382616f6ad368f3d15845916310a4a3113802df74a759d41b9d914e1be"
disposition = "copied"
source = "LICENSE.md"

[[file]]
path = "README.xml"
sha256 = "40dad59173f7453821ddd845643b537d65375c2f13c145352e7a5dd81bff1786"
disposition = "converted"
source = "README.md"

[[file]]
path = "vibe.toml"
sha256 = "6f873587fb9958e0fc57257cbd61da6b1ae5c699e6759695b56c734715654b46"
disposition = "copied"
source = "vibe.toml"

[[file]]
path = "vibevm/vibespecs/book/README.xml"
sha256 = "ec7ac7e9187c981ed0ce6cff23e75420c8880517566b2fc4a327099f659c3118"
disposition = "converted"
source = "vibevm/vibespecs/book/README.md"

[[file]]
path = "vibevm/vibespecs/book/ru/chapter-1-two-process-model.xml"
sha256 = "ac40a50cf75a12ba6e14fa490806eaebf7d733f4b2af3c4496f7935bcb9a50ba"
disposition = "copied"
source = "vibevm/vibespecs/book/ru/chapter-1-two-process-model.xml"

[[file]]
path = "vibevm/vibespecs/book/ru/chapter-2-shared-state-and-files.xml"
sha256 = "239c993d26f920f3e3d2a2ffe7e9d5d3129ecf210b495d893f7c7ed1dc1819f0"
disposition = "copied"
source = "vibevm/vibespecs/book/ru/chapter-2-shared-state-and-files.xml"

[[file]]
path = "vibevm/vibespecs/book/ru/chapter-3-memory-individual.xml"
sha256 = "2d2fbb2b1ac0c7b2e683818119aa7176146b3ba5a8d3aa05176995f658172da2"
disposition = "copied"
source = "vibevm/vibespecs/book/ru/chapter-3-memory-individual.xml"

[[file]]
path = "vibevm/vibespecs/boot/03-flow-redbook.xml"
sha256 = "571f075b92bb5a987e0d769a2da4c53c0bf4e243fc95521b5d076e21dde91da6"
disposition = "copied"
source = "vibevm/vibespecs/boot/03-flow-redbook.xml"

[[file]]
path = "vibevm/vibespecs/boot/03a-member-wal.xml"
sha256 = "ed3502e7d2b564c6ae0dc1350adcf2140d129cc87e709b77a5a1377b14b842b2"
disposition = "copied"
source = "vibevm/vibespecs/boot/03a-member-wal.xml"

[[file]]
path = "vibevm/vibespecs/boot/03b-member-wal-specspaces.xml"
sha256 = "b97c57008834bb5152f4d5a5c31a90dd86f802d666fbdb92f6d9d38466027175"
disposition = "copied"
source = "vibevm/vibespecs/boot/03b-member-wal-specspaces.xml"
