# post-compact-reorient.ps1 — SessionStart hook (matchers: compact, resume).
# Everything this script prints to stdout is injected into the model's context
# right after a compaction or a resume. Two halves: the standing re-read order,
# and live empirical state so "what is done" is derived from the tree, never
# from the compaction summary. ASCII only: PowerShell 5.1 reads BOM-less
# scripts as ANSI, so non-ASCII literals here would arrive mangled.
$ErrorActionPreference = 'SilentlyContinue'
# UTF-8 stdout MUST be set before the first write: PowerShell creates the
# stdout writer lazily at the first output and never recreates it, so a
# later assignment cannot fix mojibake (met live 2026-08-20).
[Console]::OutputEncoding = New-Object System.Text.UTF8Encoding($false)
$repo = $env:CLAUDE_PROJECT_DIR
if (-not $repo) { $repo = 'C:\Users\olegc\git\v\vibevm' }

Write-Output '=== POST-COMPACT / RESUME REORIENTATION (standing project rule) ==='
Write-Output 'The context was just compacted or resumed. Authority order is unchanged:'
Write-Output 'files and commands > the compaction summary. The summary has WAL-level'
Write-Output 'authority - dead last; re-derive state empirically before acting on it.'
Write-Output ''
Write-Output 'Re-read, in this order, before continuing ANY work:'
Write-Output '  1. NEXT-SESSION-PROMPT.md            (the owner''s word for this run)'
Write-Output '  2. campaigns/packages-2026-09/TZ-RELEASE-1.0-v0.1.md'
Write-Output '     - the _STATUS: line, the current slice, and section 10 BLOCKERS'
Write-Output '  3. TASKS.md                          (current-slice checkboxes)'
Write-Output '  4. spec/WAL.md                       (Constraints section, verbatim)'
Write-Output 'If any standing rule feels uncertain after the summary, re-read the boot'
Write-Output 'lane per CLAUDE.md (the generated STATIC lane in spec/boot/, then spec/boot/INDEX.md files).'
Write-Output ''
Write-Output '=== LIVE STATE (generated by the hook, trust this over memory) ==='
Write-Output '--- interaction mode (AGENT-MODE.toml, owner switch - OBEY IT) ---'
# auto = minimum user-facing text (telegraph progress; floor: blockers,
# owner forks, direct answers). collab = normal explanations. Subagents
# are ALWAYS quiet regardless (##subagent-quiet-clause).
$modeFile = Join-Path $repo 'AGENT-MODE.toml'
if (Test-Path $modeFile) {
  Get-Content -Encoding UTF8 $modeFile | Where-Object { $_ -match '^mode' } | Select-Object -First 1
} else {
  Write-Output '(AGENT-MODE.toml not found - default collab)'
}
Write-Output '--- git status --short (first 40 lines) ---'
git -C $repo status --short | Select-Object -First 40
Write-Output '--- last 5 commits ---'
git -C $repo log --oneline -5
Write-Output '--- release-plan status line ---'
# Read with explicit UTF8: PS 5.1 otherwise decodes the BOM-less file as ANSI.
$tz = Join-Path $repo 'campaigns\packages-2026-09\TZ-RELEASE-1.0-v0.1.md'
if (Test-Path $tz) {
  Get-Content -Encoding UTF8 $tz | Where-Object { $_ -like '_STATUS:*' } | Select-Object -First 1
} else {
  Write-Output '(release plan file not found - pre-release session)'
}
Write-Output '--- git worktrees (live workers?) ---'
git -C $repo worktree list
Write-Output '--- background check ---'
Write-Output 'Also check for live delegated workers before spawning new ones.'
exit 0
