use super::*;

#[test]
fn native_source_build_precedes_authored_target_and_phase_native_dispatch() {
    let dir = manifested(
        r#"
[project]
name = "demo"
version = "0.1.0"

[[extension]]
id = "phase-native"
point = "phase:build"
handler = { kind = "native", crate_dir = "native" }

[[extension]]
id = "compile-native"
point = "compile:source"
handler = { kind = "native", crate_dir = "native" }
applies_to = { paths = ["never/**"] }

[[artifacts.build]]
id = "observer-build"
mechanism = "build:cargo"
workdir = "observer"
outputs = [{ id = "observer", kind = "executable" }]
"#,
    );
    let vibe_ext = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .join("vibe-ext")
        .display()
        .to_string()
        .replace('\\', "/");
    std::fs::create_dir_all(dir.path().join("native/src")).unwrap();
    std::fs::write(
        dir.path().join("native/Cargo.toml"),
        format!(
            "[package]\nname='phase-native'\nversion='0.1.0'\nedition='2024'\n\n[lib]\ncrate-type=['cdylib']\n\n[dependencies]\nvibe-ext={{path={vibe_ext:?}}}\n"
        ),
    )
    .unwrap();
    std::fs::write(
        dir.path().join("native/src/lib.rs"),
        r#"
use vibe_ext::{Context, Manifest, ManifestExtension, Reply, ReplyStatus};

fn handle(_context: Context) -> Reply {
    Reply {
        artifacts: Vec::new(),
        envelope: 1,
        status: ReplyStatus::Ok,
        message: Some("phase native ran".to_owned()),
    }
}

vibe_ext::vibe_extension!(
    manifest = Manifest {
        extensions: vec![ManifestExtension {
            id: "phase-native".to_owned(),
            point: "phase:build".to_owned(),
            ir_schema: None,
        }, ManifestExtension {
            id: "compile-native".to_owned(),
            point: "compile:source".to_owned(),
            ir_schema: None,
        }],
    },
    handler = handle,
);
"#,
    )
    .unwrap();

    std::fs::create_dir_all(dir.path().join("observer/src")).unwrap();
    std::fs::write(
        dir.path().join("observer/Cargo.toml"),
        "[package]\nname='observer'\nversion='0.1.0'\nedition='2024'\nbuild='build.rs'\n",
    )
    .unwrap();
    std::fs::write(
        dir.path().join("observer/Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"observer\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    std::fs::write(
        dir.path().join("observer/build.rs"),
        r#"
fn main() {
    let records = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap().join(".vibe/state/artifacts");
    let native_record_exists = std::fs::read_dir(&records)
        .ok()
        .into_iter()
        .flatten()
        .filter_map(Result::ok)
        .any(|entry| entry.path().extension().and_then(|ext| ext.to_str()) == Some("json"));
    assert!(native_record_exists, "native record must predate authored targets");
}
"#,
    )
    .unwrap();
    std::fs::write(dir.path().join("observer/src/main.rs"), "fn main() {}\n").unwrap();

    let outcome = run_phases_over(dir.path(), vec![Phase::Build]);
    let values = match outcome {
        PhaseOutcome::Completed(values) => values,
        other => {
            panic!("native build, authored target, and phase row complete in order: {other:?}")
        }
    };
    let native = values
        .contributions
        .iter()
        .find(|row| row.key.ends_with("#phase-native"))
        .expect("the phase-native row dispatched");
    assert_eq!(native.handler, "native");
    assert_eq!(native.status, "ok");
    assert_eq!(native.message.as_deref(), Some("phase native ran"));
    assert!(
        values
            .contributions
            .iter()
            .all(|row| !row.key.ends_with("#compile-native")),
        "compile-native is a build candidate, never a lifecycle execution",
    );
    assert!(
        dir.path()
            .join(".vibe/state/artifacts/observer.json")
            .is_file(),
        "the authored target ran after observing the native record",
    );
}
