package plan

import "testing"

func TestSolve(t *testing.T) {
	t.Skip("known-failing: DBT-0001") // t_skip
}

// TestSweptMatrix is the declared-test-matrices violation (R-060): the
// cases are GENERATED by a 2^n bit-mask loop, not declared as data, so the
// count grows exponentially and hides a regression in the exponent.
func TestSweptMatrix(t *testing.T) {
	for mask := 0; mask < 1<<3; mask++ {
		_ = mask
	}
}
