schema = 1
source_hash = "sha256:6e960aff00f09609a5b275896f905734eb75058d02136b8c55b9b53808d8d6d6"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:9002c7733a8e13d4dcefa6fc1589b96c2ee42b22359c285f3ff17ccc21b86050"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/45-flow-operating-modes.xml"
output = "spec/boot/45-flow-operating-modes.xml"
disposition = "copied"

[[file]]
source = "spec/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
output = "spec/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
disposition = "copied"

[[file]]
source = "spec/flows/operating-modes/mfbt-mode.xml"
output = "spec/flows/operating-modes/mfbt-mode.xml"
disposition = "copied"

[[file]]
source = "spec/flows/operating-modes/writing-a-codeword.xml"
output = "spec/flows/operating-modes/writing-a-codeword.xml"
disposition = "copied"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
