schema = 1
source_hash = "sha256:122377e279131cab995d56735821fed44311773ff82caa872e8c562044aa3491"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:c3d0eb969f5bc2937f4e8045d5caacfe25704f455633eb9c40074620bffa1948"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/45-flow-operating-modes.xml"
output = "spec/boot/45-flow-operating-modes.xml"
disposition = "copied"

[[file]]
source = "spec/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
output = "spec/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
disposition = "copied"

[[file]]
source = "spec/flows/operating-modes/mfbt-mode.xml"
output = "spec/flows/operating-modes/mfbt-mode.xml"
disposition = "copied"

[[file]]
source = "spec/flows/operating-modes/writing-a-codeword.xml"
output = "spec/flows/operating-modes/writing-a-codeword.xml"
disposition = "copied"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
