schema = 1
source_hash = "sha256:b5af9daa01ec5a7f351c4079be3d3d3c131d36e3bccb2fe672648fdeeafec9a2"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:017ffb0a4a145a9108869b01ce32caa9a57dce44c4b27102e0345de22e3af38a"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/45-flow-operating-modes.md"
output = "spec/boot/45-flow-operating-modes.xml"
disposition = "converted"

[[file]]
source = "spec/flows/operating-modes/OPERATING-MODES-PROTOCOL.md"
output = "spec/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
disposition = "converted"

[[file]]
source = "spec/flows/operating-modes/mfbt-mode.md"
output = "spec/flows/operating-modes/mfbt-mode.xml"
disposition = "converted"

[[file]]
source = "spec/flows/operating-modes/writing-a-codeword.md"
output = "spec/flows/operating-modes/writing-a-codeword.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
