//! Building a documentation package — one walk, every artefact
//! (PROP-057 `##PIPE-LIBRARY`, `##SITE-MOUNT`).
//!
//! What a build produces is the whole machine-facing surface of a
//! package: a page in the projection the caller asked for, the page
//! manifest, the four `llms` tiers, the card's images copied under
//! content names and the placeholders generated for the roles that
//! declared none. Every one of them is a fold over the SAME page set and
//! the same resolved content, because a second walk would be a second
//! answer and nothing would say which one the reader got.
//!
//! ## The layout is the site's address map, not a choice
//!
//! `##SITE-MOUNT` fixes where a page lives —
//! `<group>/<name>/<version>/<document>/` with a trailing slash, the
//! projections beside it as files — so a build writes that tree and a
//! local reader serves the same shapes from the same function. The one
//! thing a caller supplies is the BASE it will be served under: the
//! public site mounts at `/doc/`, a reader on the loopback mounts where
//! it likes, and a translation's site adds a language segment
//! (`/doc/ru/`) that belongs to the site's route table and not to any
//! package.
//!
//! ## What a build does NOT do
//!
//! It calls no clock — both instants arrive in [`manifest::Options`] — and
//! it runs no product of its own accord. `derived` text is generated by
//! [`crate::derived`] and handed in, so a build from a warmed store on a
//! machine that has never compiled anything still produces every page,
//! with the generated blocks marked as the gaps they are rather than
//! silently empty.

specmark::scope!("spec://org.vibevm.core/vibevm/common/PROP-057#PIPE-LIBRARY");

use std::collections::BTreeMap;
use std::path::Path;

use crate::citations::{self, SpecSources};
use crate::content::Content;
use crate::error::{DocError, Result};
use crate::numbering::{expand_derived, number_blocks};
use crate::pages::{self, Page, PageSet};
use crate::{html, llms, manifest, md, media, xml};

/// Which projection a build writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Format {
    /// The island: a page's content as finished HTML, with no script, no
    /// style and no page furniture (`##PIPE-SHELL-PARSES-NOTHING`).
    #[default]
    Html,
    /// The Markdown projection — what an agent reads.
    Md,
    /// The dialect XML projection, which keeps a citation's ADDRESS
    /// rather than substituting its text.
    Xml,
}

impl Format {
    /// The word a flag spells.
    pub fn as_str(self) -> &'static str {
        match self {
            Format::Html => "html",
            Format::Md => "md",
            Format::Xml => "xml",
        }
    }

    /// Parse a flag's value.
    pub fn parse(text: &str) -> Option<Format> {
        match text {
            "html" => Some(Format::Html),
            "md" => Some(Format::Md),
            "xml" => Some(Format::Xml),
            _ => None,
        }
    }
}

/// What a build needs that the package cannot say.
#[derive(Debug, Clone)]
pub struct Options {
    pub format: Format,
    /// The path the result will be served under (`/doc/` on the site).
    pub base: String,
    /// The two instants a manifest carries.
    pub manifest: manifest::Options,
    /// Generated `derived` text by `<kind>:<reference>`, from
    /// [`crate::derived::generate`]. Empty is legal and honest: the
    /// blocks render as marked gaps rather than as nothing.
    pub derived: BTreeMap<String, String>,
}

/// One file a build produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BuiltFile {
    /// Where it goes, relative to the output root, `/`-separated.
    pub path: String,
    pub bytes: Vec<u8>,
}

/// Everything one build produced.
#[derive(Debug, Clone, Default)]
pub struct Built {
    pub files: Vec<BuiltFile>,
    /// Pages the pivot refused, named rather than silently missing.
    pub unreadable: Vec<String>,
    /// The card roles whose picture was generated rather than copied.
    pub generated_roles: Vec<String>,
}

impl Built {
    /// The human form.
    pub fn render(&self) -> String {
        let mut out = String::new();
        for page in &self.unreadable {
            out.push_str(&format!("  unreadable {page}\n"));
        }
        let bytes: usize = self.files.iter().map(|f| f.bytes.len()).sum();
        out.push_str(&format!(
            "build: {} file(s), {bytes} byte(s), {} placeholder(s) generated ({}), \
             {} unreadable page(s)\n",
            self.files.len(),
            self.generated_roles.len(),
            if self.generated_roles.is_empty() {
                "none".to_string()
            } else {
                self.generated_roles.join(", ")
            },
            self.unreadable.len()
        ));
        out
    }
}

/// Read the package and resolve everything its pages point at.
///
/// This is the one walk. A caller that needs the pages AND the content —
/// every caller — gets both from here rather than reading the tree twice.
pub fn content(
    package_dir: &Path,
    sources: &SpecSources,
    base: &str,
    derived: BTreeMap<String, String>,
) -> Result<(PageSet, Content)> {
    let set = pages::read_package(package_dir)?;
    let content = Content {
        rules: citations::resolve_rules(&set, sources),
        derived,
        examples: BTreeMap::new(),
        base: base.to_owned(),
    };
    Ok((set, content))
}

/// Render one page in one projection, with the block numbers every
/// projection shares (R-26).
///
/// The order is the norm's and it is load-bearing: expand `derived`,
/// number what is there, then render. Numbering before expansion would
/// give the web and the local reader different `p12`s for one block.
pub fn render_page(page: &Page, content: &Content, format: Format) -> String {
    let expanded = expand_derived(&page.doc, content);
    let numbering = number_blocks(&expanded);
    match format {
        Format::Html => html::to_html_numbered(&expanded, content, &numbering),
        Format::Md => md::to_markdown_numbered(&expanded, content, &numbering),
        Format::Xml => xml::to_xml_numbered(&expanded, &numbering),
    }
}

/// Where one page is served from, relative to the base
/// (`##SITE-MOUNT`, `##SITE-TRAILING-SLASH`): the HTML lives in a
/// directory that ends in a slash, and the projections lie beside it as
/// files.
pub fn page_path(prefix: &str, page_rel: &str, format: Format) -> String {
    let stem = page_rel.strip_suffix(".xml").unwrap_or(page_rel);
    match format {
        Format::Html => format!("{prefix}{stem}/index.html"),
        Format::Md => format!("{prefix}{stem}.md"),
        Format::Xml => format!("{prefix}{stem}.xml"),
    }
}

/// Build the whole package.
pub fn build(package_dir: &Path, sources: &SpecSources, options: &Options) -> Result<Built> {
    let (set, content) = content(package_dir, sources, &options.base, options.derived.clone())?;
    let built_manifest = manifest::build(package_dir, sources, &options.manifest)?;
    let card = &built_manifest.manifest.package;
    // The package's own segment of the address map. Everything a build
    // writes for THIS package hangs off it; the machine files that
    // describe the whole mount (`manifest.json`, the `llms` tiers) sit at
    // the root beside it.
    let prefix = format!("{}/{}/{}/", card.group.as_str(), card.name, card.version);

    let mut files = Vec::new();
    for page in &set.pages {
        files.push(BuiltFile {
            path: page_path(&prefix, &page.rel, options.format),
            bytes: render_page(page, &content, options.format).into_bytes(),
        });
    }

    files.push(BuiltFile {
        path: "manifest.json".to_string(),
        bytes: manifest::to_json(&built_manifest.manifest).into_bytes(),
    });
    let bodies = llms::bodies(&set, &content);
    for (name, text) in llms::tiers(&built_manifest.manifest, &bodies, &options.base) {
        files.push(BuiltFile {
            path: name.to_string(),
            bytes: text.into_bytes(),
        });
    }

    let coordinate = format!("{}/{}", card.group.as_str(), card.name);
    let kind = vibe_core::PackageKind::Doc;
    let declared = media::declared_media(package_dir)?;
    for (role, path) in &declared {
        let from = package_dir.join(path);
        let bytes = std::fs::read(&from).map_err(|e| DocError::io("reading", &from, e))?;
        files.push(BuiltFile {
            path: format!("media/{}", media::hashed_name(&bytes, path)),
            bytes,
        });
        let _ = role;
    }
    let mut generated_roles = Vec::new();
    for role in media::ROLES {
        if declared.iter().any(|(declared, _)| declared == role) {
            continue;
        }
        generated_roles.push(role.to_string());
        let (extension, bytes) = match role {
            "icon" => ("svg", media::icon_svg(&coordinate, kind).into_bytes()),
            "banner" => ("svg", media::banner_svg(&coordinate, kind).into_bytes()),
            _ => ("png", media::preview_png(&coordinate, kind, &card.title)),
        };
        files.push(BuiltFile {
            path: format!(
                "media/{}",
                media::generated_name(&coordinate, role, extension)
            ),
            bytes,
        });
    }

    Ok(Built {
        files,
        unreadable: set.unreadable.iter().map(|u| u.rel.clone()).collect(),
        generated_roles,
    })
}

/// Write a build under `out_dir`, creating the directories it needs.
pub fn write(built: &Built, out_dir: &Path) -> Result<()> {
    for file in &built.files {
        let path = out_dir.join(&file.path);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| DocError::io("creating", parent, e))?;
        }
        std::fs::write(&path, &file.bytes).map_err(|e| DocError::io("writing", &path, e))?;
    }
    Ok(())
}

/// Refuse a package that is not written in `lang`.
///
/// One package is one language (`##LOC-LANGUAGE-FIELD`), so `--lang` is
/// not a switch inside a build: it is the caller stating which language
/// it wants, and the answer is either this package or the adaptation
/// published beside it under the naming convention
/// (`##LOC-OFFICIAL-TRANSLATION`). Naming that coordinate in the refusal
/// is the whole value of the flag — a silent build of the wrong language
/// is a site page in a language nobody asked for.
pub fn expect_language(package_dir: &Path, lang: &str) -> Result<()> {
    let path = package_dir.join("vibe.toml");
    let text = std::fs::read_to_string(&path).map_err(|e| DocError::io("reading", &path, e))?;
    let value: toml::Value = toml::from_str(&text)
        .map_err(|e| DocError::manifest(&path, format!("is not readable as TOML: {e}")))?;
    let canonical = value
        .get("i18n")
        .and_then(|t| t.get("canonical"))
        .and_then(toml::Value::as_str)
        .unwrap_or(vibe_core::manifest::i18n::DEFAULT_CANONICAL_LANGUAGE);
    if canonical == lang {
        return Ok(());
    }
    let name = value
        .get("package")
        .and_then(|t| t.get("name"))
        .and_then(toml::Value::as_str)
        .unwrap_or("<name>");
    Err(DocError::manifest(
        &path,
        format!(
            "is written in `{canonical}`, and `--lang {lang}` was asked for — one documentation \
             package is one language, so the `{lang}` text is a package of its own, published \
             beside this one as `{name}-{lang}`"
        ),
    ))
}

#[cfg(test)]
mod tests;
