//! Building a documentation package — one walk, every artefact
//! (PROP-057 `##PIPE-LIBRARY`, `##SITE-MOUNT`).
//!
//! What a build produces is the whole machine-facing surface of a
//! package: a page in the projection the caller asked for, the page
//! manifest, the four `llms` tiers, the card's images copied under
//! content names and the placeholders generated for the roles that
//! declared none. Every one of them is a fold over the SAME page set and
//! the same resolved content, because a second walk would be a second
//! answer and nothing would say which one the reader got.
//!
//! ## The layout is the site's address map, not a choice
//!
//! `##SITE-MOUNT` fixes where a page lives —
//! `<group>/<name>/<version>/<document>/` with a trailing slash, the
//! projections beside it as files — so a build writes that tree and a
//! local reader serves the same shapes from the same function. The one
//! thing a caller supplies is the BASE it will be served under: the
//! public site mounts at `/doc/`, a reader on the loopback mounts where
//! it likes, and a translation's site adds a language segment
//! (`/doc/ru/`) that belongs to the site's route table and not to any
//! package.
//!
//! ## What a build does NOT do
//!
//! It calls no clock — both instants arrive in [`manifest::Options`] — and
//! it runs no product of its own accord. `derived` text is generated by
//! [`crate::derived`] and handed in, so a build from a warmed store on a
//! machine that has never compiled anything still produces every page,
//! with the generated blocks marked as the gaps they are rather than
//! silently empty.
//!
//! What it does do is COUNT those gaps and say the number ([`gaps`]). A
//! build that leaves half its examples unfilled and reports the same
//! summary as one with every input in hand is a build whose report cannot
//! be read, and the count costs one line.

specmark::scope!("spec://org.vibevm.core/vibevm/common/PROP-057#PIPE-LIBRARY");

pub mod gaps;

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
use vibe_core::progress::Progress;

use crate::citations::{self, SpecSources};
use crate::content::Content;
use crate::error::{DocError, Result};
use crate::numbering::{expand_derived, number_blocks};
use crate::pages::{self, Page, PageSet};
use crate::{html, llms, manifest, md, media, translations, xml};

pub use gaps::{Unresolved, unresolved};

/// Which projection a build writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum Format {
    /// The island: a page's content as finished HTML, with no script, no
    /// style and no page furniture (`##PIPE-SHELL-PARSES-NOTHING`).
    #[default]
    Html,
    /// The Markdown projection — what an agent reads.
    Md,
    /// The dialect XML projection, which keeps a citation's ADDRESS
    /// rather than substituting its text.
    Xml,
}

impl Format {
    /// The word a flag spells.
    pub fn as_str(self) -> &'static str {
        match self {
            Format::Html => "html",
            Format::Md => "md",
            Format::Xml => "xml",
        }
    }

    /// Parse a flag's value.
    pub fn parse(text: &str) -> Option<Format> {
        match text {
            "html" => Some(Format::Html),
            "md" => Some(Format::Md),
            "xml" => Some(Format::Xml),
            _ => None,
        }
    }
}

/// What a build needs that the package cannot say.
#[derive(Debug, Clone)]
pub struct Options {
    pub format: Format,
    /// The path the result will be served under (`/doc/` on the site).
    pub base: String,
    /// The two instants a manifest carries.
    pub manifest: manifest::Options,
    /// Generated `derived` text by `<kind>:<reference>`, from
    /// [`crate::derived::generate`]. Empty is legal and honest: the
    /// blocks render as marked gaps rather than as nothing.
    pub derived: BTreeMap<String, String>,
}

/// One file a build produced.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct BuiltFile {
    /// Where it goes, relative to the output root, `/`-separated.
    pub path: String,
    pub bytes: Vec<u8>,
}

/// Everything one build produced.
#[derive(Debug, Clone, Default)]
pub struct Built {
    pub files: Vec<BuiltFile>,
    /// Pages the pivot refused, named rather than silently missing.
    pub unreadable: Vec<String>,
    /// The card roles whose picture was generated rather than copied.
    pub generated_roles: Vec<String>,
    /// The blocks this build rendered as marked gaps, summed over its
    /// pages ([`gaps`]). A measurement and not a verdict: it changes no
    /// exit code, and it is here so that a build which fetched nothing
    /// cannot look like a build which needed nothing.
    pub unresolved: Unresolved,
}

/// What changed on disk when a complete logical build was reconciled with its
/// prior tree. The builder may compute the complete answer, but unchanged
/// files retain their bytes and mtimes and remain reusable by downstream
/// stages.
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq)]
pub struct WriteReport {
    pub written: usize,
    pub unchanged: usize,
    pub removed: usize,
}

impl Built {
    /// The human form.
    ///
    /// The gap census closes the summary line, beside the pages the pivot
    /// refused, because the two answer one question between them: what
    /// this build could not read, and what it read and could not fill.
    pub fn render(&self) -> String {
        let mut out = String::new();
        for page in &self.unreadable {
            out.push_str(&format!("  unreadable {page}\n"));
        }
        let bytes: usize = self.files.iter().map(|f| f.bytes.len()).sum();
        out.push_str(&format!(
            "build: {} file(s), {bytes} byte(s), {} placeholder(s) generated ({}), \
             {} unreadable page(s), {}\n",
            self.files.len(),
            self.generated_roles.len(),
            if self.generated_roles.is_empty() {
                "none".to_string()
            } else {
                self.generated_roles.join(", ")
            },
            self.unreadable.len(),
            self.unresolved.render()
        ));
        out
    }
}

/// Read the package and resolve everything its pages point at.
///
/// This is the one walk. A caller that needs the pages AND the content —
/// every caller — gets both from here rather than reading the tree twice.
pub fn content(
    package_dir: &Path,
    sources: &SpecSources,
    base: &str,
    derived: BTreeMap<String, String>,
) -> Result<(PageSet, Content)> {
    let set = pages::read_package(package_dir)?;
    let content = Content {
        rules: citations::resolve_rules(&set, sources),
        derived,
        // A translation authors no example and borrows every one from the
        // source page at its own address (`##LOC-EXAMPLE-REF`,
        // `##LOC-MIRROR`). A source documentation adapts nothing, so this
        // is empty for it and costs a manifest read.
        examples: translations::borrowed(package_dir, sources),
        base: base.to_owned(),
    };
    Ok((set, content))
}

/// Render one page in one projection, with the block numbers every
/// projection shares (R-26).
///
/// The order is the norm's and it is load-bearing: expand `derived`,
/// number what is there, then render. Numbering before expansion would
/// give the web and the local reader different `p12`s for one block.
///
/// The page's own address travels to the two backends that substitute
/// text, because a borrowed example is addressed as `page#id` and an id
/// alone would resolve against whatever page used it first. The XML
/// projection needs none of it: it keeps `<example ref="…"/>` by its own
/// contract.
pub fn render_page(page: &Page, content: &Content, format: Format) -> String {
    let expanded = expand_derived(&page.doc, content);
    let numbering = number_blocks(&expanded);
    match format {
        Format::Html => html::to_html_numbered(&expanded, &page.rel, content, &numbering),
        Format::Md => md::to_markdown_numbered(&expanded, &page.rel, content, &numbering),
        Format::Xml => xml::to_xml_numbered(&expanded, &numbering),
    }
}

/// Where one page is served from, relative to the base
/// (`##SITE-MOUNT`, `##SITE-TRAILING-SLASH`): the HTML lives in a
/// directory that ends in a slash, and the projections lie beside it as
/// files.
pub fn page_path(prefix: &str, page_rel: &str, format: Format) -> String {
    let stem = page_rel.strip_suffix(".xml").unwrap_or(page_rel);
    match format {
        Format::Html => format!("{prefix}{stem}/index.html"),
        Format::Md => format!("{prefix}{stem}.md"),
        Format::Xml => format!("{prefix}{stem}.xml"),
    }
}

/// Build the whole package.
pub fn build(package_dir: &Path, sources: &SpecSources, options: &Options) -> Result<Built> {
    build_observed(package_dir, sources, options, &Progress::default())
}

/// Build the whole package while reporting its existing page/media walks.
///
/// ```no_run
/// use std::{collections::BTreeMap, path::Path};
/// use vibe_core::progress::Progress;
/// use vibe_doc::{build, citations::SpecSources, manifest};
/// let options = build::Options {
///     format: build::Format::Html,
///     base: "/doc/".into(),
///     manifest: manifest::Options::at(chrono::Utc::now()),
///     derived: BTreeMap::new(),
/// };
/// let _ = build::build_observed(
///     Path::new("documentation"),
///     &SpecSources::new(),
///     &options,
///     &Progress::default(),
/// );
/// ```
pub fn build_observed(
    package_dir: &Path,
    sources: &SpecSources,
    options: &Options,
    progress: &Progress,
) -> Result<Built> {
    let (set, content) = observed(progress, "Reading documentation pages", || {
        content(package_dir, sources, &options.base, options.derived.clone())
    })?;
    let built_manifest = observed(progress, "Building documentation manifest", || {
        manifest::build(package_dir, sources, &options.manifest)
    })?;
    let card = &built_manifest.manifest.package;
    // The package's own segment of the address map. Everything a build
    // writes for THIS package hangs off it; the machine files that
    // describe the whole mount (`manifest.json`, the `llms` tiers) sit at
    // the root beside it.
    let prefix = format!("{}/{}/{}/", card.group.as_str(), card.name, card.version);

    let render = progress.task("Rendering documentation pages");
    render.set_progress(0, Some(set.pages.len() as u64), "pages");
    let mut files = Vec::new();
    // The census is taken page by page beside the render, of the same page
    // and the same bundle: a second walk of the finished bytes would be a
    // second answer, and the projections do not all mark a gap the same
    // way (`gaps::unresolved`).
    let mut unresolved = Unresolved::default();
    for page in &set.pages {
        unresolved += gaps::unresolved(page, &content);
        files.push(BuiltFile {
            path: page_path(&prefix, &page.rel, options.format),
            bytes: render_page(page, &content, options.format).into_bytes(),
        });
        render.set_progress(files.len() as u64, Some(set.pages.len() as u64), "pages");
    }
    render.finish();

    files.push(BuiltFile {
        path: "manifest.json".to_string(),
        bytes: manifest::to_json(&built_manifest.manifest).into_bytes(),
    });
    let bodies = llms::bodies(&set, &content);
    for (name, text) in llms::tiers(&built_manifest.manifest, &bodies, &options.base) {
        files.push(BuiltFile {
            path: name.to_string(),
            bytes: text.into_bytes(),
        });
    }

    // The card's images, at the addresses the MANIFEST already names.
    // One rule, read twice: `media::slots` decides where a picture is
    // served from, the manifest carries that address, and this writes the
    // file there. A build that named its own files would be the second
    // opinion the shell has no way to choose between.
    let coordinate = format!("{}/{}", card.group.as_str(), card.name);
    // The glyph of a generated placeholder is the KIND's
    // (`##CARD-PLACEHOLDERS-GENERATED`), so it is read from the package
    // rather than assumed: a build of a documentation package is the
    // common case and not the only one — the site renders every kind
    // from its own bytes (`##LEVEL-ZERO`), and a `lang` package wearing
    // a book would be a picture that says the wrong thing.
    let kind = declared_kind(package_dir);
    let mut generated_roles = Vec::new();
    let slots = observed(progress, "Reading documentation media", || {
        media::slots(package_dir, &coordinate)
    })?;
    let slot_count = slots.len() as u64;
    let media = progress.task("Rendering documentation media");
    media.set_progress(0, Some(slot_count), "assets");
    for (index, slot) in slots.into_iter().enumerate() {
        if slot.generated() {
            generated_roles.push(slot.role.to_string());
        }
        let bytes = slot.render(&coordinate, kind, &card.title);
        files.push(BuiltFile {
            path: slot.address,
            bytes,
        });
        media.set_progress((index + 1) as u64, Some(slot_count), "assets");
    }
    media.finish();

    Ok(Built {
        files,
        unreadable: set.unreadable.iter().map(|u| u.rel.clone()).collect(),
        generated_roles,
        unresolved,
    })
}

fn observed<T>(progress: &Progress, label: &str, work: impl FnOnce() -> Result<T>) -> Result<T> {
    let task = progress.task(label);
    match work() {
        Ok(value) => {
            task.finish();
            Ok(value)
        }
        Err(error) => {
            task.fail("documentation phase failed");
            Err(error)
        }
    }
}

/// The kind a package declares, or `doc` when it declares none.
///
/// Read as TOML data, and a value the vocabulary does not know reads as
/// the default rather than stopping the build: a picture is not worth a
/// refusal, and the kind is checked where kinds are checked.
fn declared_kind(package_dir: &Path) -> vibe_core::PackageKind {
    let default = vibe_core::PackageKind::Doc;
    let Ok(text) = std::fs::read_to_string(package_dir.join("vibe.toml")) else {
        return default;
    };
    let Ok(value) = toml::from_str::<toml::Value>(&text) else {
        return default;
    };
    value
        .get("package")
        .and_then(|p| p.get("kind"))
        .and_then(toml::Value::as_str)
        .and_then(|word| <vibe_core::PackageKind as std::str::FromStr>::from_str(word).ok())
        .unwrap_or(default)
}

/// Write a build under `out_dir`, creating the directories it needs.
pub fn write(built: &Built, out_dir: &Path) -> Result<()> {
    write_reconciled(built, out_dir).map(|_| ())
}

/// Reconcile a complete build into an owned output tree, writing only new or
/// changed files and removing outputs the new build no longer declares.
pub fn write_reconciled(built: &Built, out_dir: &Path) -> Result<WriteReport> {
    let desired = built
        .files
        .iter()
        .map(|file| file.path.as_str())
        .collect::<BTreeSet<_>>();
    let mut report = WriteReport::default();
    if out_dir.is_dir() {
        let mut stale = Vec::new();
        for entry in walkdir::WalkDir::new(out_dir)
            .into_iter()
            .filter_map(std::result::Result::ok)
            .filter(|entry| entry.file_type().is_file())
        {
            let relative = entry
                .path()
                .strip_prefix(out_dir)
                .unwrap_or(entry.path())
                .to_string_lossy()
                .replace('\\', "/");
            if !desired.contains(relative.as_str()) {
                stale.push(entry.path().to_path_buf());
            }
        }
        for path in stale {
            std::fs::remove_file(&path).map_err(|e| DocError::io("removing", &path, e))?;
            report.removed += 1;
        }
    }
    for file in &built.files {
        let path = out_dir.join(&file.path);
        if std::fs::read(&path).is_ok_and(|prior| prior == file.bytes) {
            report.unchanged += 1;
            continue;
        }
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent).map_err(|e| DocError::io("creating", parent, e))?;
        }
        std::fs::write(&path, &file.bytes).map_err(|e| DocError::io("writing", &path, e))?;
        report.written += 1;
    }
    Ok(report)
}

/// Refuse a package that is not written in `lang`.
///
/// One package is one language (`##LOC-LANGUAGE-FIELD`), so `--lang` is
/// not a switch inside a build: it is the caller stating which language
/// it wants, and the answer is either this package or the adaptation
/// published beside it under the naming convention
/// (`##LOC-OFFICIAL-TRANSLATION`). Naming that coordinate in the refusal
/// is the whole value of the flag — a silent build of the wrong language
/// is a site page in a language nobody asked for.
pub fn expect_language(package_dir: &Path, lang: &str) -> Result<()> {
    let path = package_dir.join("vibe.toml");
    let text = std::fs::read_to_string(&path).map_err(|e| DocError::io("reading", &path, e))?;
    let value: toml::Value = toml::from_str(&text)
        .map_err(|e| DocError::manifest(&path, format!("is not readable as TOML: {e}")))?;
    let canonical = value
        .get("i18n")
        .and_then(|t| t.get("canonical"))
        .and_then(toml::Value::as_str)
        .unwrap_or(vibe_core::manifest::i18n::DEFAULT_CANONICAL_LANGUAGE);
    if canonical == lang {
        return Ok(());
    }
    let name = value
        .get("package")
        .and_then(|t| t.get("name"))
        .and_then(toml::Value::as_str)
        .unwrap_or("<name>");
    Err(DocError::manifest(
        &path,
        format!(
            "is written in `{canonical}`, and `--lang {lang}` was asked for — one documentation \
             package is one language, so the `{lang}` text is a package of its own, published \
             beside this one as `{name}-{lang}`"
        ),
    ))
}

#[cfg(test)]
mod tests;
