//! What the composition root answers for one queued version
//! (PROP-057 `##REL-WARMUP-CLOSURE`, `##PIPE-DERIVED`).
//!
//! The library renders; it does not fetch and it does not run
//! programmes. Both of those need decisions that belong here — which
//! registries this machine reads, where its store is, and whether a
//! product may be run at all for a package the site merely publishes —
//! so both arrive through one seam.
//!
//! ## Warming is `vibe cache add`'s warming, not a second one
//!
//! `##REL-WARMUP-CLOSURE` — warming a documentation package warms its
//! subjects, so its `spec://` citations resolve without the network — is
//! a property of the warm-up and not of the command that usually asks
//! for it. So the builder calls the same function, and a manual whose
//! citations resolve for a reader on the command line resolves for a
//! reader on the site.

specmark::scope!("spec://org.vibevm.core/vibevm/common/PROP-057#REL-WARMUP-CLOSURE");

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use vibe_doc::error::DocError;
use vibe_doc::site::{Origin, Pair, Prepare};

use crate::commands::install::InstallResolver;

/// The composition root of one site build.
pub(crate) struct Builder {
    /// The registries this machine reads, opened only when this build
    /// has something to warm. A site whose only source is the host's
    /// checkout needs no registry at all, and opening one would refuse
    /// a perfectly buildable site over a `[[registry]]` nobody declared.
    pub resolver: Option<InstallResolver>,
    /// Where warmed packages land.
    pub store_root: PathBuf,
    /// The binary whose `derived` blocks are the host's, and the
    /// checkout they are generated in. Absent when this build carries no
    /// host, and unused for every other source — see [`Builder::derived`].
    pub host: Option<HostProduct>,
    /// Seconds one generated block may take.
    pub timeout_secs: u64,
}

/// The product a host's own documentation describes.
pub(crate) struct HostProduct {
    pub binary: PathBuf,
    pub checkout: PathBuf,
}

impl Prepare for Builder {
    fn warm(&self, pair: &Pair) -> vibe_doc::error::Result<PathBuf> {
        let spelled = format!("{}@={}", pair.coordinate(), pair.version);
        let reference = vibe_core::PackageRef::parse(&spelled).map_err(|e| DocError::Site {
            message: format!("`{spelled}` is not a coordinate this machine can resolve: {e}"),
        })?;
        let resolver = self.resolver.as_ref().ok_or_else(|| DocError::Site {
            message: format!(
                "`{spelled}` comes from a registry and this build opened none — a site \
                 that reads a registry needs one this machine can resolve"
            ),
        })?;
        crate::commands::cache::add::warm(resolver, &self.store_root, vec![reference]).map_err(
            |e| DocError::Site {
                message: format!("warming `{spelled}`: {e}"),
            },
        )?;
        let version = pair
            .version
            .parse::<semver::Version>()
            .map_err(|e| DocError::Site {
                message: format!("`{}` is not a version: {e}", pair.version),
            })?;
        let group = vibe_core::Group::parse(&pair.group).map_err(|e| DocError::Site {
            message: format!("`{}` is not a group: {e}", pair.group),
        })?;
        vibe_registry::lookup(&group, &pair.name, &version).ok_or_else(|| DocError::Site {
            message: format!(
                "`{spelled}` was warmed and the store does not hold it — the fetch \
                 reported success and wrote nothing"
            ),
        })
    }

    /// Generate `derived` blocks only for the host's own packages.
    ///
    /// A `derived` block is generated BY RUNNING the product the page
    /// describes (`##PIPE-DERIVED`). For the host's documentation that
    /// product is this `vibe` and the two agree by construction. For a
    /// package the site merely publishes it is not: running `vibe` to
    /// fill a stranger's block would put this binary's output on a page
    /// about something else, and a site that ran whatever a published
    /// package asked it to would be a worse idea still.
    ///
    /// So those blocks render as the marked gaps they are — which is
    /// what a build with `--no-derived` already does, and what a build
    /// from a warmed store on a machine that compiled nothing has always
    /// done.
    fn derived(&self, pair: &Pair, package_dir: &Path) -> BTreeMap<String, String> {
        if matches!(pair.origin, Origin::Registry) {
            return BTreeMap::new();
        }
        let Some(host) = &self.host else {
            return BTreeMap::new();
        };
        let Ok(coordinate) = vibe_doc::derived::coordinate_of(package_dir) else {
            return BTreeMap::new();
        };
        let env = vibe_doc::derived::DerivedEnv {
            binary: host.binary.clone(),
            repo_root: host.checkout.clone(),
            coordinate,
            timeout_secs: self.timeout_secs,
        };
        // A block that will not generate is a gap on the page and never
        // a failed site: the page says so where the text would have
        // been, which is more use to a reader than an absent version.
        let Ok(blocks) = vibe_doc::derived::generate(package_dir, &env) else {
            return BTreeMap::new();
        };
        blocks
            .into_iter()
            .map(|block| {
                (
                    vibe_doc::content::Content::derived_key(block.kind, &block.reference),
                    block.text,
                )
            })
            .collect()
    }
}
