//! Proves the *shipped* conform engine catches a discipline violation and
//! passes a clean tree — the property the whole PROP-024 relocation exists to
//! preserve: an installed `conform` is a working checker, not a description of
//! one. Drives the real `run_check` over throwaway fixtures, so it guards the
//! end-to-end gate (config load → fact extraction → rules → baseline diff →
//! non-zero on a new finding), not just the rule units.

use std::path::Path;

use tempfile::{TempDir, tempdir};

/// A seam whose domain code unwraps — a `no-unwrap-in-domain` finding. The
/// doctest fence keeps `seam-has-doctest` satisfied, so the unwrap is the
/// only finding (a clean, single-rule signal).
const DIRTY: &str = r#"/// A seam with a domain unwrap.
///
/// ```
/// let _ = myapp::parse("3");
/// ```
pub fn parse(s: &str) -> i32 {
    s.parse::<i32>().unwrap()
}
"#;

/// The same seam returning through `Option` — trips no rule.
const CLEAN: &str = r#"/// A seam that returns through Option.
///
/// ```
/// let _ = myapp::parse("3");
/// ```
pub fn parse(s: &str) -> Option<i32> {
    s.parse::<i32>().ok()
}
"#;

/// A minimal project: a `conform.toml` gating one crate `myapp` (with the
/// `Cargo.toml` that makes it crate-shaped for the gated-or-exempt tree
/// invariant), an empty baseline, and `crates/myapp/src/lib.rs` carrying
/// `lib_body`.
fn fixture(lib_body: &str) -> TempDir {
    let dir = tempdir().expect("tempdir");
    write(
        dir.path(),
        "conform.toml",
        "[rust]\nroots = [\"crates/*\"]\ngated = [\"myapp\"]\n",
    );
    write(
        dir.path(),
        "conform-baseline.json",
        "{\"schema\":1,\"findings\":[]}\n",
    );
    write(
        dir.path(),
        "crates/myapp/Cargo.toml",
        "[package]\nname = \"myapp\"\n",
    );
    write(dir.path(), "crates/myapp/src/lib.rs", lib_body);
    dir
}

fn write(root: &Path, rel: &str, body: &str) {
    let path = root.join(rel);
    std::fs::create_dir_all(path.parent().expect("parent")).expect("mkdir");
    std::fs::write(path, body).expect("write");
}

#[test]
fn catches_a_no_unwrap_violation() {
    let dir = fixture(DIRTY);
    let err = rust_ai_native_conform::run_check(dir.path(), "conform-baseline.json", None)
        .expect_err("a domain unwrap in a gated crate must fail the gate");
    assert!(
        err.to_string().contains("new finding"),
        "expected a new-finding failure, got: {err}"
    );
}

#[test]
fn passes_a_clean_gated_crate() {
    let dir = fixture(CLEAN);
    rust_ai_native_conform::run_check(dir.path(), "conform-baseline.json", None)
        .expect("a clean gated crate must pass the gate");
}

/// A 150-line `src/lib.rs` whose only non-filler line is an
/// `// INVARIANT:` invariant comment at `marker_line`; every other line is
/// inert comment filler that leads with no marker. Arithmetic, checked by
/// hand: at 150 lines the rule is active (≥ min 120); the middle third is
/// lines 51..=100 (lower = 150/3 = 50, upper = 2·150/3 = 100), so a marker
/// at line 75 is buried (red) and one at line 5 sits in the top third
/// (line 5 ≤ 50, green).
fn long_lib_with_invariant_at(marker_line: usize) -> String {
    assert!((1..=150).contains(&marker_line));
    (1..=150)
        .map(|n| {
            if n == marker_line {
                "// INVARIANT: this invariant is positioned for the exhibit.".to_string()
            } else {
                format!("// inert filler line {n}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n")
}

#[test]
fn invariant_comment_buried_in_the_middle_third_fails_the_gate() {
    let dir = fixture(&long_lib_with_invariant_at(75));
    let err = rust_ai_native_conform::run_check(dir.path(), "conform-baseline.json", None)
        .expect_err("a mid-third invariant comment in a long src file must fail");
    assert!(
        err.to_string().contains("1 new finding(s)"),
        "expected exactly the one invariant-comment-position finding: {err}"
    );
}

#[test]
fn invariant_comment_at_the_top_of_a_long_file_passes() {
    let dir = fixture(&long_lib_with_invariant_at(5));
    rust_ai_native_conform::run_check(dir.path(), "conform-baseline.json", None)
        .expect("a top-of-file invariant comment is not buried — the gate passes");
}

/// A seam with a doctested surface, plus a `#[cfg(test)]` module whose one
/// test sweeps a `2^n` bit-mask — the declared-test-matrices violation
/// (R-060): the cases are generated by enumeration, not declared as data.
const SWEPT_MATRIX: &str = r#"/// A seam with a swept test.
///
/// ```
/// let _ = myapp::answer();
/// ```
pub fn answer() -> u32 {
    0
}

#[cfg(test)]
mod tests {
    #[test]
    fn swept() {
        for mask in 0..(1 << 3) {
            let _ = mask;
        }
    }
}
"#;

/// The same seam, but the test declares its cases as a table and iterates
/// it once — the compliant shape (R-060): no `2^n` enumeration.
const DECLARED_MATRIX: &str = r#"/// A seam with a declared test.
///
/// ```
/// let _ = myapp::answer();
/// ```
pub fn answer() -> u32 {
    0
}

#[cfg(test)]
mod tests {
    #[test]
    fn declared() {
        let cases = [(1u32, 2u32), (3, 4)];
        for (a, _b) in cases {
            let _ = a;
        }
    }
}
"#;

#[test]
fn a_swept_bit_mask_test_matrix_fails_the_gate() {
    let dir = fixture(SWEPT_MATRIX);
    let err = rust_ai_native_conform::run_check(dir.path(), "conform-baseline.json", None)
        .expect_err("a 2^n bit-mask swept test matrix must fail the gate");
    // The fixture's only violation is the swept matrix (the seam is
    // doctested, no unwrap/unsafe/env), so exactly one finding fires —
    // the declared-test-matrices rule.
    assert!(
        err.to_string().contains("1 new finding(s)"),
        "expected exactly the declared-test-matrices finding: {err}"
    );
}

#[test]
fn a_declared_test_matrix_passes_the_gate() {
    let dir = fixture(DECLARED_MATRIX);
    rust_ai_native_conform::run_check(dir.path(), "conform-baseline.json", None)
        .expect("a declared table iterated once is the compliant matrix — green");
}
