schema = 1
source_hash = "sha256:c068ab0517275cc6c7d11ce0e77e20c8dc9f038c6e6e4ae0832902b063ce0fc5"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:c7562978f83b1be6f9f94443af19f095db3779d3413fb87b6579df82a6d34252"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/20-flow-sync-from-code.xml"
output = "vibevm/vibespecs/boot/20-flow-sync-from-code.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/20a-wal-binding.xml"
output = "vibevm/vibespecs/boot/20a-wal-binding.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/sync-from-code/SYNC-PROTOCOL.xml"
output = "vibevm/vibespecs/flows/sync-from-code/SYNC-PROTOCOL.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/sync-from-code/review-workflow.xml"
output = "vibevm/vibespecs/flows/sync-from-code/review-workflow.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/sync-from-code/when-to-apply.xml"
output = "vibevm/vibespecs/flows/sync-from-code/when-to-apply.xml"
disposition = "copied"
