//! End-to-end tests for the full M0 walk: init → install → list → uninstall.
//!
//! The `wal` package exercised here is the real `org.vibevm.world/wal` that
//! ships in this repo at `packages/org.vibevm.world/wal/` — the tests dogfood
//! the actual product package, not a hand-written fixture. Also covers the
//! M1.1 git-backed-registry install and the M1.15 git-source installs (`--git`
//! + `--tag` / `--branch`).

mod common;

use std::fs;

use common::{
    fixture_registry, git_available, init_project, make_per_package_registry,
    make_single_package_bare_repo, make_wal_dir_registry, vibe,
    write_project_with_per_package_registry,
};
use predicates::prelude::*;
use specmark::verifies;

#[test]
#[verifies("spec://vibevm/VIBEVM-SPEC#install-workflow-in-detail")]
fn full_install_cycle() {
    // PROP-009 loading model: `vibe install` materialises a resolved
    // package's published tree verbatim into a `vibedeps/<kind>-<name>/
    // <version>/` slot at the workspace root, then generates the boot
    // artifacts (`spec/boot/INDEX.md`, the `CLAUDE.md` redirect).
    // `vibe uninstall` removes the slot and regenerates boot. There are
    // no longer any mirrored `spec/flows/<kind>/<name>/*` files in the
    // project tree, and no `NN-` boot snippet placed directly in
    // `spec/boot/`.
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    // Install org.vibevm.world/wal from a directory registry seeded with
    // the real package tree (dogfood, not a fixture).
    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    // The package's whole published tree is materialised verbatim into
    // its `vibedeps/` slot — the real org.vibevm.world/wal v0.2.0 ships
    // `vibe.toml`, `README.md`, `spec/boot/10-flow-wal.md`, and
    // `spec/flows/wal/*.md` files (plus a skill and LICENSE, not asserted
    // here).
    let slot = project.path().join("vibedeps/flow-wal/0.2.0");
    for rel in [
        "vibe.toml",
        "README.md",
        "spec/boot/10-flow-wal.md",
        "spec/flows/wal/WAL-PROTOCOL.md",
        "spec/flows/wal/session-end-hook.md",
        "spec/flows/wal/morning-routine.md",
    ] {
        assert!(
            slot.join(rel).is_file(),
            "expected `vibedeps/flow-wal/0.2.0/{rel}` after install"
        );
    }
    // The OLD mirror paths must NOT exist any more.
    assert!(
        !project
            .path()
            .join("spec/flows/wal/WAL-PROTOCOL.md")
            .exists(),
        "the legacy [writes] mirror layout is retired — no project-tree mirror"
    );
    assert!(
        !project.path().join("spec/boot/10-flow-wal.md").exists(),
        "the NN- boot-snippet placement is retired"
    );

    // User-owned file survived untouched.
    let core_before = fs::read_to_string(project.path().join("spec/boot/00-core.md")).unwrap();

    // The generated boot manifest exists and is a `schema = 1` TOML
    // document listing the node's own foundation boot.
    let index_path = project.path().join("spec/boot/INDEX.md");
    assert!(index_path.is_file(), "spec/boot/INDEX.md must be generated");
    let index = fs::read_to_string(&index_path).unwrap();
    let index_toml: toml::Value = toml::from_str(&index).expect("INDEX.md is TOML");
    assert_eq!(
        index_toml.get("schema").and_then(|v| v.as_integer()),
        Some(1)
    );
    assert!(
        index.contains("spec/boot/00-core.md"),
        "INDEX.md must name the node's own foundation boot:\n{index}"
    );
    // Regression guard: a CLI `vibe install <pkgref>` must compose the
    // freshly-installed package's boot into INDEX.md — the manifest
    // `[requires]` is merged before the boot artifacts are regenerated.
    assert!(
        index.contains("vibedeps/flow-wal/0.2.0/spec/boot/10-flow-wal.md"),
        "INDEX.md must name the installed dependency's boot snippet:\n{index}"
    );
    // The fixtures declare no `link = "static"` dependency, so there is
    // no STATIC.md.
    assert!(
        !project.path().join("spec/boot/STATIC.md").exists(),
        "STATIC.md is only generated for static-linked dependencies"
    );
    // The redirect files are generated thin pointers at the boot
    // artifacts.
    for redirect in ["CLAUDE.md", "AGENTS.md", "GEMINI.md"] {
        let body = fs::read_to_string(project.path().join(redirect)).unwrap();
        assert!(
            body.contains("Generated by vibe") && body.contains("spec/boot/INDEX.md"),
            "{redirect} must be a generated redirect pointing at the boot artifacts"
        );
    }

    // Lockfile must now carry the entry — but with the PROP-009 shape:
    // `files_written` is empty (the footprint is the deterministic
    // `vibedeps/` slot) and there is no `boot_snippet` filename.
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert_eq!(lock.packages.len(), 1);
    assert_eq!(lock.packages[0].name, "wal");
    assert_eq!(lock.packages[0].version.to_string(), "0.2.0");
    assert!(lock.packages[0].content_hash.starts_with("sha256:"));
    assert!(
        lock.packages[0].files_written.is_empty(),
        "files_written is empty under the loading model"
    );
    assert!(
        lock.packages[0].boot_snippet.is_none(),
        "the lockfile no longer records a boot_snippet filename"
    );

    // Cache directory populated.
    assert!(
        project
            .path()
            .join(".vibe/cache/org.vibevm.world/wal/v0.2.0/vibe.toml")
            .is_file()
    );

    // `vibe list` reflects the install.
    vibe()
        .arg("list")
        .arg("--path")
        .arg(project.path())
        .assert()
        .success()
        .stdout(predicate::str::contains("flow"))
        .stdout(predicate::str::contains("wal"))
        .stdout(predicate::str::contains("0.2.0"));

    // `vibe uninstall` removes the package's `vibedeps/` slot.
    vibe()
        .arg("uninstall")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    assert!(
        !slot.exists(),
        "the vibedeps/ slot must be gone after uninstall"
    );
    // INDEX.md is regenerated and still present — boot is recomputed
    // from the now-empty resolution.
    assert!(index_path.is_file(), "INDEX.md is regenerated on uninstall");

    // User-owned file still intact.
    let core_after = fs::read_to_string(project.path().join("spec/boot/00-core.md")).unwrap();
    assert_eq!(core_before, core_after);

    // Lockfile entry removed.
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert!(lock.packages.is_empty());

    // `list` after uninstall shows no packages.
    vibe()
        .arg("list")
        .arg("--path")
        .arg(project.path())
        .assert()
        .success()
        .stdout(predicate::str::contains("no packages"));
}

/// A second `vibe install` of the same package is an idempotent
/// success, not a rejection. The depsolver still runs — a CLI pkgref
/// always takes the full path — but PROP-011 §2.3 skips re-copying the
/// `vibedeps/` slot already present for the resolved version. The slot
/// still stands and the lockfile keeps exactly one entry.
#[test]
#[verifies("spec://vibevm/VIBEVM-SPEC#install-workflow-in-detail")]
fn install_second_install_is_idempotent() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    // Second install of the same package succeeds — the slot is already
    // present for 0.2.0, so materialisation skips it (PROP-011 §2.3).
    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    // The slot is still present and the lockfile still carries exactly
    // one entry — no duplicate, no drift.
    assert!(
        project
            .path()
            .join("vibedeps/flow-wal/0.2.0/vibe.toml")
            .is_file(),
        "vibedeps/ slot must survive a re-install"
    );
    let lock: vibe_core::manifest::Lockfile =
        toml::from_str(&fs::read_to_string(project.path().join("vibe.lock")).unwrap()).unwrap();
    assert_eq!(lock.packages.len(), 1);
    assert_eq!(lock.packages[0].name, "wal");
}

/// PROP-011 §2.3 — materialise only the diff. A re-install whose slot
/// is already present for the resolved version skips the re-copy: the
/// install report lists the slot under `skipped`, not `materialised`.
#[test]
fn install_skips_a_present_slot_on_re_install() {
    let project = tempfile::tempdir().unwrap();
    // The registry lives OUTSIDE the project so a re-install's freshness
    // scan never sees it; built once and reused across both installs (a
    // second `make_wal_dir_registry` would re-copy the tree and look like
    // a change).
    let reg_home = tempfile::tempdir().unwrap();
    let registry = make_wal_dir_registry(reg_home.path());
    init_project(project.path());

    // First install materialises the `vibedeps/flow-wal/0.2.0` slot.
    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(&registry)
        .arg("--assume-yes")
        .assert()
        .success();

    // Second install — same pkgref, full pipeline — but the slot is
    // already present for the resolved version, so the copy is skipped.
    let out = vibe()
        .arg("--json")
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(&registry)
        .arg("--assume-yes")
        .output()
        .unwrap();
    assert!(out.status.success());
    let stdout = String::from_utf8(out.stdout).unwrap();
    let docs: Vec<serde_json::Value> = serde_json::Deserializer::from_str(&stdout)
        .into_iter::<serde_json::Value>()
        .collect::<Result<_, _>>()
        .expect("stdout is a stream of JSON documents");
    let report = docs.last().unwrap();
    let skipped = report["skipped"].as_array().unwrap();
    assert_eq!(skipped.len(), 1, "the present slot must be skipped");
    assert_eq!(skipped[0].as_str().unwrap(), "vibedeps/flow-wal/0.2.0");
    assert!(
        report["materialised"].as_array().unwrap().is_empty(),
        "nothing is freshly materialised on a no-op re-install"
    );
}

#[test]
fn install_reports_json() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    let out = vibe()
        .arg("--json")
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .output()
        .unwrap();
    assert!(out.status.success());

    // The plan and the report are both emitted as JSON documents,
    // concatenated on stdout. Use StreamDeserializer to read every document
    // in order and inspect the last one (the install report).
    let stdout = String::from_utf8(out.stdout).unwrap();
    let de = serde_json::Deserializer::from_str(&stdout);
    let docs: Vec<serde_json::Value> = de
        .into_iter::<serde_json::Value>()
        .collect::<Result<_, _>>()
        .expect("stdout is a stream of JSON documents");
    assert!(docs.len() >= 2, "expected at least a plan and a report");
    let last = docs.last().unwrap();
    assert_eq!(last["ok"], true);
    assert_eq!(last["command"], "install");
    // PROP-009 install report: `materialised` lists the `vibedeps/`
    // slots written, `nodes_regenerated` the nodes whose boot artifacts
    // were rebuilt.
    let materialised = last["materialised"].as_array().unwrap();
    assert_eq!(materialised.len(), 1);
    assert_eq!(materialised[0].as_str().unwrap(), "vibedeps/flow-wal/0.2.0");
    assert_eq!(last["nodes_regenerated"].as_array().unwrap().len(), 1);
}

/// PROP-011 §2.2 — a bare `vibe install` after a full install finds the
/// lockfile fresh and skips the depsolver entirely. The fast-path report
/// carries `unchanged: true` and emits no resolution plan ahead of it.
#[test]
#[verifies("spec://vibevm/VIBEVM-SPEC#install-workflow-in-detail")]
fn install_skips_resolution_when_the_lockfile_is_fresh() {
    let project = tempfile::tempdir().unwrap();
    // The registry lives OUTSIDE the project so the fresh-lockfile fast
    // path is not defeated by a re-copied registry inside the project;
    // built once and reused across both installs.
    let reg_home = tempfile::tempdir().unwrap();
    let registry = make_wal_dir_registry(reg_home.path());
    init_project(project.path());

    // First install — the full pipeline: resolve, materialise, lock. It
    // also records `org.vibevm.world/wal` in `[requires].packages`.
    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(&registry)
        .arg("--assume-yes")
        .assert()
        .success();

    // Second install with no pkgref — `[requires]` carries org.vibevm.world/wal, the
    // lock is a fresh resolution of it, the slot is materialised: the
    // depsolver is skipped.
    let out = vibe()
        .arg("--json")
        .arg("install")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(&registry)
        .arg("--assume-yes")
        .output()
        .unwrap();
    assert!(out.status.success());
    let stdout = String::from_utf8(out.stdout).unwrap();
    let docs: Vec<serde_json::Value> = serde_json::Deserializer::from_str(&stdout)
        .into_iter::<serde_json::Value>()
        .collect::<Result<_, _>>()
        .expect("stdout is a stream of JSON documents");
    // The fast path emits exactly one document — the report — with no
    // preceding resolution plan, and flags itself unchanged.
    assert_eq!(docs.len(), 1, "fast path emits only the report, no plan");
    assert_eq!(docs[0]["command"], "install");
    assert_eq!(docs[0]["unchanged"], true);
}

#[test]
fn uninstall_errors_when_package_not_installed() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("uninstall")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .failure()
        .stderr(predicate::str::contains("not installed"));
}

/// `vibe install <pkgref>` (no version) records the user-supplied
/// pkgref in `vibe.toml` `[requires].packages` with the **caret**
/// shape derived from the resolved version (`org.vibevm.world/wal@^0.2.0`).
/// Same default as Cargo / npm / Poetry — `vibe update` later picks
/// up patch-compatible bumps without needing an explicit re-pin.
#[test]
fn install_writes_caret_pkgref_to_vibe_toml_requires() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    let toml_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest =
        vibe_core::manifest::Manifest::parse_str(&toml_text).expect("vibe.toml round-trips");
    assert_eq!(
        manifest.requires.packages.len(),
        1,
        "expected exactly one entry in [requires].packages, got: {:#?}",
        manifest.requires.packages
    );
    let recorded = &manifest.requires.packages[0];
    assert_eq!(recorded.qualified_name(), "org.vibevm.world/wal");
    // Caret shape: rendered string ends in `@^<resolved>`. The real
    // org.vibevm.world/wal ships at v0.2.0 so the manifest carries `^0.2.0`.
    assert_eq!(
        recorded.to_string(),
        "org.vibevm.world/wal@^0.2.0",
        "expected caret-default constraint, got: {recorded}"
    );
    // M1.15 wire shape: `[requires.packages]` map-form table with the key
    // being the bare pkgref and the value being the constraint string.
    assert!(
        toml_text.contains("[requires.packages]"),
        "expected [requires.packages] header in rendered vibe.toml:\n{toml_text}"
    );
    assert!(
        toml_text.contains("\"org.vibevm.world/wal\" = \"^0.2.0\""),
        "expected `\"org.vibevm.world/wal\" = \"^0.2.0\"` row in rendered vibe.toml:\n{toml_text}"
    );
}

/// PROP-008 §2.6 — short-name resolution at the CLI input boundary.
/// `vibe install wal` (bare, unqualified) is resolved to the qualified
/// `org.vibevm.world/wal` against the registry, and it is the **qualified**
/// form that lands in `vibe.toml` `[requires].packages` — a manifest
/// never stores a short name.
#[test]
fn install_resolves_bare_short_name_to_qualified() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("wal") // bare short name — no group
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    let toml_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest =
        vibe_core::manifest::Manifest::parse_str(&toml_text).expect("vibe.toml round-trips");
    assert_eq!(
        manifest.requires.packages.len(),
        1,
        "expected one entry, got: {:#?}",
        manifest.requires.packages
    );
    let recorded = &manifest.requires.packages[0];
    // The short `wal` was qualified to `org.vibevm.world/wal` before the
    // manifest write — the manifest pkgref carries a group.
    assert!(
        recorded.group.is_some(),
        "manifest pkgref must be group-qualified, got: {recorded}"
    );
    assert_eq!(recorded.qualified_name(), "org.vibevm.world/wal");
    assert!(
        toml_text.contains("\"org.vibevm.world/wal\""),
        "expected the qualified key in vibe.toml:\n{toml_text}"
    );
}

/// A bare short name that resolves to no package fails the install
/// with a pointer at the qualified form — the resolver never guesses
/// (PROP-008 §2.6).
#[test]
fn install_unresolvable_short_name_fails_with_hint() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("no-such-package")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(fixture_registry())
        .arg("--assume-yes")
        .assert()
        .failure()
        .stderr(predicate::str::contains("could not resolve the short name"));
}

/// PROP-008 §2.7 — a short name matching two groups is a collision.
/// `vibe install` refuses to guess: it fails with the dedicated exit
/// code `7` ("ambiguous package", distinct from `3`) and prints the
/// numbered qualified alternatives so the operator can pick one.
#[test]
fn install_ambiguous_short_name_fails_with_exit_code_seven() {
    // A two-group registry: `org.vibevm/wal` and `com.example/wal`
    // both exist, so the bare `wal` cannot be resolved to one group.
    let registry = tempfile::tempdir().unwrap();
    for group in ["org.vibevm", "com.example"] {
        fs::create_dir_all(registry.path().join(group).join("wal").join("v0.1.0")).unwrap();
    }
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(registry.path())
        .arg("--assume-yes")
        .assert()
        .code(7)
        .stderr(predicate::str::contains("is ambiguous"))
        .stderr(predicate::str::contains("com.example/wal"))
        .stderr(predicate::str::contains("org.vibevm/wal"));
}

/// `vibe install <pkgref>@^0.1` (explicit constraint) records the
/// constraint verbatim — we don't tighten or override what the
/// operator typed. Symmetric guard around the
/// `finalize_pkgref_for_manifest` "preserve explicit" branch.
#[test]
fn install_preserves_explicit_constraint_in_vibe_toml() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal@^0.2")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    let toml_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest = vibe_core::manifest::Manifest::parse_str(&toml_text).unwrap();
    assert_eq!(manifest.requires.packages.len(), 1);
    // CLI typed `^0.2`; manifest preserves `^0.2`. We do NOT tighten
    // to the resolved `^0.2.0` — the operator's wider declaration
    // wins.
    assert_eq!(
        manifest.requires.packages[0].to_string(),
        "org.vibevm.world/wal@^0.2"
    );
}

/// `vibe install <pkgref> --exact` pins the manifest to the exact
/// resolved version (`=0.2.0`), npm `--save-exact` shape. Overrides
/// any constraint the CLI form carried.
#[test]
fn install_with_exact_flag_pins_manifest_to_eq_resolved() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--exact")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    let toml_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest = vibe_core::manifest::Manifest::parse_str(&toml_text).unwrap();
    assert_eq!(manifest.requires.packages.len(), 1);
    assert_eq!(
        manifest.requires.packages[0].to_string(),
        "org.vibevm.world/wal@=0.2.0",
        "expected =-pinned exact constraint with --exact"
    );
}

/// `vibe install` with no arguments installs every entry from
/// `vibe.toml` `[requires].packages` — the cargo `cargo build` /
/// npm `npm install` shape. A fresh clone of a vibevm project
/// reproduces its package set without re-typing every pkgref.
#[test]
fn install_from_manifest_uses_requires() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    // Hand-edit vibe.toml: declare org.vibevm.world/wal as a required package without
    // having installed it yet. This is the freshly-cloned-project case —
    // `vibe.toml` already declares the deps, but nothing has been resolved.
    let toml_path = project.path().join("vibe.toml");
    let toml_text = fs::read_to_string(&toml_path).unwrap();
    let mut manifest = vibe_core::manifest::Manifest::parse_str(&toml_text).unwrap();
    manifest
        .requires
        .packages
        .push(vibe_core::PackageRef::parse("org.vibevm.world/wal").unwrap());
    manifest.write(&toml_path).unwrap();

    // Run `vibe install` with no pkgref arguments — should pick up the
    // manifest declaration and install org.vibevm.world/wal.
    vibe()
        .arg("install")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    // Package materialised into its `vibedeps/` slot, lockfile
    // populated, manifest declaration intact.
    assert!(
        project
            .path()
            .join("vibedeps/flow-wal/0.2.0/spec/flows/wal/WAL-PROTOCOL.md")
            .is_file(),
        "the package tree is materialised verbatim into vibedeps/"
    );
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert_eq!(lock.packages.len(), 1);
    assert_eq!(lock.packages[0].name, "wal");
    assert_eq!(lock.meta.root_dependencies.len(), 1);
    assert_eq!(
        lock.meta.root_dependencies[0].qualified_name(),
        "org.vibevm.world/wal"
    );

    // Because org.vibevm.world/wal was declared in `[requires]` before this
    // install, the boot computation sees it as a dependency of the
    // project node — `INDEX.md` names its boot file inside the
    // `vibedeps/` slot, in the dependency band (between the node's own
    // foundation and user-override boot).
    let index = fs::read_to_string(project.path().join("spec/boot/INDEX.md")).unwrap();
    assert!(
        index.contains("vibedeps/flow-wal/0.2.0/spec/boot/10-flow-wal.md"),
        "INDEX.md must name the dependency's boot file under its slot:\n{index}"
    );
}

/// `vibe install` with no arguments and no declared packages anywhere
/// (manifest empty AND lockfile empty) is a clear error pointing at
/// the two ways to declare an input list.
#[test]
fn install_no_args_no_manifest_no_lock_errors() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(fixture_registry())
        .arg("--assume-yes")
        .assert()
        .failure()
        .stderr(predicate::str::contains("no packages to install"))
        .stderr(predicate::str::contains("[requires].packages"));
}

/// `vibe uninstall <pkgref>` removes the matching entry from
/// `vibe.toml` `[requires].packages`, mirroring the lockfile cleanup.
/// Pure transitives (never declared in the manifest) leave the
/// manifest untouched.
#[test]
fn uninstall_drops_pkgref_from_vibe_toml() {
    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    vibe()
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--registry")
        .arg(make_wal_dir_registry(project.path()))
        .arg("--assume-yes")
        .assert()
        .success();

    // Manifest carries the pkgref after install (sanity check that the
    // earlier test's invariant still holds in this fresh tempdir).
    let toml_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest = vibe_core::manifest::Manifest::parse_str(&toml_text).unwrap();
    assert_eq!(manifest.requires.packages.len(), 1);

    vibe()
        .arg("uninstall")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    // Manifest now empty.
    let toml_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest = vibe_core::manifest::Manifest::parse_str(&toml_text).unwrap();
    assert!(
        manifest.requires.packages.is_empty(),
        "[requires].packages should be empty after uninstall, got: {:#?}",
        manifest.requires.packages
    );
    // Empty [requires] is skipped on serialize — the rendered TOML
    // should not carry an empty section header.
    assert!(
        !toml_text.contains("[requires]"),
        "expected empty [requires] to be skipped on serialize:\n{toml_text}"
    );
}

// NOTE: `install_boot_snippet_conflict_exits_with_code_three` was
// deleted with the PROP-009 switch-over. The old model placed each
// package's boot snippet directly in the project's `spec/boot/` under
// an author-chosen `NN-` numeric prefix, so two packages sharing a
// prefix collided. The loading model retires the `NN-` prefix entirely:
// a dependency's boot lives inside its own `vibedeps/<slot>/` tree and
// the engine owns ordering by `BootCategory` band. There is no prefix,
// hence no prefix collision and no exit-code-3 path to test.

// ---------------------------------------------------------------------------
// M1.1 — install from a git-backed registry
// ---------------------------------------------------------------------------

#[test]
fn install_from_git_registry() {
    if !git_available() {
        eprintln!("skipping install_from_git_registry: git not on PATH");
        return;
    }

    let outer = tempfile::tempdir().unwrap();
    let org_root = make_per_package_registry(outer.path());
    let cache = outer.path().join("cache");
    fs::create_dir_all(&cache).unwrap();

    let project = tempfile::tempdir().unwrap();
    init_project(project.path());

    // Org URL = parent of `org.vibevm.world_wal.git`. `git+file://` prefix is
    // the Cargo / pip convention recorded in lockfiles; the resolver
    // strips it before invoking `git`, so it works with both prefixed and
    // bare forms in `vibe.toml`.
    let url = format!(
        "git+file://{}",
        org_root.to_string_lossy().replace('\\', "/")
    );
    write_project_with_per_package_registry(project.path(), &url);

    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    // Lockfile reflects the per-package shape.
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert_eq!(lock.packages.len(), 1);
    let entry = &lock.packages[0];

    // schema_version matches CURRENT (5 after PROP-008 qualified naming).
    assert_eq!(
        lock.meta.schema_version,
        vibe_core::manifest::CURRENT_SCHEMA_VERSION,
    );

    // PROP-002 §2.7 provenance: registry name, full per-package source_url,
    // tag in source_ref. No more `#flow/wal/v0.1.0` fragment shape.
    assert_eq!(entry.registry.as_deref(), Some("default"));
    assert!(
        entry.source_url.starts_with("git+file://"),
        "expected git+file:// prefix, got: {}",
        entry.source_url
    );
    assert!(
        entry.source_url.ends_with("/org.vibevm.world_wal.git"),
        "expected per-package URL ending in /org.vibevm.world_wal.git, got: {}",
        entry.source_url
    );
    assert_eq!(entry.source_ref.as_deref(), Some("v0.2.0"));
    assert!(!entry.overridden);

    // Cache layout: one bucket dir under cache/, with packages/<kind>-<name>/
    // and a clone subdir. The registry-level meta.toml lands together with
    // freshness machinery in a follow-up — this commit only requires the
    // bucket directory itself plus the package clone.
    let clone_dirs: Vec<_> = fs::read_dir(&cache)
        .unwrap()
        .filter_map(|e| e.ok())
        .collect();
    assert_eq!(clone_dirs.len(), 1, "expected one registry cache bucket");
    let bucket = clone_dirs[0].path();
    let pkg_clone = bucket.join("packages/org.vibevm.world_wal/clone");
    assert!(
        pkg_clone.join(".git").exists(),
        "per-package clone missing .git/: {}",
        pkg_clone.display()
    );
    assert!(
        pkg_clone.join("vibe.toml").exists(),
        "vibe.toml not in per-package clone: {}",
        pkg_clone.display()
    );

    // `vibe registry sync` is migrated separately — the legacy single-repo
    // sync path doesn't fit a per-package org URL. The follow-up commit
    // walks the lockfile to refresh per-package clones.
}

#[test]
#[verifies("spec://vibevm/modules/vibe-registry/PROP-002#git-source", r = 1)]
fn install_from_git_source_with_tag_records_source_kind_git() {
    if !git_available() {
        eprintln!("skipping install_from_git_source_with_tag: git not on PATH");
        return;
    }
    let outer = tempfile::tempdir().unwrap();
    let bare = make_single_package_bare_repo(outer.path());
    let cache = outer.path().join("cache");
    fs::create_dir_all(&cache).unwrap();

    let project = tempfile::tempdir().unwrap();
    init_project(project.path());
    let url = format!("file://{}", bare.to_string_lossy().replace('\\', "/"));

    // M1.15: declare git-source via CLI flags, no [[registry]] needed.
    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--git")
        .arg(&url)
        .arg("--tag")
        .arg("v0.2.0")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    // Manifest: pkgref recorded as git-source, NOT as registry-resolved.
    let manifest_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest =
        vibe_core::manifest::Manifest::parse_str(&manifest_text).expect("vibe.toml round-trips");
    assert_eq!(
        manifest.requires.git_packages.len(),
        1,
        "expected one git-source entry, got: {:#?}",
        manifest.requires.git_packages
    );
    assert!(
        manifest.requires.packages.is_empty(),
        "expected zero registry-resolved entries, got: {:#?}",
        manifest.requires.packages
    );
    let g = &manifest.requires.git_packages[0];
    assert_eq!(
        g.group,
        vibe_core::Group::parse("org.vibevm.world").unwrap()
    );
    assert_eq!(g.name, "wal");
    assert_eq!(g.url, url);
    assert!(
        matches!(&g.ref_kind, vibe_core::manifest::GitRefKind::Tag(t) if t == "v0.2.0"),
        "expected tag refkind, got: {:?}",
        g.ref_kind
    );

    // Lockfile: source_kind = "git", overridden = false, source_url = bare URL.
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert_eq!(lock.packages.len(), 1);
    let pkg = &lock.packages[0];
    assert_eq!(
        pkg.source_kind,
        Some(vibe_core::manifest::SourceKind::Git),
        "lockfile source_kind"
    );
    assert!(!pkg.overridden);
    assert_eq!(pkg.source_ref.as_deref(), Some("v0.2.0"));
    assert_eq!(pkg.registry, None);

    // Package tree materialised into its `vibedeps/` slot — a
    // git-source install lands in `vibedeps/` exactly like a
    // registry-resolved one.
    assert!(
        project
            .path()
            .join("vibedeps/flow-wal/0.2.0/spec/flows/wal/WAL-PROTOCOL.md")
            .is_file(),
        "git-source install must materialise the package tree into vibedeps/"
    );
    assert!(
        project
            .path()
            .join("vibedeps/flow-wal/0.2.0/vibe.toml")
            .is_file()
    );
}

#[test]
#[verifies("spec://vibevm/modules/vibe-registry/PROP-002#git-source", r = 1)]
fn install_from_git_source_with_branch_pins_lockfile_to_resolved_commit() {
    if !git_available() {
        eprintln!("skipping install_from_git_source_with_branch: git not on PATH");
        return;
    }
    let outer = tempfile::tempdir().unwrap();
    let bare = make_single_package_bare_repo(outer.path());
    let cache = outer.path().join("cache");
    fs::create_dir_all(&cache).unwrap();

    let project = tempfile::tempdir().unwrap();
    init_project(project.path());
    let url = format!("file://{}", bare.to_string_lossy().replace('\\', "/"));

    // M1.15: --branch is mutable; install resolves to current HEAD,
    // lockfile pins resolved_commit, vibe install (no update) stays
    // on that commit.
    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--git")
        .arg(&url)
        .arg("--branch")
        .arg("main")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    let manifest_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest =
        vibe_core::manifest::Manifest::parse_str(&manifest_text).expect("vibe.toml round-trips");
    let g = &manifest.requires.git_packages[0];
    assert!(
        matches!(&g.ref_kind, vibe_core::manifest::GitRefKind::Branch(b) if b == "main"),
        "expected branch refkind, got: {:?}",
        g.ref_kind
    );

    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    let pkg = &lock.packages[0];
    assert_eq!(pkg.source_kind, Some(vibe_core::manifest::SourceKind::Git));
    // source_ref is the declared branch name; resolved_commit (when present)
    // would be the actual SHA. Branch installs that produce a non-empty
    // resolved_commit field would here be `Some(<40-char-sha>)`; v0 of
    // M1.15 leaves it None for the file:// backend, which is acceptable
    // since identity is content-hash, not commit.
    assert_eq!(pkg.source_ref.as_deref(), Some("main"));
}

// Note: M1.15's `--rev <commit-sha>` path requires `git archive
// --remote=<url> <sha>` to resolve a non-ref-named commit, which the
// `git` upload-archive protocol does NOT support over `file://` (or
// over the smart HTTP transport). It only works against hosts that
// expose loose objects — which in practice means a real git server
// (GitHub, GitLab, etc.). The hermetic e2e cannot exercise `--rev`
// against a `file://` bare repo. Production smoke walk against
// GitHub covers this path; see `manual-tests/m1.15-git-source.md`.

/// A repeat `vibe install` (no args, re-resolving `[requires]`) of a
/// git-source declaration is an idempotent success under the loading
/// model — it re-resolves the git source and re-materialises the
/// `vibedeps/` slot. The manifest keeps exactly one git-source entry
/// and the lockfile one entry with `source_kind = "git"`.
#[test]
#[verifies("spec://vibevm/modules/vibe-registry/PROP-002#git-source", r = 1)]
fn install_git_source_then_repeat_install_no_args_is_idempotent() {
    if !git_available() {
        eprintln!("skipping install_git_source_then_repeat_install: git not on PATH");
        return;
    }
    let outer = tempfile::tempdir().unwrap();
    let bare = make_single_package_bare_repo(outer.path());
    let cache = outer.path().join("cache");
    fs::create_dir_all(&cache).unwrap();

    let project = tempfile::tempdir().unwrap();
    init_project(project.path());
    let url = format!("file://{}", bare.to_string_lossy().replace('\\', "/"));

    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--git")
        .arg(&url)
        .arg("--tag")
        .arg("v0.2.0")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    // Repeat install with no arguments — re-resolves from `[requires]`
    // and re-materialises. Idempotent: succeeds without error.
    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("install")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    // Manifest unchanged — still one git-source entry; no duplicate
    // wrote into either list during the re-install.
    let manifest_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest =
        vibe_core::manifest::Manifest::parse_str(&manifest_text).expect("vibe.toml round-trips");
    assert_eq!(manifest.requires.git_packages.len(), 1);
    assert!(manifest.requires.packages.is_empty());

    // Lockfile still has one entry, source_kind = Git, and the
    // `vibedeps/` slot is present.
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert_eq!(lock.packages.len(), 1);
    assert_eq!(
        lock.packages[0].source_kind,
        Some(vibe_core::manifest::SourceKind::Git)
    );
    assert!(
        project
            .path()
            .join("vibedeps/flow-wal/0.2.0/vibe.toml")
            .is_file()
    );
}

#[test]
fn uninstall_removes_git_source_from_manifest_and_lockfile() {
    if !git_available() {
        eprintln!("skipping uninstall_removes_git_source: git not on PATH");
        return;
    }
    let outer = tempfile::tempdir().unwrap();
    let bare = make_single_package_bare_repo(outer.path());
    let cache = outer.path().join("cache");
    fs::create_dir_all(&cache).unwrap();

    let project = tempfile::tempdir().unwrap();
    init_project(project.path());
    let url = format!("file://{}", bare.to_string_lossy().replace('\\', "/"));

    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("install")
        .arg("org.vibevm.world/wal")
        .arg("--git")
        .arg(&url)
        .arg("--tag")
        .arg("v0.2.0")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    vibe()
        .env("VIBE_REGISTRY_CACHE", &cache)
        .arg("uninstall")
        .arg("org.vibevm.world/wal")
        .arg("--path")
        .arg(project.path())
        .arg("--assume-yes")
        .assert()
        .success();

    // Manifest: git_packages entry removed.
    let manifest_text = fs::read_to_string(project.path().join("vibe.toml")).unwrap();
    let manifest =
        vibe_core::manifest::Manifest::parse_str(&manifest_text).expect("vibe.toml round-trips");
    assert!(
        manifest.requires.git_packages.is_empty(),
        "expected git_packages emptied after uninstall, got: {:?}",
        manifest.requires.git_packages
    );

    // Lockfile: empty.
    let lock_text = fs::read_to_string(project.path().join("vibe.lock")).unwrap();
    let lock: vibe_core::manifest::Lockfile = toml::from_str(&lock_text).unwrap();
    assert!(lock.packages.is_empty());

    // Files removed from the project tree.
    assert!(
        !project
            .path()
            .join("spec/flows/wal/WAL-PROTOCOL.md")
            .exists()
    );
}
