//! End-to-end coverage of `vibe explain` over an INSTALLED package (the
//! V6-FOREIGN-EXPLAIN reader): build a package with `vibe specmap`, place it
//! as an installed `vibedeps/` slot, and ask `vibe explain` about an address
//! FROM THAT PACKAGE — the canonical question answered for a foreign tree.
//!
//! The library-level behaviour (dispatch, provenance, the no-map case) is
//! covered in `vibe-trace`; this binary-level test locks the CLI surface a
//! user actually drives — `vibe specmap` then `vibe explain` — and proves the
//! reader and the writer agree on the carried-map contract end to end.

mod common;

use common::UserScratch;
use predicates::prelude::*;
use std::fs;

/// One installed-package slot under `<root>/vibedeps/org.demo.demo/0.1.0/`,
/// carrying a real map generated by `vibe specmap`. `with_map = false` omits
/// the `specmap.toml` so the package is installed but opts out of
/// traceability (the no-map case).
fn slot(root: &std::path::Path, with_map: bool) -> std::path::PathBuf {
    let slot = root.join("vibedeps/org.demo.demo/0.1.0");
    fs::create_dir_all(slot.join("crates/x/src")).unwrap();
    fs::create_dir_all(slot.join("spec")).unwrap();
    fs::write(
        slot.join("vibe.toml"),
        "[package]\ngroup = \"org.demo\"\nname = \"demo\"\nkind = \"flow\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    if with_map {
        fs::write(
            slot.join("specmap.toml"),
            "namespace = \"org.demo/demo\"\nscan_roots = [\"crates/*\"]\nspec_roots = [\"spec\"]\n",
        )
        .unwrap();
    }
    fs::write(
        slot.join("spec/D.md"),
        "## The rule {#req-r}\n`req r1`\n\nIt MUST hold.\n",
    )
    .unwrap();
    fs::write(
        slot.join("crates/x/src/lib.rs"),
        "#[spec(implements = \"spec://org.demo/demo/D#req-r\", r = 1)]\npub fn f() {}\n",
    )
    .unwrap();
    slot
}

/// §6 acceptance case 2: a foreign address whose package carried a map is
/// answered from that map, with the provenance note present.
#[test]
fn a_foreign_address_is_answered_from_the_carried_map() {
    let user = UserScratch::new();
    let project = tempfile::tempdir().unwrap();
    let slot_dir = slot(project.path(), true);

    // Generate the carried map the reader will consume.
    user.vibe()
        .arg("specmap")
        .arg("--path")
        .arg(&slot_dir)
        .assert()
        .success();
    assert!(
        slot_dir.join("package.specmap.json").exists(),
        "specmap must write the carried map"
    );

    // Ask the canonical question about an address FROM that package.
    user.vibe()
        .arg("explain")
        .arg("spec://org.demo/demo/D#req-r")
        .arg("--path")
        .arg(project.path())
        .assert()
        .success()
        .stdout(predicate::str::contains(
            "note: answered from the carried map",
        ))
        .stdout(predicate::str::contains(
            "spec unit spec://org.demo/demo/D#req-r",
        ))
        .stdout(predicate::str::contains("implements ← `x::f`"));
}

/// §6 acceptance case 1: the project's own address still builds fresh (no
/// foreign note) even with a foreign carried map present alongside it.
#[test]
fn the_projects_own_address_builds_fresh_alongside_a_carried_map() {
    let user = UserScratch::new();
    let project = tempfile::tempdir().unwrap();
    let root = project.path();

    // The project's own spec tree, under its own namespace `proj`.
    fs::write(
        root.join("specmap.toml"),
        "namespace = \"proj\"\nscan_roots = [\"crates/*\"]\nspec_roots = [\"spec\"]\n",
    )
    .unwrap();
    fs::create_dir_all(root.join("crates/p/src")).unwrap();
    fs::create_dir_all(root.join("spec")).unwrap();
    fs::write(root.join("spec/P.md"), "## own {#req-o}\n`req r1`\n").unwrap();
    fs::write(
        root.join("crates/p/src/lib.rs"),
        "#[verifies(\"spec://proj/P#req-o\")]\nfn t() {}\n",
    )
    .unwrap();

    // A foreign carried map sits alongside it.
    let slot_dir = slot(root, true);
    user.vibe()
        .arg("specmap")
        .arg("--path")
        .arg(&slot_dir)
        .assert()
        .success();

    user.vibe()
        .arg("explain")
        .arg("spec://proj/P#req-o")
        .arg("--path")
        .arg(root)
        .assert()
        .success()
        .stdout(predicate::str::contains("carried map").not())
        .stdout(predicate::str::contains("verifies ← `p::t`"));
}

/// §6 acceptance case 3: an installed package without a map gets the distinct
/// "does not participate" message (not the engine's generic not-found).
#[test]
fn an_installed_package_without_a_map_reports_it_does_not_participate() {
    let user = UserScratch::new();
    let project = tempfile::tempdir().unwrap();
    slot(project.path(), false); // installed, no specmap.toml → no map

    user.vibe()
        .arg("explain")
        .arg("spec://org.demo/demo/D#req-r")
        .arg("--path")
        .arg(project.path())
        .assert()
        .failure()
        .stderr(predicate::str::contains("does not participate"))
        .stderr(predicate::str::contains("org.demo/demo"));
}

/// §6 acceptance case 4: a non-existent address is the engine's not-found, as
/// before — here an address nothing owns (no such coordinate anywhere).
#[test]
fn an_unknown_address_is_the_engine_not_found() {
    let user = UserScratch::new();
    let project = tempfile::tempdir().unwrap();
    user.vibe()
        .arg("explain")
        .arg("spec://no.such/pkg/D#x")
        .arg("--path")
        .arg(project.path())
        .assert()
        .failure()
        .stderr(predicate::str::contains("no spec unit"));
}
