schema = 1
source_hash = "sha256:6808c68c672e5a4bd2d43b125f07280c15b11e8acefc53e26b93e9016b6f6178"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:1c41d09eddca00ad561ed53fc2415748091059995f7cb6d4f6d6dfbc314a652a"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
