schema = 1
source_hash = "sha256:7db7c326dd38712829b727c88167e24236408b8285d1d3ef597e7bb8c8ea0f78"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:d39620e0571e04b71dcc0db2d5513f223c8697457ddf58293ede4664f4c0f00a"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
