schema = 1
source_hash = "sha256:fb2c5b33312b1e5f5ae0fbd2b470b3a9270f81d1ee89ec358c3b6c8a8e993830"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:062a00acb252f7501b64dd30fdd3d93178a5f09bcf9d830008ecbbd03f88a85d"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
