use std::collections::BTreeMap;

use super::super::ir::{ContributionMeta, OriginRename};

#[derive(Clone, Copy)]
pub(crate) enum CommentSyntax {
    Markdown,
    Xml,
}

#[derive(Clone, Copy)]
enum Layout {
    Inline,
    Block,
}

/// The opening of every engine-framed generated comment, in either syntax.
///
/// Spelled once so a READER of the framing — the emitted-tape segmenter the
/// `xml-minify` binding drives — recognises exactly what the emitters below
/// write, rather than carrying a second copy of the grammar.
pub(crate) const GENERATED_COMMENT_OPEN: &str = "<!-- ";

/// The closing of an INLINE generated comment. The block layout closes with
/// `\n-->` instead, and is deliberately not spelled through this constant.
pub(crate) const GENERATED_COMMENT_CLOSE: &str = " -->";

/// The reserved channel every generated XML comment rides.
pub(crate) const XML_GENERATED_CHANNEL: &str = "vibe:c1 ";

fn generated_comment(syntax: CommentSyntax, payload: &str, layout: Layout) -> String {
    if matches!(syntax, CommentSyntax::Xml) {
        return format!(
            "{GENERATED_COMMENT_OPEN}{XML_GENERATED_CHANNEL}{}{GENERATED_COMMENT_CLOSE}",
            vibe_specdoc::encode_generated_xml_comment(payload)
        );
    }
    match layout {
        Layout::Inline => format!("{GENERATED_COMMENT_OPEN}{payload}{GENERATED_COMMENT_CLOSE}"),
        Layout::Block => format!("{GENERATED_COMMENT_OPEN}{payload}\n-->"),
    }
}

/// The artifact's opening comment block: the three provenance lines, then —
/// only for a nonempty active plan — the transforms header, then the blank
/// line that closes the block.
///
/// `transforms` is the already-built header payload (R4 architecture §7.1),
/// `None` for the empty plan. Passing `None` reproduces the exact historical
/// bytes, which is why every owner that activates nothing keeps its committed
/// artifact byte-identical.
pub(crate) fn static_header(
    syntax: CommentSyntax,
    generated_path: &str,
    transforms: Option<&str>,
) -> String {
    let mut output = static_header_block(syntax, generated_path);
    if let Some(payload) = transforms {
        output.push_str(&transforms_header(payload));
        output.push('\n');
    }
    output.push('\n');
    output
}

/// The truthful opening of a compiled static lane that skipped one or more
/// unavailable compiler-native transforms. The pending payload is framed by
/// the same generated-comment authority as the active payload; its contents
/// are owned by the compiler pending-header builder, not interpreted here.
pub(crate) fn static_header_with_pending(
    syntax: CommentSyntax,
    generated_path: &str,
    active_transforms: Option<&str>,
    pending_transforms: &str,
) -> String {
    let mut output = static_header_block(syntax, generated_path);
    if let Some(payload) = active_transforms {
        output.push_str(&transforms_header(payload));
        output.push('\n');
    }
    output.push_str(&transforms_header(pending_transforms));
    output.push_str("\n\n");
    output
}

/// The three provenance header lines, each terminated — the block the
/// optional transforms header extends and the blank separator closes.
///
/// Split out because a reader that cannot know whether a header was written
/// (the wire tape gate reconstructs framing from provenance, which carries no
/// plan) must consume the fixed part first and then decide.
pub(crate) fn static_header_block(syntax: CommentSyntax, generated_path: &str) -> String {
    let mut output = String::new();
    for payload in header_payloads(generated_path) {
        output.push_str(&generated_comment(syntax, &payload, Layout::Inline));
        output.push('\n');
    }
    output
}

/// The active-transforms header comment (R4 architecture §7.1).
///
/// ONE spelling for both lanes, deliberately: the payload's tokens are
/// already encoded by the shared codec, so the comment carries no `--` and no
/// terminal `-` and is XML-comment-safe unconditionally — it needs neither
/// the `vibe:c1` wrapper the XML lane puts around free-form payloads nor a
/// second Markdown-only form. An HTML comment is lawful Markdown, so the same
/// bytes serve both.
pub(crate) fn transforms_header(payload: &str) -> String {
    format!("{GENERATED_COMMENT_OPEN}{payload}{GENERATED_COMMENT_CLOSE}")
}

pub(super) fn header_payloads(generated_path: &str) -> [String; 3] {
    [
        format!("{generated_path} — generated by vibe, do not edit."),
        "The static boot lane (PROP-009 §2.3): the highest-priority".to_string(),
        "contributions, compiled anchor-qualified. Read this first, in full.".to_string(),
    ]
}

pub(crate) fn resolution_preamble(syntax: CommentSyntax, source_root: &str) -> String {
    format!(
        "{}\n\n",
        generated_comment(syntax, &resolution_payload(source_root), Layout::Block)
    )
}

pub(super) fn resolution_payload(source_root: &str) -> String {
    format!(
        concat!(
            "RESOLUTION RULES — read these five lines before anything else:\n",
            "  1. Labels in this file are qualified: <origin-slug>--<original>. The origin\n",
            "     is named by the provenance comment above each block; the original short\n",
            "     label is the tail after the last `--`.\n",
            "  2. A short label you cannot find here → check the RENAMED ANCHORS table\n",
            "     below for its qualified heirs; never guess among look-alikes.\n",
            "  3. Full spec:// addresses resolve against package SOURCES under {}/,\n",
            "     never against this generated file. This file is a cache, not a target.\n",
            "  4. `#use spec://… as X` binds a file-local alias; `@!X` is a mandatory read\n",
            "     of X's target (same rules as @spec://…). In this compiled file every @!X\n",
            "     is already rewritten to its full address.\n",
            "  5. An ambiguous or unresolvable short reference is an ERROR to surface with\n",
            "     candidates — never silently pick one."
        ),
        source_root
    )
}

pub(crate) fn tombstone(syntax: CommentSyntax, renames: &[OriginRename]) -> String {
    format!(
        "{}\n\n",
        generated_comment(syntax, &tombstone_payload(renames), Layout::Block)
    )
}

pub(crate) fn tombstone_payload(renames: &[OriginRename]) -> String {
    let mut groups: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for entry in renames {
        groups
            .entry(entry.rename.original.clone())
            .or_default()
            .push((entry.origin.clone(), entry.rename.qualified.clone()));
    }
    let mut payload = String::from("RENAMED ANCHORS (short → qualified heirs):");
    for (short, mut heirs) in groups {
        heirs.sort();
        let listed = heirs
            .iter()
            .map(|(origin, qualified)| format!("{qualified} ({origin})"))
            .collect::<Vec<_>>()
            .join(", ");
        payload.push_str(&format!("\n  {short} → {listed}"));
    }
    payload
}

pub(crate) fn static_marker(syntax: CommentSyntax, meta: &ContributionMeta) -> String {
    generated_comment(syntax, &static_marker_payload(meta), Layout::Inline)
}

pub(crate) fn static_marker_payload(meta: &ContributionMeta) -> String {
    format!("vibe:static {} — {}", meta.origin, meta.path)
}

pub(crate) fn elided_marker(syntax: CommentSyntax, meta: &ContributionMeta) -> String {
    generated_comment(syntax, &elided_marker_payload(meta), Layout::Inline)
}

pub(crate) fn elided_marker_payload(meta: &ContributionMeta) -> String {
    format!(
        "vibe:static {} — {}; zone elided: emitted member-by-member in this lane (once-each, B-006)",
        meta.origin, meta.path
    )
}

pub(crate) fn hoisted_marker(syntax: CommentSyntax, origin: &str) -> String {
    generated_comment(syntax, &hoisted_marker_payload(origin), Layout::Inline)
}

/// The two halves of the hoisted contribution marker's payload, spelled once
/// so [`hoisted_marker_payload`] and [`hoisted_marker_origin`] cannot drift.
const HOISTED_MARKER_PREFIX: &str = "vibe:hoisted ";
const HOISTED_MARKER_SUFFIX: &str = " — text in the root STATIC.md";

pub(crate) fn hoisted_marker_payload(origin: &str) -> String {
    format!("{HOISTED_MARKER_PREFIX}{origin}{HOISTED_MARKER_SUFFIX}")
}

/// The origin one hoisted marker payload names, or `None` for any other
/// generated payload — the READER of the spelling directly above.
fn hoisted_origin_in_payload(payload: &str) -> Option<&str> {
    payload
        .strip_prefix(HOISTED_MARKER_PREFIX)?
        .strip_suffix(HOISTED_MARKER_SUFFIX)
}

/// The origin one GENERATED XML comment names as a hoisted contribution
/// marker, or `None` for any other comment.
///
/// A hoisted contribution writes a bare top-level `#use` line into the lane
/// rather than a document (`static_xml::emit_xml`), which is the one shape
/// the segmented emitted-tape adapter cannot minify honestly (R4
/// architecture §8). That adapter therefore has to recognise the marker —
/// and it asks the emit cell, which owns both the payload spelling and the
/// `vibe:c1` codec that carries it, rather than re-spelling either.
///
/// A non-`vibe:c1` comment (the §7.1 transforms header) carries no
/// contribution identity, and a malformed one is the wire tape gate's fault
/// to raise: answering `None` for both only ever preserves more bytes.
pub(crate) fn hoisted_origin_in_comment(comment: &str) -> Option<String> {
    let payload = vibe_specdoc::decode_generated_xml_comment(comment)
        .ok()
        .flatten()?;
    hoisted_origin_in_payload(&payload).map(str::to_owned)
}
