use std::collections::BTreeMap;

use super::super::ir::{ContributionMeta, OriginRename};

#[derive(Clone, Copy)]
pub(crate) enum CommentSyntax {
    Markdown,
    Xml,
}

#[derive(Clone, Copy)]
enum Layout {
    Inline,
    Block,
}

fn generated_comment(syntax: CommentSyntax, payload: &str, layout: Layout) -> String {
    if matches!(syntax, CommentSyntax::Xml) {
        return format!(
            "<!-- vibe:c1 {} -->",
            vibe_specdoc::encode_generated_xml_comment(payload)
        );
    }
    match layout {
        Layout::Inline => format!("<!-- {payload} -->"),
        Layout::Block => format!("<!-- {payload}\n-->"),
    }
}

/// The artifact's opening comment block: the three provenance lines, then —
/// only for a nonempty active plan — the transforms header, then the blank
/// line that closes the block.
///
/// `transforms` is the already-built header payload (R4 architecture §7.1),
/// `None` for the empty plan. Passing `None` reproduces the exact historical
/// bytes, which is why every owner that activates nothing keeps its committed
/// artifact byte-identical.
pub(crate) fn static_header(
    syntax: CommentSyntax,
    generated_path: &str,
    transforms: Option<&str>,
) -> String {
    let mut output = static_header_block(syntax, generated_path);
    if let Some(payload) = transforms {
        output.push_str(&transforms_header(payload));
        output.push('\n');
    }
    output.push('\n');
    output
}

/// The three provenance header lines, each terminated — the block the
/// optional transforms header extends and the blank separator closes.
///
/// Split out because a reader that cannot know whether a header was written
/// (the wire tape gate reconstructs framing from provenance, which carries no
/// plan) must consume the fixed part first and then decide.
pub(crate) fn static_header_block(syntax: CommentSyntax, generated_path: &str) -> String {
    let mut output = String::new();
    for payload in header_payloads(generated_path) {
        output.push_str(&generated_comment(syntax, &payload, Layout::Inline));
        output.push('\n');
    }
    output
}

/// The active-transforms header comment (R4 architecture §7.1).
///
/// ONE spelling for both lanes, deliberately: the payload's tokens are
/// already encoded by the shared codec, so the comment carries no `--` and no
/// terminal `-` and is XML-comment-safe unconditionally — it needs neither
/// the `vibe:c1` wrapper the XML lane puts around free-form payloads nor a
/// second Markdown-only form. An HTML comment is lawful Markdown, so the same
/// bytes serve both.
pub(crate) fn transforms_header(payload: &str) -> String {
    format!("<!-- {payload} -->")
}

pub(super) fn header_payloads(generated_path: &str) -> [String; 3] {
    [
        format!("{generated_path} — generated by vibe, do not edit."),
        "The static boot lane (PROP-009 §2.3): the highest-priority".to_string(),
        "contributions, compiled anchor-qualified. Read this first, in full.".to_string(),
    ]
}

pub(crate) fn resolution_preamble(syntax: CommentSyntax, source_root: &str) -> String {
    format!(
        "{}\n\n",
        generated_comment(syntax, &resolution_payload(source_root), Layout::Block)
    )
}

pub(super) fn resolution_payload(source_root: &str) -> String {
    format!(
        concat!(
            "RESOLUTION RULES — read these five lines before anything else:\n",
            "  1. Labels in this file are qualified: <origin-slug>--<original>. The origin\n",
            "     is named by the provenance comment above each block; the original short\n",
            "     label is the tail after the last `--`.\n",
            "  2. A short label you cannot find here → check the RENAMED ANCHORS table\n",
            "     below for its qualified heirs; never guess among look-alikes.\n",
            "  3. Full spec:// addresses resolve against package SOURCES under {}/,\n",
            "     never against this generated file. This file is a cache, not a target.\n",
            "  4. `#use spec://… as X` binds a file-local alias; `@!X` is a mandatory read\n",
            "     of X's target (same rules as @spec://…). In this compiled file every @!X\n",
            "     is already rewritten to its full address.\n",
            "  5. An ambiguous or unresolvable short reference is an ERROR to surface with\n",
            "     candidates — never silently pick one."
        ),
        source_root
    )
}

pub(crate) fn tombstone(syntax: CommentSyntax, renames: &[OriginRename]) -> String {
    format!(
        "{}\n\n",
        generated_comment(syntax, &tombstone_payload(renames), Layout::Block)
    )
}

pub(crate) fn tombstone_payload(renames: &[OriginRename]) -> String {
    let mut groups: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for entry in renames {
        groups
            .entry(entry.rename.original.clone())
            .or_default()
            .push((entry.origin.clone(), entry.rename.qualified.clone()));
    }
    let mut payload = String::from("RENAMED ANCHORS (short → qualified heirs):");
    for (short, mut heirs) in groups {
        heirs.sort();
        let listed = heirs
            .iter()
            .map(|(origin, qualified)| format!("{qualified} ({origin})"))
            .collect::<Vec<_>>()
            .join(", ");
        payload.push_str(&format!("\n  {short} → {listed}"));
    }
    payload
}

pub(crate) fn static_marker(syntax: CommentSyntax, meta: &ContributionMeta) -> String {
    generated_comment(syntax, &static_marker_payload(meta), Layout::Inline)
}

pub(crate) fn static_marker_payload(meta: &ContributionMeta) -> String {
    format!("vibe:static {} — {}", meta.origin, meta.path)
}

pub(crate) fn elided_marker(syntax: CommentSyntax, meta: &ContributionMeta) -> String {
    generated_comment(syntax, &elided_marker_payload(meta), Layout::Inline)
}

pub(crate) fn elided_marker_payload(meta: &ContributionMeta) -> String {
    format!(
        "vibe:static {} — {}; zone elided: emitted member-by-member in this lane (once-each, B-006)",
        meta.origin, meta.path
    )
}

pub(crate) fn hoisted_marker(syntax: CommentSyntax, origin: &str) -> String {
    generated_comment(syntax, &hoisted_marker_payload(origin), Layout::Inline)
}

pub(crate) fn hoisted_marker_payload(origin: &str) -> String {
    format!("vibe:hoisted {origin} — text in the root STATIC.md")
}
