//! Crash-safe publication of a generated directory.
//!
//! Generation happens in a fresh sibling directory on the same volume. The
//! live tree is not touched until every output tree for the run has finished.
//! Publication then follows the Windows-compatible two-rename sequence: move
//! the old tree aside, move the new tree into place, and remove the old tree.
//! If the second rename fails, the old tree is restored before the error is
//! returned. An abrupt process exit may leave complete `.new-*` / `.old-*`
//! siblings; the next run recovers an absent live tree and cleans the debris.

use std::ffi::OsStr;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use anyhow::{Context, Result, bail};

/// A fresh sibling tree waiting to replace `live`.
pub(crate) struct StagedOutputTree {
    live: PathBuf,
    fresh: PathBuf,
    old: PathBuf,
}

impl StagedOutputTree {
    /// Recover an interrupted prior swap, clean stale siblings, and create the
    /// fresh directory. The live tree's contents are never removed here.
    pub(crate) fn prepare(live: &Path) -> Result<Self> {
        let parent = live.parent().with_context(|| {
            format!(
                "{} has no parent; a generated tree needs a sibling staging area",
                live.display()
            )
        })?;
        let name = live.file_name().and_then(OsStr::to_str).with_context(|| {
            format!(
                "{} has no UTF-8 final component; cannot name sibling staging trees",
                live.display()
            )
        })?;
        fs::create_dir_all(parent)
            .with_context(|| format!("creating output parent {}", parent.display()))?;

        let new_prefix = format!("{name}.new-");
        let old_prefix = format!("{name}.old-");
        let (mut stale_new, mut stale_old) = stale_siblings(parent, &new_prefix, &old_prefix)?;

        if !live.exists() {
            recover_missing_live(live, &mut stale_new, &mut stale_old)?;
        }

        for stale in stale_new.iter().chain(stale_old.iter()) {
            if let Err(error) = remove_path(stale) {
                eprintln!(
                    "warning: could not remove stale codegen tree {}: {error:#}",
                    stale.display()
                );
            }
        }

        let suffix = unique_suffix()?;
        let fresh = parent.join(format!("{new_prefix}{suffix}"));
        let old = parent.join(format!("{old_prefix}{suffix}"));
        fs::create_dir(&fresh)
            .with_context(|| format!("creating fresh generated tree {}", fresh.display()))?;

        Ok(Self {
            live: live.to_path_buf(),
            fresh,
            old,
        })
    }

    /// The directory into which all generators and post-processors write.
    pub(crate) fn fresh(&self) -> &Path {
        &self.fresh
    }

    /// Publish the complete fresh tree. A failure to move the live tree is
    /// reported before it has changed; a failure to install the fresh tree
    /// triggers an immediate rollback of the old tree.
    pub(crate) fn install(self) -> Result<()> {
        let had_live = self.live.exists();
        if had_live {
            fs::rename(&self.live, &self.old).with_context(|| {
                format!(
                    "moving live generated tree {} aside to {} before publication; \
                     the live tree is unchanged if this rename fails (it may be locked by an IDE)",
                    self.live.display(),
                    self.old.display()
                )
            })?;
        }

        if let Err(install_error) = fs::rename(&self.fresh, &self.live) {
            if had_live {
                match fs::rename(&self.old, &self.live) {
                    Ok(()) => {
                        bail!(
                            "installing fresh generated tree {} at {} failed: {install_error}; \
                             restored the complete old tree",
                            self.fresh.display(),
                            self.live.display()
                        );
                    }
                    Err(rollback_error) => {
                        bail!(
                            "installing fresh generated tree {} at {} failed: {install_error}; \
                             restoring {} also failed: {rollback_error}. No generated bytes were \
                             deleted: the complete old and new trees remain at those sibling paths",
                            self.fresh.display(),
                            self.live.display(),
                            self.old.display()
                        );
                    }
                }
            }
            return Err(install_error).with_context(|| {
                format!(
                    "installing first generated tree {} at {}; the complete new tree remains beside it",
                    self.fresh.display(),
                    self.live.display()
                )
            });
        }

        if had_live && let Err(error) = remove_path(&self.old) {
            eprintln!(
                "warning: installed the new generated tree at {}, but could not remove old tree {}: {error:#}",
                self.live.display(),
                self.old.display()
            );
        }
        Ok(())
    }
}

fn stale_siblings(
    parent: &Path,
    new_prefix: &str,
    old_prefix: &str,
) -> Result<(Vec<PathBuf>, Vec<PathBuf>)> {
    let mut stale_new = Vec::new();
    let mut stale_old = Vec::new();
    for entry in fs::read_dir(parent).with_context(|| format!("scanning {}", parent.display()))? {
        let entry = entry.with_context(|| format!("reading entry under {}", parent.display()))?;
        let name = entry.file_name();
        let Some(name) = name.to_str() else {
            continue;
        };
        if name.starts_with(new_prefix) {
            stale_new.push(entry.path());
        } else if name.starts_with(old_prefix) {
            stale_old.push(entry.path());
        }
    }
    stale_new.sort();
    stale_old.sort();
    Ok((stale_new, stale_old))
}

/// An interruption between the two Windows renames leaves no canonical path,
/// but it leaves a complete old tree beside it. Restore that tree before any
/// cleanup. A first-ever generation may instead have only one complete new
/// tree. More than one candidate is ambiguous and is never resolved by
/// deleting data.
fn recover_missing_live(
    live: &Path,
    stale_new: &mut Vec<PathBuf>,
    stale_old: &mut Vec<PathBuf>,
) -> Result<()> {
    let candidate = if stale_old.len() == 1 {
        Some(stale_old.remove(0))
    } else if stale_old.is_empty() && stale_new.len() == 1 {
        Some(stale_new.remove(0))
    } else if stale_old.is_empty() && stale_new.is_empty() {
        None
    } else {
        bail!(
            "generated tree {} is absent and recovery is ambiguous: found {} old and {} new sibling trees. \
             Nothing was deleted; inspect those complete candidates and restore one to the live path",
            live.display(),
            stale_old.len(),
            stale_new.len()
        );
    };

    if let Some(candidate) = candidate {
        fs::rename(&candidate, live).with_context(|| {
            format!(
                "recovering missing generated tree {} from complete sibling {}",
                live.display(),
                candidate.display()
            )
        })?;
        eprintln!(
            "warning: recovered missing generated tree {} from interrupted-swap sibling {}",
            live.display(),
            candidate.display()
        );
    }
    Ok(())
}

fn unique_suffix() -> Result<String> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .context("system clock is before the Unix epoch")?
        .as_nanos();
    Ok(format!("{}-{now}", std::process::id()))
}

fn remove_path(path: &Path) -> Result<()> {
    let metadata = fs::symlink_metadata(path)
        .with_context(|| format!("reading stale path {}", path.display()))?;
    if metadata.is_dir() && !metadata.file_type().is_symlink() {
        fs::remove_dir_all(path).with_context(|| format!("removing directory {}", path.display()))
    } else {
        fs::remove_file(path).with_context(|| format!("removing file {}", path.display()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn read(path: &Path) -> Result<String> {
        fs::read_to_string(path).with_context(|| format!("reading {}", path.display()))
    }

    #[test]
    fn generation_does_not_touch_live_tree_before_install() -> Result<()> {
        let root = tempfile::tempdir()?;
        let live = root.path().join("generated");
        fs::create_dir(&live)?;
        fs::write(live.join("old.rs"), "old")?;

        let staged = StagedOutputTree::prepare(&live)?;
        fs::write(staged.fresh().join("new.rs"), "new")?;

        assert_eq!(read(&live.join("old.rs"))?, "old");
        assert!(!live.join("new.rs").exists());
        Ok(())
    }

    #[test]
    fn install_swaps_complete_tree_and_removes_old_sibling() -> Result<()> {
        let root = tempfile::tempdir()?;
        let live = root.path().join("generated");
        fs::create_dir(&live)?;
        fs::write(live.join("old.rs"), "old")?;

        let staged = StagedOutputTree::prepare(&live)?;
        fs::write(staged.fresh().join("new.rs"), "new")?;
        staged.install()?;

        assert!(!live.join("old.rs").exists());
        assert_eq!(read(&live.join("new.rs"))?, "new");
        assert_eq!(fs::read_dir(root.path())?.count(), 1);
        Ok(())
    }

    #[test]
    fn failed_second_rename_restores_old_tree() -> Result<()> {
        let root = tempfile::tempdir()?;
        let live = root.path().join("generated");
        fs::create_dir(&live)?;
        fs::write(live.join("old.rs"), "old")?;

        let staged = StagedOutputTree::prepare(&live)?;
        fs::remove_dir_all(staged.fresh())?;
        let error = staged.install().expect_err("missing fresh tree must fail");

        assert!(error.to_string().contains("restored the complete old tree"));
        assert_eq!(read(&live.join("old.rs"))?, "old");
        Ok(())
    }

    #[test]
    fn prepare_recovers_old_tree_left_between_renames() -> Result<()> {
        let root = tempfile::tempdir()?;
        let live = root.path().join("generated");
        let old = root.path().join("generated.old-interrupted");
        let fresh = root.path().join("generated.new-interrupted");
        fs::create_dir(&old)?;
        fs::write(old.join("old.rs"), "old")?;
        fs::create_dir(&fresh)?;
        fs::write(fresh.join("new.rs"), "new")?;

        let staged = StagedOutputTree::prepare(&live)?;

        assert_eq!(read(&live.join("old.rs"))?, "old");
        assert!(!fresh.exists());
        assert!(staged.fresh().exists());
        Ok(())
    }
}
