//! REDs for truthful compiler-pending artifact finalization.

use std::sync::{Arc, Mutex};

use vibe_core::manifest::ExtensionKey;

use crate::compiler::builtin::{
    compile_artifact_native_managed, compile_artifact_native_managed_observed,
};
use crate::compiler::emit::{emitted_bytes_digest, framing};
use crate::compiler::ir::{
    ArtifactContext, ArtifactFrame, ArtifactId, ArtifactInput, ArtifactPlan, ArtifactTarget,
    EmittedArtifact, StaticCompileMode, emitted_output_fingerprint,
};
use crate::compiler::observer::{CompileObserver, EmissionEvent, StageDeltaEvent, defer_emission};
use crate::compiler::pass::PassName;
use crate::{SectionSource, SpecAddress};

use super::header::transforms_header_payload;
use super::lowering_worlds::Declared;
use super::native_finalize::{compiler_pending_header_payload, finalize_compiler_pending_artifact};
use super::native_manager_test_support::{FakeInvoker, ReplyMode, plan as lowered_plan};
use super::native_policy::{
    CompilerNativeOutcome, CompilerNativePolicy, CompilerPendingArtifact, CompilerPendingSet,
};
use super::plan::TransformPlan;

const IDS: [&str; 4] = ["first", "middle", "later", "last"];
const KEYS: [&str; 4] = [
    "__host__/demo#first",
    "__host__/demo#middle",
    "__host__/demo#later",
    "__host__/demo#last",
];
const FINGERPRINT: [u8; 32] = [0x11; 32];
const BODY: &str = "# Body {#root}\n\ntruth\n";

struct EmptySource;

impl SectionSource for EmptySource {
    fn section_text(&self, _address: &SpecAddress) -> Result<String, String> {
        Ok(String::new())
    }
}

fn transforms(extra: bool) -> TransformPlan {
    let mut declared = IDS
        .iter()
        .map(|id| Declared::native(id, "compile:emitted"))
        .collect::<Vec<_>>();
    if extra {
        declared.push(Declared::native("extra", "compile:lane"));
    }
    lowered_plan(declared).transforms().clone()
}

fn artifact_plan(target: ArtifactTarget, transforms: TransformPlan) -> ArtifactPlan {
    let path = if target == ArtifactTarget::StaticXml {
        "vibevm/vibespecs/boot/STATIC.xml"
    } else {
        "vibevm/vibespecs/boot/STATIC.md"
    };
    ArtifactPlan::static_lane(
        target,
        path,
        "vibevm/vibedeps",
        vec![ArtifactInput::simple("host", "boot/body.md", BODY).unwrap()],
    )
    .unwrap()
    .with_transforms(transforms)
}

fn collect(target: ArtifactTarget, mode: ReplyMode) -> (TransformPlan, CompilerPendingArtifact) {
    let transforms = transforms(false);
    let outcome = compile_artifact_native_managed(
        artifact_plan(target, transforms.clone()),
        &EmptySource,
        &FakeInvoker::new(mode),
        CompilerNativePolicy::collect(),
    )
    .unwrap();
    match outcome {
        CompilerNativeOutcome::Pending(pending) => (transforms, pending),
        CompilerNativeOutcome::Ready(_) => panic!("fixture must collect pending state"),
    }
}

fn wrap(artifact: EmittedArtifact, pending: CompilerPendingSet) -> CompilerPendingArtifact {
    match CompilerNativeOutcome::pending(artifact, pending) {
        CompilerNativeOutcome::Pending(pending) => pending,
        CompilerNativeOutcome::Ready(_) => unreachable!(),
    }
}

fn opening(bytes: &[u8]) -> &str {
    std::str::from_utf8(bytes)
        .unwrap()
        .split_once("\n\n")
        .unwrap()
        .0
}

fn expected_opening(target: &ArtifactTarget, pending_orders: &[u32]) -> String {
    let path = if target == &ArtifactTarget::StaticXml {
        "vibevm/vibespecs/boot/STATIC.xml"
    } else {
        "vibevm/vibespecs/boot/STATIC.md"
    };
    let channel = if target == &ArtifactTarget::StaticXml {
        "vibe:c1 "
    } else {
        ""
    };
    let mut lines = vec![
        format!("<!-- {channel}{path} — generated by vibe, do not edit. -->"),
        format!("<!-- {channel}The static boot lane (PROP-009 §2.3): the highest-priority -->"),
        format!(
            "<!-- {channel}contributions, compiled anchor-qualified. Read this first, in full. -->"
        ),
    ];
    let active = KEYS
        .iter()
        .enumerate()
        .filter(|(order, _)| !pending_orders.contains(&(*order as u32)))
        .map(|(_, key)| *key)
        .collect::<Vec<_>>();
    if !active.is_empty() {
        lines.push(format!("<!-- vibe:transforms {} -->", active.join(" ")));
    }
    let pending = pending_orders
        .iter()
        .map(|order| format!("{order}={}", KEYS[*order as usize]))
        .collect::<Vec<_>>()
        .join(" ");
    lines.push(format!(
        "<!-- vibe:transforms-pending sha256:{} {pending} -->",
        "11".repeat(32)
    ));
    lines.join("\n")
}

#[derive(Default)]
struct EmissionCollector {
    emissions: Mutex<Vec<EmissionEvent>>,
}

impl CompileObserver for EmissionCollector {
    fn emission(&self, event: &EmissionEvent) {
        self.emissions.lock().unwrap().push(event.clone());
    }

    fn stage_delta(&self, _event: &StageDeltaEvent) {}
}

#[test]
fn pending_finalization_delivers_only_final_byte_consistent_emission_evidence() {
    let transforms = transforms(false);
    let downstream = Arc::new(EmissionCollector::default());
    let (observer, completion) = defer_emission(downstream.clone());
    let outcome = compile_artifact_native_managed_observed(
        artifact_plan(ArtifactTarget::StaticMarkdown, transforms.clone()),
        &EmptySource,
        &FakeInvoker::new(ReplyMode::BuildableOrder(1)),
        CompilerNativePolicy::collect(),
        observer,
    )
    .unwrap();
    let pending = match outcome {
        CompilerNativeOutcome::Pending(pending) => pending,
        CompilerNativeOutcome::Ready(_) => panic!("fixture must remain pending"),
    };
    let provisional_len = pending.artifact_for_test().bytes().len();
    assert!(downstream.emissions.lock().unwrap().is_empty());

    let finalized = finalize_compiler_pending_artifact(pending, &transforms, &FINGERPRINT).unwrap();
    let final_len = finalized.artifact().bytes().len();
    assert_ne!(
        final_len, provisional_len,
        "pending framing moves total bytes"
    );
    completion.deliver(finalized.artifact());

    let emissions = downstream.emissions.lock().unwrap();
    assert_eq!(emissions.len(), 1);
    let event = &emissions[0];
    assert_eq!(event.total_bytes(), final_len);
    assert_ne!(event.total_bytes(), provisional_len);
    let contribution_bytes = event
        .contributions()
        .iter()
        .map(|row| row.bytes())
        .fold(0usize, usize::saturating_add);
    assert_eq!(
        event.frame_bytes(),
        final_len.saturating_sub(contribution_bytes)
    );
}

#[test]
fn markdown_and_xml_first_middle_last_and_all_have_hard_truthful_openings() {
    for target in [ArtifactTarget::StaticMarkdown, ArtifactTarget::StaticXml] {
        for (mode, orders) in [
            (ReplyMode::BuildableOrder(0), vec![0]),
            (ReplyMode::BuildableOrder(1), vec![1]),
            (ReplyMode::BuildableOrder(3), vec![3]),
            (ReplyMode::BuildableSourceUnavailable, vec![0, 1, 2, 3]),
        ] {
            let (plan, provisional) = collect(target.clone(), mode);
            let full = transforms_header_payload(&plan).unwrap();
            assert!(
                opening(provisional.artifact_for_test().bytes()).contains(&full),
                "emitted-stage pending is learned only after the full active header exists"
            );
            let finalized =
                finalize_compiler_pending_artifact(provisional, &plan, &FINGERPRINT).unwrap();
            assert_eq!(
                opening(finalized.artifact().bytes()),
                expected_opening(&target, &orders),
                "{target:?} pending {orders:?}"
            );
        }
    }
}

#[test]
fn finalization_preserves_body_and_provenance_and_recomputes_only_output_digest() {
    let (plan, provisional) = collect(ArtifactTarget::StaticMarkdown, ReplyMode::BuildableOrder(1));
    let (mut artifact, pending) = provisional.into_parts();
    artifact
        .provenance
        .emitted_transforms
        .push(PassName::new("compile:emitted:executed").unwrap());
    let before_bytes = artifact.bytes().to_vec();
    let before_provenance = artifact.provenance().clone();
    let expected = framing::static_header(
        framing::CommentSyntax::Markdown,
        "vibevm/vibespecs/boot/STATIC.md",
        transforms_header_payload(&plan).as_deref(),
    );
    let body = before_bytes
        .strip_prefix(expected.as_bytes())
        .unwrap()
        .to_vec();
    let provisional_fingerprint = artifact.output_fingerprint();

    let finalized =
        finalize_compiler_pending_artifact(wrap(artifact, pending), &plan, &FINGERPRINT).unwrap();
    assert!(finalized.artifact().bytes().ends_with(&body));
    assert!(
        std::str::from_utf8(&body).unwrap().contains("truth"),
        "the preserved suffix contains the fixture body"
    );
    assert_ne!(
        finalized.artifact().output_fingerprint(),
        provisional_fingerprint
    );
    assert_eq!(
        finalized.artifact().output_fingerprint(),
        emitted_output_fingerprint(finalized.artifact().bytes())
    );
    let mut expected_provenance = before_provenance;
    expected_provenance.bytes_digest = emitted_bytes_digest(finalized.artifact().bytes());
    assert_eq!(finalized.artifact().provenance(), &expected_provenance);
    assert_eq!(
        finalized.artifact().provenance.emitted_transforms,
        [PassName::new("compile:emitted:executed").unwrap()]
    );
}

#[test]
fn every_opening_region_and_a_moved_global_duplicate_refuse() {
    for needle in [
        "generated by vibe",
        "highest-priority",
        "anchor-qualified",
        "vibe:transforms ",
        "\n\n",
    ] {
        let (plan, provisional) =
            collect(ArtifactTarget::StaticMarkdown, ReplyMode::BuildableOrder(2));
        let (mut artifact, pending) = provisional.into_parts();
        let position = std::str::from_utf8(artifact.bytes())
            .unwrap()
            .find(needle)
            .unwrap();
        artifact.bytes[position] ^= 1;
        assert!(
            finalize_compiler_pending_artifact(wrap(artifact, pending), &plan, &FINGERPRINT,)
                .is_err(),
            "tampered region {needle:?}"
        );
    }

    let (plan, provisional) = collect(ArtifactTarget::StaticXml, ReplyMode::BuildableOrder(2));
    let (mut artifact, pending) = provisional.into_parts();
    let duplicate = artifact.bytes().to_vec();
    artifact.bytes[0] = b'X';
    artifact.bytes.extend_from_slice(&duplicate);
    assert!(
        finalize_compiler_pending_artifact(wrap(artifact, pending), &plan, &FINGERPRINT).is_err(),
        "a valid opening later in the tape is never searched for"
    );

    let (plan, provisional) = collect(ArtifactTarget::StaticMarkdown, ReplyMode::BuildableOrder(2));
    let (mut artifact, pending) = provisional.into_parts();
    let duplicate_full_active_opening = framing::static_header(
        framing::CommentSyntax::Markdown,
        "vibevm/vibespecs/boot/STATIC.md",
        transforms_header_payload(&plan).as_deref(),
    );
    artifact
        .bytes
        .extend_from_slice(duplicate_full_active_opening.as_bytes());
    assert!(
        finalize_compiler_pending_artifact(wrap(artifact, pending), &plan, &FINGERPRINT).is_err(),
        "an untouched valid opening cannot launder duplicate reserved framing in its suffix"
    );
}

fn pending_from_entries(
    plan: &TransformPlan,
    entries: Vec<(u32, ExtensionKey)>,
) -> CompilerPendingSet {
    CompilerPendingSet::from_plan_entries_for_test(plan, entries).unwrap()
}

fn manual_pending(
    context: ArtifactContext,
    plan: &TransformPlan,
    pending: CompilerPendingSet,
) -> CompilerPendingArtifact {
    let target = context.target();
    let syntax = if target == ArtifactTarget::StaticXml {
        framing::CommentSyntax::Xml
    } else {
        framing::CommentSyntax::Markdown
    };
    let generated_path = match context.frame() {
        ArtifactFrame::StaticLane { generated_path, .. } => generated_path.as_str(),
        ArtifactFrame::CompatibilityFragment => "compatibility.md",
    };
    let bytes = framing::static_header(
        syntax,
        generated_path,
        transforms_header_payload(plan).as_deref(),
    )
    .into_bytes();
    wrap(EmittedArtifact::testing(context, bytes), pending)
}

#[test]
fn wrong_plan_order_key_and_nonstatic_contexts_refuse_before_artifact_escape() {
    let plan = transforms(false);
    let key0 = ExtensionKey::authored(KEYS[0]);
    let key1 = ExtensionKey::authored(KEYS[1]);
    let static_context = ArtifactContext::new(
        ArtifactId::new("static-md").unwrap(),
        ArtifactTarget::StaticMarkdown,
        ArtifactFrame::StaticLane {
            generated_path: "vibevm/vibespecs/boot/STATIC.md".into(),
            source_root: "vibevm/vibedeps".into(),
        },
        StaticCompileMode::QualifyPerNode,
    )
    .unwrap();
    for set in [
        pending_from_entries(
            &plan,
            vec![(0, ExtensionKey::authored("__host__/demo#wrong"))],
        ),
        pending_from_entries(&plan, vec![(1, key0.clone())]),
    ] {
        assert!(
            finalize_compiler_pending_artifact(
                manual_pending(static_context.clone(), &plan, set),
                &plan,
                &FINGERPRINT,
            )
            .is_err()
        );
    }
    let other = transforms(true);
    let other_set = pending_from_entries(&other, vec![(1, key1)]);
    assert!(
        finalize_compiler_pending_artifact(
            manual_pending(static_context, &plan, other_set),
            &plan,
            &FINGERPRINT,
        )
        .is_err()
    );

    for context in [
        ArtifactContext::compatibility(StaticCompileMode::Plain),
        ArtifactContext::testing(
            ArtifactId::new("custom").unwrap(),
            ArtifactTarget::custom("custom").unwrap(),
            ArtifactFrame::CompatibilityFragment,
            StaticCompileMode::Plain,
        ),
        ArtifactContext::testing(
            ArtifactId::new("custom-static").unwrap(),
            ArtifactTarget::custom("custom-static").unwrap(),
            ArtifactFrame::StaticLane {
                generated_path: "STATIC.custom".into(),
                source_root: "sources".into(),
            },
            StaticCompileMode::QualifyPerNode,
        ),
        ArtifactContext::testing(
            ArtifactId::new("forged-static").unwrap(),
            ArtifactTarget::StaticMarkdown,
            ArtifactFrame::StaticLane {
                generated_path: "STATIC.md".into(),
                source_root: "sources".into(),
            },
            StaticCompileMode::QualifyPerNode,
        ),
    ] {
        let set = pending_from_entries(&plan, vec![(0, ExtensionKey::authored(KEYS[0]))]);
        assert!(
            finalize_compiler_pending_artifact(
                manual_pending(context, &plan, set),
                &plan,
                &FINGERPRINT,
            )
            .is_err()
        );
    }
}

#[test]
fn header_authority_finalized_ownership_and_debug_surface_are_bounded() {
    let plan = transforms(false);
    let empty = pending_from_entries(&plan, Vec::new());
    assert!(compiler_pending_header_payload(&empty, &FINGERPRINT).is_err());
    let set = pending_from_entries(
        &plan,
        vec![(
            0,
            ExtensionKey::authored("__host__/demo#dash--percent%tail-"),
        )],
    );
    let payload = compiler_pending_header_payload(&set, &FINGERPRINT).unwrap();
    assert_eq!(
        payload,
        format!(
            "vibe:transforms-pending sha256:{} 0=__host__/demo#dash-%2Dpercent%25tail%2D",
            "11".repeat(32)
        )
    );
    assert!(!payload.contains("--"));
    assert!(!payload.ends_with('-'));

    let (plan, provisional) = collect(ArtifactTarget::StaticMarkdown, ReplyMode::BuildableOrder(0));
    let provisional_debug = format!("{provisional:?}");
    assert!(!provisional_debug.contains(BODY));
    let finalized = finalize_compiler_pending_artifact(provisional, &plan, &FINGERPRINT).unwrap();
    let finalized_debug = format!("{finalized:?}");
    assert!(!finalized_debug.contains(BODY));
    assert!(!finalized_debug.contains(&finalized.artifact().output_fingerprint()));
    let (_artifact, expected) = finalized.into_parts();
    let resolve = CompilerNativePolicy::resolve(expected);
    assert!(format!("{resolve:?}").contains("Resolve"));

    let finalizer = include_str!("native_policy/finalize.rs");
    for forbidden in [
        "std::fs",
        "std::path",
        "vibe_workspace",
        "vibe_lifecycle",
        "Cargo",
        "parse_pending",
        "recover",
    ] {
        assert!(!finalizer.contains(forbidden), "forbidden {forbidden}");
    }
    let workspace = include_str!("../../../../vibe-workspace/src/extension_world/pending.rs");
    assert!(!workspace.contains("vibe:transforms-pending"));
    assert!(!workspace.contains("encode_generated_xml_comment"));
    assert!(workspace.contains("compiler_pending_header_payload"));
}
