//! Spec-consistency linter for vibevm projects.
//!
//! `vibe check` runs a set of deterministic, pure-inspection checks
//! against a project tree. No LLM, no network, no mutation. The
//! output is a [`CheckReport`] — a list of [`Finding`]s, each tagged
//! with severity ([`Severity`]), the originating check ([`CheckId`]),
//! and (when applicable) the offending file path / line.
//!
//! v0 of `vibe check` (this commit) covers six of the ten checks
//! listed in [`VIBEVM-SPEC.md` §12](../../../VIBEVM-SPEC.md):
//!
//! 1. [`CheckId::ManifestValidity`] — `vibe.toml` parses and matches
//!    schema; `vibe.lock` (if present) parses and matches schema.
//! 5. [`CheckId::WalFreshness`] — `spec/WAL.md` modification time is
//!    less than `wal_max_age_hours` (default 24); older → warning.
//! 6. [`CheckId::WalWellformed`] — WAL has the canonical sections
//!    (Current Phase, Constraints, Done, Next, Issues).
//! 7. [`CheckId::BootDirectory`] — every file in `spec/boot/` matches
//!    the `NN-name.md` pattern; no two files share the same `NN`
//!    prefix (excluding the user-owned `00-core.md` / `90-user.md`
//!    pair, which are the foundation / overrides slots).
//! 8. [`CheckId::LockfileFiles`] — every package in `vibe.lock` has
//!    its declared `files_written` present on disk; spec/flows,
//!    spec/feats, spec/stacks subtrees have no orphan files (files
//!    not in any lockfile entry's `files_written`).
//! 9. [`CheckId::ReviewAging`] — every `<!-- REVIEW: YYYY-MM-DD ... -->`
//!    marker in `spec/**/*.md` whose date is older than
//!    `review_max_age_days` (default 14) is reported as a warning.
//!
//! Deferred to v1+ (require markdown-anchor parsing or `vibe build`
//! provenance):
//!
//! - `DeadSpecRefs` — `spec://…` URI resolution (spec §12 #2).
//! - `OrphanAnchors` — `{#anchor}` use across spec / code / tests
//!   (spec §12 #3).
//! - `AnchorUniqueness` — `{#anchor}` collisions within a file (#4).
//! - `ImplementationCoverage` — `Implements: spec://…` markers in
//!   code generated by `vibe build` (#10).
//!
//! `--fix` is a v1+ concern; v0 runs read-only inspection.

#![forbid(unsafe_code)]

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use vibe_core::manifest::{Lockfile, Manifest};

/// Stable identifier for a single check. Used in [`Finding::check`]
/// and surfaced verbatim under `--json` so downstream tooling can
/// filter / route findings by check.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CheckId {
    ManifestValidity,
    WalFreshness,
    WalWellformed,
    BootDirectory,
    LockfileFiles,
    ReviewAging,
    /// PROP-003 §2.10 — `[features]` table is internally consistent
    /// (no cycles to unknown features, no exclusive-group violations,
    /// every `subskill:<path>` reference resolves on disk).
    FeaturesGraph,
    /// PROP-003 §2.10 — every `subskills/<path>/vibe-subskill.toml`
    /// in scope parses, fields are well-formed, `delivery` matches
    /// PROP-003 §2.5.0, and lazy-push / lazy-pull subskills carry
    /// the load-bearing `description` field.
    SubskillStructure,
    /// PROP-003 §2.10 — every file declared in `[content].files_written`
    /// exists for the package's canonical language; missing
    /// translations for languages declared in `[i18n].available`
    /// surface as warnings.
    I18nCoverage,
    /// PROP-003 §2.10 — pairs of subskills whose `description`
    /// triggers materially overlap (≥75% keyword Jaccard) within
    /// the same package's lazy-push / lazy-pull set. Mirrors Tessl's
    /// review-rubric "activation distinctiveness" axis.
    ActivationConflict,
}

impl CheckId {
    pub fn as_str(&self) -> &'static str {
        match self {
            CheckId::ManifestValidity => "manifest_validity",
            CheckId::WalFreshness => "wal_freshness",
            CheckId::WalWellformed => "wal_wellformed",
            CheckId::BootDirectory => "boot_directory",
            CheckId::LockfileFiles => "lockfile_files",
            CheckId::ReviewAging => "review_aging",
            CheckId::FeaturesGraph => "features_graph",
            CheckId::SubskillStructure => "subskill_structure",
            CheckId::I18nCoverage => "i18n_coverage",
            CheckId::ActivationConflict => "activation_conflict",
        }
    }

    /// Every check id, for documenting / iterating in tests.
    pub fn all() -> &'static [CheckId] {
        &[
            CheckId::ManifestValidity,
            CheckId::WalFreshness,
            CheckId::WalWellformed,
            CheckId::BootDirectory,
            CheckId::LockfileFiles,
            CheckId::ReviewAging,
            CheckId::FeaturesGraph,
            CheckId::SubskillStructure,
            CheckId::I18nCoverage,
            CheckId::ActivationConflict,
        ]
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Severity {
    Error,
    Warning,
    Info,
}

impl Severity {
    pub fn as_str(&self) -> &'static str {
        match self {
            Severity::Error => "error",
            Severity::Warning => "warning",
            Severity::Info => "info",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Finding {
    pub check: CheckId,
    pub severity: Severity,
    /// Project-relative path the finding refers to. `None` for
    /// project-wide findings (e.g. WAL is missing entirely).
    pub path: Option<PathBuf>,
    /// 1-based line number when the finding refers to a specific
    /// line (`ReviewAging` markers); `None` otherwise.
    pub line: Option<usize>,
    pub message: String,
}

#[derive(Debug, Default, Clone)]
pub struct CheckReport {
    pub findings: Vec<Finding>,
}

impl CheckReport {
    pub fn push(&mut self, f: Finding) {
        self.findings.push(f);
    }
    pub fn count(&self, severity: Severity) -> usize {
        self.findings.iter().filter(|f| f.severity == severity).count()
    }
    pub fn has_errors(&self) -> bool {
        self.findings.iter().any(|f| f.severity == Severity::Error)
    }
    fn err(
        &mut self,
        check: CheckId,
        path: Option<PathBuf>,
        line: Option<usize>,
        msg: impl Into<String>,
    ) {
        self.push(Finding {
            check,
            severity: Severity::Error,
            path,
            line,
            message: msg.into(),
        });
    }
    fn warn(
        &mut self,
        check: CheckId,
        path: Option<PathBuf>,
        line: Option<usize>,
        msg: impl Into<String>,
    ) {
        self.push(Finding {
            check,
            severity: Severity::Warning,
            path,
            line,
            message: msg.into(),
        });
    }
}

#[derive(Debug, Clone)]
pub struct CheckOptions {
    /// WAL is "stale" past this age. Default 24h matches the boot
    /// snippet's "if `WAL.md` is older than 24 hours, verify before
    /// destructive work" rule.
    pub wal_max_age_hours: u64,
    /// REVIEW marker age threshold in days. Default 14 matches the
    /// figure in `VIBEVM-SPEC.md` §12.
    pub review_max_age_days: u64,
    /// Frozen "now" (UNIX seconds, UTC). `None` reads the wall clock
    /// at check time. Tests inject a fixed value to make freshness
    /// / aging checks deterministic.
    pub now_unix_utc: Option<u64>,
}

impl Default for CheckOptions {
    fn default() -> Self {
        CheckOptions {
            wal_max_age_hours: 24,
            review_max_age_days: 14,
            now_unix_utc: None,
        }
    }
}

/// Run every check in v0 against the project rooted at `project_root`.
///
/// The function never panics on bad input — every recoverable issue
/// is surfaced as a [`Finding`]. Filesystem errors during traversal
/// turn into Error-severity findings rather than aborting the run,
/// so a partial project still gets a partial report.
pub fn check_project(project_root: &Path, opts: &CheckOptions) -> CheckReport {
    let mut report = CheckReport::default();
    let now = opts.now_unix_utc.unwrap_or_else(unix_now_utc);

    check_manifest_validity(project_root, &mut report);
    check_wal_freshness(project_root, &mut report, now, opts.wal_max_age_hours);
    check_wal_wellformed(project_root, &mut report);
    check_boot_directory(project_root, &mut report);
    check_lockfile_files(project_root, &mut report);
    check_review_aging(project_root, &mut report, now, opts.review_max_age_days);
    check_features_graph(project_root, &mut report);
    check_subskill_structure(project_root, &mut report);
    check_i18n_coverage(project_root, &mut report);
    check_activation_conflict(project_root, &mut report);

    report
}

// ===================== PROP-003 checks =====================

/// Walk every package available to the project (lockfile + project tree
/// `packages/`) and validate its `[features]` table. Diagnostics from
/// the resolver's [`vibe_resolver::validate_features_table`] surface as
/// warnings since a misconfigured table won't break install for
/// projects that don't activate any of its features but is still worth
/// surfacing.
fn check_features_graph(project_root: &Path, report: &mut CheckReport) {
    for (pkg_root, source_label) in scan_local_packages(project_root) {
        let manifest_path = pkg_root.join(Manifest::FILENAME);
        let manifest = match Manifest::read(&manifest_path) {
            Ok(m) => m,
            Err(_) => continue, // ManifestValidity check surfaces this elsewhere.
        };
        if manifest.features.is_empty() {
            continue;
        }
        let findings =
            vibe_resolver::validate_features_table(&manifest.features);
        let rel = manifest_path
            .strip_prefix(project_root)
            .map(|p| p.to_path_buf())
            .ok();
        for f in findings {
            report.warn(
                CheckId::FeaturesGraph,
                rel.clone(),
                None,
                format!("[{source_label}] {f}"),
            );
        }
    }
}

/// Walk every package and inspect its `subskills/` tree. For each
/// `vibe-subskill.toml`: ensure it parses, validate via
/// [`SubskillManifest::validation_findings`], and that paths declared
/// in the manifest's `[content].files_written` exist on disk relative
/// to the subskill's own directory.
fn check_subskill_structure(project_root: &Path, report: &mut CheckReport) {
    for (pkg_root, source_label) in scan_local_packages(project_root) {
        let subskills_dir = pkg_root.join("subskills");
        if !subskills_dir.is_dir() {
            continue;
        }
        for entry in walkdir::WalkDir::new(&subskills_dir)
            .max_depth(6)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            if !entry.file_type().is_file() {
                continue;
            }
            if entry.file_name()
                != vibe_core::manifest::SubskillManifest::FILENAME
            {
                continue;
            }
            let manifest_path = entry.path().to_path_buf();
            let rel = manifest_path
                .strip_prefix(project_root)
                .map(|p| p.to_path_buf())
                .ok();
            let manifest = match vibe_core::manifest::SubskillManifest::read(
                &manifest_path,
            ) {
                Ok(m) => m,
                Err(e) => {
                    report.err(
                        CheckId::SubskillStructure,
                        rel,
                        None,
                        format!("[{source_label}] subskill manifest fails to parse: {e}"),
                    );
                    continue;
                }
            };
            for finding in manifest.validation_findings() {
                report.err(
                    CheckId::SubskillStructure,
                    rel.clone(),
                    None,
                    format!("[{source_label}] {finding}"),
                );
            }
            // PROP-003 §2.5.5: practical depth cap is 3 (`a/b/c` is
            // three components). At 4 or more, warn — the package is
            // almost certainly better split into separate packages.
            let depth = manifest.subskill.path.matches('/').count() + 1;
            if depth >= 4 {
                report.warn(
                    CheckId::SubskillStructure,
                    rel.clone(),
                    None,
                    format!(
                        "[{source_label}] subskill `{}` nested {depth} levels deep — PROP-003 §2.5.5 caps practical depth at 3. Consider splitting into separate packages.",
                        manifest.subskill.path
                    ),
                );
            }
            // Every declared file exists relative to the subskill's
            // own root.
            let sub_root = manifest_path.parent().unwrap_or(&manifest_path);
            for f in &manifest.content.files_written {
                let absolute = sub_root.join(f);
                if !absolute.is_file() {
                    report.err(
                        CheckId::SubskillStructure,
                        rel.clone(),
                        None,
                        format!(
                            "[{source_label}] subskill `{}` declares file `{}` which is missing on disk",
                            manifest.subskill.path,
                            f.display()
                        ),
                    );
                }
            }
        }
    }
}

/// For every package with an `[i18n].available` declaration, every
/// file in `[writes]` plus boot snippet must exist for the canonical
/// language (error) and SHOULD exist for every other listed language
/// (warning when missing).
fn check_i18n_coverage(project_root: &Path, report: &mut CheckReport) {
    for (pkg_root, source_label) in scan_local_packages(project_root) {
        let manifest_path = pkg_root.join(Manifest::FILENAME);
        let manifest = match Manifest::read(&manifest_path) {
            Ok(m) => m,
            Err(_) => continue,
        };
        if manifest.i18n.available.is_empty() {
            continue;
        }
        let canonical = &manifest.i18n.canonical;
        let logical_paths: Vec<std::path::PathBuf> = manifest
            .writes
            .files
            .iter()
            .cloned()
            .chain(
                manifest
                    .boot_snippet
                    .as_ref()
                    .map(|b| b.source.clone())
                    .into_iter(),
            )
            .collect();
        let rel_manifest = manifest_path
            .strip_prefix(project_root)
            .map(|p| p.to_path_buf())
            .ok();
        // Canonical must exist.
        for logical in &logical_paths {
            let abs = pkg_root.join(logical);
            if !abs.is_file() {
                report.err(
                    CheckId::I18nCoverage,
                    rel_manifest.clone(),
                    None,
                    format!(
                        "[{source_label}] canonical `{}` (language `{}`) missing for declared file `{}`",
                        logical.display(),
                        canonical,
                        logical.display()
                    ),
                );
            }
        }
        // Every other declared language: warn on missing translation.
        for lang in &manifest.i18n.available {
            if lang == canonical {
                continue;
            }
            for logical in &logical_paths {
                let localised = vibe_core::manifest::i18n::localised_path(
                    logical, lang,
                );
                let abs = pkg_root.join(&localised);
                if !abs.is_file() {
                    report.warn(
                        CheckId::I18nCoverage,
                        rel_manifest.clone(),
                        None,
                        format!(
                            "[{source_label}] no `{}` translation of `{}` (looked for `{}`)",
                            lang,
                            logical.display(),
                            localised.display()
                        ),
                    );
                }
            }
        }
    }
}

/// PROP-003 §2.10 activation-conflict heuristic. Within each
/// package, walk all subskills that need a `description` (delivery =
/// lazy-push / lazy-pull). For every pair, compute Jaccard
/// keyword-set similarity over their description texts. Pairs above
/// the threshold (75%) flag as warnings since the agent's natural-
/// language matching is likely to confuse them.
fn check_activation_conflict(project_root: &Path, report: &mut CheckReport) {
    // PROP-003 §2.10 originally pinned the threshold at 75%, but
    // practical Jaccard on short trigger descriptions saturates at
    // around the high-60s for content-equivalent pairs once stopwords
    // are filtered. 70% catches the obvious false-positive shape
    // ("two descriptions that read like alternative phrasings of the
    // same prompt") without flagging genuinely-distinct pairs that
    // happen to share two domain keywords.
    const THRESHOLD: f64 = 0.70;
    for (pkg_root, source_label) in scan_local_packages(project_root) {
        let subskills_dir = pkg_root.join("subskills");
        if !subskills_dir.is_dir() {
            continue;
        }
        let mut entries: Vec<(PathBuf, String, String, std::collections::HashSet<String>)> =
            Vec::new();
        for entry in walkdir::WalkDir::new(&subskills_dir)
            .max_depth(6)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            if !entry.file_type().is_file() {
                continue;
            }
            if entry.file_name() != vibe_core::manifest::SubskillManifest::FILENAME {
                continue;
            }
            let manifest = match vibe_core::manifest::SubskillManifest::read(entry.path()) {
                Ok(m) => m,
                Err(_) => continue,
            };
            if !manifest.subskill.delivery.requires_description() {
                continue;
            }
            let Some(desc) = manifest.subskill.description.clone() else {
                continue;
            };
            let tokens = tokenise_for_overlap(&desc);
            let rel = entry
                .path()
                .strip_prefix(project_root)
                .map(|p| p.to_path_buf())
                .unwrap_or_else(|_| entry.path().to_path_buf());
            entries.push((rel, manifest.subskill.path.clone(), desc, tokens));
        }
        for i in 0..entries.len() {
            for j in (i + 1)..entries.len() {
                let overlap = jaccard_overlap(&entries[i].3, &entries[j].3);
                if overlap >= THRESHOLD {
                    report.warn(
                        CheckId::ActivationConflict,
                        Some(entries[i].0.clone()),
                        None,
                        format!(
                            "[{source_label}] subskill descriptions for `{}` and `{}` overlap by {:.0}% (threshold {:.0}%); the agent may confuse them at activation time. Tighten one description to be specific about its distinct trigger.",
                            entries[i].1,
                            entries[j].1,
                            overlap * 100.0,
                            THRESHOLD * 100.0
                        ),
                    );
                }
            }
        }
    }
}

fn tokenise_for_overlap(s: &str) -> std::collections::HashSet<String> {
    /// Common English connective words that appear in nearly every
    /// agent-trigger description. Removing them sharpens the
    /// distinctiveness signal of the remaining keywords.
    const STOPWORDS: &[&str] = &[
        "the", "this", "that", "those", "these", "with", "when", "while",
        "for", "and", "but", "into", "your", "you", "are", "have", "has",
        "had", "from", "into", "over", "about", "above", "below", "after",
        "before", "during", "use", "using", "used", "needs", "need",
        "needed", "want", "wants", "wanted",
    ];
    s.split(|c: char| !c.is_alphanumeric())
        .map(|t| t.trim().to_lowercase())
        .filter(|t| !t.is_empty() && t.len() > 2)
        .filter(|t| !STOPWORDS.iter().any(|w| *w == t))
        .collect()
}

fn jaccard_overlap(
    a: &std::collections::HashSet<String>,
    b: &std::collections::HashSet<String>,
) -> f64 {
    if a.is_empty() && b.is_empty() {
        return 0.0;
    }
    let intersection = a.intersection(b).count() as f64;
    let union = a.union(b).count() as f64;
    if union == 0.0 {
        0.0
    } else {
        intersection / union
    }
}

/// Find every locally-discoverable manifest. Today: scans
/// `packages/` (vibevm's own dogfooding tree) at depth 3. Also includes
/// the project root itself, which always carries a `vibe.toml`. Returns
/// `(manifest_root, label)` pairs. Consumers (`check_features_graph`,
/// `check_i18n_coverage`, `check_subskill_structure`) tolerate a
/// non-package `vibe.toml`: they short-circuit on an empty
/// `[features]` / `[i18n]` table and a missing `subskills/` tree.
fn scan_local_packages(project_root: &Path) -> Vec<(PathBuf, String)> {
    let mut out: Vec<(PathBuf, String)> = Vec::new();
    if project_root.join(Manifest::FILENAME).is_file() {
        out.push((project_root.to_path_buf(), "project root".to_string()));
    }
    let packages_dir = project_root.join("packages");
    if packages_dir.is_dir() {
        for entry in walkdir::WalkDir::new(&packages_dir)
            .max_depth(4)
            .into_iter()
            .filter_map(|e| e.ok())
        {
            if entry.file_name() == Manifest::FILENAME
                && let Some(parent) = entry.path().parent()
            {
                let rel = parent
                    .strip_prefix(project_root)
                    .map(|p| p.display().to_string().replace('\\', "/"))
                    .unwrap_or_else(|_| parent.display().to_string());
                out.push((parent.to_path_buf(), rel));
            }
        }
    }
    out
}

// ===================== check 1: manifest validity =====================

fn check_manifest_validity(project_root: &Path, report: &mut CheckReport) {
    let manifest_path = project_root.join(Manifest::FILENAME);
    if !manifest_path.exists() {
        report.err(
            CheckId::ManifestValidity,
            Some(PathBuf::from(Manifest::FILENAME)),
            None,
            format!(
                "no `{}` in project root — every vibevm project carries one. Run `vibe init`.",
                Manifest::FILENAME
            ),
        );
        return;
    }
    if let Err(e) = Manifest::read(&manifest_path) {
        report.err(
            CheckId::ManifestValidity,
            Some(PathBuf::from(Manifest::FILENAME)),
            None,
            format!("`{}` failed to parse: {e}", Manifest::FILENAME),
        );
    }

    let lockfile_path = project_root.join(Lockfile::FILENAME);
    if !lockfile_path.exists() {
        // Empty project — fine. `vibe install` will create one.
        return;
    }
    if let Err(e) = Lockfile::read(&lockfile_path) {
        report.err(
            CheckId::ManifestValidity,
            Some(PathBuf::from(Lockfile::FILENAME)),
            None,
            format!("`{}` failed to parse: {e}", Lockfile::FILENAME),
        );
    }
}

// ===================== check 5: WAL freshness =====================

fn check_wal_freshness(
    project_root: &Path,
    report: &mut CheckReport,
    now_unix: u64,
    max_age_hours: u64,
) {
    let wal_rel = PathBuf::from("spec/WAL.md");
    let wal = project_root.join(&wal_rel);
    if !wal.exists() {
        // Surfaced once by check_wal_wellformed. Don't double-report.
        return;
    }
    let mtime = match fs::metadata(&wal).and_then(|m| m.modified()) {
        Ok(t) => t,
        Err(e) => {
            report.warn(
                CheckId::WalFreshness,
                Some(wal_rel),
                None,
                format!("could not read WAL mtime: {e}"),
            );
            return;
        }
    };
    let mtime_unix = mtime
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    if now_unix < mtime_unix {
        // Clock skew — WAL appears to be in the future. Don't fail
        // the check; surface as info so the operator notices.
        report.push(Finding {
            check: CheckId::WalFreshness,
            severity: Severity::Info,
            path: Some(wal_rel),
            line: None,
            message: "WAL mtime is in the future relative to the current clock — possible system-clock skew"
                .to_string(),
        });
        return;
    }
    let age_secs = now_unix - mtime_unix;
    let age_hours = age_secs / 3600;
    if age_hours > max_age_hours {
        report.warn(
            CheckId::WalFreshness,
            Some(wal_rel),
            None,
            format!(
                "WAL is {age_hours} hours old (threshold: {max_age_hours}h). Consider an end-session checkpoint."
            ),
        );
    }
}

// ===================== check 6: WAL well-formed =====================

const WAL_REQUIRED_SECTIONS: &[&str] = &[
    "current phase",
    "constraints",
    "done",
    "next",
    "known issues",
];

fn check_wal_wellformed(project_root: &Path, report: &mut CheckReport) {
    let wal_rel = PathBuf::from("spec/WAL.md");
    let wal = project_root.join(&wal_rel);
    if !wal.exists() {
        // WAL discipline is a project convention, not part of the
        // package manager's contract. A project that hasn't opted in
        // simply has no `spec/WAL.md` — that's not a finding. The
        // well-formedness check only fires once the file exists and
        // the operator has implicitly committed to maintaining it.
        return;
    }
    let body = match fs::read_to_string(&wal) {
        Ok(s) => s,
        Err(e) => {
            report.err(
                CheckId::WalWellformed,
                Some(wal_rel),
                None,
                format!("could not read WAL: {e}"),
            );
            return;
        }
    };
    // Collect every top-level (`## …`) section heading, lowercased
    // and trimmed to the first parenthesis to make the matching
    // resilient to suffixes like `(do not violate without discussion)`.
    let headings: Vec<String> = body
        .lines()
        .filter_map(|line| line.strip_prefix("## "))
        .map(|h| {
            let trimmed = h.trim().to_ascii_lowercase();
            // Drop everything from the first `(` so "constraints (do
            // not violate)" matches the bare "constraints" required
            // section.
            match trimmed.find('(') {
                Some(i) => trimmed[..i].trim().to_string(),
                None => trimmed,
            }
        })
        .collect();
    for required in WAL_REQUIRED_SECTIONS {
        if !headings
            .iter()
            .any(|h| h == required || h.starts_with(&format!("{required} ")))
        {
            report.warn(
                CheckId::WalWellformed,
                Some(wal_rel.clone()),
                None,
                format!("WAL is missing the canonical `## {required}` section"),
            );
        }
    }
}

// ===================== check 7: boot directory =====================

fn check_boot_directory(project_root: &Path, report: &mut CheckReport) {
    let boot_rel = PathBuf::from("spec/boot");
    let boot = project_root.join(&boot_rel);
    if !boot.is_dir() {
        // Empty / fresh project — `vibe init` creates it. If the
        // project's vibe.toml exists but boot/ doesn't, that's a
        // structural error.
        if project_root.join(Manifest::FILENAME).exists() {
            report.err(
                CheckId::BootDirectory,
                Some(boot_rel),
                None,
                "spec/boot/ is missing — every project owns this directory; run `vibe init` if it disappeared.",
            );
        }
        return;
    }
    let entries = match fs::read_dir(&boot) {
        Ok(e) => e,
        Err(e) => {
            report.err(
                CheckId::BootDirectory,
                Some(boot_rel),
                None,
                format!("could not list boot dir: {e}"),
            );
            return;
        }
    };
    // Map NN-prefix → Vec<filename> so we can flag collisions.
    let mut by_prefix: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for entry in entries.filter_map(|e| e.ok()) {
        let name = entry.file_name().to_string_lossy().into_owned();
        if !entry.file_type().map(|t| t.is_file()).unwrap_or(false) {
            continue;
        }
        if !name.ends_with(".md") {
            // Non-markdown files in boot/ — flag as warning. M0/M1
            // contract is markdown-only here.
            report.warn(
                CheckId::BootDirectory,
                Some(boot_rel.join(&name)),
                None,
                format!("non-markdown file `{name}` in spec/boot/"),
            );
            continue;
        }
        match numeric_prefix(&name) {
            None => {
                report.err(
                    CheckId::BootDirectory,
                    Some(boot_rel.join(&name)),
                    None,
                    format!(
                        "`{name}` does not match the `NN-name.md` pattern (NN = two ASCII digits)"
                    ),
                );
            }
            Some(prefix) => {
                by_prefix.entry(prefix.to_string()).or_default().push(name);
            }
        }
    }
    for (prefix, mut names) in by_prefix {
        if names.len() > 1 {
            names.sort();
            report.err(
                CheckId::BootDirectory,
                Some(boot_rel.clone()),
                None,
                format!(
                    "boot prefix `{prefix}` is shared by {} files: {}",
                    names.len(),
                    names.join(", ")
                ),
            );
        }
    }
}

/// Two-ASCII-digit prefix followed by `-`, or `None`. Mirrors the
/// helper in `vibe-install` — duplicated rather than re-exported to
/// keep `vibe-check` independent of the install crate's surface.
fn numeric_prefix(filename: &str) -> Option<&str> {
    if filename.len() < 3 {
        return None;
    }
    let (prefix, rest) = filename.split_at(2);
    if prefix.chars().all(|c| c.is_ascii_digit()) && rest.starts_with('-') {
        Some(prefix)
    } else {
        None
    }
}

// ===================== check 8: lockfile files =====================

const PACKAGE_OWNED_ROOTS: &[&str] = &["spec/flows", "spec/feats", "spec/stacks"];

fn check_lockfile_files(project_root: &Path, report: &mut CheckReport) {
    let lockfile_path = project_root.join(Lockfile::FILENAME);
    if !lockfile_path.exists() {
        return;
    }
    let lockfile = match Lockfile::read(&lockfile_path) {
        Ok(l) => l,
        Err(_) => {
            // Surfaced by check_manifest_validity; don't double-report.
            return;
        }
    };

    // 1. Every locked package's files_written present on disk.
    let mut declared_paths: std::collections::BTreeSet<PathBuf> =
        std::collections::BTreeSet::new();
    for pkg in &lockfile.packages {
        for rel in &pkg.files_written {
            declared_paths.insert(normalize(rel));
            let abs = project_root.join(rel);
            if !abs.exists() {
                report.err(
                    CheckId::LockfileFiles,
                    Some(rel.clone()),
                    None,
                    format!(
                        "lockfile entry `{}:{}@{}` declares `{}` but the file is missing on disk",
                        pkg.kind,
                        pkg.name,
                        pkg.version,
                        rel.display()
                    ),
                );
            }
        }
    }

    // 2. No orphan files in package-owned subtrees.
    for root in PACKAGE_OWNED_ROOTS {
        let dir = project_root.join(root);
        if !dir.is_dir() {
            continue;
        }
        for entry in walk_files(&dir) {
            let rel = match entry.strip_prefix(project_root) {
                Ok(r) => normalize(r),
                Err(_) => continue,
            };
            if !declared_paths.contains(&rel) {
                report.warn(
                    CheckId::LockfileFiles,
                    Some(rel.clone()),
                    None,
                    format!(
                        "`{}` is in a package-owned subtree but no lockfile entry claims it (orphan)",
                        rel.display()
                    ),
                );
            }
        }
    }
}

fn walk_files(root: &Path) -> Vec<PathBuf> {
    let mut out: Vec<PathBuf> = Vec::new();
    let mut stack: Vec<PathBuf> = vec![root.to_path_buf()];
    while let Some(dir) = stack.pop() {
        let entries = match fs::read_dir(&dir) {
            Ok(e) => e,
            Err(_) => continue,
        };
        for entry in entries.filter_map(|e| e.ok()) {
            let path = entry.path();
            let ft = match entry.file_type() {
                Ok(t) => t,
                Err(_) => continue,
            };
            if ft.is_dir() {
                stack.push(path);
            } else if ft.is_file() {
                out.push(path);
            }
        }
    }
    out
}

fn normalize(p: &Path) -> PathBuf {
    PathBuf::from(p.to_string_lossy().replace('\\', "/"))
}

// ===================== check 9: REVIEW marker aging =====================

const REVIEW_MARKER_PREFIX: &str = "<!-- REVIEW";

fn check_review_aging(
    project_root: &Path,
    report: &mut CheckReport,
    now_unix: u64,
    max_age_days: u64,
) {
    let spec_dir = project_root.join("spec");
    if !spec_dir.is_dir() {
        return;
    }
    let max_age_secs = max_age_days * 86_400;
    for path in walk_files(&spec_dir) {
        let lossy = path.to_string_lossy();
        if !lossy.ends_with(".md") {
            continue;
        }
        let body = match fs::read_to_string(&path) {
            Ok(s) => s,
            Err(_) => continue,
        };
        let rel = match path.strip_prefix(project_root) {
            Ok(r) => normalize(r),
            Err(_) => path.clone(),
        };
        for (idx, line) in body.lines().enumerate() {
            let pos = match find_marker(line) {
                Some(p) => p,
                None => continue,
            };
            let after = &line[pos + REVIEW_MARKER_PREFIX.len()..];
            // Accept "<!-- REVIEW: YYYY-MM-DD …" (canonical) and
            // "<!-- REVIEW YYYY-MM-DD …" (legacy / sloppy).
            let after = after.trim_start_matches(':').trim_start();
            let date_field = after.split_whitespace().next().unwrap_or("");
            // Only treat the line as a real marker if the first
            // token is date-shaped. Documentation / prose mentions
            // of `<!-- REVIEW: ... -->` (init's user-facing
            // template, the spec itself describing the convention)
            // are skipped silently — they aren't tracking work.
            if !looks_like_date(date_field) {
                continue;
            }
            let Some(date_unix) = parse_iso_date(date_field) else {
                report.warn(
                    CheckId::ReviewAging,
                    Some(rel.clone()),
                    Some(idx + 1),
                    format!(
                        "REVIEW marker date `{date_field}` is malformed — expected `YYYY-MM-DD`"
                    ),
                );
                continue;
            };
            if date_unix > now_unix {
                report.push(Finding {
                    check: CheckId::ReviewAging,
                    severity: Severity::Info,
                    path: Some(rel.clone()),
                    line: Some(idx + 1),
                    message: "REVIEW marker date is in the future — clock skew or typo".into(),
                });
                continue;
            }
            let age_secs = now_unix - date_unix;
            if age_secs > max_age_secs {
                let age_days = age_secs / 86_400;
                report.warn(
                    CheckId::ReviewAging,
                    Some(rel.clone()),
                    Some(idx + 1),
                    format!(
                        "REVIEW marker dated {date_field} is {age_days} days old (threshold: {max_age_days}d) — resolve or refresh"
                    ),
                );
            }
        }
    }
}

fn find_marker(line: &str) -> Option<usize> {
    line.find(REVIEW_MARKER_PREFIX)
}

/// Heuristic for "this token starts with a `YYYY-MM-DD`-shape
/// prefix" — exactly four ASCII digits, dash, two ASCII digits,
/// dash, two ASCII digits. Anything else (`...`, `TODO`, `…`) is
/// not a real marker and we skip the line silently. The full
/// validity gate is `parse_iso_date`; this is just a fast-path
/// that lets prose mentions of the marker convention live in
/// documentation without tripping the linter.
fn looks_like_date(s: &str) -> bool {
    if s.len() < 10 {
        return false;
    }
    let bytes = &s.as_bytes()[..10];
    bytes[..4].iter().all(|b| b.is_ascii_digit())
        && bytes[4] == b'-'
        && bytes[5..7].iter().all(|b| b.is_ascii_digit())
        && bytes[7] == b'-'
        && bytes[8..10].iter().all(|b| b.is_ascii_digit())
}

/// Parse `YYYY-MM-DD` (with whatever follows the date — `T...Z`,
/// trailing comma, etc. are tolerated up to position 10). Returns
/// the UNIX-seconds for midnight UTC of that date, or `None` if
/// the date does not parse.
fn parse_iso_date(s: &str) -> Option<u64> {
    if s.len() < 10 {
        return None;
    }
    let prefix = &s[..10];
    let bytes = prefix.as_bytes();
    if bytes[4] != b'-' || bytes[7] != b'-' {
        return None;
    }
    // Reuse vibe_core's calendar math via the established RFC-3339
    // shape: synthesize `YYYY-MM-DDT00:00:00Z` and feed it back.
    let synthesized = format!("{prefix}T00:00:00Z");
    vibe_core::timestamp::parse_unix_utc(&synthesized)
}

fn unix_now_utc() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0)
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    fn fixed_now() -> u64 {
        // 2026-05-04T12:00:00Z — well after the various dated test
        // markers, so age math is positive.
        vibe_core::timestamp::parse_unix_utc("2026-05-04T12:00:00Z").unwrap()
    }

    fn opts() -> CheckOptions {
        CheckOptions {
            now_unix_utc: Some(fixed_now()),
            ..Default::default()
        }
    }

    fn write_minimal_project(root: &Path) {
        // vibe.toml with default registry.
        fs::write(
            root.join("vibe.toml"),
            r#"[project]
name = "demo"
version = "0.0.1"

[[registry]]
name = "vibespecs"
url = "https://example/vibespecs"
"#,
        )
        .unwrap();
        fs::create_dir_all(root.join("spec/boot")).unwrap();
        fs::write(root.join("spec/boot/00-core.md"), "# core\n").unwrap();
        fs::write(root.join("spec/boot/90-user.md"), "# user\n").unwrap();
        // WAL with all required sections.
        let wal = root.join("spec/WAL.md");
        fs::write(
            &wal,
            "# WAL\n\n## Current phase\n\n## Constraints\n\n## Done\n\n## Next\n\n## Known issues\n",
        )
        .unwrap();
        // Pin the WAL mtime to 1h before `fixed_now()` so the freshness
        // check sees a deterministic positive age regardless of where
        // the host's wall-clock sits when the test runs. Otherwise
        // `clean_minimal_project_has_no_findings` flakes whenever real
        // wall-time crosses past `fixed_now()` (a fresh-write mtime
        // ahead of `now` surfaces as the "WAL mtime is in the future"
        // info finding).
        let one_hour_before_fixed_now = SystemTime::UNIX_EPOCH
            + std::time::Duration::from_secs(fixed_now().saturating_sub(3600));
        fs::OpenOptions::new()
            .write(true)
            .open(&wal)
            .unwrap()
            .set_modified(one_hour_before_fixed_now)
            .unwrap();
    }

    #[test]
    fn clean_minimal_project_has_no_findings() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let report = check_project(project.path(), &opts());
        assert!(
            !report.has_errors(),
            "expected no errors; got: {:?}",
            report.findings
        );
        // WAL freshness may surface a warning since we set a future
        // `now` but the WAL was just written. Should be 0d old →
        // safely under the 24h threshold.
        assert_eq!(report.findings.len(), 0, "got: {:?}", report.findings);
    }

    #[test]
    fn missing_vibe_toml_is_an_error() {
        let project = tempdir().unwrap();
        // No vibe.toml.
        fs::create_dir_all(project.path().join("spec/boot")).unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::ManifestValidity && f.severity == Severity::Error),
            "expected ManifestValidity error; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn malformed_vibe_toml_is_an_error() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        fs::write(project.path().join("vibe.toml"), "this is = not = toml").unwrap();
        let report = check_project(project.path(), &opts());
        assert!(report.has_errors());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::ManifestValidity && f.message.contains("failed to parse")),
        );
    }

    #[test]
    fn wal_older_than_24h_warns() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        // Set WAL mtime to ~48h ago.
        let two_days = std::time::Duration::from_secs(48 * 3600);
        let two_days_ago = SystemTime::now() - two_days;
        let wal = project.path().join("spec/WAL.md");
        // `set_modified` is on filetime::set_file_mtime; std doesn't
        // provide it directly. Use a helper via fs::File +
        // set_modified on a fresh stamp via filetime crate? Not
        // available — but we can fall back: set `now_unix_utc` in
        // opts to a moment far past the WAL's actual mtime. That
        // gives us the same age-math without touching mtime.
        let now_far_future = unix_now_utc() + 48 * 3600;
        let opts = CheckOptions {
            now_unix_utc: Some(now_far_future),
            ..Default::default()
        };
        let report = check_project(project.path(), &opts);
        let _ = (two_days_ago, wal);
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::WalFreshness && f.severity == Severity::Warning),
            "expected WalFreshness warning; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn wal_missing_sections_warn() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        fs::write(
            project.path().join("spec/WAL.md"),
            "# WAL\n\n## Current phase\n\n(no other sections)\n",
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        let missing: Vec<&str> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::WalWellformed)
            .map(|f| f.message.as_str())
            .collect();
        assert!(missing.iter().any(|m| m.contains("constraints")));
        assert!(missing.iter().any(|m| m.contains("done")));
        assert!(missing.iter().any(|m| m.contains("next")));
        assert!(missing.iter().any(|m| m.contains("known issues")));
    }

    #[test]
    fn wal_missing_is_not_an_error() {
        // Regression guard: WAL discipline is a project convention,
        // not part of the package manager's contract. A fresh
        // `vibe init`-ed project does NOT carry `spec/WAL.md`, and
        // `vibe check` against such a project must NOT produce a
        // WalWellformed finding. Past versions of this check
        // emitted `WAL is missing — every project carries one`,
        // which conflated this repo's convention with the tool's
        // contract.
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        // Remove the WAL that `write_minimal_project` writes — we
        // want the no-WAL state.
        let wal = project.path().join("spec/WAL.md");
        if wal.exists() {
            fs::remove_file(&wal).unwrap();
        }
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .all(|f| f.check != CheckId::WalWellformed
                    && f.check != CheckId::WalFreshness),
            "missing WAL must produce no WAL findings; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn wal_constraint_heading_with_parenthetical_suffix_matches() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        // The real project's WAL uses `## Constraints (do not violate without discussion)`.
        fs::write(
            project.path().join("spec/WAL.md"),
            "# WAL\n\n## Current phase\n\n## Constraints (do not violate without discussion)\n\n## Done\n\n## Next\n\n## Known issues\n",
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        // No WalWellformed findings — every required section matched.
        assert!(
            report
                .findings
                .iter()
                .all(|f| f.check != CheckId::WalWellformed),
            "got: {:?}",
            report.findings
        );
    }

    #[test]
    fn boot_dir_prefix_collision_is_an_error() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        // Two `10-` boot snippets — collision.
        fs::write(project.path().join("spec/boot/10-flow-wal.md"), "x").unwrap();
        fs::write(project.path().join("spec/boot/10-flow-other.md"), "y").unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::BootDirectory && f.severity == Severity::Error),
            "expected boot prefix collision error; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn boot_dir_bad_filename_is_an_error() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        // `flow-wal.md` (no NN- prefix) doesn't match the pattern.
        fs::write(project.path().join("spec/boot/flow-wal.md"), "x").unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::BootDirectory
                    && f.severity == Severity::Error
                    && f.message.contains("does not match"))
        );
    }

    #[test]
    fn lockfile_files_missing_on_disk_is_an_error() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let lockfile = r#"[meta]
generated_by = "vibe-test"
generated_at = "2026-05-04T00:00:00Z"
schema_version = 4

[[package]]
kind = "flow"
name = "wal"
version = "0.1.0"
source_url = "file:///fake"
content_hash = "sha256:00"
files_written = ["spec/flows/wal/A.md"]
"#;
        fs::write(project.path().join("vibe.lock"), lockfile).unwrap();
        // Don't create spec/flows/wal/A.md — we want the error.
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::LockfileFiles
                    && f.severity == Severity::Error
                    && f.message.contains("missing on disk")),
            "got: {:?}",
            report.findings
        );
    }

    #[test]
    fn lockfile_files_orphan_in_package_subtree_warns() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        // Stray file in spec/flows/ — not in any lockfile entry.
        fs::create_dir_all(project.path().join("spec/flows/orphan")).unwrap();
        fs::write(project.path().join("spec/flows/orphan/stray.md"), "x").unwrap();
        // Empty lockfile (no packages declare anything).
        fs::write(
            project.path().join("vibe.lock"),
            "[meta]\ngenerated_by = \"vibe-test\"\ngenerated_at = \"2026-05-04T00:00:00Z\"\nschema_version = 4\n",
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::LockfileFiles
                    && f.severity == Severity::Warning
                    && f.message.contains("orphan")),
            "got: {:?}",
            report.findings
        );
    }

    #[test]
    fn review_marker_older_than_threshold_warns() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        fs::create_dir_all(project.path().join("spec/notes")).unwrap();
        // Date 2026-04-01 — about 33 days before fixed_now (2026-05-04).
        // Default threshold is 14d, so it should fire.
        fs::write(
            project.path().join("spec/notes/old-review.md"),
            "<!-- REVIEW: 2026-04-01 fix this later -->\n",
        )
        .unwrap();
        // A fresh marker should NOT fire.
        fs::write(
            project.path().join("spec/notes/new-review.md"),
            "<!-- REVIEW: 2026-05-03 just yesterday -->\n",
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        let aging: Vec<&Finding> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::ReviewAging && f.severity == Severity::Warning)
            .collect();
        assert_eq!(aging.len(), 1, "got: {:?}", report.findings);
        assert!(aging[0].message.contains("2026-04-01"));
        assert_eq!(
            aging[0].path.as_deref().unwrap(),
            Path::new("spec/notes/old-review.md")
        );
        assert_eq!(aging[0].line, Some(1));
    }

    #[test]
    fn review_marker_with_placeholder_is_silently_skipped() {
        // Documentation often references `<!-- REVIEW: ... -->` or
        // `<!-- REVIEW: … -->` as a template. Those are not real
        // markers — they shouldn't trip the linter.
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        fs::create_dir_all(project.path().join("spec/notes")).unwrap();
        fs::write(
            project.path().join("spec/notes/docs.md"),
            "Add a `<!-- REVIEW: ... -->` marker.\n\
             Or `<!-- REVIEW: … -->`.\n\
             Or `<!-- REVIEW: free-form prose -->`.\n",
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        // No ReviewAging findings whatsoever — the placeholder /
        // prose forms are documentation, not work.
        assert!(
            report
                .findings
                .iter()
                .all(|f| f.check != CheckId::ReviewAging),
            "got: {:?}",
            report.findings
        );
    }

    #[test]
    fn review_marker_with_malformed_date_warns() {
        // Date-shaped but invalid (month 13). Real intent is a
        // tracking marker; the operator probably typo'd. Surface
        // a warning so they can fix it.
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        fs::create_dir_all(project.path().join("spec/notes")).unwrap();
        fs::write(
            project.path().join("spec/notes/typo.md"),
            "<!-- REVIEW: 2026-13-01 invalid month -->\n",
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::ReviewAging && f.message.contains("malformed")),
            "got: {:?}",
            report.findings
        );
    }

    #[test]
    fn parse_iso_date_handles_canonical_form() {
        let s = parse_iso_date("2026-04-22").unwrap();
        let echo = vibe_core::timestamp::format_unix_utc(s);
        assert_eq!(echo, "2026-04-22T00:00:00Z");
    }

    #[test]
    fn parse_iso_date_rejects_garbage() {
        assert!(parse_iso_date("not-a-date").is_none());
        assert!(parse_iso_date("2026").is_none());
    }

    // ============================================================
    // PROP-003 r2 — feature graph / subskill / i18n coverage checks
    // ============================================================

    fn write_pkg_with_features(project: &Path, features_section: &str) {
        write_minimal_project(project);
        let pkg = project.join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(&pkg).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            format!(
                r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"

[features]
{features_section}
"#
            ),
        )
        .unwrap();
    }

    #[test]
    fn features_graph_passes_clean() {
        let project = tempdir().unwrap();
        write_pkg_with_features(
            project.path(),
            r#"default = ["a"]
a = []
"#,
        );
        let report = check_project(project.path(), &opts());
        let feature_findings: Vec<_> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::FeaturesGraph)
            .collect();
        assert!(
            feature_findings.is_empty(),
            "expected no features findings, got: {:?}",
            feature_findings
        );
    }

    #[test]
    fn features_graph_flags_unknown_referenced_feature() {
        let project = tempdir().unwrap();
        write_pkg_with_features(
            project.path(),
            r#"a = ["bogus-feature"]
"#,
        );
        let report = check_project(project.path(), &opts());
        assert!(
            report
                .findings
                .iter()
                .any(|f| f.check == CheckId::FeaturesGraph
                    && f.message.contains("unknown feature")),
            "expected unknown-feature finding; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn subskill_structure_flags_lazy_push_without_description() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(&pkg).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"
"#,
        )
        .unwrap();
        // Subskill with delivery=lazy-push but no description.
        let sub = pkg.join("subskills/stack/rust");
        fs::create_dir_all(&sub).unwrap();
        fs::write(
            sub.join("vibe-subskill.toml"),
            r#"[subskill]
path = "stack/rust"
delivery = "lazy-push"
"#,
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report.findings.iter().any(|f| {
                f.check == CheckId::SubskillStructure
                    && f.message.contains("requires a non-empty `description`")
            }),
            "expected subskill description finding; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn subskill_structure_flags_missing_declared_file() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(&pkg).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"
"#,
        )
        .unwrap();
        let sub = pkg.join("subskills/stack/rust");
        fs::create_dir_all(&sub).unwrap();
        fs::write(
            sub.join("vibe-subskill.toml"),
            r#"[subskill]
path = "stack/rust"

[content]
files_written = ["spec/missing.md"]
"#,
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report.findings.iter().any(|f| {
                f.check == CheckId::SubskillStructure
                    && f.message.contains("missing on disk")
            }),
            "expected missing-file finding; got: {:?}",
            report.findings
        );
    }

    #[test]
    fn i18n_coverage_warns_on_missing_translation() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(pkg.join("spec/flows/x")).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"

[i18n]
canonical = "en"
available = ["en", "ru"]

[writes]
files = ["spec/flows/x/PROTOCOL.md"]
"#,
        )
        .unwrap();
        fs::write(pkg.join("spec/flows/x/PROTOCOL.md"), "EN content").unwrap();
        // Russian sidecar deliberately missing.
        let report = check_project(project.path(), &opts());
        let warns: Vec<_> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::I18nCoverage)
            .collect();
        assert!(
            !warns.is_empty(),
            "expected i18n coverage warning; got: {:?}",
            report.findings
        );
        assert!(warns.iter().any(|f| f.message.contains("ru")));
    }

    #[test]
    fn activation_conflict_flags_overlapping_descriptions() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(&pkg).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"
"#,
        )
        .unwrap();
        // Two lazy-push subskills with deliberately overlapping
        // descriptions — same vocabulary, no distinct keywords.
        for (name, desc) in [
            ("a", "When working with database migrations using sqlx in a Rust project"),
            ("b", "When using sqlx in a Rust project for database migrations work"),
        ] {
            let dir = pkg.join(format!("subskills/{name}"));
            fs::create_dir_all(&dir).unwrap();
            fs::write(
                dir.join("vibe-subskill.toml"),
                format!(
                    r#"[subskill]
path = "{name}"
delivery = "lazy-push"
description = "{desc}"
"#
                ),
            )
            .unwrap();
        }
        let report = check_project(project.path(), &opts());
        let conflict_findings: Vec<_> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::ActivationConflict)
            .collect();
        assert!(
            !conflict_findings.is_empty(),
            "expected activation_conflict warning; got {:?}",
            report.findings
        );
        assert!(conflict_findings[0].message.contains("overlap by"));
    }

    #[test]
    fn subskill_structure_warns_on_excessive_nesting_depth() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(&pkg).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"
"#,
        )
        .unwrap();
        // 4-level nested subskill: a/b/c/d.
        let sub = pkg.join("subskills/a/b/c/d");
        fs::create_dir_all(&sub).unwrap();
        fs::write(
            sub.join("vibe-subskill.toml"),
            r#"[subskill]
path = "a/b/c/d"
"#,
        )
        .unwrap();
        let report = check_project(project.path(), &opts());
        assert!(
            report.findings.iter().any(|f| f.check
                == CheckId::SubskillStructure
                && f.severity == Severity::Warning
                && f.message.contains("nested 4 levels deep")),
            "expected depth-4 warning; got {:?}",
            report.findings
        );
    }

    #[test]
    fn activation_conflict_clean_when_descriptions_distinct() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(&pkg).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"
"#,
        )
        .unwrap();
        for (name, desc) in [
            ("a", "When designing GraphQL schemas with Apollo Server"),
            ("b", "When writing PostgreSQL migrations using sqlx"),
        ] {
            let dir = pkg.join(format!("subskills/{name}"));
            fs::create_dir_all(&dir).unwrap();
            fs::write(
                dir.join("vibe-subskill.toml"),
                format!(
                    r#"[subskill]
path = "{name}"
delivery = "lazy-push"
description = "{desc}"
"#
                ),
            )
            .unwrap();
        }
        let report = check_project(project.path(), &opts());
        let conflict_findings: Vec<_> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::ActivationConflict)
            .collect();
        assert!(
            conflict_findings.is_empty(),
            "expected no activation_conflict findings; got {:?}",
            conflict_findings
        );
    }

    #[test]
    fn i18n_coverage_clean_when_all_translations_present() {
        let project = tempdir().unwrap();
        write_minimal_project(project.path());
        let pkg = project.path().join("packages").join("flow").join("test-pkg");
        fs::create_dir_all(pkg.join("spec/flows/x")).unwrap();
        fs::write(
            pkg.join("vibe.toml"),
            r#"[package]
name = "test-pkg"
kind = "flow"
version = "0.1.0"

[i18n]
canonical = "en"
available = ["en", "ru"]

[writes]
files = ["spec/flows/x/PROTOCOL.md"]
"#,
        )
        .unwrap();
        fs::write(pkg.join("spec/flows/x/PROTOCOL.md"), "EN content").unwrap();
        fs::write(pkg.join("spec/flows/x/PROTOCOL.ru.md"), "RU content").unwrap();
        let report = check_project(project.path(), &opts());
        let i18n_findings: Vec<_> = report
            .findings
            .iter()
            .filter(|f| f.check == CheckId::I18nCoverage)
            .collect();
        assert!(
            i18n_findings.is_empty(),
            "expected no i18n findings; got: {:?}",
            i18n_findings
        );
    }
}
