//! The canonical index: compose the two scanners into `specmap.json`
//! (PROP-014 §2.5) — derived, deterministic, committed, regenerated by
//! `cargo xtask specmap`, gated by `--check` exactly the way
//! `check-codegen` gates the wire types.
//!
//! Beyond raw nodes and edges the index carries the **suspects table**
//! (PROP-014 §2.2, asymmetric invalidation): every edge pinned to an
//! older revision than its unit currently declares. Suspect detection
//! is intra-tree and therefore deterministic; the *unbumped-hash*
//! diagnostic ("content changed while `r` did not") needs the previous
//! index and is emitted as regeneration-time stderr, never stored.

specmark::scope!("spec://vibevm/neworder/PROP-014#index");

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result};
use vibe_wire::generated::specmap::{Specmap, Suspect, Warning};

use crate::{mdspec, rscan};

/// Repo-relative location of the committed index.
pub const INDEX_REL_PATH: &str = "specmap.json";

/// Current index schema number. 2: canonical (house-style) URI
/// doc-paths, `spec_unit.file`, the `suspects` table.
pub const SCHEMA: u32 = 2;

fn verb_str(e: &vibe_wire::generated::specmap::Edge) -> &'static str {
    use vibe_wire::generated::specmap::EdgeVerb::*;
    match e.verb {
        Implements => "implements",
        Verifies => "verifies",
        Documents => "documents",
        Deviates => "deviates",
        Informs => "informs",
    }
}

fn verb_key(e: &vibe_wire::generated::specmap::Edge) -> u8 {
    use vibe_wire::generated::specmap::EdgeVerb::*;
    match e.verb {
        Implements => 0,
        Verifies => 1,
        Documents => 2,
        Deviates => 3,
        Informs => 4,
    }
}

/// Build the index for the tree under `root`. Pure function of the
/// tree: same tree → same value.
pub fn build(root: &Path) -> Specmap {
    let (mut spec_units, mut md_warnings) = mdspec::scan_spec_tree(root);
    let (mut code_items, mut edges, mut rs_warnings) = rscan::scan_workspace(root);

    let mut warnings = Vec::new();
    warnings.append(&mut md_warnings);
    warnings.append(&mut rs_warnings);

    // Asymmetric-invalidation analysis (PROP-014 §2.2). On a duplicate
    // anchor the first occurrence wins here; the duplicate itself is
    // already a warning from mdspec.
    let mut unit_revisions: BTreeMap<&str, Option<u32>> = BTreeMap::new();
    for u in &spec_units {
        unit_revisions
            .entry(u.uri.as_str())
            .or_insert(u.revision.as_deref().copied());
    }
    let mut suspects: Vec<Suspect> = Vec::new();
    for e in &edges {
        match unit_revisions.get(e.uri.as_str()) {
            None => warnings.push(Warning {
                code: "dangling-edge".to_string(),
                message: format!(
                    "edge `{}` --{}--> `{}`: no spec unit carries this anchor",
                    e.fromSymbol,
                    verb_str(e),
                    e.uri
                ),
                file: e.file.clone(),
                line: e.line,
            }),
            Some(None) => {
                if let Some(p) = e.pinnedR.as_deref() {
                    warnings.push(Warning {
                        code: "pin-into-unmarked-unit".to_string(),
                        message: format!(
                            "edge `{}` pins r{p} but `{}` carries no kind/revision line yet",
                            e.fromSymbol, e.uri
                        ),
                        file: e.file.clone(),
                        line: e.line,
                    });
                }
            }
            Some(Some(rev)) => {
                if let Some(p) = e.pinnedR.as_deref() {
                    if p < rev {
                        suspects.push(Suspect {
                            fromSymbol: e.fromSymbol.clone(),
                            uri: e.uri.clone(),
                            pinnedR: *p,
                            currentR: *rev,
                            file: e.file.clone(),
                            line: e.line,
                        });
                    } else if p > rev {
                        warnings.push(Warning {
                            code: "pin-ahead-of-unit".to_string(),
                            message: format!(
                                "edge `{}` pins r{p} but `{}` is only at r{rev} — \
                                 a reverted spec or a typo'd pin",
                                e.fromSymbol, e.uri
                            ),
                            file: e.file.clone(),
                            line: e.line,
                        });
                    }
                }
            }
        }
    }

    // Canonical ordering — the determinism contract.
    spec_units.sort_by(|a, b| (&a.docPath, a.line).cmp(&(&b.docPath, b.line)));
    code_items.sort_by(|a, b| (&a.symbol, &a.file, a.line).cmp(&(&b.symbol, &b.file, b.line)));
    code_items.dedup_by(|a, b| a.symbol == b.symbol && a.file == b.file && a.line == b.line);
    edges.sort_by(|a, b| {
        (&a.fromSymbol, verb_key(a), &a.uri, &a.file, a.line).cmp(&(
            &b.fromSymbol,
            verb_key(b),
            &b.uri,
            &b.file,
            b.line,
        ))
    });
    suspects.sort_by(|a, b| {
        (&a.uri, &a.fromSymbol, &a.file, a.line).cmp(&(&b.uri, &b.fromSymbol, &b.file, b.line))
    });
    warnings.sort_by(|a, b| {
        (&a.file, a.line, &a.code, &a.message).cmp(&(&b.file, b.line, &b.code, &b.message))
    });

    Specmap {
        schema: SCHEMA,
        specUnits: spec_units,
        codeItems: code_items,
        edges,
        suspects,
        warnings,
    }
}

/// Canonical bytes: pretty JSON + trailing newline.
pub fn to_canonical_bytes(map: &Specmap) -> Result<String> {
    let mut s = serde_json::to_string_pretty(map).context("serialising specmap")?;
    s.push('\n');
    Ok(s)
}

pub fn index_path(root: &Path) -> PathBuf {
    root.join(INDEX_REL_PATH)
}

/// Classify the difference between the previously-committed index and
/// a freshly-built one — the regeneration-time drift report:
///
/// - **revision bumps** (`rN` → `rM`) with the suspect edges they
///   create (the drift-drill (a) signal);
/// - **unbumped hashes** — unit content changed while `r` stayed put:
///   *editorial, or forgot to bump?* (the drift-drill (b) signal;
///   GUIDE-SPEC-AUTHORING §4: bump, or mark the commit body
///   `spec-editorial: <anchor>`);
/// - unit/edge population changes, as counts.
pub fn classify_drift(old: &Specmap, new: &Specmap) -> Vec<String> {
    let mut lines = Vec::new();
    let old_units: BTreeMap<&str, (Option<u32>, &str)> = old
        .specUnits
        .iter()
        .map(|u| {
            (
                u.uri.as_str(),
                (u.revision.as_deref().copied(), u.contentHash.as_str()),
            )
        })
        .collect();
    let new_units: BTreeMap<&str, (Option<u32>, &str, &str)> = new
        .specUnits
        .iter()
        .map(|u| {
            (
                u.uri.as_str(),
                (
                    u.revision.as_deref().copied(),
                    u.contentHash.as_str(),
                    u.anchor.as_str(),
                ),
            )
        })
        .collect();

    for (uri, (new_rev, new_hash, anchor)) in &new_units {
        let Some((old_rev, old_hash)) = old_units.get(uri) else {
            continue;
        };
        if old_rev == new_rev {
            // A unit with no revision line has no revision discipline
            // to audit yet — hash movement there is plain text churn.
            if old_hash != new_hash
                && let Some(rev) = new_rev
            {
                lines.push(format!(
                    "unbumped-hash: `{uri}` content changed while the revision stayed \
                     at r{rev} — editorial, or forgot to bump? (bump `r`, or mark the \
                     commit body `spec-editorial: {anchor}`)"
                ));
            }
        } else {
            let fa = old_rev
                .map(|n| format!("r{n}"))
                .unwrap_or_else(|| "—".into());
            let fb = new_rev
                .map(|n| format!("r{n}"))
                .unwrap_or_else(|| "—".into());
            lines.push(format!("revision bump: `{uri}` {fa} → {fb}"));
            for s in &new.suspects {
                if s.uri == *uri {
                    lines.push(format!(
                        "  now SUSPECT: `{}` (pinned r{}) at {}:{} — re-affirm after review",
                        s.fromSymbol, s.pinnedR, s.file, s.line
                    ));
                }
            }
        }
    }

    let added = new_units
        .keys()
        .filter(|k| !old_units.contains_key(*k))
        .count();
    let removed = old_units
        .keys()
        .filter(|k| !new_units.contains_key(*k))
        .count();
    if added > 0 {
        lines.push(format!("units added: {added}"));
    }
    if removed > 0 {
        lines.push(format!("units removed: {removed}"));
    }
    let edge_key = |e: &vibe_wire::generated::specmap::Edge| {
        format!("{}|{}|{}", e.fromSymbol, verb_str(e), e.uri)
    };
    let old_edges: std::collections::BTreeSet<String> = old.edges.iter().map(edge_key).collect();
    let new_edges: std::collections::BTreeSet<String> = new.edges.iter().map(edge_key).collect();
    let e_added = new_edges.difference(&old_edges).count();
    let e_removed = old_edges.difference(&new_edges).count();
    if e_added > 0 {
        lines.push(format!("edges added: {e_added}"));
    }
    if e_removed > 0 {
        lines.push(format!("edges removed: {e_removed}"));
    }
    lines
}

fn load_committed(root: &Path) -> Option<Specmap> {
    let text = std::fs::read_to_string(index_path(root)).ok()?;
    serde_json::from_str(&text).ok()
}

/// Regenerate and write `specmap.json`. Returns (path, summary).
/// Emits the drift report against the previously-committed index to
/// stderr before overwriting.
pub fn write(root: &Path) -> Result<(PathBuf, Summary)> {
    let map = build(root);
    let summary = Summary::of(&map);
    if let Some(old) = load_committed(root) {
        for line in classify_drift(&old, &map) {
            eprintln!("  drift: {line}");
        }
    }
    let bytes = to_canonical_bytes(&map)?;
    let path = index_path(root);
    std::fs::write(&path, bytes).with_context(|| format!("writing {}", path.display()))?;
    Ok((path, summary))
}

/// `--check`: regenerate and byte-compare against the committed file.
/// On drift the error carries the classified report, so the drill
/// signals (revision bumps → suspects; unbumped hashes) are visible at
/// the gate itself.
pub fn check(root: &Path) -> Result<std::result::Result<Summary, String>> {
    let map = build(root);
    let summary = Summary::of(&map);
    let fresh = to_canonical_bytes(&map)?;
    let path = index_path(root);
    let committed = std::fs::read_to_string(&path).with_context(|| {
        format!(
            "reading {} — run `cargo xtask specmap` first",
            path.display()
        )
    })?;
    if fresh == committed {
        return Ok(Ok(summary));
    }
    let mut msg = format!("`{}` is out of date relative to the tree.", path.display());
    if let Ok(old) = serde_json::from_str::<Specmap>(&committed) {
        for line in classify_drift(&old, &map) {
            msg.push_str("\n  drift: ");
            msg.push_str(&line);
        }
    }
    msg.push_str("\nRun `cargo xtask specmap`, review the drift, and commit the result.");
    Ok(Err(msg))
}

/// Counts for the human one-liner.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Summary {
    pub spec_units: usize,
    pub code_items: usize,
    pub edges: usize,
    pub suspects: usize,
    pub warnings: usize,
}

impl Summary {
    pub fn of(map: &Specmap) -> Self {
        Summary {
            spec_units: map.specUnits.len(),
            code_items: map.codeItems.len(),
            edges: map.edges.len(),
            suspects: map.suspects.len(),
            warnings: map.warnings.len(),
        }
    }
}

impl std::fmt::Display for Summary {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{} spec units, {} tagged code items, {} edges, {} suspects, {} warnings",
            self.spec_units, self.code_items, self.edges, self.suspects, self.warnings
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn repo_root() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .unwrap()
            .parent()
            .unwrap()
            .to_path_buf()
    }

    /// PROP-014 §2.5: determinism is a tested property — index twice,
    /// assert byte-identical. Runs over the real repository tree.
    #[test]
    fn index_is_deterministic_over_the_real_tree() {
        let root = repo_root();
        let a = to_canonical_bytes(&build(&root)).unwrap();
        let b = to_canonical_bytes(&build(&root)).unwrap();
        assert_eq!(a, b);
        assert!(a.ends_with('\n'));
    }

    #[test]
    fn real_tree_has_a_node_inventory() {
        let root = repo_root();
        let map = build(&root);
        assert!(
            map.specUnits.len() > 100,
            "expected a substantial unit inventory, got {}",
            map.specUnits.len()
        );
        // Ordering invariant: (doc_path, line) non-decreasing.
        assert!(
            map.specUnits
                .windows(2)
                .all(|w| (&w[0].docPath, w[0].line) <= (&w[1].docPath, w[1].line))
        );
        // House-style URIs: no `spec/` prefix, no `.md`.
        assert!(
            map.specUnits
                .iter()
                .all(|u| !u.uri.starts_with("spec://vibevm/spec/") && !u.uri.contains(".md#"))
        );
    }

    /// End-to-end over a synthetic tree: suspects, dangling edges and
    /// pin-ahead warnings all surface.
    #[test]
    fn suspects_dangling_and_pin_ahead_are_detected() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join("spec")).unwrap();
        std::fs::write(
            root.join("spec/T.md"),
            "## The contract {#req-t}\n`req r2`\n\nIt MUST hold.\n",
        )
        .unwrap();
        let src_dir = root.join("crates/x/src");
        std::fs::create_dir_all(&src_dir).unwrap();
        std::fs::write(
            src_dir.join("lib.rs"),
            r#"
#[spec(implements = "spec://vibevm/T#req-t", r = 1)]
pub fn stale() {}

#[spec(implements = "spec://vibevm/T#req-t", r = 2)]
pub fn current() {}

#[spec(implements = "spec://vibevm/T#req-t", r = 3)]
pub fn ahead() {}

#[spec(implements = "spec://vibevm/T#req-missing", r = 1)]
pub fn dangling() {}
"#,
        )
        .unwrap();

        let map = build(root);
        assert_eq!(map.specUnits.len(), 1);
        assert_eq!(map.specUnits[0].uri, "spec://vibevm/T#req-t");
        assert_eq!(map.edges.len(), 4);
        assert_eq!(map.suspects.len(), 1, "exactly the r1 pin is suspect");
        assert_eq!(map.suspects[0].fromSymbol, "x::stale");
        assert_eq!(map.suspects[0].pinnedR, 1);
        assert_eq!(map.suspects[0].currentR, 2);
        let codes: Vec<&str> = map.warnings.iter().map(|w| w.code.as_str()).collect();
        assert!(codes.contains(&"dangling-edge"), "{codes:?}");
        assert!(codes.contains(&"pin-ahead-of-unit"), "{codes:?}");
    }

    #[test]
    fn drift_classification_reports_bumps_and_unbumped_hashes() {
        let tmp = tempfile::tempdir().unwrap();
        let root = tmp.path();
        std::fs::create_dir_all(root.join("spec")).unwrap();
        let src_dir = root.join("crates/x/src");
        std::fs::create_dir_all(&src_dir).unwrap();
        std::fs::write(
            src_dir.join("lib.rs"),
            "#[spec(implements = \"spec://vibevm/T#req-t\", r = 1)]\npub fn f() {}\n",
        )
        .unwrap();

        std::fs::write(
            root.join("spec/T.md"),
            "## C {#req-t}\n`req r1`\n\nIt MUST hold.\n",
        )
        .unwrap();
        let old = build(root);

        // (b) editorial change, no bump → unbumped-hash.
        std::fs::write(
            root.join("spec/T.md"),
            "## C {#req-t}\n`req r1`\n\nIt MUST always hold.\n",
        )
        .unwrap();
        let edited = build(root);
        let report = classify_drift(&old, &edited);
        assert!(
            report.iter().any(|l| l.starts_with("unbumped-hash:")),
            "{report:?}"
        );

        // (a) semantic change + bump → revision bump + suspect listing.
        std::fs::write(
            root.join("spec/T.md"),
            "## C {#req-t}\n`req r2`\n\nIt MUST hold, monotonically.\n",
        )
        .unwrap();
        let bumped = build(root);
        let report = classify_drift(&old, &bumped);
        assert!(
            report.iter().any(|l| l.starts_with("revision bump:")),
            "{report:?}"
        );
        assert!(
            report.iter().any(|l| l.contains("now SUSPECT")),
            "{report:?}"
        );
        assert_eq!(bumped.suspects.len(), 1);
    }
}
