schema = 1
source_hash = "sha256:c78b2169bf7dd3293cec0c02a884718d1bebf664fb5ced10d69a169ca9c7bd43"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:a5a60be2b58c3602c2fe0d04f6470778a4338a18f4074489fbb1d1acd3d59148"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/11-flow-wal-specspaces.xml"
output = "spec/boot/11-flow-wal-specspaces.xml"
disposition = "copied"

[[file]]
source = "spec/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
output = "spec/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
disposition = "copied"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
