schema = 1
source_hash = "sha256:8cd5500cc6910233a8f291ab3be98e478119157b078ed95fe2a6968f06fa25c7"
output_format = "xml"
converter_recipe = "specdoc/3"
derived_hash = "sha256:f365f9128bc74851b2cc54f2095ccdc8273bb597f6661aebe49779d0600ce8a3"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/11-flow-wal-specspaces.md"
output = "spec/boot/11-flow-wal-specspaces.xml"
disposition = "converted"

[[file]]
source = "spec/flows/wal-specspaces/SPECSPACES-PROTOCOL.md"
output = "spec/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
