use std::env;
use std::fs;
use std::process::{Command, ExitStatus};

use tempfile::TempDir;
use vibe_spec::{
    ArtifactInput, ArtifactPlan, ArtifactTarget, SectionSource, SpecAddress,
    compile_artifact_missing_backend_test_vehicle, compile_artifact_opaque_test_vehicle,
    compile_artifact_replacement_test_vehicle,
};

use super::*;

const CHILD_ROOT: &str = "VIBEVM_R32_TXN_CHILD_ROOT";
const CHILD_DIRECTION: &str = "VIBEVM_R32_TXN_CHILD_DIRECTION";
const CHILD_POINT: &str = "VIBEVM_R32_TXN_CHILD_POINT";
const CHILD_ROLLBACK: &str = "VIBEVM_R32_TXN_CHILD_ROLLBACK";

struct FailAt(WritePoint);

impl FaultInjector for FailAt {
    fn check(&self, point: WritePoint, path: &Path) -> Result<(), WorkspaceError> {
        if point == self.0 {
            Err(injected(path, format!("injected {point:?}")))
        } else {
            Ok(())
        }
    }
}

struct FailPrimaryAndEveryRestore;

impl FaultInjector for FailPrimaryAndEveryRestore {
    fn check(&self, point: WritePoint, path: &Path) -> Result<(), WorkspaceError> {
        match point {
            WritePoint::IndexReplace => Err(injected(path, "primary INDEX failure")),
            WritePoint::RollbackRestore => Err(injected(
                path,
                format!("rollback restore failure for {}", path.display()),
            )),
            _ => Ok(()),
        }
    }
}

#[derive(Clone, Copy)]
enum Direction {
    MarkdownToXml,
    XmlToMarkdown,
}

impl Direction {
    fn code(self) -> &'static str {
        match self {
            Direction::MarkdownToXml => "md-xml",
            Direction::XmlToMarkdown => "xml-md",
        }
    }

    fn parse(value: &str) -> Self {
        match value {
            "md-xml" => Direction::MarkdownToXml,
            "xml-md" => Direction::XmlToMarkdown,
            other => panic!("unknown child direction {other}"),
        }
    }

    fn old_name(self) -> &'static str {
        match self {
            Direction::MarkdownToXml => "STATIC.md",
            Direction::XmlToMarkdown => "STATIC.xml",
        }
    }

    fn new_name(self) -> &'static str {
        match self {
            Direction::MarkdownToXml => "STATIC.xml",
            Direction::XmlToMarkdown => "STATIC.md",
        }
    }
}

struct Fixture {
    index: PathBuf,
    selected: PathBuf,
    stale: PathBuf,
    old_index: Vec<u8>,
    new_index: Vec<u8>,
}

impl Fixture {
    fn write(&self) -> ArtifactWrite<'_> {
        ArtifactWrite {
            index_path: &self.index,
            index_bytes: &self.new_index,
            static_path: &self.selected,
            static_bytes: Some(b"NEW-STATIC"),
            stale_path: &self.stale,
        }
    }

    fn assert_old(&self) {
        assert_eq!(fs::read(&self.index).unwrap(), self.old_index);
        assert_eq!(fs::read(&self.stale).unwrap(), b"OLD-STATIC");
        assert!(!entry_present(&self.selected));
        assert_exactly_one_static(self.index.parent().unwrap());
    }

    fn assert_new(&self) {
        assert_eq!(fs::read(&self.index).unwrap(), self.new_index);
        assert_eq!(fs::read(&self.selected).unwrap(), b"NEW-STATIC");
        assert!(!entry_present(&self.stale));
        assert_exactly_one_static(self.index.parent().unwrap());
    }
}

fn fixture(root: &Path, direction: Direction) -> Fixture {
    fs::create_dir_all(root).unwrap();
    let index = root.join("INDEX.md");
    let selected = root.join(direction.new_name());
    let stale = root.join(direction.old_name());
    let old_index = index_bytes(direction.old_name());
    let new_index = index_bytes(direction.new_name());
    fs::write(&index, &old_index).unwrap();
    fs::write(&stale, b"OLD-STATIC").unwrap();
    let _ = fs::remove_file(&selected);
    Fixture {
        index,
        selected,
        stale,
        old_index,
        new_index,
    }
}

fn index_bytes(static_name: &str) -> Vec<u8> {
    format!(
        "# vibevm/vibespecs/boot/INDEX.md — generated by vibe, do not edit.\n\
         schema = 1\n\
         static = \"vibevm/vibespecs/boot/{static_name}\"\n\n\
         [[entry]]\n\
         path = \"vibevm/vibespecs/boot/00-core.xml\"\n\
         kind = \"static\"\n"
    )
    .into_bytes()
}

#[test]
fn every_caught_stage_commit_and_cleanup_failure_restores_the_old_selector_world() {
    for point in [
        WritePoint::IndexWrite,
        WritePoint::StaticWrite,
        WritePoint::PostStagePreReplace,
        WritePoint::StaticReplace,
        WritePoint::PostStaticPreIndex,
        WritePoint::IndexReplace,
    ] {
        let temp = TempDir::new().unwrap();
        let fixture = fixture(temp.path(), Direction::MarkdownToXml);
        let result = write_with_faults(fixture.write(), &FailAt(point));
        assert!(result.is_err(), "{point:?} did not fire");
        fixture.assert_old();
        assert!(!intent_exists(temp.path()), "{point:?}: {result:?}");
    }
}

#[test]
fn post_commit_selector_or_stale_errors_keep_both_carriers_until_retry_converges() {
    for point in [
        WritePoint::PostIndexPreStaleCleanup,
        WritePoint::StaleRemove,
    ] {
        let temp = TempDir::new().unwrap();
        let fixture = fixture(temp.path(), Direction::MarkdownToXml);
        assert!(write_with_faults(fixture.write(), &FailAt(point)).is_err());
        assert_eq!(fs::read(&fixture.index).unwrap(), fixture.new_index);
        assert_eq!(fs::read(&fixture.selected).unwrap(), b"NEW-STATIC");
        assert_eq!(fs::read(&fixture.stale).unwrap(), b"OLD-STATIC");
        assert_eq!(static_count(temp.path()), 2);
        write_with_faults(fixture.write(), &NoFault).unwrap();
        fixture.assert_new();
    }
}

#[test]
fn rollback_attempts_every_path_and_reports_primary_plus_all_restore_failures() {
    let temp = TempDir::new().unwrap();
    let fixture = fixture(temp.path(), Direction::MarkdownToXml);
    let error = write_with_faults(fixture.write(), &FailPrimaryAndEveryRestore).unwrap_err();
    let message = error.to_string();
    assert!(message.contains("primary INDEX failure"), "{message}");
    for name in ["INDEX.md", "STATIC.md", "STATIC.xml"] {
        assert!(message.contains(name), "missing {name}: {message}");
    }
    assert!(intent_exists(temp.path()));
    recover_pending(temp.path()).unwrap();
    fixture.assert_old();
}

#[test]
fn child_interruptions_recover_real_markdown_xml_selector_switches() {
    for direction in [Direction::MarkdownToXml, Direction::XmlToMarkdown] {
        for point in [
            WritePoint::PostStagePreReplace,
            WritePoint::PostStaticPreIndex,
            WritePoint::PostIndexPreStaleCleanup,
        ] {
            let temp = TempDir::new().unwrap();
            let fixture = fixture(temp.path(), direction);
            assert_interrupted(spawn_child(temp.path(), direction, point, false));
            assert!(intent_exists(temp.path()), "{point:?}");
            recover_pending(temp.path()).unwrap();
            write_with_faults(fixture.write(), &NoFault).unwrap();
            fixture.assert_new();
            assert!(!intent_exists(temp.path()));
        }
    }
}

#[test]
fn child_interruption_during_rollback_resumes_the_durable_rollback_intent() {
    for direction in [Direction::MarkdownToXml, Direction::XmlToMarkdown] {
        let temp = TempDir::new().unwrap();
        let fixture = fixture(temp.path(), direction);
        assert_interrupted(spawn_child(
            temp.path(),
            direction,
            WritePoint::PostRollbackRestore,
            true,
        ));
        assert!(intent_exists(temp.path()));
        assert!(temp.path().join("ROLLBACK-MUTATED").is_file());
        assert!(!entry_present(&fixture.selected));
        recover_pending(temp.path()).unwrap();
        fixture.assert_old();
        assert!(!intent_exists(temp.path()));
    }
}

#[test]
fn recovery_refuses_a_concurrent_third_state_without_clobbering_it() {
    let temp = TempDir::new().unwrap();
    let fixture = fixture(temp.path(), Direction::MarkdownToXml);
    assert_interrupted(spawn_child(
        temp.path(),
        Direction::MarkdownToXml,
        WritePoint::PostStaticPreIndex,
        false,
    ));
    fs::write(&fixture.index, b"CONCURRENT-INDEX").unwrap();

    let error = recover_pending(temp.path()).unwrap_err();
    assert!(error.to_string().contains("concurrent/third state"));
    assert_eq!(fs::read(&fixture.index).unwrap(), b"CONCURRENT-INDEX");
    assert!(intent_exists(temp.path()));
}

#[test]
fn generated_jtd_transaction_type_parses_the_committed_toml_corpus_strictly() {
    let corpus =
        include_str!("../../../../../formats/corpora/boot-artifact-transaction/e1/commit.toml");
    let journal: Journal = toml::from_str(corpus).unwrap();
    assert_eq!(journal.schema, JOURNAL_SCHEMA);
    assert_eq!(journal.mode, JournalMode::Commit);
    validate_journal(&journal, Path::new(JOURNAL_NAME), JournalMode::Commit).unwrap();
    assert_eq!(
        toml::from_str::<Journal>(&toml::to_string(&journal).unwrap()).unwrap(),
        journal
    );
    assert!(toml::from_str::<Journal>(&format!("{corpus}\nunknown = true\n")).is_err());
}

fn spawn_child(root: &Path, direction: Direction, point: WritePoint, rollback: bool) -> ExitStatus {
    Command::new(env::current_exe().unwrap())
        .arg("--exact")
        .arg("boot_artifacts::transaction::tests::transaction_child_helper")
        .arg("--nocapture")
        .env(CHILD_ROOT, root)
        .env(CHILD_DIRECTION, direction.code())
        .env(CHILD_POINT, format!("{point:?}"))
        .env(CHILD_ROLLBACK, if rollback { "1" } else { "0" })
        .status()
        .unwrap()
}

fn assert_interrupted(status: ExitStatus) {
    assert_eq!(status.code(), Some(86), "child status: {status}");
}

struct ChildExit {
    point: WritePoint,
    rollback: bool,
}

impl FaultInjector for ChildExit {
    fn check(&self, point: WritePoint, path: &Path) -> Result<(), WorkspaceError> {
        if self.rollback && point == WritePoint::IndexReplace {
            return Err(injected(path, "child primary failure"));
        }
        if point == self.point {
            if self.rollback {
                fs::write(
                    path.parent().unwrap().join("ROLLBACK-MUTATED"),
                    path.display().to_string(),
                )
                .unwrap();
            }
            std::process::exit(86);
        }
        Ok(())
    }
}

#[test]
fn transaction_child_helper() {
    let Ok(root) = env::var(CHILD_ROOT) else {
        return;
    };
    let direction = Direction::parse(&env::var(CHILD_DIRECTION).unwrap());
    let point = parse_point(&env::var(CHILD_POINT).unwrap());
    let rollback = env::var(CHILD_ROLLBACK).unwrap() == "1";
    let fixture = Fixture {
        index: PathBuf::from(&root).join("INDEX.md"),
        selected: PathBuf::from(&root).join(direction.new_name()),
        stale: PathBuf::from(&root).join(direction.old_name()),
        old_index: index_bytes(direction.old_name()),
        new_index: index_bytes(direction.new_name()),
    };
    let result = write_with_faults(fixture.write(), &ChildExit { point, rollback });
    panic!("child reached the end instead of interruption: {result:?}");
}

fn parse_point(value: &str) -> WritePoint {
    match value {
        "PostStagePreReplace" => WritePoint::PostStagePreReplace,
        "PostStaticPreIndex" => WritePoint::PostStaticPreIndex,
        "PostIndexPreStaleCleanup" => WritePoint::PostIndexPreStaleCleanup,
        "PostRollbackRestore" => WritePoint::PostRollbackRestore,
        other => panic!("unknown child point {other}"),
    }
}

fn assert_exactly_one_static(root: &Path) {
    let count = static_count(root);
    assert_eq!(count, 1, "STATIC invariant at {}", root.display());
}

fn static_count(root: &Path) -> usize {
    [root.join("STATIC.md"), root.join("STATIC.xml")]
        .iter()
        .filter(|path| fs::symlink_metadata(path).is_ok())
        .count()
}

fn intent_exists(root: &Path) -> bool {
    entry_present(&journal_path(root)) || entry_present(&rollback_journal_path(root))
}

fn entry_present(path: &Path) -> bool {
    match fs::symlink_metadata(path) {
        Ok(_) => true,
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => false,
        Err(error) => panic!("metadata for {} failed: {error}", path.display()),
    }
}

fn injected(path: &Path, reason: impl ToString) -> WorkspaceError {
    WorkspaceError::Io {
        path: path.to_path_buf(),
        reason: reason.to_string(),
    }
}

struct NoSource;

impl SectionSource for NoSource {
    fn section_text(&self, _addr: &SpecAddress) -> Result<String, String> {
        Err("unexpected resolver call".to_string())
    }
}

fn test_plan() -> ArtifactPlan {
    ArtifactPlan::static_lane(
        ArtifactTarget::StaticMarkdown,
        "vibevm/vibespecs/boot/STATIC.md",
        "vibevm/vibedeps",
        vec![ArtifactInput::simple("org.demo/a", "boot/a.md", "# A\n").unwrap()],
    )
    .unwrap()
}

#[test]
fn opaque_custom_compile_and_real_writer_preserve_arbitrary_bytes_without_shipping_controls() {
    let emitted = compile_artifact_opaque_test_vehicle(test_plan(), &NoSource).unwrap();
    assert_eq!(emitted.bytes(), [0x00, 0xff, b'\n']);

    let temp = TempDir::new().unwrap();
    let index = temp.path().join("INDEX.md");
    let selected = temp.path().join("STATIC.md");
    let stale = temp.path().join("STATIC.xml");
    write_production(ArtifactWrite {
        index_path: &index,
        index_bytes: b"INDEX",
        static_path: &selected,
        static_bytes: Some(emitted.bytes()),
        stale_path: &stale,
    })
    .unwrap();
    assert_eq!(fs::read(index).unwrap(), b"INDEX");
    assert_eq!(fs::read(selected).unwrap(), [0x00, 0xff, b'\n']);
}

#[test]
fn missing_and_invalid_replacement_backends_fail_before_the_writer() {
    assert!(compile_artifact_missing_backend_test_vehicle(test_plan(), &NoSource).is_err());
    let error = compile_artifact_replacement_test_vehicle(test_plan(), &NoSource).unwrap_err();
    assert!(error.to_string().contains("STATIC Markdown is not UTF-8"));
}
