schema = 1
source_hash = "sha256:da9a22e59a5e8b2444f7d1dd17e75d4cb33039d30aecccf4619126d4e4be1453"
output_format = "xml"
converter_recipe = "specdoc/1"
derived_hash = "sha256:099bf2562caa6a4b93d28b11e53edead34912c74caa3b70399141b1ce7f29dc7"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/31-flow-conventional-commits.md"
output = "spec/boot/31-flow-conventional-commits.xml"
disposition = "converted"

[[file]]
source = "spec/flows/conventional-commits/conventional-commits.md"
output = "spec/flows/conventional-commits/conventional-commits.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
