schema = 1
source_hash = "sha256:ceb04c60d2cea4dce8976a62928b3716edffe4442cc43319886de8847ff33df7"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:46cbcd6b23ec3b8c134fb326e03a8648bd24a4643af027b0cda59a8f2482483b"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "spec/boot/31-flow-conventional-commits.xml"
output = "spec/boot/31-flow-conventional-commits.xml"
disposition = "copied"

[[file]]
source = "spec/flows/conventional-commits/conventional-commits.xml"
output = "spec/flows/conventional-commits/conventional-commits.xml"
disposition = "copied"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
