//! Unit tests for the variant-naming arm — one per behaviour it owes,
//! including the two decisions R27 took that are easy to lose later:
//! that `x-rust-variants` is read INDEPENDENTLY of `x-rust-type`, and
//! that both forms carrying variants (an `enum`'s values, a
//! `discriminator`'s mapping keys) are covered by the one rule.
//!
//! They drive the production driver through the sibling suite's
//! harness, so a green here is a green of the whole pipeline in its
//! recorded order rather than of this arm in isolation.

use anyhow::Result;
use serde_json::json;

use crate::codegen::domain_types::tests::through_pipeline;

/// The emission of a closed vocabulary whose two wire strings collapse
/// to one identifier, so the generator disambiguates the second with a
/// numeric suffix — the real `naming_convention` shape, shortened.
const VOCAB_EMISSION: &str = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub enum Naming {
    #[serde(rename = "kind-name")]
    KindName,

    #[serde(rename = "kind/name")]
    KindName0,
}

#[derive(Serialize, Deserialize)]
pub struct Holder {
    #[serde(rename = "naming")]
    pub naming: Naming,
}
"#;

/// The named variant is renamed and its wire string is untouched — the
/// whole point of keying on the value rather than on the identifier.
#[test]
fn a_named_variant_takes_the_identifier_the_schema_chooses() -> Result<()> {
    let doc = json!({
        "definitions": {
            "naming": {
                "metadata": {
                    "x-vocabulary": "closed",
                    "x-rust-variants": { "kind/name": "KindSlashName" }
                },
                "enum": ["kind-name", "kind/name"]
            }
        },
        "properties": { "naming": { "ref": "naming" } }
    });
    let out = through_pipeline(VOCAB_EMISSION, doc, "holder")?;
    assert!(
        out.contains("#[serde(rename = \"kind/name\")]\n    KindSlashName,"),
        "the identifier moved and the wire string did not:\n{out}"
    );
    assert!(
        !out.contains("KindName0"),
        "the minted name survived:\n{out}"
    );
    assert!(
        out.contains("#[serde(rename = \"kind-name\")]\n    KindName,"),
        "the variant nobody named must not move:\n{out}"
    );
    Ok(())
}

/// R27's independence decision, pinned: a definition may name its
/// variants WITHOUT naming its type. Coupling the two would have
/// written today's tree — where the one definition needing variant
/// names happens to name its type too — into the rule.
#[test]
fn variants_are_named_without_naming_the_type() -> Result<()> {
    let doc = json!({
        "definitions": {
            "naming": {
                "metadata": {
                    "x-vocabulary": "closed",
                    "x-rust-variants": { "kind/name": "KindSlashName" }
                },
                "enum": ["kind-name", "kind/name"]
            }
        },
        "properties": { "naming": { "ref": "naming" } }
    });
    let out = through_pipeline(VOCAB_EMISSION, doc, "holder")?;
    assert!(
        out.contains("pub enum Naming {"),
        "the type keeps its name:\n{out}"
    );
    assert!(
        out.contains("KindSlashName,"),
        "the variant still moved:\n{out}"
    );
    Ok(())
}

/// A chosen name the generator already minted is a no-op, byte for
/// byte: a schema agreeing with the emission must not move the file.
#[test]
fn a_name_the_generator_already_minted_moves_nothing() -> Result<()> {
    let doc = json!({
        "definitions": {
            "naming": {
                "metadata": {
                    "x-vocabulary": "closed",
                    "x-rust-variants": { "kind-name": "KindName" }
                },
                "enum": ["kind-name", "kind/name"]
            }
        },
        "properties": { "naming": { "ref": "naming" } }
    });
    let out = through_pipeline(VOCAB_EMISSION, doc, "holder")?;
    assert_eq!(
        out,
        VOCAB_EMISSION.replace("    #[serde(rename = \"naming\")]\n", "")
    );
    Ok(())
}

/// R27's other half: a discriminator's mapping keys are variants too,
/// and one rule covers both forms. A rule that reached only the form
/// which happened to need it first would be a rule shaped by the tree.
#[test]
fn a_discriminator_arm_is_named_the_same_way() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum Event {
    #[serde(rename = "kind/name")]
    EventKindName(EventKindName),
}

#[derive(Serialize, Deserialize)]
pub struct EventKindName {
    #[serde(rename = "at")]
    pub at: String,
}
"#;
    let doc = json!({
        "definitions": {
            "event": {
                "metadata": { "x-rust-variants": { "kind/name": "KindSlashName" } },
                "discriminator": "kind",
                "mapping": { "kind/name": { "properties": { "at": { "type": "string" } } } }
            }
        },
        "properties": {}
    });
    let out = through_pipeline(src, doc, "holder")?;
    assert!(
        out.contains("KindSlashName(Box<EventKindName>),"),
        "the union arm took the chosen identifier:\n{out}"
    );
    assert!(
        out.contains("#[serde(rename = \"kind/name\")]"),
        "the arm's wire string did not move:\n{out}"
    );
    Ok(())
}

/// A key naming a value the definition does not have is caught on the
/// SCHEMA side, before any Rust is read — the two documents disagree
/// about the vocabulary, not about the emission, and the message says
/// which values the definition does carry.
#[test]
fn a_key_outside_the_vocabulary_refuses_naming_the_values() -> Result<()> {
    let doc = json!({
        "definitions": {
            "naming": {
                "metadata": {
                    "x-vocabulary": "closed",
                    "x-rust-variants": { "kind_name": "KindSlashName" }
                },
                "enum": ["kind-name", "kind/name"]
            }
        },
        "properties": { "naming": { "ref": "naming" } }
    });
    let err = through_pipeline(VOCAB_EMISSION, doc, "holder")
        .expect_err("a key outside the vocabulary must refuse")
        .to_string();
    assert!(
        err.contains("kind_name"),
        "the refusal names the key: {err}"
    );
    assert!(
        err.contains("kind-name, kind/name"),
        "the refusal lists the values the definition carries: {err}"
    );
    Ok(())
}

/// The annotation on a form with no variants refuses: only an `enum` or
/// a `discriminator` has any, and a struct's fields are not variants.
#[test]
fn the_annotation_on_a_form_without_variants_refuses() -> Result<()> {
    let doc = json!({
        "definitions": {
            "naming": {
                "metadata": { "x-rust-variants": { "kind/name": "KindSlashName" } },
                "properties": { "at": { "type": "string" } }
            }
        },
        "properties": { "naming": { "ref": "naming" } }
    });
    let err = through_pipeline(VOCAB_EMISSION, doc, "holder")
        .expect_err("a form without variants must refuse")
        .to_string();
    assert!(
        err.contains("no variants"),
        "the refusal says what the form lacks: {err}"
    );
    Ok(())
}

/// A non-string identifier refuses: the value is source text spliced
/// into the generated file, so a number there is an author's typo
/// rather than a policy.
#[test]
fn a_non_string_identifier_refuses() -> Result<()> {
    let doc = json!({
        "definitions": {
            "naming": {
                "metadata": {
                    "x-vocabulary": "closed",
                    "x-rust-variants": { "kind/name": 7 }
                },
                "enum": ["kind-name", "kind/name"]
            }
        },
        "properties": { "naming": { "ref": "naming" } }
    });
    let err = through_pipeline(VOCAB_EMISSION, doc, "holder")
        .expect_err("a non-string identifier must refuse")
        .to_string();
    assert!(
        err.contains("must be a string"),
        "the refusal says what the value must be: {err}"
    );
    Ok(())
}
