//! The managed redirect block (PROP-012) — vibevm's `<vibevm>` block in the
//! agent instruction files (`CLAUDE.md` / `AGENTS.md` / `GEMINI.md`).
//!
//! vibevm owns only the delimited block inside each co-tenant file; the rest
//! of every file belongs to the developer and any other tool and is preserved
//! verbatim. PROP-012 §2: a plain line scan finds the `<vibevm>` / `</vibevm>`
//! markers (no markdown parse), absent markers create the block, a present
//! pair splices a fresh body between them touching nothing outside, and a
//! malformed pair is a hard stop. The block body itself ([`render_redirect`])
//! is the PROP-009 §2.3 redirect, unchanged — PROP-012
//! changed the envelope, not the payload.

specmark::scope!("spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#surface");

#[cfg(test)]
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

use specmark::spec;
use vibe_core::manifest::SpecFormat;

use super::{io_err, static_path};
use crate::{WorkspaceError, layout_paths, safe_file};

/// The agent instruction files a node carries at its root. vibevm owns
/// only a `<vibevm>` block inside each (PROP-012); the rest of every file
/// belongs to the developer and any other tool sharing it.
pub const REDIRECT_FILES: &[&str] = &["CLAUDE.md", "AGENTS.md", "GEMINI.md"];

/// The opening marker of vibevm's managed block (PROP-012 §2.2), matched
/// as a whole trimmed line.
pub const BLOCK_OPEN: &str = "<vibevm>";

/// The closing marker of vibevm's managed block — see [`BLOCK_OPEN`].
pub const BLOCK_CLOSE: &str = "</vibevm>";

/// The header line of the pre-PROP-012 whole-file generated redirect. A
/// file carrying no `<vibevm>` markers but beginning with this line was
/// wholly vibevm's, and is migrated to a managed block wholesale
/// (PROP-012 §4).
const OLD_GENERATED_HEADER: &str =
    "<!-- Generated by vibe — do not edit. This file is overwritten on `vibe install`. -->";

/// The body of vibevm's managed block — the text between the `<vibevm>`
/// markers. PROP-012 §2.5: the payload is the PROP-009 §2.3 redirect,
/// unchanged; only the envelope (a fenced region of a shared file) is new.
const BLOCK_BODY_PREFIX: &str = "\
<!-- Generated by vibe — do not edit inside this block; it is rewritten on `vibe install`. Text outside the <vibevm> markers is yours. -->

# Session boot

This project's boot sequence is computed by vibe (the PROP-009 loading
model). To begin a session, read these files in order:

1. `";

const BLOCK_BODY_AFTER_STATIC: &str = "\
` — if it exists. The static (priority) lane: read it
   first and in full.
2. `";

const BLOCK_BODY_SUFFIX: &str = "\
` — a generated TOML manifest. Read every file named
   by its `[[entry]]` tables, in the listed order. A `kind = \"static\"`
   entry is read directly; a `kind = \"dynamic\"` entry is an INCLUDE
   resolved at boot, and one carrying a `when` condition is read only when
   that condition holds for the current session.

Boot is pure file-reading — there is nothing to execute.";

/// The body of vibevm's managed redirect block — the text between the
/// `<vibevm>` markers (PROP-012 §2.5).
#[spec(
    implements = "spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#content",
    r = 1
)]
pub fn render_redirect() -> &'static str {
    static BODY: OnceLock<String> = OnceLock::new();
    BODY.get_or_init(|| render_redirect_with_spec_format(SpecFormat::Mixed))
        .as_str()
}

/// Render the redirect with its static pointer following the target format.
pub fn render_redirect_with_spec_format(spec_format: SpecFormat) -> String {
    format!(
        "{BLOCK_BODY_PREFIX}{}{BLOCK_BODY_AFTER_STATIC}{}{BLOCK_BODY_SUFFIX}",
        static_path(spec_format),
        layout_paths::boot(vibe_core::layout::INDEX_MD)
    )
}

/// The full managed block — the `<vibevm>` marker, the body, the
/// `</vibevm>` marker — as written into an instruction file. Ends with a
/// trailing newline so it slots cleanly into a file.
fn render_block(spec_format: SpecFormat) -> String {
    let body = render_redirect_with_spec_format(spec_format);
    format!("{BLOCK_OPEN}\n{body}\n{BLOCK_CLOSE}\n")
}

/// Where vibevm's managed `<vibevm>` block sits in an instruction file
/// (PROP-012 §2.2–§2.3).
#[derive(Debug, Clone, PartialEq, Eq)]
#[spec(
    implements = "spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#markers",
    r = 1
)]
pub enum BlockLocation {
    /// No `<vibevm>` markers at all — the block is created on write (§2.3).
    Absent,
    /// Exactly one well-formed pair. `[start, end)` is the block's byte
    /// span — the first byte of the `<vibevm>` line to the byte after the
    /// `</vibevm>` line (its newline included when present).
    Present { start: usize, end: usize },
    /// The markers are malformed — not exactly one ordered pair. The
    /// string names the defect for the operator.
    Malformed(String),
}

/// Locate vibevm's managed block in `content` by a plain line scan: a
/// line whose trimmed text equals `<vibevm>` / `</vibevm>` is a marker
/// (PROP-012 §2.2). No markdown parse, no model — the detection that
/// gates a mutating write must be deterministic and trivial.
#[spec(
    implements = "spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#markers",
    r = 1
)]
pub fn locate_block(content: &str) -> BlockLocation {
    let mut open: Option<(usize, usize)> = None;
    let mut close: Option<(usize, usize)> = None;
    let mut open_lines: Vec<usize> = Vec::new();
    let mut close_lines: Vec<usize> = Vec::new();
    let mut offset = 0usize;
    for (line_no, line) in content.split_inclusive('\n').enumerate() {
        let trimmed = line.strip_suffix('\n').unwrap_or(line).trim();
        if trimmed == BLOCK_OPEN {
            open_lines.push(line_no + 1);
            open.get_or_insert((offset, offset + line.len()));
        } else if trimmed == BLOCK_CLOSE {
            close_lines.push(line_no + 1);
            close.get_or_insert((offset, offset + line.len()));
        }
        offset += line.len();
    }
    // Matching on the recorded spans (not just the counts) lets the
    // compiler carry the "one of each → both recorded" invariant; the
    // impossible counts-without-spans combination falls through to the
    // Malformed arm instead of a panic. A Malformed report names each
    // marker's line — the drill's precision: the operator repairs the
    // file by hand and must not have to search for the markers.
    match (open_lines.len(), close_lines.len(), open, close) {
        (0, 0, _, _) => BlockLocation::Absent,
        (1, 1, Some((open_start, _)), Some((close_start, close_end))) => {
            if open_start < close_start {
                BlockLocation::Present {
                    start: open_start,
                    end: close_end,
                }
            } else {
                BlockLocation::Malformed(format!(
                    "the `</vibevm>` marker (line {}) precedes its `<vibevm>` opener (line {})",
                    close_lines[0], open_lines[0]
                ))
            }
        }
        (opens, closes, _, _) => BlockLocation::Malformed(format!(
            "expected zero markers or exactly one `<vibevm>` … `</vibevm>` pair, found \
             {opens} `<vibevm>` marker line(s){} and {closes} `</vibevm>` marker line(s){}",
            at_lines(&open_lines),
            at_lines(&close_lines)
        )),
    }
}

/// Render a marker-line list as ` at line(s) 12, 40` — empty when there
/// are no markers, so a zero count is not followed by an empty list.
fn at_lines(lines: &[usize]) -> String {
    if lines.is_empty() {
        String::new()
    } else {
        let joined = lines
            .iter()
            .map(|l| l.to_string())
            .collect::<Vec<_>>()
            .join(", ");
        format!(" at line(s) {joined}")
    }
}

/// Write vibevm's managed block into the instruction file at `path`
/// (PROP-012 §2.3). Returns the path when the file changed, or `None`
/// when it already carried a byte-identical block (no write — no churn).
///
/// Absent markers → append a fresh block at end of file, preserving every
/// existing byte (or, when the whole file is the pre-PROP-012 generated
/// redirect, replace it wholesale — PROP-012 §4); a missing file is
/// created. Present → splice the new body between the markers, touching
/// nothing outside them. Malformed → [`WorkspaceError::MalformedRedirectBlock`]
/// without writing — callers validate at plan time (PROP-012 §2.4), so
/// this is the defensive last line.
#[cfg(test)]
#[spec(
    implements = "spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#create",
    r = 1
)]
#[spec(
    implements = "spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#migration",
    r = 1
)]
fn write_managed_block(path: &Path) -> Result<Option<PathBuf>, WorkspaceError> {
    write_managed_block_with_spec_format(path, SpecFormat::Mixed, "redirecttest")
}

fn write_managed_block_with_spec_format(
    path: &Path,
    spec_format: SpecFormat,
    transaction: &str,
) -> Result<Option<PathBuf>, WorkspaceError> {
    let existing = match safe_file::read_optional(path).map_err(|error| io_err(path, error))? {
        Some(bytes) => Some(
            String::from_utf8(bytes).map_err(|error| WorkspaceError::Io {
                path: path.to_path_buf(),
                reason: error.to_string(),
            })?,
        ),
        None => None,
    };
    let block = render_block(spec_format);
    let new_content = match &existing {
        None => block,
        Some(content) => match locate_block(content) {
            BlockLocation::Malformed(reason) => {
                return Err(WorkspaceError::MalformedRedirectBlock {
                    path: path.to_path_buf(),
                    reason,
                });
            }
            BlockLocation::Present { start, end } => {
                let mut out = String::with_capacity(content.len());
                out.push_str(&content[..start]);
                out.push_str(&block);
                out.push_str(&content[end..]);
                out
            }
            BlockLocation::Absent => {
                if content.trim().is_empty()
                    || content.trim_start().starts_with(OLD_GENERATED_HEADER)
                {
                    // An empty file, or the pre-PROP-012 whole-file
                    // generated redirect — the file was vibevm's, so
                    // reclaim it as a block (PROP-012 §4).
                    block
                } else {
                    // Co-tenant content — append the block after it,
                    // preserving every existing byte (PROP-012 §2.3).
                    let mut out = content.clone();
                    if !out.ends_with('\n') {
                        out.push('\n');
                    }
                    out.push('\n');
                    out.push_str(&block);
                    out
                }
            }
        },
    };
    if existing.as_deref() == Some(new_content.as_str()) {
        return Ok(None);
    }
    super::transaction::replace_selector(path, new_content.as_bytes(), transaction)?;
    Ok(Some(path.to_path_buf()))
}

/// Write vibevm's managed `<vibevm>` block into every agent instruction
/// file ([`REDIRECT_FILES`]) of the node rooted at `node_dir` (PROP-012).
/// Returns the files actually written — a file already carrying an
/// identical block is left untouched.
pub fn write_redirect_blocks(node_dir: &Path) -> Result<Vec<PathBuf>, WorkspaceError> {
    write_redirect_blocks_with_spec_format(node_dir, SpecFormat::Mixed)
}

/// Write the managed redirects with the selected static-lane target.
pub fn write_redirect_blocks_with_spec_format(
    node_dir: &Path,
    spec_format: SpecFormat,
) -> Result<Vec<PathBuf>, WorkspaceError> {
    let boot_dir = node_dir.join(vibe_core::layout::current_boot_dir());
    let nonce = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();
    let transaction = format!("redirect{}{nonce}", std::process::id());
    super::transaction::with_boot_lock(&boot_dir, || {
        write_redirect_blocks_with_transaction(node_dir, spec_format, &transaction)
    })
}

pub(super) fn write_redirect_blocks_with_transaction(
    node_dir: &Path,
    spec_format: SpecFormat,
    transaction: &str,
) -> Result<Vec<PathBuf>, WorkspaceError> {
    write_redirect_blocks_with_faults(node_dir, spec_format, transaction, &NoRedirectFault)
}

trait RedirectFaultInjector {
    fn after_replace(&self, index: usize, path: &Path) -> Result<(), WorkspaceError>;
}

struct NoRedirectFault;

impl RedirectFaultInjector for NoRedirectFault {
    fn after_replace(&self, _index: usize, _path: &Path) -> Result<(), WorkspaceError> {
        Ok(())
    }
}

fn write_redirect_blocks_with_faults(
    node_dir: &Path,
    spec_format: SpecFormat,
    transaction: &str,
    faults: &impl RedirectFaultInjector,
) -> Result<Vec<PathBuf>, WorkspaceError> {
    let mut written = Vec::new();
    for (index, name) in REDIRECT_FILES.iter().enumerate() {
        let path = node_dir.join(name);
        if let Some(path) = write_managed_block_with_spec_format(&path, spec_format, transaction)? {
            written.push(path);
        }
        faults.after_replace(index, &path)?;
    }
    Ok(written)
}

#[cfg(test)]
#[path = "redirect/tests.rs"]
mod tests;

#[cfg(test)]
#[path = "redirect/interruption_tests.rs"]
mod interruption_tests;
