//! Unit tests for [`super`], out-of-line per the file-length budget.
//! Included via `#[cfg(test)] #[path] mod tests;`, so the module-tree
//! position — and therefore `use super::*` — is unchanged from the
//! inline form. Non-`#[test]` helpers carry `#[cfg(test)]` so
//! file-grain scanners (the conform frontend) scope their `unwrap`s
//! as test code.

use super::*;
use crate::boot::{BootBand, BootEntry};
use specmark::verifies;
use tempfile::TempDir;
use vibe_core::manifest::{LinkType, PackageFormat, TargetOs, WhenCondition};
use vibe_spec::{DocTree, FileResolver, FsSectionSource, SectionSource, SpecAddress};

#[cfg(test)]
fn entry(path: &str, link: LinkType, origin: &str) -> BootEntry {
    BootEntry {
        path: path.to_string(),
        band: BootBand::Dependency,
        link,
        when: None,
        origin: origin.to_string(),
        use_ref: false,
        format: Default::default(),
        unit_substituted: false,
        elided: false,
    }
}

/// A `BootEntry` with an explicit link and `when` — for exercising the
/// `INDEX.md` rendering of conditional entries directly.
#[cfg(test)]
fn entry_when(path: &str, link: LinkType, when: Option<WhenCondition>, origin: &str) -> BootEntry {
    BootEntry {
        path: path.to_string(),
        band: BootBand::Dependency,
        link,
        when,
        origin: origin.to_string(),
        use_ref: false,
        format: Default::default(),
        unit_substituted: false,
        elided: false,
    }
}

#[cfg(test)]
fn boot(entries: Vec<BootEntry>) -> EffectiveBoot {
    EffectiveBoot { entries }
}

/// A `normal`-format `static` entry — the renderer compiles its `#use` /
/// `#source` closure rather than concatenating the file (PROP-035 §8).
#[cfg(test)]
fn entry_normal(path: &str, origin: &str) -> BootEntry {
    BootEntry {
        path: path.to_string(),
        band: BootBand::Dependency,
        link: LinkType::Static,
        when: None,
        origin: origin.to_string(),
        use_ref: false,
        format: PackageFormat::Normal,
        unit_substituted: false,
        elided: false,
    }
}

/// Write the `greeter` normal-package fixture into `ws`'s `vibedeps/` slot and
/// return the contract's workspace-relative path — a runnable reference model
/// (scaffold H) of a `normal` package: a contract that `#source`s an impl and
/// `#use`s a prelude, plus an `unused` section reachable by neither directive
/// (so the compile must tree-shake it away, PROP-035 §7.2).
#[cfg(test)]
fn write_greeter_fixture(ws: &Path) -> String {
    let base = ws.join("vibedeps/flow-greeter/1.0.0/spec");
    let write = |rel: &str, body: &str| {
        let p = base.join(rel);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(&p, body).unwrap();
    };
    write(
        "contract/greeting.md",
        "# Greeting contract {#root}\n\
         #source spec://com.example.hello/greeter/source/greeting#root\n\
         #use spec://com.example.hello/greeter/contract/prelude#root\n\n\
         CONTRACT_BODY\n",
    );
    write(
        "source/greeting.md",
        "# Greeting impl {#root}\n\nSOURCE_BODY\n",
    );
    write("contract/prelude.md", "# Prelude {#root}\n\nPRELUDE_BODY\n");
    write(
        "contract/unused.md",
        "# Unused {#root}\n\nUNUSED_SHOULD_NOT_APPEAR\n",
    );
    "vibedeps/flow-greeter/1.0.0/spec/contract/greeting.md".to_string()
}

#[test]
fn render_index_of_empty_boot_is_just_the_schema() {
    let text = render_index(&boot(vec![]), None).unwrap();
    let parsed: toml::Value = toml::from_str(&text).unwrap();
    assert_eq!(parsed.get("schema").unwrap().as_integer(), Some(1));
    assert!(parsed.get("static").is_none());
    assert!(parsed.get("entry").is_none());
}

#[test]
fn render_index_carries_static_and_dynamic_entries_in_order() {
    let b = boot(vec![
        // Unconditional → read directly (kind "static").
        entry("spec/boot/00-core.md", LinkType::Dynamic, "."),
        // Conditional (a `when`) → gated INCLUDE (kind "dynamic").
        entry_when(
            "vibedeps/stack-rust/2.1.0/boot/rust.md",
            LinkType::Dynamic,
            Some(WhenCondition::Os(TargetOs::Linux)),
            "stack:rust",
        ),
    ]);
    let text = render_index(&b, None).unwrap();
    assert!(text.contains("generated by vibe, do not edit"));
    let parsed: toml::Value = toml::from_str(&text).unwrap();
    let entries = parsed.get("entry").unwrap().as_array().unwrap();
    assert_eq!(entries.len(), 2);
    assert_eq!(
        entries[0].get("path").unwrap().as_str(),
        Some("spec/boot/00-core.md")
    );
    assert_eq!(entries[0].get("kind").unwrap().as_str(), Some("static"));
    assert_eq!(entries[1].get("kind").unwrap().as_str(), Some("dynamic"));
}

#[test]
fn render_index_inline_pointer_present_only_with_static_entries() {
    let without = render_index(
        &boot(vec![entry("spec/boot/00-core.md", LinkType::Dynamic, ".")]),
        None,
    )
    .unwrap();
    assert!(!without.contains("static ="));

    let with = render_index(
        &boot(vec![entry(
            "vibedeps/flow-crit/1.0.0/boot.md",
            LinkType::Static,
            "flow:crit",
        )]),
        None,
    )
    .unwrap();
    let parsed: toml::Value = toml::from_str(&with).unwrap();
    assert_eq!(
        parsed.get("static").unwrap().as_str(),
        Some("spec/boot/STATIC.md")
    );
}

#[test]
fn render_index_emits_when_on_a_dynamic_entry() {
    let b = boot(vec![entry_when(
        "vibedeps/stack-windows/1.0.0/boot.md",
        LinkType::Dynamic,
        Some(WhenCondition::Os(TargetOs::Windows)),
        "stack:windows",
    )]);
    let text = render_index(&b, None).unwrap();
    // The header documents the OS test for the agent.
    assert!(text.contains("(windows / macos / linux)"), "{text}");
    let parsed: toml::Value = toml::from_str(&text).unwrap();
    let e = &parsed.get("entry").unwrap().as_array().unwrap()[0];
    assert_eq!(e.get("kind").unwrap().as_str(), Some("dynamic"));
    assert_eq!(e.get("when").unwrap().as_str(), Some("os:windows"));
}

#[test]
fn render_index_unconditional_entry_is_kind_static() {
    // A dynamically-linked entry with no `when` is read directly — kind
    // "static", and no `when` key.
    let b = boot(vec![entry_when(
        "vibedeps/stack-rust/2.1.0/boot.md",
        LinkType::Dynamic,
        None,
        "stack:rust",
    )]);
    let parsed: toml::Value = toml::from_str(&render_index(&b, None).unwrap()).unwrap();
    let e = &parsed.get("entry").unwrap().as_array().unwrap()[0];
    assert_eq!(e.get("kind").unwrap().as_str(), Some("static"));
    assert!(
        e.get("when").is_none(),
        "an unconditional entry carries no `when`"
    );
}

#[test]
fn render_index_excludes_static_lane_entries() {
    // A statically-linked entry belongs in STATIC.md, not INDEX.md — only
    // the dynamic entry is indexed.
    let b = boot(vec![
        entry(
            "vibedeps/flow-crit/1.0.0/boot.md",
            LinkType::Static,
            "flow:crit",
        ),
        entry("spec/boot/00-core.md", LinkType::Dynamic, "."),
    ]);
    let parsed: toml::Value = toml::from_str(&render_index(&b, None).unwrap()).unwrap();
    let entries = parsed.get("entry").unwrap().as_array().unwrap();
    assert_eq!(entries.len(), 1);
    assert_eq!(
        entries[0].get("path").unwrap().as_str(),
        Some("spec/boot/00-core.md")
    );
}

#[test]
fn render_static_is_none_without_static_entries() {
    let ws = TempDir::new().unwrap();
    let b = boot(vec![entry("spec/boot/00-core.md", LinkType::Dynamic, ".")]);
    assert!(render_static(&b, ws.path()).unwrap().is_none());
}

#[test]
fn render_static_concatenates_contributions_verbatim() {
    let ws = TempDir::new().unwrap();
    let crit = ws.path().join("vibedeps/flow-crit/1.0.0/boot.md");
    fs::create_dir_all(crit.parent().unwrap()).unwrap();
    fs::write(&crit, "# Critical discipline\n\nAlways do the thing.").unwrap();

    let b = boot(vec![entry(
        "vibedeps/flow-crit/1.0.0/boot.md",
        LinkType::Static,
        "flow:crit",
    )]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();
    assert!(text.contains("generated by vibe, do not edit"));
    assert!(text.contains("<!-- vibe:static flow:crit"));
    assert!(text.contains("# Critical discipline"));
    assert!(text.contains("Always do the thing."));
}

#[test]
fn render_static_expands_an_embed_directive() {
    // The payoff (PROP-035 §8): a #embed in a static contribution is
    // expanded when STATIC.md is compiled.
    let ws = TempDir::new().unwrap();
    let contrib = ws.path().join("vibedeps/flow-x/1.0.0/boot.md");
    fs::create_dir_all(contrib.parent().unwrap()).unwrap();
    fs::write(
        &contrib,
        "# X {#root}\n#embed spec://vibevm/common/TARGET#root",
    )
    .unwrap();
    let target = ws.path().join("spec/common/TARGET.md");
    fs::create_dir_all(target.parent().unwrap()).unwrap();
    fs::write(&target, "# Target {#root}\nEMBEDDED CONTENT").unwrap();

    let b = boot(vec![entry(
        "vibedeps/flow-x/1.0.0/boot.md",
        LinkType::Static,
        "flow:x",
    )]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();
    assert!(text.contains("EMBEDDED CONTENT"), "{text}");
    assert!(!text.contains("#embed"), "{text}");
}

#[test]
fn render_static_without_directives_is_left_verbatim() {
    // The guard: a directive-free lane is not touched by the compiler, so
    // vibevm's own boot stays byte-identical until it adopts the format.
    let ws = TempDir::new().unwrap();
    let contrib = ws.path().join("vibedeps/flow-y/1.0.0/boot.md");
    fs::create_dir_all(contrib.parent().unwrap()).unwrap();
    fs::write(&contrib, "# Y\n\nplain boot content, no directives.").unwrap();
    let b = boot(vec![entry(
        "vibedeps/flow-y/1.0.0/boot.md",
        LinkType::Static,
        "flow:y",
    )]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();
    assert!(text.contains("plain boot content, no directives."));
}

#[test]
#[verifies("spec://vibevm/modules/vibe-workspace/PROP-035#pipeline")]
fn render_static_compiles_a_normal_package_closure() {
    // The heart of `normal + static` (PROP-035 §8): the contribution is
    // compiled to its `#use`/`#source`-resolved, tree-shaken, dependency-
    // ordered closure — not the file concatenated verbatim.
    let ws = TempDir::new().unwrap();
    let contract = write_greeter_fixture(ws.path());
    let b = boot(vec![entry_normal(&contract, "com.example.hello/greeter")]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();

    // Source-merge (§7.3): the contract's `#source` impl body folds in.
    assert!(text.contains("CONTRACT_BODY"), "{text}");
    assert!(text.contains("SOURCE_BODY"), "{text}");
    // Tree-shaking (§7.2): the `#use`'d prelude is pulled...
    assert!(text.contains("PRELUDE_BODY"), "{text}");
    // ...but a section nothing `#use`s never enters the closure.
    assert!(!text.contains("UNUSED_SHOULD_NOT_APPEAR"), "{text}");
    // Topological order (§8 phase 2): the dependency precedes its user.
    let prelude = text.find("PRELUDE_BODY").unwrap();
    let contract_body = text.find("CONTRACT_BODY").unwrap();
    assert!(
        prelude < contract_body,
        "dependency must precede its user:\n{text}"
    );
    // No directive survives the compile (§7.1 / §8). Asserted line-wise so the
    // resolution preamble's documentation of `#use … as` (rule 4) is not
    // mistaken for a surviving directive line.
    assert!(
        !text.lines().any(|l| l.trim_start().starts_with("#use ")),
        "{text}"
    );
    assert!(
        !text.lines().any(|l| l.trim_start().starts_with("#source ")),
        "{text}"
    );
    assert!(
        !text.lines().any(|l| l.trim_start().starts_with("#embed ")),
        "{text}"
    );
}

#[test]
#[verifies("spec://vibevm/modules/vibe-workspace/PROP-035#formats")]
fn render_static_normal_differs_from_simple_on_the_same_file() {
    // The crux of the format distinction (PROP-035 §3/§8): the SAME contract
    // file pulled `static` compiles (normal) versus concatenates verbatim
    // (simple). This is the differential oracle for the feature.
    let ws = TempDir::new().unwrap();
    let contract = write_greeter_fixture(ws.path());

    let normal = render_static(
        &boot(vec![entry_normal(&contract, "com.example.hello/greeter")]),
        ws.path(),
    )
    .unwrap()
    .unwrap();
    let simple = render_static(
        &boot(vec![entry(
            &contract,
            LinkType::Static,
            "com.example.hello/greeter",
        )]),
        ws.path(),
    )
    .unwrap()
    .unwrap();

    // `simple` carries the file verbatim: the directive is unresolved, the
    // source is not merged, and the dependency is not pulled.
    assert!(
        simple.lines().any(|l| l.trim_start().starts_with("#use ")),
        "simple keeps the directive:\n{simple}"
    );
    assert!(
        !simple.contains("SOURCE_BODY"),
        "simple must not merge source"
    );
    assert!(
        !simple.contains("PRELUDE_BODY"),
        "simple must not pull the dep"
    );
    // `normal` resolves the closure: directive gone (line-wise — the
    // preamble documents `#use`, so a literal `.contains` would false-pass),
    // source merged, dep pulled.
    assert!(
        !normal.lines().any(|l| l.trim_start().starts_with("#use ")),
        "normal must resolve the directive:\n{normal}"
    );
    assert!(normal.contains("SOURCE_BODY"));
    assert!(normal.contains("PRELUDE_BODY"));
    assert_ne!(
        normal, simple,
        "normal and simple must produce different static lanes"
    );
}

#[test]
fn render_static_errors_on_a_missing_contribution() {
    let ws = TempDir::new().unwrap();
    let b = boot(vec![entry(
        "vibedeps/flow-gone/1.0.0/boot.md",
        LinkType::Static,
        "flow:gone",
    )]);
    let err = render_static(&b, ws.path()).unwrap_err();
    assert!(matches!(err, WorkspaceError::Io { .. }), "{err}");
}

// ----- B-011 (W3): qualify-on-splice, preamble, tombstone, @!X, R3, R4 -----

/// Write a `simple` boot file into a fresh `vibedeps/<slot>/<ver>/boot.md`.
#[cfg(test)]
fn write_simple_boot(ws: &Path, slot: &str, body: &str) -> String {
    let p = ws.join(format!("vibedeps/{slot}/1.0.0/boot.md"));
    fs::create_dir_all(p.parent().unwrap()).unwrap();
    fs::write(&p, body).unwrap();
    format!("vibedeps/{slot}/1.0.0/boot.md")
}

#[test]
fn golden_splice_qualifies_colliding_labels_and_emits_preamble_and_tombstone() {
    // The B-011 golden (acceptance 1): two simple contributions whose
    // `{#root}` and `##FACT` labels collide. After qualify-on-splice every
    // label is unique by construction, the resolution preamble leads, and the
    // tombstone names each retired short name with its qualified heirs.
    let ws = TempDir::new().unwrap();
    let alpha = write_simple_boot(
        ws.path(),
        "flow-alpha",
        "# Alpha {#root}\n\n##FACT the alpha fact.\n",
    );
    let beta = write_simple_boot(
        ws.path(),
        "flow-beta",
        "# Beta {#root}\n\n##FACT the beta fact.\n",
    );
    let b = boot(vec![
        entry(&alpha, LinkType::Static, "org.demo/alpha"),
        entry(&beta, LinkType::Static, "org.demo/beta"),
    ]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();

    // (1) Zero duplicate anchors over the colliding splice — the gate.
    let dups = DocTree::parse(&text).duplicate_anchors().to_vec();
    assert!(
        dups.is_empty(),
        "colliding labels must be qualified apart:\n{text}"
    );
    // The qualified labels are present, one origin each.
    assert!(text.contains("{#org-demo--alpha--root}"), "{text}");
    assert!(text.contains("{#org-demo--beta--root}"), "{text}");
    assert!(text.contains("##org-demo--alpha--FACT"), "{text}");

    // (2) The resolution preamble, verbatim (rule 1 + the header line).
    assert!(text.contains("RESOLUTION RULES"), "{text}");
    assert!(
        text.contains("qualified: <origin-slug>--<original>"),
        "{text}"
    );

    // (3) The tombstone, directly under the header: each short name with both
    // qualified heirs and origins (FACT sorts before root in the BTreeMap).
    assert!(
        text.contains("RENAMED ANCHORS (short → qualified heirs):"),
        "{text}"
    );
    assert!(
        text.contains(
            "root → org-demo--alpha--root (org.demo/alpha), org-demo--beta--root (org.demo/beta)"
        ),
        "{text}"
    );
    assert!(
        text.contains(
            "FACT → org-demo--alpha--FACT (org.demo/alpha), org-demo--beta--FACT (org.demo/beta)"
        ),
        "{text}"
    );
}

#[test]
fn render_static_omits_the_tombstone_when_no_label_was_renamed() {
    // The tombstone appears only when the qualify phase renamed something. A
    // label-free lane carries no tombstone (and the preamble still leads).
    let ws = TempDir::new().unwrap();
    let p = write_simple_boot(ws.path(), "flow-plain", "Plain prose, no labels at all.");
    let b = boot(vec![entry(&p, LinkType::Static, "org.demo/plain")]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();
    // The tombstone's specific opener is absent (the preamble documents a
    // "RENAMED ANCHORS table" in rule 2, so a literal `contains` would lie).
    assert!(
        !text.contains("RENAMED ANCHORS (short → qualified heirs):"),
        "{text}"
    );
    assert!(text.contains("RESOLUTION RULES"), "{text}");
}

/// Write a `normal` fixture whose contract `#use … as pre`s a prelude and
/// references it via `@!pre` — exercising the compiled-lane `@!X` rewrite
/// (acceptance 1's fourth sub-assertion; necessarily normal-path, since R3
/// forbids `@!` in a `simple` contribution).
#[cfg(test)]
fn write_aliaser_fixture(ws: &Path) -> String {
    let base = ws.join("vibedeps/demo-aliaser/1.0.0/spec");
    let write = |rel: &str, body: &str| {
        let p = base.join(rel);
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(&p, body).unwrap();
    };
    write(
        "contract/greeting.md",
        "# Greeting {#greet-root}\n\
         #use spec://com.example.hello/aliaser/contract/prelude#root as pre\n\
         Sees @!pre here.\n",
    );
    write("contract/prelude.md", "# Prelude {#root}\n\nPRELUDE_BODY\n");
    "vibedeps/demo-aliaser/1.0.0/spec/contract/greeting.md".to_string()
}

#[test]
fn render_static_rewrites_at_bang_to_the_full_address_in_a_normal_closure() {
    let ws = TempDir::new().unwrap();
    let contract = write_aliaser_fixture(ws.path());
    let b = boot(vec![entry_normal(&contract, "com.example.hello/aliaser")]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();

    // `@!pre` became the alias target's full address.
    assert!(
        text.contains("@spec://com.example.hello/aliaser/contract/prelude#root"),
        "{text}"
    );
    assert!(!text.contains("@!pre"), "{text}");
    // The aliased dependency is emitted (it is a real `#use` edge).
    assert!(text.contains("PRELUDE_BODY"), "{text}");
    // The alias declaration left with the stripped `#use` line; the contract's
    // own distinct label is qualified (no collision with the prelude's `#root`).
    assert!(
        text.contains("{#com-example-hello--aliaser--greet-root}"),
        "{text}"
    );
    assert!(
        text.contains("{#com-example-hello--aliaser--root}"),
        "{text}"
    );
    assert!(
        DocTree::parse(&text).duplicate_anchors().is_empty(),
        "{text}"
    );
}

#[test]
fn render_static_errors_when_a_simple_contribution_carries_an_as_clause() {
    // R3: a `#use … as <Alias>` clause is `normal`-format machinery; a `simple`
    // contribution is carried whole and cannot bind aliases.
    let ws = TempDir::new().unwrap();
    let p = write_simple_boot(
        ws.path(),
        "flow-bad",
        "# Bad {#root}\n#use spec://org.demo/other/doc#root as dep\nbody\n",
    );
    let b = boot(vec![entry(&p, LinkType::Static, "org.demo/bad")]);
    let err = render_static(&b, ws.path()).unwrap_err();
    let WorkspaceError::InlineCompile { reason } = err else {
        panic!("expected InlineCompile, got {err:?}");
    };
    assert!(reason.contains("alias machinery"), "{reason}");
    assert!(reason.contains("PROP-035 §7.2"), "{reason}");
}

#[test]
fn render_static_errors_when_a_simple_contribution_carries_at_bang() {
    // R3: an `@!<Alias>` use is likewise `normal`-format machinery.
    let ws = TempDir::new().unwrap();
    let p = write_simple_boot(ws.path(), "flow-bad2", "# Bad {#root}\nSees @!dep here.\n");
    let b = boot(vec![entry(&p, LinkType::Static, "org.demo/bad2")]);
    let err = render_static(&b, ws.path()).unwrap_err();
    let WorkspaceError::InlineCompile { reason } = err else {
        panic!("expected InlineCompile, got {err:?}");
    };
    assert!(reason.contains("alias machinery"), "{reason}");
}

#[test]
fn fs_section_source_surfaces_qualified_candidates_on_a_short_anchor_miss() {
    // R4 (B-011 §6.1 layer 3): a missed short anchor answers with its qualified
    // heirs, never emptiness. A document whose `#root` was qualified to
    // `org-x--aaa--root` is queried for the short `root` — the resolver's miss
    // error lists the heir.
    let ws = TempDir::new().unwrap();
    let doc = ws.path().join("spec/common/TARGET.md");
    fs::create_dir_all(doc.parent().unwrap()).unwrap();
    fs::write(
        &doc,
        "# Target {#org-x--aaa--root}\n##org-x--aaa--FACT a fact\n",
    )
    .unwrap();
    let src = FsSectionSource::new(FileResolver::new(ws.path(), HOST_NAMESPACE));
    let addr = SpecAddress::parse("spec://vibevm/common/TARGET#root").unwrap();
    let err = src.section_text(&addr).unwrap_err();
    assert!(err.contains("anchor not found"), "{err}");
    assert!(err.contains("qualified candidates for `root`"), "{err}");
    assert!(err.contains("org-x--aaa--root"), "{err}");
}

// ----- B-006 rider (W-B): per-node qualify for cross-origin closures --------

/// Write a `normal` fixture whose host contract `#use`s a node in a DIFFERENT
/// package — the case per-node qualification exists for. The host package
/// `com.example.host/host` references the dep package's `##THE-RULE` via a
/// short link; without per-node qualify the dep's labels would be
/// mis-attributed to the host's origin. Each package lives in its own
/// `vibedeps/<slot>/1.0.0/spec/…` slot, matched by the `-<name>` suffix the
/// resolver keys on (name `host` → slot `demo-host`; name `dep` → slot
/// `demo-dep`). Returns the host contract's workspace-relative path.
#[cfg(test)]
fn write_cross_pkg_fixture(ws: &Path) -> String {
    let write = |slot: &str, rel: &str, body: &str| {
        let p = ws.join(format!("vibedeps/{slot}/1.0.0/spec/{rel}"));
        fs::create_dir_all(p.parent().unwrap()).unwrap();
        fs::write(&p, body).unwrap();
    };
    write(
        "demo-host",
        "contract/host.md",
        "# Host {#root}\n\
         #use spec://com.example.dep/dep/contract/dep#root\n\
         See (#THE-RULE) from the dep.\n\
         HOST_BODY\n",
    );
    write(
        "demo-dep",
        "contract/dep.md",
        "# Dep {#root}\n##THE-RULE the rule\nDEP_BODY\n",
    );
    "vibedeps/demo-host/1.0.0/spec/contract/host.md".to_string()
}

#[test]
fn render_static_qualifies_a_normal_closure_per_node_across_packages() {
    // Q7 (E4-W2-NODE-QUALIFY): a normal closure spanning two packages is
    // qualified PER-NODE — the dep's labels carry the dep's origin, never the
    // host entry's — and the cross-node short link resolves to the dep's
    // qualified heir. `qualify_contribution` is NOT run over the compiled body
    // (no double prefix); the per-node renames land in the tombstone.
    let ws = TempDir::new().unwrap();
    let contract = write_cross_pkg_fixture(ws.path());
    let b = boot(vec![entry_normal(&contract, "com.example.host/host")]);
    let text = render_static(&b, ws.path()).unwrap().unwrap();

    // (1) The dep's labels are qualified under the DEP's origin — per-node, not
    // the host entry's. Whole-body qualify under the entry's origin could never
    // produce this.
    assert!(text.contains("{#com-example-dep--dep--root}"), "{text}");
    assert!(text.contains("##com-example-dep--dep--THE-RULE"), "{text}");
    // The host's own label is under the host's origin.
    assert!(text.contains("{#com-example-host--host--root}"), "{text}");
    // (2) The cross-node short link resolved to the dep's qualified heir.
    assert!(text.contains("(#com-example-dep--dep--THE-RULE)"), "{text}");
    // (3) No double prefix: the dep's label was neither mis-attributed to the
    // host origin (whole-body qualify) nor double-prefixed (whole-body over the
    // per-node compile).
    assert!(
        !text.contains("##com-example-host--host--THE-RULE"),
        "dep's label mis-attributed to host origin: {text}"
    );
    assert!(
        !text.contains("com-example-host--host--com-example-dep"),
        "double prefix from re-qualifying: {text}"
    );
    // (4) The per-node renames land in the tombstone — both origins present.
    assert!(
        text.contains("THE-RULE → com-example-dep--dep--THE-RULE (com.example.dep/dep)"),
        "{text}"
    );
    assert!(
        text.contains("com-example-host--host--root (com.example.host/host)"),
        "{text}"
    );
    // (5) Zero duplicate anchors over the cross-package splice — the gate.
    assert!(
        DocTree::parse(&text).duplicate_anchors().is_empty(),
        "{text}"
    );
}
