//! Artifact-wide characterization at the workspace/compiler seam. R3 may
//! replace the monolithic one-seed internals, but the final lane still has one
//! shared frame around contributions in effective-boot declaration order.

use std::fs;

use specmark::verifies;
use tempfile::TempDir;
use vibe_core::manifest::{LinkType, SpecFormat};

use super::tests::{boot, coord, entry, entry_normal};
use super::*;

const ALPHA_BODY: &str = "# Alpha {#root}\n\n##A-FACT alpha normal.\n";
const SIMPLE_BODY: &str = "# Simple {#root}\n\n##S-FACT simple middle.\n";
const OMEGA_BODY: &str = "# Omega {#root}\n\n##O-FACT omega normal.\n";

fn write_entry(ws: &Path, slot: &str, body: &str) -> String {
    let slot = crate::layout_paths::vibedeps(format!("{slot}/1.0.0"));
    let rel = crate::layout_paths::slot_specs(slot, "boot/entry.md");
    let path = ws.join(&rel);
    fs::create_dir_all(path.parent().unwrap()).unwrap();
    fs::write(path, body).unwrap();
    rel
}

fn fixture() -> (TempDir, EffectiveBoot, String, String, String) {
    let ws = TempDir::new().unwrap();
    let alpha = write_entry(ws.path(), "org.demo.alpha", ALPHA_BODY);
    let simple = write_entry(ws.path(), "org.demo.simple", SIMPLE_BODY);
    let omega = write_entry(ws.path(), "org.demo.omega", OMEGA_BODY);
    let effective = boot(vec![
        entry_normal(&alpha, "org.demo/alpha"),
        entry(&simple, LinkType::Static, "org.demo/simple"),
        entry_normal(&omega, "org.demo/omega"),
    ]);
    (ws, effective, alpha, simple, omega)
}

#[test]
#[verifies("spec://org.vibevm.core/vibevm/common/PROP-054#IR-REFACTOR")]
#[verifies("spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-009#artifacts")]
fn final_static_assembly_keeps_one_frame_and_normal_simple_normal_order_in_markdown_and_xml() {
    let (ws, effective, alpha, simple, omega) = fixture();
    let markdown =
        render_static_with_spec_format(&effective, ws.path(), &coord(), SpecFormat::Markdown)
            .unwrap()
            .unwrap();
    let expected_markdown = format!(
        concat!(
            "<!-- vibevm/vibespecs/boot/STATIC.md — generated by vibe, do not edit. -->\n",
            "<!-- The static boot lane (PROP-009 §2.3): the highest-priority -->\n",
            "<!-- contributions, compiled anchor-qualified. Read this first, in full. -->\n\n",
            "<!-- RESOLUTION RULES — read these five lines before anything else:\n",
            "  1. Labels in this file are qualified: <origin-slug>--<original>. The origin\n",
            "     is named by the provenance comment above each block; the original short\n",
            "     label is the tail after the last `--`.\n",
            "  2. A short label you cannot find here → check the RENAMED ANCHORS table\n",
            "     below for its qualified heirs; never guess among look-alikes.\n",
            "  3. Full spec:// addresses resolve against package SOURCES under vibevm/vibedeps/,\n",
            "     never against this generated file. This file is a cache, not a target.\n",
            "  4. `#use spec://… as X` binds a file-local alias; `@!X` is a mandatory read\n",
            "     of X's target (same rules as @spec://…). In this compiled file every @!X\n",
            "     is already rewritten to its full address.\n",
            "  5. An ambiguous or unresolvable short reference is an ERROR to surface with\n",
            "     candidates — never silently pick one.\n",
            "-->\n\n",
            "<!-- RENAMED ANCHORS (short → qualified heirs):\n",
            "  A-FACT → org-demo--alpha--A-FACT (org.demo/alpha)\n",
            "  O-FACT → org-demo--omega--O-FACT (org.demo/omega)\n",
            "  S-FACT → org-demo--simple--S-FACT (org.demo/simple)\n",
            "  root → org-demo--alpha--root (org.demo/alpha), org-demo--omega--root (org.demo/omega), org-demo--simple--root (org.demo/simple)\n",
            "-->\n\n",
            "<!-- vibe:static org.demo/alpha — {alpha} -->\n\n",
            "<!-- vibe:begin spec://org.demo/alpha/boot/entry -->\n",
            "# Alpha {{#org-demo--alpha--root}}\n\n",
            "##org-demo--alpha--A-FACT alpha normal.\n",
            "<!-- vibe:end spec://org.demo/alpha/boot/entry -->\n\n",
            "<!-- vibe:static org.demo/simple — {simple} -->\n\n",
            "# Simple {{#org-demo--simple--root}}\n\n",
            "##org-demo--simple--S-FACT simple middle.\n\n",
            "<!-- vibe:static org.demo/omega — {omega} -->\n\n",
            "<!-- vibe:begin spec://org.demo/omega/boot/entry -->\n",
            "# Omega {{#org-demo--omega--root}}\n\n",
            "##org-demo--omega--O-FACT omega normal.\n",
            "<!-- vibe:end spec://org.demo/omega/boot/entry -->\n\n",
        ),
        alpha = alpha,
        simple = simple,
        omega = omega,
    );
    assert_eq!(markdown, expected_markdown);

    let xml = render_static_with_spec_format(&effective, ws.path(), &coord(), SpecFormat::Xml)
        .unwrap()
        .unwrap();
    assert!(
        xml.starts_with(
            "<!-- vibevm/vibespecs/boot/STATIC.xml — generated by vibe, do not edit. -->\n"
        ),
        "{xml}"
    );
    assert_eq!(xml.matches("RESOLUTION RULES —").count(), 1, "{xml}");
    assert_eq!(
        xml.matches("RENAMED ANCHORS (short → qualified heirs):")
            .count(),
        1,
        "{xml}"
    );
    assert_eq!(xml.matches("<!-- vibe:static ").count(), 3, "{xml}");
    assert_eq!(xml.matches("<spec ").count(), 3, "{xml}");
    assert!(!xml.contains("<!-- vibe:begin "), "{xml}");
    assert!(!xml.contains("<!-- vibe:end "), "{xml}");
    // Current byte oracle: the XML pivot strips `vibe:begin`, but its filter
    // still names the historical `vibe:close` spelling, so the two normal
    // entries carry their `vibe:end` marker as escaped payload. R3 is a
    // byte-identity refactor; changing this belongs to a separate fix.
    assert_eq!(xml.matches("&lt;!-- vibe:end ").count(), 2, "{xml}");

    let alpha_payload = vibe_specdoc::to_xml(
        &vibe_specdoc::from_markdown(concat!(
            "# Alpha {#org-demo--alpha--root}\n\n",
            "##org-demo--alpha--A-FACT alpha normal.\n",
            "<!-- vibe:end spec://org.demo/alpha/boot/entry -->",
        ))
        .unwrap(),
    );
    let simple_payload = vibe_specdoc::to_xml(
        &vibe_specdoc::from_markdown(
            "# Simple {#org-demo--simple--root}\n\n##org-demo--simple--S-FACT simple middle.\n",
        )
        .unwrap(),
    );
    let omega_payload = vibe_specdoc::to_xml(
        &vibe_specdoc::from_markdown(concat!(
            "# Omega {#org-demo--omega--root}\n\n",
            "##org-demo--omega--O-FACT omega normal.\n",
            "<!-- vibe:end spec://org.demo/omega/boot/entry -->",
        ))
        .unwrap(),
    );
    for payload in [&alpha_payload, &simple_payload, &omega_payload] {
        assert_eq!(
            xml.matches(payload).count(),
            1,
            "payload:\n{payload}\nlane:\n{xml}"
        );
    }

    let alpha_marker = format!("<!-- vibe:static org.demo/alpha — {alpha} -->");
    let simple_marker = format!("<!-- vibe:static org.demo/simple — {simple} -->");
    let omega_marker = format!("<!-- vibe:static org.demo/omega — {omega} -->");
    let positions = [
        xml.find(&alpha_marker).unwrap(),
        xml.find(&alpha_payload).unwrap(),
        xml.find(&simple_marker).unwrap(),
        xml.find(&simple_payload).unwrap(),
        xml.find(&omega_marker).unwrap(),
        xml.find(&omega_payload).unwrap(),
    ];
    assert!(
        positions.windows(2).all(|pair| pair[0] < pair[1]),
        "declaration/payload order moved: {positions:?}\n{xml}"
    );
    assert!(
        xml.contains(
            "root → org-demo--alpha--root (org.demo/alpha), org-demo--omega--root (org.demo/omega), org-demo--simple--root (org.demo/simple)"
        ),
        "{xml}"
    );
}
