// A swept test matrix (R-060): the case count is 2^n, generated by a
// bit-mask loop rather than declared as data — the violation this fixture
// exhibits alongside its other findings. The count grows exponentially
// with the axes, hiding a regression in the exponent.
for (let mask = 0; mask < 1 << 3; mask++) {
  // exercised once per generated case
}
