schema = 1
source_hash = "sha256:afb8e42cc47cfecf798955264bdd8cf50d4e9f5c31b8782f816cabbe039e722a"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:f8da7df259f3000c44477ca8a9b7bc37191fffd0a980892a8be15b8c163d114a"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
