schema = 1
source_hash = "sha256:73a11945f4baea9418f801e12b1bf87a466db2a138f9975fbfa28c3f8c24a33b"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:b514bae18c9d3df3d1c1810e3074a1b2ab7685a481b3bab60ebfe5cd7d9766e2"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
