//! Unit tests for the arm-boxing pass — one per behaviour the pass owes
//! its callers: the rewrite itself, every pass-through (vocabulary enums,
//! structs, untagged enums), the idempotency that keeps `check-codegen`
//! stable, and the loud refusals that keep a moved generator pin from
//! being absorbed silently. The samples quote the pinned emission shape
//! of jtd-codegen 0.4.1 verbatim — the pass exists to be exact about
//! that shape, so the tests must be exact about it too.

use super::box_union_arms;
use anyhow::Result;

/// The union of the real `repomd` schema — the §-3 shape this pass was
/// built against, quoted verbatim from the generated file.
const TAGGED_UNION: &str = r#"#[derive(Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum RepomdFileEntry {
    #[serde(rename = "directory")]
    Directory(RepomdFileEntryDirectory),

    #[serde(rename = "file")]
    File(RepomdFileEntryFile),
}
"#;

/// Both arms of a recognised union take their `Box` — attributes,
/// layout, line endings and everything else stay byte for byte. This is
/// the test that fails without the transformation: it asserts the exact
/// output, not a substring, so a partial or creative rewrite cannot
/// sneak through.
#[test]
fn boxes_every_arm_of_a_discriminator_union() -> Result<()> {
    let out = box_union_arms(TAGGED_UNION, "repomd/mod.rs")?;
    assert_eq!(
        out,
        r#"#[derive(Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum RepomdFileEntry {
    #[serde(rename = "directory")]
    Directory(Box<RepomdFileEntryDirectory>),

    #[serde(rename = "file")]
    File(Box<RepomdFileEntryFile>),
}
"#
    );
    Ok(())
}

/// A whole generated file in the shape of the real one — header, `use`,
/// structs, a vocabulary enum, the union, a trailing struct — changes in
/// exactly one place: the union's arms. Everything around the union is
/// the generator's layout, and the pass must not so much as breathe on
/// it, or `check-codegen` would report drift that isn't ours. The doc
/// comment QUOTING the tag attribute (like the real file's does) must
/// not open a union.
#[test]
fn a_whole_generated_file_changes_only_in_the_union() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Tags are lowercase, per the writer's
/// `#[serde(tag = "kind", rename_all = "lowercase")]`.
#[derive(Serialize, Deserialize)]
pub struct Repomd {
    #[serde(rename = "files")]
    pub files: HashMap<String, RepomdFileEntry>,
}

#[derive(Serialize, Deserialize)]
pub enum NamingConvention {
    #[serde(rename = "fqdn")]
    Fqdn,

    #[serde(rename = "kind-name")]
    KindName,
}

#[derive(Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum RepomdFileEntry {
    #[serde(rename = "directory")]
    Directory(RepomdFileEntryDirectory),

    #[serde(rename = "file")]
    File(RepomdFileEntryFile),
}

#[derive(Serialize, Deserialize)]
pub struct RepomdFileEntryDirectory {
    #[serde(rename = "entries")]
    pub entries: u32,
}
"#;
    let out = box_union_arms(src, "repomd/mod.rs")?;
    let expected = src
        .replace(
            "Directory(RepomdFileEntryDirectory),",
            "Directory(Box<RepomdFileEntryDirectory>),",
        )
        .replace(
            "File(RepomdFileEntryFile),",
            "File(Box<RepomdFileEntryFile>),",
        );
    assert_eq!(out, expected);
    Ok(())
}

/// Vocabulary enums — all variants unit, no payload to box — pass through
/// untouched. Boxing is for union arms; a dictionary is not a union.
#[test]
fn vocabulary_enums_pass_through() -> Result<()> {
    let src = r#"#[derive(Serialize, Deserialize)]
pub enum NamingConvention {
    #[serde(rename = "fqdn")]
    Fqdn,

    #[serde(rename = "kind-name")]
    KindName,
}
"#;
    assert_eq!(box_union_arms(src, "repomd/mod.rs")?, src);
    Ok(())
}

/// Structs pass through untouched — including a field whose type already
/// carries a `Box`, which is none of this pass's business: the pass
/// boxes union ARMS, not types wherever they appear.
#[test]
fn structs_pass_through() -> Result<()> {
    let src = r#"#[derive(Serialize, Deserialize)]
pub struct RepomdFileEntryFile {
    #[serde(rename = "size")]
    pub size: u32,

    #[serde(rename = "cache")]
    pub cache: Box<RepomdFileEntryDirectory>,
}
"#;
    assert_eq!(box_union_arms(src, "repomd/mod.rs")?, src);
    Ok(())
}

/// A tuple enum WITHOUT `#[serde(tag = …)]` passes through untouched.
/// The pass's discriminator is the tag attribute — the marker of a JTD
/// discriminator union — never tuple-ness: an untagged tuple enum is not
/// the wire union this pass exists for, and boxing it would change
/// someone else's representation on a guess.
#[test]
fn untagged_tuple_enums_pass_through() -> Result<()> {
    let src = r#"#[derive(Serialize, Deserialize)]
pub enum NotAWireUnion {
    #[serde(rename = "a")]
    Alpha(Alpha),

    #[serde(rename = "b")]
    Beta(Beta),
}
"#;
    assert_eq!(box_union_arms(src, "elsewhere/mod.rs")?, src);
    Ok(())
}

/// An arm already carrying `Box<…>` is not boxed again — nesting boxes
/// would change the representation for no reason and break the
/// idempotency contract the next test pins.
#[test]
fn an_already_boxed_arm_is_not_boxed_again() -> Result<()> {
    let src = r#"#[serde(tag = "kind")]
pub enum Mixed {
    #[serde(rename = "directory")]
    Directory(Box<RepomdFileEntryDirectory>),

    #[serde(rename = "file")]
    File(RepomdFileEntryFile),
}
"#;
    let out = box_union_arms(src, "repomd/mod.rs")?;
    assert_eq!(
        out,
        r#"#[serde(tag = "kind")]
pub enum Mixed {
    #[serde(rename = "directory")]
    Directory(Box<RepomdFileEntryDirectory>),

    #[serde(rename = "file")]
    File(Box<RepomdFileEntryFile>),
}
"#
    );
    Ok(())
}

/// The second run over the pass's own output is the identity — otherwise
/// `check-codegen` would flag a file that a `codegen` run just wrote, and
/// the gate would blink on every panel lap.
#[test]
fn the_pass_is_idempotent() -> Result<()> {
    let once = box_union_arms(TAGGED_UNION, "repomd/mod.rs")?;
    let twice = box_union_arms(&once, "repomd/mod.rs")?;
    assert_eq!(once, twice);
    Ok(())
}

/// An unfamiliar line inside a recognised union refuses loudly: the
/// message names the file, the line, the offending text verbatim, and
/// the recipe. The generator's emission shape is pinned; a line this
/// pass does not know means the pin moved, and the one unacceptable
/// answer is a silent partial rewrite.
#[test]
fn an_unfamiliar_line_inside_a_union_refuses() {
    let src = r#"#[derive(Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum Odd {
    #[serde(rename = "a")]
    A(Alpha),

    pub entries: u32,
}
"#;
    let err = box_union_arms(src, "odd/mod.rs")
        .expect_err("a field line inside an enum is not the pinned shape");
    let msg = err.to_string();
    assert!(msg.contains("odd/mod.rs:7"), "names file and line: {msg}");
    assert!(msg.contains("pub entries: u32"), "quotes the line: {msg}");
    assert!(
        msg.contains("postproc.rs") && msg.contains("cargo xtask codegen"),
        "says what to do: {msg}"
    );
}

/// A `#[serde(tag = …)]` attribute that opens no enum refuses too: the
/// recognition contract is attribute-then-`pub enum … {`, and anything
/// else is a moved pin, not a union to guess at.
#[test]
fn a_tag_attribute_that_opens_no_enum_refuses() {
    let src = r#"#[derive(Serialize, Deserialize)]
#[serde(tag = "kind")]
pub struct NotAnEnum {
    pub entries: u32,
}
"#;
    let err = box_union_arms(src, "odd/mod.rs")
        .expect_err("a tag attribute over a struct is not the pinned shape");
    let msg = err.to_string();
    assert!(
        msg.contains("odd/mod.rs:3"),
        "names the line that broke the contract: {msg}"
    );
    assert!(
        msg.contains("cargo xtask codegen"),
        "says what to do: {msg}"
    );
}
