schema = 1
source_hash = "sha256:6f454486ce7f3edcc208231b2b88fea61be6b65938ada1914a98ddfcb957960d"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:66a1828063574dece74f3f9ec6382e53ca190b0370affa6375a4db37aa5b2157"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/30-flow-atomic-commits.xml"
output = "vibevm/vibespecs/boot/30-flow-atomic-commits.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/atomic-commits/ATOMIC-COMMITS-PROTOCOL.xml"
output = "vibevm/vibespecs/flows/atomic-commits/ATOMIC-COMMITS-PROTOCOL.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/atomic-commits/splitting-large-changes.xml"
output = "vibevm/vibespecs/flows/atomic-commits/splitting-large-changes.xml"
disposition = "copied"
