//! Unit tests for the domain-types pass — one per behaviour the pass
//! owes its callers (the acceptance's A4 panel, plus the two shapes the
//! real tree contributes: a root annotation that renames the stem-named
//! struct, and the timestamp fragment whose substitution orphans a
//! whole `chrono` import). The samples quote the pinned emission shape
//! of jtd-codegen as the EARLIER passes receive it — every field still
//! carrying its `#[serde(rename = …)]`, the imports as the generator
//! wrote them — because these tests drive the production driver
//! `rewrite_generated` itself over scratch files: a green here is a
//! green of the whole pipeline in its recorded order, and the red
//! proof is honest by construction (before the pass is registered in
//! `postproc`, the same tests fail on the untouched file — that run is
//! quoted in the step's report). The scratch `resolved` document rides
//! on a real registered schema's claim, because the strictness pass
//! refuses a schema no `formats/REGISTRY.toml` record names.

use anyhow::Result;
use serde_json::{Value, json};

use crate::codegen::postproc::rewrite_generated;
use crate::codegen::strictness::Strictness;
use crate::repo_root;

/// Drive the production pipeline over a one-off emission and resolved
/// document. The resolved file's stem names the root type the way
/// jtd-codegen would: `holder.jtd.json` → `pub struct Holder`.
///
/// `pub(crate)` so the variant-naming suite beside it drives the same
/// harness rather than a copy: two harnesses would drift, and a test
/// that runs a different pipeline than production is exactly the
/// fixture that cannot fail.
pub(crate) fn through_pipeline(src: &str, doc: Value, root_stem: &str) -> Result<String> {
    let dir = tempfile::tempdir()?;
    let file = dir.path().join("mod.rs");
    std::fs::write(&file, src)?;
    let resolved = dir.path().join(format!("{root_stem}.jtd.json"));
    std::fs::write(&resolved, serde_json::to_string(&doc)?)?;
    let root = repo_root()?;
    let strictness = Strictness::load(&root)?;
    let schema = root
        .join("schemas")
        .join("index")
        .join("e1")
        .join("by_purl.jtd.json");
    rewrite_generated(&file, &resolved, &schema, &strictness)?;
    let out = std::fs::read_to_string(&file)?;
    // The trait floor is a LATER pass's subject, and `derive_floor`'s own
    // suite is what asserts it lands. Normalise it back to the emission's
    // derive form here so the expectations below speak about the pass
    // this file is named for. The reason is structural rather than
    // convenience: without it, every future pass that touches every type
    // would force an edit in every other pass's expectations, and that
    // coupling grows with the square of the pass count.
    Ok(out.replace(
        "#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]",
        "#[derive(Serialize, Deserialize)]",
    ))
}

/// The emission of a one-alias schema, snake-case pass input form: the
/// alias with its doc comment, and one struct leaning on the alias.
const GROUP_EMISSION: &str = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

/// A group qualifier.
pub type Group = String;

#[derive(Serialize, Deserialize)]
pub struct Widget {
    #[serde(rename = "group")]
    pub group: Group,
}
"#;

/// A4.1 — a scalar fragment's annotation is the alias's new right
/// side; the alias's own name, and every field that leans on it, stay
/// exactly where the generator put them.
#[test]
fn a_scalar_annotation_replaces_the_right_side_and_keeps_the_name() -> Result<()> {
    let doc = json!({
        "definitions": {
            "group": {
                "type": "string",
                "metadata": { "x-rust-type": "vibe_core::Group" }
            },
            "widget": {
                "properties": { "group": { "ref": "group" } },
                "metadata": { "x-rust-type": "Widget" }
            }
        },
        "properties": { "widget": { "ref": "widget" } }
    });
    assert_eq!(
        through_pipeline(GROUP_EMISSION, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

/// A group qualifier.
pub type Group = vibe_core::Group;

#[derive(Serialize, Deserialize)]
pub struct Widget {
    pub group: Group,
}
"#
    );
    Ok(())
}

/// A4.2 — a structure whose annotation names it differently is renamed,
/// the declaration and every whole-token usage together (the field
/// typing `Widget` is the usage the test owes the arm: a rename that
/// stopped at the declaration would leave the file uncompilable).
#[test]
fn a_struct_with_a_mismatched_name_is_renamed_with_every_token() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Holder {
    #[serde(rename = "widget")]
    pub widget: Widget,
}

#[derive(Serialize, Deserialize)]
pub struct Widget {
    #[serde(rename = "group")]
    pub group: String,
}
"#;
    let doc = json!({
        "definitions": {
            "widget": {
                "properties": { "group": { "type": "string" } },
                "metadata": { "x-rust-type": "Gadget" }
            }
        },
        "properties": { "widget": { "ref": "widget" } }
    });
    assert_eq!(
        through_pipeline(src, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Holder {
    pub widget: Gadget,
}

#[derive(Serialize, Deserialize)]
pub struct Gadget {
    pub group: String,
}
"#
    );
    Ok(())
}

/// A4.3 — an annotation that already names the type is a no-op: the
/// output is byte for byte the exact text, and byte for byte what the
/// same pipeline produces with no annotation on that definition at
/// all.
#[test]
fn a_matching_name_leaves_the_file_byte_for_byte() -> Result<()> {
    let annotated = json!({
        "definitions": {
            "group": { "type": "string" },
            "widget": {
                "properties": { "group": { "ref": "group" } },
                "metadata": { "x-rust-type": "Widget" }
            }
        },
        "properties": { "widget": { "ref": "widget" } }
    });
    let bare = json!({
        "definitions": {
            "group": { "type": "string" },
            "widget": { "properties": { "group": { "ref": "group" } } }
        },
        "properties": { "widget": { "ref": "widget" } }
    });
    let expected = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

/// A group qualifier.
pub type Group = String;

#[derive(Serialize, Deserialize)]
pub struct Widget {
    pub group: Group,
}
"#;
    assert_eq!(
        through_pipeline(GROUP_EMISSION, annotated, "holder")?,
        expected
    );
    assert_eq!(through_pipeline(GROUP_EMISSION, bare, "holder")?, expected);
    Ok(())
}

/// A4.4 — an annotation whose declaration is not in the file refuses,
/// naming the authored schema and the definition: the emission shape
/// the pass is pinned to has moved, and a silent skip would hide that
/// behind a green run.
#[test]
fn an_annotation_without_a_declaration_refuses() -> Result<()> {
    let doc = json!({
        "definitions": {
            "ghost": {
                "type": "string",
                "metadata": { "x-rust-type": "crate::Ghost" }
            }
        }
    });
    let err = through_pipeline(GROUP_EMISSION, doc, "holder")
        .expect_err("no `pub type Ghost` stands in the file");
    let msg = err.to_string();
    assert!(
        msg.contains("by_purl.jtd.json"),
        "names the authored schema: {msg}"
    );
    assert!(msg.contains("ghost"), "names the definition: {msg}");
    assert!(
        msg.contains("pub type Ghost"),
        "names the declaration it looked for: {msg}"
    );
    assert!(
        msg.contains("cargo xtask codegen"),
        "gives the recipe: {msg}"
    );
    Ok(())
}

/// A4.5 — a definition without the annotation is not the pass's
/// business: `Entry` keeps its right side byte for byte while the
/// annotated sibling changes in the same run, exactly the way the real
/// `entry.jtd.json` root lives without one.
#[test]
fn a_definition_without_the_annotation_stays_untouched() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

pub type Entry = VersionEntry;

/// A group qualifier.
pub type Group = String;

#[derive(Serialize, Deserialize)]
pub struct VersionEntry {
    #[serde(rename = "group")]
    pub group: Group,
}
"#;
    let doc = json!({
        "definitions": {
            "entry": { "ref": "version_entry" },
            "group": {
                "type": "string",
                "metadata": { "x-rust-type": "vibe_core::Group" }
            },
            "version_entry": { "properties": { "group": { "ref": "group" } } }
        }
    });
    assert_eq!(
        through_pipeline(src, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

pub type Entry = VersionEntry;

/// A group qualifier.
pub type Group = vibe_core::Group;

#[derive(Serialize, Deserialize)]
pub struct VersionEntry {
    pub group: Group,
}
"#
    );
    Ok(())
}

/// A4.6 — a substitution that orphans BOTH items of a braced import
/// takes the whole line, newline included.
#[test]
fn a_substitution_orphaning_both_items_removes_the_line() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use crate::{Alpha, Beta};

pub type Pair = Alpha<Beta>;
"#;
    let doc = json!({
        "definitions": {
            "pair": {
                "type": "string",
                "metadata": { "x-rust-type": "crate::Domain" }
            }
        }
    });
    assert_eq!(
        through_pipeline(src, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

pub type Pair = crate::Domain;
"#
    );
    Ok(())
}

/// A4.7 — a substitution that orphans ONE item of two removes only it:
/// the rule is "take what the substitution orphaned", not "clean the
/// imports up", and `Beta` — still typed in a field — stands.
#[test]
fn a_substitution_orphaning_one_item_keeps_the_other() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use crate::{Alpha, Beta};

pub type Pair = Alpha;

#[derive(Serialize, Deserialize)]
pub struct Holder {
    #[serde(rename = "beta")]
    pub beta: Beta,
}
"#;
    let doc = json!({
        "definitions": {
            "pair": {
                "type": "string",
                "metadata": { "x-rust-type": "crate::Domain" }
            }
        },
        "properties": { "beta": { "type": "string" } }
    });
    assert_eq!(
        through_pipeline(src, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use crate::Beta;

pub type Pair = crate::Domain;

#[derive(Serialize, Deserialize)]
pub struct Holder {
    pub beta: Beta,
}
"#
    );
    Ok(())
}

/// A4.8 — a `use` line in any other shape refuses, naming the file and
/// the line: the emission's import grammar is pinned by the
/// generator's version, and its drift must be heard, not absorbed.
#[test]
fn an_unfamiliar_use_line_refuses_naming_file_and_line() -> Result<()> {
    let src = "// Code generated by jtd-codegen for Rust v0.2.1\n\nuse std::collections::*;\n\npub type Group = String;\n";
    let doc = json!({
        "definitions": {
            "group": {
                "type": "string",
                "metadata": { "x-rust-type": "vibe_core::Group" }
            }
        }
    });
    let err = through_pipeline(src, doc, "holder")
        .expect_err("a glob import is not a shape the pass knows");
    let msg = err.to_string();
    assert!(msg.contains("mod.rs:3"), "names the file and line: {msg}");
    assert!(
        msg.contains("use std::collections::*;"),
        "quotes the line: {msg}"
    );
    assert!(
        msg.contains("cargo xtask codegen"),
        "gives the recipe: {msg}"
    );
    Ok(())
}

/// A1's refusal — an annotation on a form the pass cannot classify
/// from both sides names the schema, the definition and the form, and
/// rules nothing.
#[test]
fn an_annotation_on_an_unclassifiable_form_refuses() -> Result<()> {
    let doc = json!({
        "definitions": {
            "tags": {
                "elements": { "type": "string" },
                "metadata": { "x-rust-type": "Vec<String>" }
            }
        }
    });
    let err = through_pipeline(GROUP_EMISSION, doc, "holder")
        .expect_err("an array form has no arm to rule through");
    let msg = err.to_string();
    assert!(
        msg.contains("by_purl.jtd.json"),
        "names the authored schema: {msg}"
    );
    assert!(msg.contains("tags"), "names the definition: {msg}");
    assert!(
        msg.contains("`elements` (array) form"),
        "names the form: {msg}"
    );
    Ok(())
}

/// The journal shape of the name arm: the ROOT carries the annotation,
/// the generator named the root after the schema's stem, and the one
/// declaration token is the whole rename — the real `journal.jtd.json`
/// root renames `Journal` → `JournalRecord` exactly like this.
#[test]
fn the_root_annotation_renames_the_stem_named_struct() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Holder {
    #[serde(rename = "actor")]
    pub actor: String,
}
"#;
    let doc = json!({
        "properties": { "actor": { "type": "string" } },
        "metadata": { "x-rust-type": "Registry" }
    });
    assert_eq!(
        through_pipeline(src, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct Registry {
    pub actor: String,
}
"#
    );
    Ok(())
}

/// The timestamp shape of the real change: the generator emits
/// `DateTime<FixedOffset>` with a `chrono` import, the annotation
/// (P23: self-sufficient) replaces the right side, and BOTH items
/// orphan — even though the doc comment above the alias still says
/// `chrono::DateTime<Utc>`, a `::`-qualified path segment names the
/// path, never the imported name. The whole `use` line goes.
#[test]
fn the_timestamp_substitution_takes_the_chrono_import_with_it() -> Result<()> {
    let src = r#"// Code generated by jtd-codegen for Rust v0.2.1

use chrono::{DateTime, FixedOffset};
use serde::{Deserialize, Serialize};

/// RFC 3339 timestamp — `chrono::DateTime<Utc>` in code.
pub type Timestamp = DateTime<FixedOffset>;

#[derive(Serialize, Deserialize)]
pub struct Holder {
    #[serde(rename = "at")]
    pub at: Timestamp,
}
"#;
    let doc = json!({
        "definitions": {
            "timestamp": {
                "type": "timestamp",
                "metadata": { "x-rust-type": "chrono::DateTime<chrono::Utc>" }
            }
        },
        "properties": { "at": { "ref": "timestamp" } }
    });
    assert_eq!(
        through_pipeline(src, doc, "holder")?,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

/// RFC 3339 timestamp — `chrono::DateTime<Utc>` in code.
pub type Timestamp = chrono::DateTime<chrono::Utc>;

#[derive(Serialize, Deserialize)]
pub struct Holder {
    pub at: Timestamp,
}
"#
    );
    Ok(())
}
