schema = 1
source_hash = "sha256:fd3ddc05880b6af0374e42d18cb9df7f2f35ab2410d61447e0330c51be052d9f"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:ce94731d84dfebd31d18aa5409aa0430c1adbd2d39135412c92d77ab466c68c7"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/11-flow-wal-specspaces.xml"
output = "vibevm/vibespecs/boot/11-flow-wal-specspaces.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
output = "vibevm/vibespecs/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
disposition = "copied"
