schema = 1
source_hash = "sha256:545f1cb2aa9fe627005633c60350b91cdf25a7b9d6e08d82fdeedce24900838c"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:1b0d7e213b13ffc3bbd8c399e589af400070d5379ae63c37562affd80407f2bc"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/11-flow-wal-specspaces.xml"
output = "vibevm/vibespecs/boot/11-flow-wal-specspaces.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
output = "vibevm/vibespecs/flows/wal-specspaces/SPECSPACES-PROTOCOL.xml"
disposition = "copied"
