schema = 1
source_hash = "sha256:1aac79a76caf8f62f0027d90e0791a88b6c0e011c254145f7b4f459dbad3c306"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:d39620e0571e04b71dcc0db2d5513f223c8697457ddf58293ede4664f4c0f00a"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
