// A swept test matrix (R-060): the case count is 2^n, generated by a
// bit-mask loop rather than declared as data — the violation this fixture
// exhibits alongside its other findings. The count grows exponentially
// with the axes, hiding a regression in the exponent.
for (let mask = 0; mask < 1 << 3; mask++) {
  // exercised once per generated case
}

// The nested-loops half (R-060): three C-style for-loops nested — a
// Cartesian product of GENERATED axes (each bound is a computed `0..n`
// range, not a declared collection), so the case count is a product no
// reader multiplies out.
for (let i = 0; i < 2; i++) {
  for (let j = 0; j < 2; j++) {
    for (let k = 0; k < 2; k++) {
      // one generated combination
    }
  }
}
