//! `discipline-rust ledger render` — the human views over the two
//! BROWNFIELD §3 registries: `discipline/DEBT.md` from `debt.json`
//! (whose own header has promised "Human view: DEBT.md, generated from
//! this file" since the terraform) and `discipline/INTENT.md` from
//! `intent.json`. Deterministic renders (stable grouping + ordering,
//! a generated-by banner naming the regen command); `--check`
//! regenerates and byte-compares, exiting non-zero on drift — the
//! sweep's staleness item, mechanised.
//!
//! Tolerant reader: entries are JSON objects with a conventional but
//! evolving field set, so the renderer takes what is present and never
//! fails on a missing optional — a registry the engines can parse must
//! always render.

use std::path::Path;

use anyhow::{Context, Result, bail};
use serde_json::Value;

fn field<'a>(entry: &'a Value, key: &str) -> Option<&'a str> {
    entry.get(key).and_then(Value::as_str)
}

fn load_entries(root: &Path, rel: &str) -> Result<Vec<Value>> {
    let path = root.join(rel);
    let text =
        std::fs::read_to_string(&path).with_context(|| format!("reading {}", path.display()))?;
    let file: Value = serde_json::from_str(&text).with_context(|| format!("parsing {rel}"))?;
    Ok(file
        .get("entries")
        .and_then(Value::as_array)
        .cloned()
        .unwrap_or_default())
}

fn banner(view: &str, source: &str) -> String {
    format!(
        "<!-- GENERATED by `discipline-rust ledger render` from {source} — do not edit;\n\
         \x20    edit the registry and re-render. `ledger render --check` gates drift. -->\n\
         # {view}\n\n"
    )
}

fn bullet_line(entry: &Value, headline_key: &str) -> String {
    let id = field(entry, "id").unwrap_or("(no id)");
    let headline = field(entry, headline_key)
        .or_else(|| field(entry, "title"))
        .or_else(|| field(entry, "detail"))
        .unwrap_or("(untitled)");
    let mut line = format!("- **{id}**");
    if let Some(kind) = field(entry, "kind") {
        line.push_str(&format!(" `{kind}`"));
    }
    if let Some(severity) = field(entry, "severity") {
        line.push_str(&format!(" [{severity}]"));
    }
    line.push_str(&format!(" — {}", headline.trim()));
    if let Some(filed) = field(entry, "filed_as") {
        line.push_str(&format!(" _(filed as {filed})_"));
    }
    if let Some(resolution) = field(entry, "resolution") {
        line.push_str(&format!(" _({})_", resolution.trim()));
    }
    line.push('\n');
    line
}

/// Group entries by `group_key` in `order` (unknown values last,
/// alphabetically), id-sorted inside each group.
fn render_groups(entries: &[Value], group_key: &str, order: &[&str], headline_key: &str) -> String {
    let mut out = String::new();
    let group_of =
        |entry: &Value| -> String { field(entry, group_key).unwrap_or("(unset)").to_string() };
    let mut groups: Vec<String> = entries.iter().map(&group_of).collect();
    groups.sort();
    groups.dedup();
    groups.sort_by_key(|g| order.iter().position(|o| o == g).unwrap_or(order.len()));
    for group in groups {
        let mut members: Vec<&Value> = entries.iter().filter(|e| group_of(e) == group).collect();
        members.sort_by_key(|e| field(e, "id").unwrap_or_default().to_string());
        out.push_str(&format!("## {group} ({})\n\n", members.len()));
        for entry in members {
            out.push_str(&bullet_line(entry, headline_key));
        }
        out.push('\n');
    }
    out
}

/// Render both views to strings: `(DEBT.md, INTENT.md)`.
pub fn render_views(root: &Path, debt_rel: &str, intent_rel: &str) -> Result<(String, String)> {
    let debt_entries = load_entries(root, debt_rel)?;
    let mut debt = banner("Debt registry — human view", debt_rel);
    debt.push_str(&format!("{} entr(ies).\n\n", debt_entries.len()));
    debt.push_str(&render_groups(
        &debt_entries,
        "disposition",
        &["open", "accepted", "filed", "fixed"],
        "title",
    ));

    let intent_entries = load_entries(root, intent_rel)?;
    let mut intent = banner("Intent ledger — human view", intent_rel);
    intent.push_str(&format!("{} entr(ies).\n\n", intent_entries.len()));
    intent.push_str(&render_groups(
        &intent_entries,
        "state",
        &["open", "rescoped", "done", "rejected"],
        "title",
    ));
    Ok((debt, intent))
}

const DEBT_VIEW: &str = "discipline/DEBT.md";
const INTENT_VIEW: &str = "discipline/INTENT.md";

pub fn run_ledger_render(root: &Path, debt_rel: &str, intent_rel: &str, check: bool) -> Result<()> {
    let (debt, intent) = render_views(root, debt_rel, intent_rel)?;
    let targets = [(DEBT_VIEW, debt), (INTENT_VIEW, intent)];
    if check {
        let mut stale = Vec::new();
        for (rel, fresh) in &targets {
            let committed = std::fs::read_to_string(root.join(rel)).unwrap_or_default();
            if &committed != fresh {
                stale.push(*rel);
            }
        }
        if stale.is_empty() {
            eprintln!("ledger render --check: both views match their registries.");
            return Ok(());
        }
        bail!(
            "ledger render --check: stale view(s): {} — run `discipline-rust ledger render` \
             and commit the result",
            stale.join(", ")
        );
    }
    for (rel, fresh) in &targets {
        let path = root.join(rel);
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&path, fresh).with_context(|| format!("writing {rel}"))?;
        eprintln!("ledger render: wrote {rel}");
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn registry(entries: &str) -> String {
        format!("{{ \"schema\": 1, \"entries\": [{entries}] }}")
    }

    #[test]
    fn renders_grouped_ordered_views_and_check_gates_drift() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let root = tmp.path();
        std::fs::create_dir_all(root.join("r")).expect("dir");
        std::fs::write(
            root.join("r/debt.json"),
            registry(
                "{\"id\":\"DBT-0002\",\"kind\":\"failing-test\",\"severity\":\"P2\",\
                  \"title\":\"two\",\"disposition\":\"open\"},\
                 {\"id\":\"DBT-0001\",\"kind\":\"stale-doc\",\"severity\":\"P3\",\
                  \"title\":\"one\",\"disposition\":\"fixed\"}",
            ),
        )
        .expect("debt");
        std::fs::write(
            root.join("r/intent.json"),
            registry("{\"id\":\"INT-0001\",\"title\":\"audit\",\"state\":\"open\"}"),
        )
        .expect("intent");

        run_ledger_render(root, "r/debt.json", "r/intent.json", false).expect("render");
        let debt = std::fs::read_to_string(root.join(DEBT_VIEW)).expect("view");
        assert!(debt.starts_with("<!-- GENERATED"));
        // `open` groups before `fixed`, entries carry id/kind/severity.
        let open_at = debt.find("## open (1)").expect("open group");
        let fixed_at = debt.find("## fixed (1)").expect("fixed group");
        assert!(open_at < fixed_at, "{debt}");
        assert!(debt.contains("**DBT-0002** `failing-test` [P2] — two"));

        run_ledger_render(root, "r/debt.json", "r/intent.json", true).expect("check clean");

        // Registry change → stale view → red check.
        std::fs::write(
            root.join("r/intent.json"),
            registry("{\"id\":\"INT-0002\",\"title\":\"new\",\"state\":\"open\"}"),
        )
        .expect("mutate");
        let err = run_ledger_render(root, "r/debt.json", "r/intent.json", true)
            .expect_err("stale view must fail");
        assert!(err.to_string().contains("INTENT.md"), "{err}");
    }
}
