schema = 1
source_hash = "sha256:88debf58c36db427658500dafbd9bb5dc4542b8353a2aa812fc03f2b31d86bc0"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:988053e8876e3a152f575871264def4d323510b8ca662fb76c38d86c5928e838"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/31-flow-conventional-commits.xml"
output = "vibevm/vibespecs/boot/31-flow-conventional-commits.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/conventional-commits/conventional-commits.xml"
output = "vibevm/vibespecs/flows/conventional-commits/conventional-commits.xml"
disposition = "copied"
