schema = 1
source_hash = "sha256:04a03d3bd572cd3c865868c0a096f5f61606197924b886aa369bdaf56af243f8"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:0f899c94eefef04174256c29caa291cb9cc7172dd61b423e6a9194dfcac2f8bd"

[[file]]
source = "LICENSE"
output = "LICENSE"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/31-flow-conventional-commits.xml"
output = "vibevm/vibespecs/boot/31-flow-conventional-commits.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/conventional-commits/conventional-commits.xml"
output = "vibevm/vibespecs/flows/conventional-commits/conventional-commits.xml"
disposition = "copied"
