"""The shipped parser, and the only way this package looks at a document.

Nothing here reads Markdown or XML. A document becomes readable exactly once, by
`vibe progress mirror` — the engine's own parse, projection dispatch and content
hashing (PROP-045 `##PROJECTION-READ`) — and every consumer downstream reads the
`ParsedDoc` JSON it wrote. A second implementation of the hash recipe is the bug
`text-stability.py`'s `#recipe-drift` guard was built to catch, and the way not
to need that guard is to have no second implementation.
"""

import collections
import json
import os
import pathlib
import shutil
import subprocess

from .refusal import Refusal

# The scope a materialised historical tree gets: both legacy roots, both live
# roots, both serialisations. Narrow by construction anyway — such a tree holds
# exactly the blobs this package put in it.
SCRATCH_SCOPE = (
    "# Generated by corpus_migration — a materialised tree's scope. Narrow by\n"
    "# construction: the tree holds exactly the files that were written into it.\n"
    "schema = 1\n"
    'include = ["spec/**/*.md", "spec/**/*.xml",\n'
    '           "packages/**/*.md", "packages/**/*.xml",\n'
    '           "vibevm/vibespecs/**/*.md", "vibevm/vibespecs/**/*.xml",\n'
    '           "vibevm/vibepacks/**/*.md", "vibevm/vibepacks/**/*.xml"]\n'
    "exclude = []\n\n"
    "[progress]\n"
    'cache_dir = ".payloads"\n'
)


class Mirror:
    """A `run/mirror/` directory as written by `vibe progress mirror`."""

    def __init__(self, directory):
        self.dir = pathlib.Path(directory)
        self._cache = {}

    def _file(self, path):
        return self.dir / (path.replace("/", "__") + ".json")

    def has(self, path):
        return self._file(path).exists()

    def doc(self, path):
        if path not in self._cache:
            f = self._file(path)
            if not f.exists():
                raise Refusal(f"no mirror for `{path}` under {self.dir}")
            self._cache[path] = json.loads(f.read_text(encoding="utf-8"))
        return self._cache[path]

    def paths(self):
        return sorted(p.name[:-len(".json")].replace("__", "/")
                      for p in self.dir.glob("*.json"))

    def marked_facts(self, path):
        """`{fact id: [content hash, …]}` — a list, so a duplicate stays visible."""
        out = collections.defaultdict(list)
        for block in self.doc(path)["blocks"]:
            for fact in block.get("facts", []):
                if fact.get("marked") and fact.get("id"):
                    out[fact["id"]].append(fact["content_hash"])
        return out

    def fact_bodies(self, path):
        """`{fact id: [body, …]}`, the same shape and for the same reason."""
        out = collections.defaultdict(list)
        for block in self.doc(path)["blocks"]:
            for fact in block.get("facts", []):
                if fact.get("marked") and fact.get("id"):
                    out[fact["id"]].append(fact["body"])
        return out

    def units(self, path):
        return self.doc(path)["units"]

    def content_hash(self, path):
        return self.doc(path)["content_hash"]


def unit_frag(unit):
    """A unit's address fragment, exactly as `progress_core::baseline::unit_addr`
    spells it: its anchor, or `L<line_start>` when it has none."""
    return unit.get("anchor") or "L%d" % unit["line_start"]


# --------------------------------------------------------------------------
# Driving the shipped CLI
# --------------------------------------------------------------------------


def vibe_command(root, explicit=None):
    if explicit:
        return [explicit]
    env = os.environ.get("VIBE_BIN")
    if env:
        return [env]
    for rel in ("target/debug/vibe.exe", "target/debug/vibe",
                "target/release/vibe.exe", "target/release/vibe"):
        candidate = pathlib.Path(root) / rel
        if candidate.is_file():
            return [str(candidate)]
    return ["cargo", "run", "-p", "vibe-cli", "--locked", "--quiet", "--"]


def have_vibe(root):
    """True when a shipped CLI can actually be reached — a test skips on False."""
    cmd = vibe_command(root)
    return cmd[0] != "cargo" or shutil.which("cargo") is not None


def run(cmd, cwd):
    proc = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True,
                          encoding="utf-8", errors="replace")
    if proc.returncode != 0:
        raise Refusal(f"`{' '.join(cmd)}` failed with exit {proc.returncode}",
                      [proc.stdout.strip(), proc.stderr.strip()])
    return proc.stdout


def git(root, *args):
    return subprocess.run(["git", *args], cwd=root, capture_output=True, text=True,
                          encoding="utf-8", errors="replace").stdout


def blob_exists(root, rev, path):
    """Does `rev:path` name a blob? Asked with `cat-file -e`, whose exit code is
    the whole answer — never by reading output and calling emptiness absence.
    A zero-byte `git show` and a missing path are indistinguishable on stdout,
    and treating the second as "the file was empty" is how an unread document
    gets certified as unchanged."""
    return subprocess.run(["git", "cat-file", "-e", f"{rev}:{path}"], cwd=root,
                          capture_output=True).returncode == 0


# `git cat-file --batch` answers a query it could not resolve by ECHOING the
# query and appending one word. The query is `<rev>:<path>` and a path may hold
# spaces, so the answer cannot be read by counting tokens — `abc:my file.md
# missing` splits into three exactly like a real header does. The only reliable
# discriminator is the trailing word, so it is matched as a suffix and matched
# FIRST, before anything numeric is attempted.
BATCH_ABSENT = (" missing", " ambiguous", " dangling", " notdir", " loop")


def batch_header(line, query):
    """One `git cat-file --batch` header → the blob's size, or `None` if absent.

    Anything that is neither a blob header nor a recognised absence answer is a
    `Refusal` carrying the line verbatim — never a `ValueError` from parsing a
    word as a size, and never a silent skip. The three shapes are kept apart on
    purpose: absence is data this module reports, a non-blob type is a caller
    error, and a malformed line means git said something this code does not
    understand, which must stop the run rather than be guessed at.
    """
    text = line.decode("utf-8", "replace").rstrip("\r\n")
    if any(text.endswith(word) for word in BATCH_ABSENT):
        return None
    parts = text.split(" ")
    if len(parts) != 3 or not parts[2].isdigit():
        raise Refusal("`git cat-file --batch` answered a header this module cannot read",
                      [f"query `{query}` -> `{text}`"])
    if parts[1] != "blob":
        raise Refusal(f"`{query}` is a `{parts[1]}`, not a blob — refusing to read it as a document")
    return int(parts[2])


def materialise(root, rev, paths, dest, scope=SCRATCH_SCOPE):
    """Write every `rev:<path>` blob under `dest`, with a scope file observing them.

    Refuses naming every path that is not a blob at `rev`. `git cat-file --batch`
    reports a missing object on its header line, so absence is detected before a
    single byte is read rather than inferred from the bytes afterwards — and an
    absent path leaves NO file behind, so a later parse can never mistake an
    empty file for an empty document. This is the only absence parser in the
    package; [`blob_exists`] answers the same question by exit code for a single
    path, and nothing else reads a header.
    """
    if dest.exists():
        shutil.rmtree(dest)
    dest.mkdir(parents=True, exist_ok=True)
    proc = subprocess.Popen(["git", "cat-file", "--batch"], cwd=root,
                            stdin=subprocess.PIPE, stdout=subprocess.PIPE)
    absent = []
    try:
        for path in paths:
            query = f"{rev}:{path}"
            proc.stdin.write((query + "\n").encode())
            proc.stdin.flush()
            size = batch_header(proc.stdout.readline(), query)
            if size is None:
                absent.append(path)
                continue
            blob = proc.stdout.read(size)
            proc.stdout.read(1)
            target = dest / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(blob)
    finally:
        proc.stdin.close()
        proc.wait()
    if absent:
        raise Refusal(f"{len(absent)} path(s) are not blobs at {rev}", absent[:20])
    (dest / "facts.toml").write_text(scope, encoding="utf-8")
    return dest


def mirror_tree(vibe, root, tree, zone="campaigns/scratch"):
    """Parse `tree` with the shipped parser; hand back the `Mirror` it wrote."""
    run(vibe + ["progress", "mirror", "--quiet", "--path", str(tree), "--campaign", zone], root)
    return Mirror(pathlib.Path(tree) / zone / "run" / "mirror")
