//! Generated boot artifacts — `STATIC.md`, `INDEX.md`, the redirect.
//!
//! PROP-009 §2.3. The computed-view engine ([`crate::boot`]) produces an
//! [`EffectiveBoot`]; this module projects it into the files an AI agent
//! reads at session start:
//!
//! - **`STATIC.md`** — the verbatim concatenation, in composed order, of
//!   every `static`-linked contribution. Read first — the priority lane.
//!   Generated only when the node has static contributions.
//! - **`INDEX.md`** — a generated TOML manifest: a `schema` version, an
//!   `static` pointer (when an `STATIC.md` exists), and an ordered list of
//!   `[[entry]]` tables, each with a `path` and a `kind` (`static` /
//!   `dynamic`). Always generated.
//! - **The redirect** — a managed `<vibevm>` block (PROP-012) inside each
//!   of `CLAUDE.md` / `AGENTS.md` / `GEMINI.md`, pointing a session at
//!   `STATIC.md` then `INDEX.md`. vibevm owns only the block; the rest of
//!   each file belongs to the developer and any other tool and is
//!   preserved verbatim.
//!
//! `STATIC.md` and `INDEX.md` are git-tracked and carry a "generated — do
//! not edit" header. Boot stays pure file-reading — the redirect points
//! at files, it never becomes "run `vibe`".
//!
//! ## `when` on dynamic entries
//!
//! A `[boot_snippet]` may carry a `when` condition (PROP-009 §2.4 / §2.6).
//! The computed-view engine renders such a contribution as a `dynamic`
//! entry, and [`render_index`] writes the condition into the `INDEX.md`
//! `[[entry]]` as `when = "os:<name>"`. The agent evaluates it at boot: it
//! reads a `dynamic` entry's file only when the condition holds for the
//! session's operating system. The committed `INDEX.md` is therefore
//! OS-invariant — every entry is listed, and the OS test happens at read
//! time. A `dynamic` entry without `when` is an unconditional INCLUDE —
//! still valid.

specmark::scope!("spec://vibevm/modules/vibe-workspace/PROP-009#artifacts");

use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;
use specmark::spec;
use vibe_spec::{
    Directives, FileResolver, FsSectionSource, RenameEntry, SelfCoordinate, expand_embeds,
    qualify_contribution,
};

use crate::WorkspaceError;
use crate::boot::EffectiveBoot;
use normal::compile_normal_entry;

/// `normal + static` compilation — the branch that compiles a `normal`
/// package's closure rather than concatenating it (PROP-035 §8).
mod normal;

/// The managed redirect block (PROP-012) — `<vibevm>` in `CLAUDE.md` /
/// `AGENTS.md` / `GEMINI.md`, moved out of this cell along its seam.
mod redirect;
pub use redirect::{
    BLOCK_CLOSE, BLOCK_OPEN, BlockLocation, REDIRECT_FILES, locate_block, render_redirect,
    write_redirect_blocks,
};

/// `schema` version of the generated `INDEX.md` manifest (PROP-009 §2.3).
pub const INDEX_SCHEMA: u32 = 1;

/// The header comment line carrying a unit's boot-graph fingerprint
/// (PROP-038 §2.7). Present on a per-unit `INDEX.md` so a later regeneration
/// can skip a unit whose fingerprint is unchanged (§2.8). A leading `#` makes
/// it a TOML comment — invisible to the manifest parser.
pub const FP_MARKER: &str = "# vibe:fp ";

/// Read the fingerprint recorded in a generated artifact's header, if any
/// (PROP-038 §2.7). Returns the trimmed hash after [`FP_MARKER`].
pub fn read_fingerprint(text: &str) -> Option<String> {
    text.lines()
        .find_map(|l| l.trim().strip_prefix(FP_MARKER))
        .map(|s| s.trim().to_string())
}

/// Generated-artifact filenames, relative to a node's `spec/boot/`.
pub const STATIC_FILE: &str = "STATIC.md";
/// See [`STATIC_FILE`].
pub const INDEX_FILE: &str = "INDEX.md";

const INDEX_HEADER: &str = "\
# spec/boot/INDEX.md — generated by vibe, do not edit.
# The computed boot sequence (PROP-009 §2.3). Read every file the
# `[[entry]]` list names, in order.
#
# A `kind = \"static\"` entry: read the file directly. A `kind = \"dynamic\"`
# entry: an INCLUDE resolved at boot — when it also carries
# `when = \"os:<name>\"`, read the file only if the session's operating
# system is <name> (windows / macos / linux), and skip it otherwise.

";

/// The resolution preamble (B-011 §5.1, owner-priority placement 2026-08-04) —
/// the first lines of the lane, after the three header comments. Boss-authored
/// text, emitted verbatim; do not reword. A session re-reads `STATIC.md` at
/// every start and after compaction, so placing the rules here is what makes
/// them un-forgettable (design §5.1).
const RESOLUTION_PREAMBLE: &str = "\
<!-- RESOLUTION RULES — read these five lines before anything else:
  1. Labels in this file are qualified: <origin-slug>--<original>. The origin
     is named by the provenance comment above each block; the original short
     label is the tail after the last `--`.
  2. A short label you cannot find here → check the RENAMED ANCHORS table
     below for its qualified heirs; never guess among look-alikes.
  3. Full spec:// addresses resolve against package SOURCES under vibedeps/,
     never against this generated file. This file is a cache, not a target.
  4. `#use spec://… as X` binds a file-local alias; `@!X` is a mandatory read
     of X's target (same rules as @spec://…). In this compiled file every @!X
     is already rewritten to its full address.
  5. An ambiguous or unresolvable short reference is an ERROR to surface with
     candidates — never silently pick one.
-->

";

const STATIC_HEADER: &str = "\
<!-- spec/boot/STATIC.md — generated by vibe, do not edit. -->
<!-- The static boot lane (PROP-009 §2.3): the highest-priority -->
<!-- contributions, compiled anchor-qualified. Read this first, in full. -->

";

/// One `[[entry]]` of the generated `INDEX.md` manifest.
#[derive(Debug, Serialize)]
struct IndexEntry {
    /// Path of the boot file, as composed by the engine.
    path: String,
    /// `"static"` — read the file directly — or `"dynamic"` — an INCLUDE
    /// the agent resolves at boot.
    kind: &'static str,
    /// Activation condition for a `dynamic` entry (PROP-009 §2.3) — the
    /// wire string `"os:<name>"`. `None` on a `static` entry or an
    /// unconditional `dynamic` one.
    #[serde(skip_serializing_if = "Option::is_none")]
    when: Option<String>,
}

/// The serialised shape of `INDEX.md`.
#[derive(Debug, Serialize)]
struct IndexManifest {
    schema: u32,
    #[serde(rename = "static", skip_serializing_if = "Option::is_none")]
    static_lane: Option<String>,
    #[serde(rename = "entry", skip_serializing_if = "Vec::is_empty")]
    entries: Vec<IndexEntry>,
}

/// Render the `INDEX.md` TOML manifest for a node's effective boot.
///
/// Pure — the manifest is paths and kinds, no file content. The `static`
/// pointer is present exactly when `boot` has `static`-linked entries.
/// Serialisation is structurally infallible with today's fixed manifest
/// shape; the error is routed anyway so a future shape change degrades
/// to a diagnosis instead of a panic.
pub fn render_index(
    boot: &EffectiveBoot,
    fingerprint: Option<&str>,
) -> Result<String, WorkspaceError> {
    let has_static = boot.static_entries().next().is_some();
    let manifest = IndexManifest {
        schema: INDEX_SCHEMA,
        static_lane: has_static.then(|| format!("spec/boot/{STATIC_FILE}")),
        entries: boot
            .dynamic_entries()
            .map(|e| IndexEntry {
                path: e.path.clone(),
                // Every INDEX entry is dynamically linked (read by reference);
                // its read-timing derives from `when` — a conditional entry is
                // a gated INCLUDE ("dynamic"), an unconditional one is read
                // directly ("static"). PROP-009 §2.3.
                kind: if e.when.is_some() {
                    "dynamic"
                } else {
                    "static"
                },
                when: e.when.map(|w| w.to_string()),
            })
            .collect(),
    };
    let body = toml::to_string_pretty(&manifest).map_err(|e| WorkspaceError::IndexRender {
        reason: e.to_string(),
    })?;
    // The fingerprint header (PROP-038 §2.7) — a TOML comment, so the manifest
    // stays parseable. Omitted (`None`) on a node so its INDEX.md is
    // byte-stable; carried on a per-unit INDEX to drive the dirty-subgraph.
    let fp_line = match fingerprint {
        Some(fp) => format!("{FP_MARKER}{fp}\n\n"),
        None => String::new(),
    };
    Ok(format!("{INDEX_HEADER}{fp_line}{body}"))
}

/// Render `STATIC.md` — the concatenation of the `static`-linked
/// contributions, in composed order. Returns `None` when the node has no
/// static contributions (no `STATIC.md` is generated then).
///
/// A `simple` contribution is carried **verbatim** (PROP-035 §3); a `normal`
/// one is **compiled** to its `#use`/`#source`-resolved, tree-shaken closure
/// (PROP-035 §8, [`compile_normal_entry`]) — so a `normal + static` edge bakes
/// in only what the contract actually reaches, merged, in dependency order,
/// rather than the whole file. `workspace_root` resolves each contribution's
/// path (and every `spec://` a `normal` closure walks) against the
/// materialised `vibedeps/` tree.
pub fn render_static(
    boot: &EffectiveBoot,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
) -> Result<Option<String>, WorkspaceError> {
    let entries: Vec<_> = boot.static_entries().collect();
    if entries.is_empty() {
        return Ok(None);
    }
    // B-011 (PROP-035 §8 phase 5 / §11): the lane is built in two parts — the
    // concatenated, origin-qualified contribution bodies, and the tombstone of
    // every rename the qualify phase made. The header (with its resolution
    // preamble) leads; the tombstone sits directly under it (START-placement,
    // design §5.1/§6.1) when at least one rename happened; then the bodies.
    let mut bodies = String::new();
    let mut tombstone: Vec<(String, RenameEntry)> = Vec::new();
    for entry in entries {
        if entry.elided {
            // B-006 (lane dedup): this entry's whole static zone is emitted
            // member-by-member elsewhere in this lane (once-each). Render a
            // provenance stub — NO `#use`, no body — so the lane carries the
            // zone's text exactly once while the graph membership stays
            // visible. Deliberately not a hoist marker (B1): there is no
            // single root copy to point at; every member is right here.
            bodies.push_str(&format!(
                "<!-- vibe:static {} — {}; zone elided: emitted member-by-member in this lane (once-each, B-006) -->\n\n",
                entry.origin, entry.path
            ));
            continue;
        }
        if entry.use_ref {
            // A soft-hoist reference (PROP-038 §2.5): this package's text lives
            // once in the global root STATIC.md. Leave a `#use` marker so the
            // graph edge survives locally and the read-set dedups the read —
            // the agent knows the package is part of this zone without a
            // duplicated copy.
            bodies.push_str(&format!(
                "<!-- vibe:hoisted {} — text in the root STATIC.md -->\n#use spec://{}\n\n",
                entry.origin, entry.origin
            ));
            continue;
        }
        // An HTML-comment provenance marker — invisible in rendered markdown,
        // names the origin the block's labels are qualified under (B-011 §3).
        bodies.push_str(&format!(
            "<!-- vibe:static {} — {} -->\n\n",
            entry.origin, entry.path
        ));
        // PROP-035 §8: a `normal` package's static contribution is the
        // `#use` / `#source`-resolved, tree-shaken closure reachable from its
        // contract — compiled (with `@!X` already rewritten to its full
        // address, §7.4) and qualified **per-node** (each node under its own
        // origin, B-006 rider) — not concatenated. A `simple` package is
        // carried verbatim (its over-load the author's problem, PROP-035 §3).
        //
        // Both branches yield `(body, per-node renames)` — the normal branch's
        // renames already carry each node's own origin; the simple branch's are
        // wrapped under the entry's origin. So the body is pushed as-compiled
        // and the renames flow straight into the tombstone: a `normal` body is
        // NEVER re-qualified whole under the entry's origin (that would
        // mis-attribute a spliced-in node's labels and double-prefix every
        // label).
        let (body, mut renames): (String, Vec<(String, RenameEntry)>) = if entry.format.is_normal()
        {
            compile_normal_entry(entry, workspace_root, self_coord)?
        } else {
            let abs = workspace_root.join(&entry.path);
            let raw = fs::read_to_string(&abs).map_err(|e| io_err(&abs, e))?;
            // R3 (B-011): `#use … as` / `@!` are `normal`-format machinery; a
            // `simple` contribution is carried whole and cannot bind or resolve
            // aliases. Detected on the verbatim text (before any embed), so an
            // embed-spliced `@!` from another document is not mis-attributed.
            if let Some(reason) = simple_alias_machinery(&raw) {
                return Err(WorkspaceError::InlineCompile {
                    reason: format!("the simple package `{}` {reason}", entry.origin),
                });
            }
            // R1 (B-011): expand this entry's `#embed`s to a fixed point BEFORE
            // qualifying, so a label an embed splices in is qualified under the
            // entry's origin and tombstoned with the rest. Per-entry, not
            // whole-lane — `#embed` targets `spec://` sources under vibedeps/,
            // never a sibling lane entry, so the result is identical and each
            // entry's final body is self-contained for the qualify pass.
            let expanded = if has_embed_directive(&raw) {
                let source =
                    FsSectionSource::new(FileResolver::new(workspace_root, self_coord.clone()));
                expand_embeds(&raw, &source).map_err(|e| WorkspaceError::InlineCompile {
                    reason: e.to_string(),
                })?
            } else {
                raw
            };
            // B-011 §3 (PROP-035 §8 phase 5): qualify every label this entry
            // defines under its origin slug, and rewrite its intra-document
            // `(#x)` links to match — a pure function of (body, origin), so the
            // lane is collision-free by construction and append-only.
            let (qualified, entry_renames) = qualify_contribution(&expanded, &entry.origin);
            let pairs = entry_renames
                .into_iter()
                .map(|r| (entry.origin.clone(), r))
                .collect();
            (qualified, pairs)
        };
        tombstone.append(&mut renames);
        bodies.push_str(body.trim_end());
        bodies.push_str("\n\n");
    }
    let mut out = String::from(STATIC_HEADER);
    out.push_str(RESOLUTION_PREAMBLE);
    if !tombstone.is_empty() {
        out.push_str(&render_tombstone(&tombstone));
    }
    out.push_str(&bodies);
    Ok(Some(out))
}

/// R3 (B-011): detect alias machinery a `simple`-format contribution must not
/// carry — a `#use … as <Alias>` clause (the file's alias table is non-empty)
/// or an `@!<Alias>` use with no matching declaration (the scanner reports it
/// as an undeclared alias). Returns the defect description when present.
fn simple_alias_machinery(raw: &str) -> Option<String> {
    let d = Directives::parse(raw);
    let has_as_clause = !d.aliases.is_empty();
    let has_at_bang = d
        .errors
        .iter()
        .any(|e| e.message.contains("undeclared alias"));
    if has_as_clause || has_at_bang {
        Some(
            "carries alias machinery (`#use … as` / `@!`) that is \
             `normal`-format only (PROP-035 §7.2); convert the package to \
             `format = \"normal\"` or drop the alias"
                .to_string(),
        )
    } else {
        None
    }
}

/// The RENAMED ANCHORS tombstone (B-011 §6.1 layer 2 / PROP-035 §11
/// `##STATIC-TOMBSTONE-TABLE`) — a single HTML comment (invisible in render,
/// no new anchors minted) with one line per retired short name, each grouped
/// with its qualified heirs and their origins. Deterministic order: short name
/// ascending, then origin ascending within a group.
fn render_tombstone(renames: &[(String, RenameEntry)]) -> String {
    // Group by the original short name; within a group keep every
    // (origin, qualified) heir.
    let mut groups: BTreeMap<String, Vec<(String, String)>> = BTreeMap::new();
    for (origin, r) in renames {
        groups
            .entry(r.original.clone())
            .or_default()
            .push((origin.clone(), r.qualified.clone()));
    }
    let mut out = String::from("<!-- RENAMED ANCHORS (short → qualified heirs):\n");
    for (short, mut heirs) in groups {
        heirs.sort();
        let listed: Vec<String> = heirs
            .iter()
            .map(|(origin, qualified)| format!("{qualified} ({origin})"))
            .collect();
        out.push_str(&format!("  {short} → {}\n", listed.join(", ")));
    }
    out.push_str("-->\n\n");
    out
}

/// Whether the static lane carries an `#embed` directive (a line starting with
/// `#embed ` after leading whitespace) — the guard that keeps a directive-free
/// lane byte-identical.
fn has_embed_directive(text: &str) -> bool {
    text.lines().any(|l| l.trim_start().starts_with("#embed "))
}

/// What [`write_boot_artifacts`] wrote — for the caller to report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WrittenArtifacts {
    /// Absolute path of the generated `INDEX.md` — always written.
    pub index: PathBuf,
    /// Absolute path of the generated `STATIC.md`, when the node had
    /// static contributions; `None` otherwise.
    pub static_lane: Option<PathBuf>,
    /// Absolute paths of the instruction files whose `<vibevm>` block was
    /// written or updated this run; a file already carrying an identical
    /// block is not listed (PROP-012).
    pub redirects: Vec<PathBuf>,
}

/// Generate and write a node's boot artifacts (PROP-009 §2.3): `INDEX.md`
/// always, `STATIC.md` when the node has static contributions, and the
/// `CLAUDE.md` / `AGENTS.md` / `GEMINI.md` redirects.
///
/// `node_dir` is the node's root; `workspace_root` is the absolute
/// workspace root, used to resolve the static contributions' content;
/// `self_coord` is the workspace root's own `<group>/<name>` coordinate
/// (B-031 — the host is a package coordinate), the authority a `spec://`
/// address names to reach the authored `spec/` tree. A stale `STATIC.md`
/// from an earlier generation is removed when the node no longer has static
/// contributions, so it is never read by mistake.
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#co-tenant",
    r = 1
)]
pub fn write_boot_artifacts(
    node_dir: &Path,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    boot: &EffectiveBoot,
) -> Result<WrittenArtifacts, WorkspaceError> {
    let boot_dir = node_dir.join("spec").join("boot");
    fs::create_dir_all(&boot_dir).map_err(|e| io_err(&boot_dir, e))?;

    // INDEX.md — always. A node carries no fingerprint (byte-stable); the
    // per-unit dirty-subgraph (PROP-038 §2.8) is emit-side, in `hybrid_emit`.
    let index = boot_dir.join(INDEX_FILE);
    fs::write(&index, render_index(boot, None)?).map_err(|e| io_err(&index, e))?;

    // STATIC.md — only when there are static contributions.
    let static_path = boot_dir.join(STATIC_FILE);
    let static_lane = match render_static(boot, workspace_root, self_coord)? {
        Some(text) => {
            fs::write(&static_path, text).map_err(|e| io_err(&static_path, e))?;
            Some(static_path)
        }
        None => {
            if static_path.exists() {
                fs::remove_file(&static_path).map_err(|e| io_err(&static_path, e))?;
            }
            None
        }
    };

    // The redirects — vibevm's managed `<vibevm>` block in each (PROP-012).
    // Only the block is written; co-tenant content is preserved, and a
    // file already carrying an identical block is left untouched.
    let redirects = write_redirect_blocks(node_dir)?;

    Ok(WrittenArtifacts {
        index,
        static_lane,
        redirects,
    })
}

/// Build a [`WorkspaceError::Io`] from a `std::io::Error` and its path.
fn io_err(path: &Path, e: std::io::Error) -> WorkspaceError {
    WorkspaceError::Io {
        path: path.to_path_buf(),
        reason: e.to_string(),
    }
}

#[cfg(test)]
#[path = "boot_artifacts/tests.rs"]
mod tests;

#[cfg(test)]
#[path = "boot_artifacts/tests_qualify.rs"]
mod tests_qualify;
