//! Generated boot artifacts — the format-selected `STATIC` lane, `INDEX.md`,
//! and the redirect.
//!
//! PROP-009 §2.3. The computed-view engine ([`crate::boot`]) produces an
//! [`EffectiveBoot`]; this module projects it into the files an AI agent
//! reads at session start:
//!
//! - **`STATIC.md` / `STATIC.xml`** — the concatenation, in composed order, of
//!   every `static`-linked contribution. Read first — the priority lane.
//!   Generated only when the node has static contributions.
//! - **`INDEX.md`** — a generated TOML manifest: a `schema` version, an
//!   `static` pointer (when an `STATIC.md` exists), and an ordered list of
//!   `[[entry]]` tables, each with a `path` and a `kind` (`static` /
//!   `dynamic`). Always generated.
//! - **The redirect** — a managed `<vibevm>` block (PROP-012) inside each
//!   of `CLAUDE.md` / `AGENTS.md` / `GEMINI.md`, pointing a session at
//!   `STATIC.md` then `INDEX.md`. vibevm owns only the block; the rest of
//!   each file belongs to the developer and any other tool and is
//!   preserved verbatim.
//!
//! `STATIC.md` and `INDEX.md` are git-tracked and carry a "generated — do
//! not edit" header. Boot stays pure file-reading — the redirect points
//! at files, it never becomes "run `vibe`".
//!
//! ## `when` on dynamic entries
//!
//! A `[boot_snippet]` may carry a `when` condition (PROP-009 §2.4 / §2.6).
//! The computed-view engine renders such a contribution as a `dynamic`
//! entry, and [`render_index`] writes the condition into the `INDEX.md`
//! `[[entry]]` as `when = "os:<name>"`. The agent evaluates it at boot: it
//! reads a `dynamic` entry's file only when the condition holds for the
//! session's operating system. The committed `INDEX.md` is therefore
//! OS-invariant — every entry is listed, and the OS test happens at read
//! time. A `dynamic` entry without `when` is an unconditional INCLUDE —
//! still valid.

specmark::scope!("spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-009#artifacts");

#[cfg(test)]
use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;
use specmark::spec;
use vibe_core::{layout, manifest::SpecFormat};
use vibe_spec::{
    ArtifactCompileError, ArtifactInputType, ArtifactPlan, ArtifactTarget, EmittedArtifact,
    FileResolver, FsSectionSource, SelfCoordinate, TransformPlan, compile_artifact,
    compile_artifact_traced,
};

use crate::boot::EffectiveBoot;
use crate::compile_trace::{ScopeAcquisition, TraceRun};
use crate::{WorkspaceError, layout_paths};

/// `normal + static` compilation — the branch that compiles a `normal`
/// package's closure rather than concatenating it (PROP-035 §8).
mod normal;
pub(crate) mod transaction;

pub(crate) mod native_managed;
pub use native_managed::OwnerNativeCompileContinuation;
/// The artifact's ordered inputs and their TYPED declaring providers — the
/// T10B seam, out of line per the file-length budget.
mod inputs;

/// The R4.3 analyzer's compile half — the observed spelling and the
/// compile result's attribution side, out of line per the file-length
/// budget.
mod analyzed;
pub(crate) use analyzed::{StaticCompile, compile_static_analyzed};

/// Manager-owned per-unit publication — the compiled INDEX/STATIC triple's
/// narrow seam onto the transaction manager (R4.1 atom B).
pub(crate) mod publication;
pub(crate) use publication::publish_unit_artifacts;
use publication::stale_static_file;

mod format;
pub use format::{STATIC_FILE, STATIC_XML_FILE, resolve_static_path, static_file, static_path};

/// The managed redirect block (PROP-012) — `<vibevm>` in `CLAUDE.md` /
/// `AGENTS.md` / `GEMINI.md`, moved out of this cell along its seam.
mod redirect;
pub use redirect::{
    BLOCK_CLOSE, BLOCK_OPEN, BlockLocation, REDIRECT_FILES, locate_block, render_redirect,
    render_redirect_with_spec_format, write_redirect_blocks,
    write_redirect_blocks_with_spec_format,
};

/// `schema` version of the generated `INDEX.md` manifest (PROP-009 §2.3).
pub const INDEX_SCHEMA: u32 = 1;

/// The header comment line carrying a unit's boot-graph fingerprint
/// (PROP-038 §2.7). Present on a per-unit `INDEX.md` so a later regeneration
/// can skip a unit whose fingerprint is unchanged (§2.8). A leading `#` makes
/// it a TOML comment — invisible to the manifest parser.
pub const FP_MARKER: &str = "# vibe:fp ";

/// Read the fingerprint recorded in a generated artifact's header, if any
/// (PROP-038 §2.7). Returns the trimmed hash after [`FP_MARKER`].
pub fn read_fingerprint(text: &str) -> Option<String> {
    text.lines()
        .find_map(|l| l.trim().strip_prefix(FP_MARKER))
        .map(|s| s.trim().to_string())
}

/// Generated INDEX filename, relative to a node's boot lane.
pub use vibe_core::layout::INDEX_MD as INDEX_FILE;

const INDEX_HEADER_SUFFIX: &str = "\
 — generated by vibe, do not edit.
# The computed boot sequence (PROP-009 §2.3). Read every file the
# `[[entry]]` list names, in order.
#
# `installed:<group>/<name>` is resolved during generation: true
# contributions appear normally; false contributions are absent entirely.
# A `kind = \"static\"` entry: read the file directly. A `kind = \"dynamic\"`
# entry: an INCLUDE resolved at boot — when it also carries
# `when = \"os:<name>\"`, read the file only if the session's operating
# system is <name> (windows / macos / linux), and skip it otherwise.

";

fn index_header() -> String {
    format!("# {}{INDEX_HEADER_SUFFIX}", layout_paths::boot(INDEX_FILE))
}

/// One `[[entry]]` of the generated `INDEX.md` manifest.
#[derive(Debug, Serialize)]
struct IndexEntry {
    /// Path of the boot file, as composed by the engine.
    path: String,
    /// `"static"` — read the file directly — or `"dynamic"` — an INCLUDE
    /// the agent resolves at boot.
    kind: &'static str,
    /// Activation condition for a `dynamic` entry (PROP-009 §2.3) — the
    /// wire string `"os:<name>"`. `None` on a `static` entry or an
    /// unconditional `dynamic` one.
    #[serde(skip_serializing_if = "Option::is_none")]
    when: Option<String>,
}

/// The serialised shape of `INDEX.md`.
#[derive(Debug, Serialize)]
struct IndexManifest {
    schema: u32,
    #[serde(rename = "static", skip_serializing_if = "Option::is_none")]
    static_lane: Option<String>,
    #[serde(rename = "entry", skip_serializing_if = "Vec::is_empty")]
    entries: Vec<IndexEntry>,
}

/// Render the `INDEX.md` TOML manifest for a node's effective boot.
///
/// Pure — the manifest is paths and kinds, no file content. The `static`
/// pointer is present exactly when `boot` has `static`-linked entries.
/// Serialisation is structurally infallible with today's fixed manifest
/// shape; the error is routed anyway so a future shape change degrades
/// to a diagnosis instead of a panic.
pub fn render_index(
    boot: &EffectiveBoot,
    fingerprint: Option<&str>,
) -> Result<String, WorkspaceError> {
    render_index_with_spec_format(boot, fingerprint, SpecFormat::Mixed)
}

/// Render `INDEX.md` with its static pointer following the target format.
pub fn render_index_with_spec_format(
    boot: &EffectiveBoot,
    fingerprint: Option<&str>,
    spec_format: SpecFormat,
) -> Result<String, WorkspaceError> {
    let prepared = publication::prepare_index(boot, spec_format)?;
    Ok(publication::finish_index(prepared, fingerprint, None))
}

pub(super) fn prepare_index_body(
    boot: &EffectiveBoot,
    spec_format: SpecFormat,
) -> Result<String, WorkspaceError> {
    let has_static = boot.static_entries().next().is_some();
    let manifest = IndexManifest {
        schema: INDEX_SCHEMA,
        static_lane: has_static.then(|| static_path(spec_format).to_string()),
        entries: boot
            .dynamic_entries()
            .map(|e| IndexEntry {
                path: e.path.clone(),
                // Every INDEX entry is dynamically linked (read by reference);
                // its read-timing derives from `when` — a conditional entry is
                // a gated INCLUDE ("dynamic"), an unconditional one is read
                // directly ("static"). PROP-009 §2.3.
                kind: if e.when.is_some() {
                    "dynamic"
                } else {
                    "static"
                },
                when: e.when.as_ref().map(ToString::to_string),
            })
            .collect(),
    };
    let body = toml::to_string_pretty(&manifest).map_err(|e| WorkspaceError::IndexRender {
        reason: e.to_string(),
    })?;
    Ok(body)
}

/// Render `STATIC.md` — the concatenation of the `static`-linked
/// contributions, in composed order. Returns `None` when the node has no
/// static contributions (no `STATIC.md` is generated then).
///
/// A `simple` contribution is carried whole — no tree-shaking, no alias
/// resolution (PROP-035 §3's sense of "verbatim"), though the emitted text
/// is NOT byte-identical to the source: `#embed`s expand, anchors/links
/// qualify, trailing whitespace trims, and the generated framing wraps it.
/// A `normal`
/// one is **compiled** to its `#use`/`#source`-resolved, tree-shaken closure
/// (PROP-035 §8, the compiler's whole-artifact normal input) — so a `normal + static` edge bakes
/// in only what the contract actually reaches, merged, in dependency order,
/// rather than the whole file. `workspace_root` resolves each contribution's
/// path (and every `spec://` a `normal` closure walks) against the
/// materialised dependency tree.
pub fn render_static(
    boot: &EffectiveBoot,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
) -> Result<Option<String>, WorkspaceError> {
    render_static_with_spec_format(boot, workspace_root, self_coord, SpecFormat::Mixed)
}

/// Render the static lane in the project's effective target format.
///
/// This entry has no extension world to scope a plan by, so it pins the
/// empty plan — the historical schedule, bytes and errors exactly
/// (`R4-TRANSFORM-PLAN-ABI` §7). The install path, which does hold a world,
/// goes through [`render_static_observed`].
pub fn render_static_with_spec_format(
    boot: &EffectiveBoot,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    spec_format: SpecFormat,
) -> Result<Option<String>, WorkspaceError> {
    render_static_observed(
        boot,
        workspace_root,
        self_coord,
        spec_format,
        None,
        TransformPlan::empty(),
    )
}

/// [`render_static_with_spec_format`] through one not-yet-acquired trace
/// occurrence. `acquisition` is the borrowed run plus the base identity a
/// traced caller minted for THIS artifact; the occurrence itself is acquired
/// at the compile boundary inside. `None` is the historical untraced path,
/// byte-for-byte.
///
/// `transforms` is the lane owner's own transform plan (R4 architecture §5.1:
/// activation authority follows the artifact being written), already lowered
/// by the caller that holds the world. The per-unit path passes THAT
/// package's view; a caller with no world passes
/// [`TransformPlan::empty`].
pub(crate) fn render_static_observed(
    boot: &EffectiveBoot,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    spec_format: SpecFormat,
    acquisition: Option<&ScopeAcquisition<'_>>,
    transforms: TransformPlan,
) -> Result<Option<String>, WorkspaceError> {
    let compiled = compile_static_artifact_with(
        boot,
        workspace_root,
        self_coord,
        spec_format,
        acquisition,
        transforms,
        None,
        compile_artifact,
    )?;
    compiled
        .map(|compiled| {
            String::from_utf8(compiled.artifact.into_bytes()).map_err(|error| {
                WorkspaceError::InlineCompile {
                    reason: format!(
                        "the built-in STATIC backend returned non-UTF-8 bytes: {error}"
                    ),
                }
            })
        })
        .transpose()
}

/// Compile one node's static lane exactly once, traced or not.
///
/// The trace law of this seam (R3.4): no static entries means no scope AND no
/// compiler, exactly as before; an acquisition present means the occurrence is
/// taken **at the compile boundary** — after every fallible preparation step,
/// immediately before the ONE compiler call — and that call runs through the
/// resulting sink ([`compile_artifact_traced`]), its result supplying both the
/// scope's terminal word and the artifact; no acquisition means the historical
/// `compiler` path, exactly once. A compiler failure fails the scope and then
/// returns the ORIGINAL error mapping unchanged; a later transaction failure
/// may legitimately leave the scope `compiled` (the command owner finalises
/// the run).
///
/// Acquiring here rather than in the caller is the point: an input that cannot
/// be built and a plan the compiler refuses to accept both return before a
/// scope exists, so no pre-compiler refusal can leave a pending occurrence for
/// work that was never attempted.
///
/// The injected `compiler` is the seam the characterization tests use; it is
/// consulted only on the unobserved, untraced path — the traced and
/// observed paths are always the real built-in schedule, because that is
/// the schedule a trace certifies and the one whose evidence the analyzer
/// reports.
///
/// The `observer` is the R4.3 analyzer seam, threaded beside the trace
/// acquisition exactly as T10C threaded the owner plan: `None` is every
/// write path's historical behavior, `Some` hands the same compile's
/// attribution evidence to one in-process observer and changes no byte
/// of the result.
// The observer is one argument past the lint's threshold, same shape as
// the two wrappers above: the other seven are the emission inputs this
// entry already took before R4.3.
#[allow(clippy::too_many_arguments)]
pub(crate) fn compile_static_artifact_with(
    boot: &EffectiveBoot,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    spec_format: SpecFormat,
    acquisition: Option<&ScopeAcquisition<'_>>,
    transforms: TransformPlan,
    observer: Option<std::sync::Arc<dyn vibe_spec::CompileObserver>>,
    compiler: impl FnOnce(
        ArtifactPlan,
        &FsSectionSource,
    ) -> Result<EmittedArtifact, ArtifactCompileError>,
) -> Result<Option<StaticCompile>, WorkspaceError> {
    let entries: Vec<_> = boot.static_entries().collect();
    if entries.is_empty() {
        return Ok(None);
    }
    let (inputs, providers) = inputs::build_with_providers(entries, workspace_root, self_coord)?;
    let target = if matches!(spec_format, SpecFormat::Xml) {
        ArtifactTarget::StaticXml
    } else {
        ArtifactTarget::StaticMarkdown
    };
    let plan = ArtifactPlan::static_lane(
        target,
        static_path(spec_format),
        layout_paths::vibedeps(""),
        inputs,
    )
    .map_err(|error| WorkspaceError::InlineCompile {
        reason: error.to_string(),
    })?
    // The owner-scoped plan of the lane being written. An empty plan adds no
    // pass, so this attachment is byte-inert for every owner that declares
    // no compile-point extension — which is every owner in this repository.
    .with_transforms(transforms);
    let source = FsSectionSource::new(FileResolver::new(workspace_root, self_coord.clone()));
    // THE COMPILE BOUNDARY. Every fallible preparation above has completed;
    // the next thing that happens is the compiler. Only now is the occurrence
    // acquired — and a refusal to declare it simply compiles untraced.
    let scope = acquisition.and_then(ScopeAcquisition::acquire);
    // The ONE compiler call: through the observer when analyzing, through
    // the acquired sink when tracing, through the historical path when
    // neither. Its result — never a second compile — supplies the scope's
    // terminal word, the observer's evidence and the artifact.
    let compiled = match (observer, &scope) {
        (Some(observer), _) => vibe_spec::compile_artifact_observed(plan, &source, observer),
        (None, Some(scope)) => compile_artifact_traced(plan, &source, scope),
        (None, None) => compiler(plan, &source),
    };
    match compiled {
        Ok(artifact) => {
            if let Some(scope) = &scope {
                scope.complete_lossy(&artifact.output_fingerprint());
            }
            Ok(Some(StaticCompile {
                artifact,
                providers,
            }))
        }
        Err(error) => {
            if let Some(scope) = &scope {
                scope.fail_lossy(&error.to_string());
            }
            let reason = match error {
                ArtifactCompileError::Input { input, source }
                    if input.kind == ArtifactInputType::Normal =>
                {
                    format!(
                        "compiling the normal package `{}` closure (PROP-035 §8): {source}",
                        input.origin
                    )
                }
                error => error.to_string(),
            };
            Err(WorkspaceError::InlineCompile { reason })
        }
    }
}

/// What [`write_boot_artifacts`] wrote — for the caller to report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WrittenArtifacts {
    /// Absolute path of the generated `INDEX.md` — always written.
    pub index: PathBuf,
    /// Absolute path of the generated `STATIC.md`, when the node had
    /// static contributions; `None` otherwise.
    pub static_lane: Option<PathBuf>,
    /// Absolute paths of the instruction files whose `<vibevm>` block was
    /// written or updated this run; a file already carrying an identical
    /// block is not listed (PROP-012).
    pub redirects: Vec<PathBuf>,
}

/// Generate and write a node's boot artifacts (PROP-009 §2.3): `INDEX.md`
/// always, `STATIC.md` when the node has static contributions, and the
/// `CLAUDE.md` / `AGENTS.md` / `GEMINI.md` redirects.
///
/// `node_dir` is the node's root; `workspace_root` is the absolute
/// workspace root, used to resolve the static contributions' content;
/// `self_coord` is the workspace root's own `<group>/<name>` coordinate
/// (B-031 — the host is a package coordinate), the authority a `spec://`
/// address names to reach the authored specs tree. A stale `STATIC.md`
/// from an earlier generation is removed when the node no longer has static
/// contributions, so it is never read by mistake.
#[spec(
    implements = "spec://org.vibevm.core/vibevm/modules/vibe-workspace/PROP-012#co-tenant",
    r = 1
)]
pub fn write_boot_artifacts(
    node_dir: &Path,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    boot: &EffectiveBoot,
) -> Result<WrittenArtifacts, WorkspaceError> {
    write_boot_artifacts_with_spec_format(
        node_dir,
        workspace_root,
        self_coord,
        boot,
        SpecFormat::Mixed,
    )
}

/// Generate boot artifacts with the static lane following `spec_format`.
///
/// No extension world reaches this entry, so the node lane it writes carries
/// the empty plan — the historical schedule and bytes exactly. The install
/// path goes through [`write_boot_artifacts_traced`], which does hold one.
pub fn write_boot_artifacts_with_spec_format(
    node_dir: &Path,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    boot: &EffectiveBoot,
    spec_format: SpecFormat,
) -> Result<WrittenArtifacts, WorkspaceError> {
    write_boot_artifacts_inner(
        node_dir,
        workspace_root,
        self_coord,
        boot,
        spec_format,
        None,
        TransformPlan::empty(),
    )
}

/// The traced sibling: one borrowed run, carried through this node's static
/// compile. `node_rel` is the node's canonical workspace-relative path (`.`)
/// — the portable identity the trace records, never `node_dir`. A recorder
/// absent, or a node with no static entries, compiles exactly as the wrapper
/// above; a recorder present mints the base identity here and the occurrence
/// is acquired at the compile boundary below, completing from the compiler's
/// own result. The run is borrowed: this layer never opens or finishes it.
///
/// `transforms` is this NODE's own owner-scoped plan (R4 architecture §5.1:
/// a node manifest activates its node lane), lowered by the caller that
/// holds the durable world.
// The owner plan is one argument past the lint's threshold; the other seven
// are the emission inputs this entry already took before T10B.
#[allow(clippy::too_many_arguments)]
pub(crate) fn write_boot_artifacts_traced(
    node_dir: &Path,
    node_rel: &str,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    boot: &EffectiveBoot,
    spec_format: SpecFormat,
    trace: Option<&TraceRun>,
    transforms: TransformPlan,
) -> Result<WrittenArtifacts, WorkspaceError> {
    // A node with no static contributions declares no scope at all, and the
    // base identity is only minted when a recorder is present, so off mode
    // allocates no id or label strings.
    let acquisition = trace
        .filter(|_| boot.static_entries().next().is_some())
        .map(|run| ScopeAcquisition::node(run, node_rel, spec_format));
    write_boot_artifacts_inner(
        node_dir,
        workspace_root,
        self_coord,
        boot,
        spec_format,
        acquisition.as_ref(),
        transforms,
    )
}

// Same shape as its two wrappers: the owner plan is the one addition.
#[allow(clippy::too_many_arguments)]
fn write_boot_artifacts_inner(
    node_dir: &Path,
    workspace_root: &Path,
    self_coord: &SelfCoordinate,
    boot: &EffectiveBoot,
    spec_format: SpecFormat,
    acquisition: Option<&ScopeAcquisition<'_>>,
    transforms: TransformPlan,
) -> Result<WrittenArtifacts, WorkspaceError> {
    // Compile every fallible semantic artifact before touching existing files.
    // INDEX rendering precedes the compiler and may refuse — which is exactly
    // why the trace occurrence is NOT acquired here: it is taken inside, at
    // the compile boundary, so a refusal on this line declares nothing.
    let index_text = render_index_with_spec_format(boot, None, spec_format)?;
    let static_artifact = compile_static_artifact_with(
        boot,
        workspace_root,
        self_coord,
        spec_format,
        acquisition,
        transforms,
        None,
        compile_artifact,
    )?
    .map(|compiled| compiled.artifact);
    let boot_dir = node_dir.join(layout::current_boot_dir());

    // INDEX.md — always. A node carries no fingerprint (byte-stable); the
    // per-unit dirty-subgraph (PROP-038 §2.8) is emit-side, in `hybrid_emit`.
    let index = boot_dir.join(INDEX_FILE);

    // The selected STATIC artifact — only when there are static contributions.
    // The generator owns both spellings and always removes the unselected one.
    let static_path = boot_dir.join(static_file(spec_format));
    let stale_path = boot_dir.join(stale_static_file(spec_format));
    let redirects = transaction::write_production_with_selectors(
        transaction::ArtifactWrite {
            index_path: &index,
            index_bytes: index_text.as_bytes(),
            static_path: &static_path,
            static_bytes: static_artifact.as_ref().map(EmittedArtifact::bytes),
            stale_path: &stale_path,
        },
        |transaction| {
            redirect::write_redirect_blocks_with_transaction(node_dir, spec_format, transaction)
        },
    )?;
    let static_lane = static_artifact.map(|_| static_path);

    Ok(WrittenArtifacts {
        index,
        static_lane,
        redirects,
    })
}

fn io_err(path: &Path, error: std::io::Error) -> WorkspaceError {
    WorkspaceError::Io {
        path: path.to_path_buf(),
        reason: error.to_string(),
    }
}

#[cfg(test)]
#[path = "boot_artifacts/tests.rs"]
mod tests;

#[cfg(test)]
#[path = "boot_artifacts/tests_inheritance_parity.rs"]
mod tests_inheritance_parity;

#[cfg(test)]
#[path = "boot_artifacts/tests_ir_characterization.rs"]
mod tests_ir_characterization;

#[cfg(test)]
#[path = "boot_artifacts/tests_qualify.rs"]
mod tests_qualify;

#[cfg(test)]
#[path = "boot_artifacts/native_managed_tests.rs"]
pub(crate) mod native_managed_tests;
