//! Generated boot artifacts — `INLINE.md`, `INDEX.md`, the redirect.
//!
//! PROP-009 §2.3. The computed-view engine ([`crate::boot`]) produces an
//! [`EffectiveBoot`]; this module projects it into the files an AI agent
//! reads at session start:
//!
//! - **`INLINE.md`** — the verbatim concatenation, in composed order, of
//!   every `inline`-linked contribution. Read first — the priority lane.
//!   Generated only when the node has inline contributions.
//! - **`INDEX.md`** — a generated TOML manifest: a `schema` version, an
//!   `inline` pointer (when an `INLINE.md` exists), and an ordered list of
//!   `[[entry]]` tables, each with a `path` and a `kind` (`static` /
//!   `dynamic`). Always generated.
//! - **The redirect** — a managed `<vibevm>` block (PROP-012) inside each
//!   of `CLAUDE.md` / `AGENTS.md` / `GEMINI.md`, pointing a session at
//!   `INLINE.md` then `INDEX.md`. vibevm owns only the block; the rest of
//!   each file belongs to the developer and any other tool and is
//!   preserved verbatim.
//!
//! `INLINE.md` and `INDEX.md` are git-tracked and carry a "generated — do
//! not edit" header. Boot stays pure file-reading — the redirect points
//! at files, it never becomes "run `vibe`".
//!
//! ## `when` on dynamic entries
//!
//! A `[boot_snippet]` may carry a `when` condition (PROP-009 §2.4 / §2.6).
//! The computed-view engine renders such a contribution as a `dynamic`
//! entry, and [`render_index`] writes the condition into the `INDEX.md`
//! `[[entry]]` as `when = "os:<name>"`. The agent evaluates it at boot: it
//! reads a `dynamic` entry's file only when the condition holds for the
//! session's operating system. The committed `INDEX.md` is therefore
//! OS-invariant — every entry is listed, and the OS test happens at read
//! time. A `dynamic` entry without `when` is an unconditional INCLUDE —
//! still valid.

specmark::scope!("spec://vibevm/modules/vibe-workspace/PROP-009#artifacts");

use std::fs;
use std::path::{Path, PathBuf};

use serde::Serialize;
use specmark::spec;
use vibe_core::manifest::LinkType;

use crate::WorkspaceError;
use crate::boot::EffectiveBoot;

/// `schema` version of the generated `INDEX.md` manifest (PROP-009 §2.3).
pub const INDEX_SCHEMA: u32 = 1;

/// Generated-artifact filenames, relative to a node's `spec/boot/`.
pub const INLINE_FILE: &str = "INLINE.md";
/// See [`INLINE_FILE`].
pub const INDEX_FILE: &str = "INDEX.md";

/// The agent instruction files a node carries at its root. vibevm owns
/// only a `<vibevm>` block inside each (PROP-012); the rest of every file
/// belongs to the developer and any other tool sharing it.
pub const REDIRECT_FILES: &[&str] = &["CLAUDE.md", "AGENTS.md", "GEMINI.md"];

/// The opening marker of vibevm's managed block (PROP-012 §2.2), matched
/// as a whole trimmed line.
pub const BLOCK_OPEN: &str = "<vibevm>";

/// The closing marker of vibevm's managed block — see [`BLOCK_OPEN`].
pub const BLOCK_CLOSE: &str = "</vibevm>";

/// The header line of the pre-PROP-012 whole-file generated redirect. A
/// file carrying no `<vibevm>` markers but beginning with this line was
/// wholly vibevm's, and is migrated to a managed block wholesale
/// (PROP-012 §4).
const OLD_GENERATED_HEADER: &str =
    "<!-- Generated by vibe — do not edit. This file is overwritten on `vibe install`. -->";

const INDEX_HEADER: &str = "\
# spec/boot/INDEX.md — generated by vibe, do not edit.
# The computed boot sequence (PROP-009 §2.3). Read every file the
# `[[entry]]` list names, in order.
#
# A `kind = \"static\"` entry: read the file directly. A `kind = \"dynamic\"`
# entry: an INCLUDE resolved at boot — when it also carries
# `when = \"os:<name>\"`, read the file only if the session's operating
# system is <name> (windows / macos / linux), and skip it otherwise.

";

const INLINE_HEADER: &str = "\
<!-- spec/boot/INLINE.md — generated by vibe, do not edit. -->
<!-- The inline boot lane (PROP-009 §2.3): the highest-priority -->
<!-- contributions, concatenated verbatim. Read this first, in full. -->

";

/// The body of vibevm's managed block — the text between the `<vibevm>`
/// markers. PROP-012 §2.5: the payload is the PROP-009 §2.3 redirect,
/// unchanged; only the envelope (a fenced region of a shared file) is new.
const BLOCK_BODY: &str = "\
<!-- Generated by vibe — do not edit inside this block; it is rewritten on `vibe install`. Text outside the <vibevm> markers is yours. -->

# Session boot

This project's boot sequence is computed by vibe (the PROP-009 loading
model). To begin a session, read these files in order:

1. `spec/boot/INLINE.md` — if it exists. The priority lane: read it first
   and in full.
2. `spec/boot/INDEX.md` — a generated TOML manifest. Read every file named
   by its `[[entry]]` tables, in the listed order. A `kind = \"static\"`
   entry is read directly; a `kind = \"dynamic\"` entry is an INCLUDE
   resolved at boot, and one carrying a `when` condition is read only when
   that condition holds for the current session.

Boot is pure file-reading — there is nothing to execute.";

/// One `[[entry]]` of the generated `INDEX.md` manifest.
#[derive(Debug, Serialize)]
struct IndexEntry {
    /// Path of the boot file, as composed by the engine.
    path: String,
    /// `"static"` — read the file directly — or `"dynamic"` — an INCLUDE
    /// the agent resolves at boot.
    kind: &'static str,
    /// Activation condition for a `dynamic` entry (PROP-009 §2.3) — the
    /// wire string `"os:<name>"`. `None` on a `static` entry or an
    /// unconditional `dynamic` one.
    #[serde(skip_serializing_if = "Option::is_none")]
    when: Option<String>,
}

/// The serialised shape of `INDEX.md`.
#[derive(Debug, Serialize)]
struct IndexManifest {
    schema: u32,
    #[serde(skip_serializing_if = "Option::is_none")]
    inline: Option<String>,
    #[serde(rename = "entry", skip_serializing_if = "Vec::is_empty")]
    entries: Vec<IndexEntry>,
}

/// Render the `INDEX.md` TOML manifest for a node's effective boot.
///
/// Pure — the manifest is paths and kinds, no file content. The `inline`
/// pointer is present exactly when `boot` has `inline`-linked entries.
pub fn render_index(boot: &EffectiveBoot) -> String {
    let has_inline = boot.inline_entries().next().is_some();
    let manifest = IndexManifest {
        schema: INDEX_SCHEMA,
        inline: has_inline.then(|| format!("spec/boot/{INLINE_FILE}")),
        entries: boot
            .indexed_entries()
            .map(|e| IndexEntry {
                path: e.path.clone(),
                kind: match e.link {
                    LinkType::Static => "static",
                    LinkType::Dynamic => "dynamic",
                    LinkType::Inline => {
                        unreachable!("inline entries are excluded by indexed_entries()")
                    }
                },
                // `when` is meaningful only on a `dynamic` entry
                // (PROP-009 §2.3); a `static` entry is always read.
                when: match e.link {
                    LinkType::Dynamic => e.when.map(|w| w.to_string()),
                    _ => None,
                },
            })
            .collect(),
    };
    let body = toml::to_string_pretty(&manifest)
        .expect("the INDEX manifest is a fixed struct and always serialises");
    format!("{INDEX_HEADER}{body}")
}

/// Render `INLINE.md` — the verbatim concatenation of the `inline`-linked
/// contributions, in composed order. Returns `None` when the node has no
/// inline contributions (no `INLINE.md` is generated then).
///
/// `workspace_root` resolves each contribution's path to its content on
/// disk; the contributions live in the materialised `vibedeps/` tree.
pub fn render_inline(
    boot: &EffectiveBoot,
    workspace_root: &Path,
) -> Result<Option<String>, WorkspaceError> {
    let inline: Vec<_> = boot.inline_entries().collect();
    if inline.is_empty() {
        return Ok(None);
    }
    let mut out = String::from(INLINE_HEADER);
    for entry in inline {
        let abs = workspace_root.join(&entry.path);
        let content = fs::read_to_string(&abs).map_err(|e| io_err(&abs, e))?;
        // An HTML-comment provenance marker — invisible in rendered
        // markdown, so the concatenated content stays verbatim.
        out.push_str(&format!(
            "<!-- vibe:inline {} — {} -->\n\n",
            entry.origin, entry.path
        ));
        out.push_str(content.trim_end());
        out.push_str("\n\n");
    }
    Ok(Some(out))
}

/// The body of vibevm's managed redirect block — the text between the
/// `<vibevm>` markers (PROP-012 §2.5).
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#content",
    r = 1
)]
pub fn render_redirect() -> &'static str {
    BLOCK_BODY
}

/// The full managed block — the `<vibevm>` marker, the body, the
/// `</vibevm>` marker — as written into an instruction file. Ends with a
/// trailing newline so it slots cleanly into a file.
fn render_block() -> String {
    format!("{BLOCK_OPEN}\n{BLOCK_BODY}\n{BLOCK_CLOSE}\n")
}

/// Where vibevm's managed `<vibevm>` block sits in an instruction file
/// (PROP-012 §2.2–§2.3).
#[derive(Debug, Clone, PartialEq, Eq)]
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#markers",
    r = 1
)]
pub enum BlockLocation {
    /// No `<vibevm>` markers at all — the block is created on write (§2.3).
    Absent,
    /// Exactly one well-formed pair. `[start, end)` is the block's byte
    /// span — the first byte of the `<vibevm>` line to the byte after the
    /// `</vibevm>` line (its newline included when present).
    Present { start: usize, end: usize },
    /// The markers are malformed — not exactly one ordered pair. The
    /// string names the defect for the operator.
    Malformed(String),
}

/// Locate vibevm's managed block in `content` by a plain line scan: a
/// line whose trimmed text equals `<vibevm>` / `</vibevm>` is a marker
/// (PROP-012 §2.2). No markdown parse, no model — the detection that
/// gates a mutating write must be deterministic and trivial.
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#markers",
    r = 1
)]
pub fn locate_block(content: &str) -> BlockLocation {
    let mut open: Option<(usize, usize)> = None;
    let mut close: Option<(usize, usize)> = None;
    let mut opens = 0usize;
    let mut closes = 0usize;
    let mut offset = 0usize;
    for line in content.split_inclusive('\n') {
        let trimmed = line.strip_suffix('\n').unwrap_or(line).trim();
        if trimmed == BLOCK_OPEN {
            opens += 1;
            open.get_or_insert((offset, offset + line.len()));
        } else if trimmed == BLOCK_CLOSE {
            closes += 1;
            close.get_or_insert((offset, offset + line.len()));
        }
        offset += line.len();
    }
    match (opens, closes) {
        (0, 0) => BlockLocation::Absent,
        (1, 1) => {
            let (open_start, _) = open.expect("opens == 1, so an open marker was recorded");
            let (close_start, close_end) =
                close.expect("closes == 1, so a close marker was recorded");
            if open_start < close_start {
                BlockLocation::Present {
                    start: open_start,
                    end: close_end,
                }
            } else {
                BlockLocation::Malformed(
                    "the `</vibevm>` marker precedes its `<vibevm>` opener".to_string(),
                )
            }
        }
        (opens, closes) => BlockLocation::Malformed(format!(
            "expected exactly one `<vibevm>` … `</vibevm>` pair, found {opens} `<vibevm>` \
             and {closes} `</vibevm>` marker line(s)"
        )),
    }
}

/// Write vibevm's managed block into the instruction file at `path`
/// (PROP-012 §2.3). Returns the path when the file changed, or `None`
/// when it already carried a byte-identical block (no write — no churn).
///
/// Absent markers → append a fresh block at end of file, preserving every
/// existing byte (or, when the whole file is the pre-PROP-012 generated
/// redirect, replace it wholesale — PROP-012 §4); a missing file is
/// created. Present → splice the new body between the markers, touching
/// nothing outside them. Malformed → [`WorkspaceError::MalformedRedirectBlock`]
/// without writing — callers validate at plan time (PROP-012 §2.4), so
/// this is the defensive last line.
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#create",
    r = 1
)]
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#migration",
    r = 1
)]
fn write_managed_block(path: &Path) -> Result<Option<PathBuf>, WorkspaceError> {
    let existing = match fs::read_to_string(path) {
        Ok(s) => Some(s),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
        Err(e) => return Err(io_err(path, e)),
    };
    let block = render_block();
    let new_content = match &existing {
        None => block,
        Some(content) => match locate_block(content) {
            BlockLocation::Malformed(reason) => {
                return Err(WorkspaceError::MalformedRedirectBlock {
                    path: path.to_path_buf(),
                    reason,
                });
            }
            BlockLocation::Present { start, end } => {
                let mut out = String::with_capacity(content.len());
                out.push_str(&content[..start]);
                out.push_str(&block);
                out.push_str(&content[end..]);
                out
            }
            BlockLocation::Absent => {
                if content.trim().is_empty()
                    || content.trim_start().starts_with(OLD_GENERATED_HEADER)
                {
                    // An empty file, or the pre-PROP-012 whole-file
                    // generated redirect — the file was vibevm's, so
                    // reclaim it as a block (PROP-012 §4).
                    block
                } else {
                    // Co-tenant content — append the block after it,
                    // preserving every existing byte (PROP-012 §2.3).
                    let mut out = content.clone();
                    if !out.ends_with('\n') {
                        out.push('\n');
                    }
                    out.push('\n');
                    out.push_str(&block);
                    out
                }
            }
        },
    };
    if existing.as_deref() == Some(new_content.as_str()) {
        return Ok(None);
    }
    fs::write(path, &new_content).map_err(|e| io_err(path, e))?;
    Ok(Some(path.to_path_buf()))
}

/// Write vibevm's managed `<vibevm>` block into every agent instruction
/// file ([`REDIRECT_FILES`]) of the node rooted at `node_dir` (PROP-012).
/// Returns the files actually written — a file already carrying an
/// identical block is left untouched.
pub fn write_redirect_blocks(node_dir: &Path) -> Result<Vec<PathBuf>, WorkspaceError> {
    let mut written = Vec::new();
    for name in REDIRECT_FILES {
        if let Some(path) = write_managed_block(&node_dir.join(name))? {
            written.push(path);
        }
    }
    Ok(written)
}

/// What [`write_boot_artifacts`] wrote — for the caller to report.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct WrittenArtifacts {
    /// Absolute path of the generated `INDEX.md` — always written.
    pub index: PathBuf,
    /// Absolute path of the generated `INLINE.md`, when the node had
    /// inline contributions; `None` otherwise.
    pub inline: Option<PathBuf>,
    /// Absolute paths of the instruction files whose `<vibevm>` block was
    /// written or updated this run; a file already carrying an identical
    /// block is not listed (PROP-012).
    pub redirects: Vec<PathBuf>,
}

/// Generate and write a node's boot artifacts (PROP-009 §2.3): `INDEX.md`
/// always, `INLINE.md` when the node has inline contributions, and the
/// `CLAUDE.md` / `AGENTS.md` / `GEMINI.md` redirects.
///
/// `node_dir` is the node's root; `workspace_root` is the absolute
/// workspace root, used to resolve the inline contributions' content. A
/// stale `INLINE.md` from an earlier generation is removed when the node
/// no longer has inline contributions, so it is never read by mistake.
#[spec(
    implements = "spec://vibevm/modules/vibe-workspace/PROP-012#co-tenant",
    r = 1
)]
pub fn write_boot_artifacts(
    node_dir: &Path,
    workspace_root: &Path,
    boot: &EffectiveBoot,
) -> Result<WrittenArtifacts, WorkspaceError> {
    let boot_dir = node_dir.join("spec").join("boot");
    fs::create_dir_all(&boot_dir).map_err(|e| io_err(&boot_dir, e))?;

    // INDEX.md — always.
    let index = boot_dir.join(INDEX_FILE);
    fs::write(&index, render_index(boot)).map_err(|e| io_err(&index, e))?;

    // INLINE.md — only when there are inline contributions.
    let inline_path = boot_dir.join(INLINE_FILE);
    let inline = match render_inline(boot, workspace_root)? {
        Some(text) => {
            fs::write(&inline_path, text).map_err(|e| io_err(&inline_path, e))?;
            Some(inline_path)
        }
        None => {
            if inline_path.exists() {
                fs::remove_file(&inline_path).map_err(|e| io_err(&inline_path, e))?;
            }
            None
        }
    };

    // The redirects — vibevm's managed `<vibevm>` block in each (PROP-012).
    // Only the block is written; co-tenant content is preserved, and a
    // file already carrying an identical block is left untouched.
    let redirects = write_redirect_blocks(node_dir)?;

    Ok(WrittenArtifacts {
        index,
        inline,
        redirects,
    })
}

/// Build a [`WorkspaceError::Io`] from a `std::io::Error` and its path.
fn io_err(path: &Path, e: std::io::Error) -> WorkspaceError {
    WorkspaceError::Io {
        path: path.to_path_buf(),
        reason: e.to_string(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::boot::{BootBand, BootEntry};
    use specmark::verifies;
    use tempfile::TempDir;
    use vibe_core::manifest::{TargetOs, WhenCondition};

    fn entry(path: &str, link: LinkType, origin: &str) -> BootEntry {
        BootEntry {
            path: path.to_string(),
            band: BootBand::Dependency,
            link,
            when: None,
            origin: origin.to_string(),
        }
    }

    /// A `BootEntry` with an explicit link and `when` — for exercising the
    /// `INDEX.md` rendering of conditional entries directly.
    fn entry_when(
        path: &str,
        link: LinkType,
        when: Option<WhenCondition>,
        origin: &str,
    ) -> BootEntry {
        BootEntry {
            path: path.to_string(),
            band: BootBand::Dependency,
            link,
            when,
            origin: origin.to_string(),
        }
    }

    fn boot(entries: Vec<BootEntry>) -> EffectiveBoot {
        EffectiveBoot { entries }
    }

    #[test]
    fn render_index_of_empty_boot_is_just_the_schema() {
        let text = render_index(&boot(vec![]));
        let parsed: toml::Value = toml::from_str(&text).unwrap();
        assert_eq!(parsed.get("schema").unwrap().as_integer(), Some(1));
        assert!(parsed.get("inline").is_none());
        assert!(parsed.get("entry").is_none());
    }

    #[test]
    fn render_index_carries_static_and_dynamic_entries_in_order() {
        let b = boot(vec![
            entry("spec/boot/00-core.md", LinkType::Static, "."),
            entry(
                "vibedeps/stack-rust/2.1.0/boot/rust.md",
                LinkType::Dynamic,
                "stack:rust",
            ),
        ]);
        let text = render_index(&b);
        assert!(text.contains("generated by vibe, do not edit"));
        let parsed: toml::Value = toml::from_str(&text).unwrap();
        let entries = parsed.get("entry").unwrap().as_array().unwrap();
        assert_eq!(entries.len(), 2);
        assert_eq!(
            entries[0].get("path").unwrap().as_str(),
            Some("spec/boot/00-core.md")
        );
        assert_eq!(entries[0].get("kind").unwrap().as_str(), Some("static"));
        assert_eq!(entries[1].get("kind").unwrap().as_str(), Some("dynamic"));
    }

    #[test]
    fn render_index_inline_pointer_present_only_with_inline_entries() {
        let without = render_index(&boot(vec![entry(
            "spec/boot/00-core.md",
            LinkType::Static,
            ".",
        )]));
        assert!(!without.contains("inline ="));

        let with = render_index(&boot(vec![entry(
            "vibedeps/flow-crit/1.0.0/boot.md",
            LinkType::Inline,
            "flow:crit",
        )]));
        let parsed: toml::Value = toml::from_str(&with).unwrap();
        assert_eq!(
            parsed.get("inline").unwrap().as_str(),
            Some("spec/boot/INLINE.md")
        );
    }

    #[test]
    fn render_index_emits_when_on_a_dynamic_entry() {
        let b = boot(vec![entry_when(
            "vibedeps/stack-windows/1.0.0/boot.md",
            LinkType::Dynamic,
            Some(WhenCondition::Os(TargetOs::Windows)),
            "stack:windows",
        )]);
        let text = render_index(&b);
        // The header documents the OS test for the agent.
        assert!(text.contains("(windows / macos / linux)"), "{text}");
        let parsed: toml::Value = toml::from_str(&text).unwrap();
        let e = &parsed.get("entry").unwrap().as_array().unwrap()[0];
        assert_eq!(e.get("kind").unwrap().as_str(), Some("dynamic"));
        assert_eq!(e.get("when").unwrap().as_str(), Some("os:windows"));
    }

    #[test]
    fn render_index_dynamic_without_when_omits_the_key() {
        let b = boot(vec![entry_when(
            "vibedeps/stack-rust/2.1.0/boot.md",
            LinkType::Dynamic,
            None,
            "stack:rust",
        )]);
        let parsed: toml::Value = toml::from_str(&render_index(&b)).unwrap();
        let e = &parsed.get("entry").unwrap().as_array().unwrap()[0];
        assert_eq!(e.get("kind").unwrap().as_str(), Some("dynamic"));
        assert!(
            e.get("when").is_none(),
            "an unconditional dynamic entry carries no `when`"
        );
    }

    #[test]
    fn render_index_never_emits_when_on_a_static_entry() {
        // Defensive: the engine never produces a `static` entry carrying a
        // `when` (a condition forces `dynamic`), but the renderer drops a
        // stray one rather than emit an incoherent `static` + `when`.
        let b = boot(vec![entry_when(
            "spec/boot/00-core.md",
            LinkType::Static,
            Some(WhenCondition::Os(TargetOs::Linux)),
            ".",
        )]);
        let parsed: toml::Value = toml::from_str(&render_index(&b)).unwrap();
        let e = &parsed.get("entry").unwrap().as_array().unwrap()[0];
        assert_eq!(e.get("kind").unwrap().as_str(), Some("static"));
        assert!(
            e.get("when").is_none(),
            "a static entry must not carry `when`"
        );
    }

    #[test]
    fn render_inline_is_none_without_inline_entries() {
        let ws = TempDir::new().unwrap();
        let b = boot(vec![entry("spec/boot/00-core.md", LinkType::Static, ".")]);
        assert!(render_inline(&b, ws.path()).unwrap().is_none());
    }

    #[test]
    fn render_inline_concatenates_contributions_verbatim() {
        let ws = TempDir::new().unwrap();
        let crit = ws.path().join("vibedeps/flow-crit/1.0.0/boot.md");
        fs::create_dir_all(crit.parent().unwrap()).unwrap();
        fs::write(&crit, "# Critical discipline\n\nAlways do the thing.").unwrap();

        let b = boot(vec![entry(
            "vibedeps/flow-crit/1.0.0/boot.md",
            LinkType::Inline,
            "flow:crit",
        )]);
        let text = render_inline(&b, ws.path()).unwrap().unwrap();
        assert!(text.contains("generated by vibe, do not edit"));
        assert!(text.contains("<!-- vibe:inline flow:crit"));
        assert!(text.contains("# Critical discipline"));
        assert!(text.contains("Always do the thing."));
    }

    #[test]
    fn render_inline_errors_on_a_missing_contribution() {
        let ws = TempDir::new().unwrap();
        let b = boot(vec![entry(
            "vibedeps/flow-gone/1.0.0/boot.md",
            LinkType::Inline,
            "flow:gone",
        )]);
        let err = render_inline(&b, ws.path()).unwrap_err();
        assert!(matches!(err, WorkspaceError::Io { .. }), "{err}");
    }

    #[test]
    fn render_redirect_points_at_the_boot_files() {
        let r = render_redirect();
        assert!(r.contains("do not edit"));
        assert!(r.contains("spec/boot/INLINE.md"));
        assert!(r.contains("spec/boot/INDEX.md"));
    }

    #[test]
    fn write_boot_artifacts_writes_index_and_redirects() {
        let ws = TempDir::new().unwrap();
        let b = boot(vec![entry("spec/boot/00-core.md", LinkType::Static, ".")]);
        let written = write_boot_artifacts(ws.path(), ws.path(), &b).unwrap();

        assert!(written.index.is_file());
        assert!(written.inline.is_none());
        assert!(!ws.path().join("spec/boot/INLINE.md").exists());
        assert_eq!(written.redirects.len(), 3);
        for name in REDIRECT_FILES {
            assert!(ws.path().join(name).is_file(), "{name} must be written");
        }
    }

    #[test]
    fn write_boot_artifacts_writes_inline_when_present() {
        let ws = TempDir::new().unwrap();
        let crit = ws.path().join("vibedeps/flow-crit/1.0.0/boot.md");
        fs::create_dir_all(crit.parent().unwrap()).unwrap();
        fs::write(&crit, "# discipline").unwrap();

        let b = boot(vec![entry(
            "vibedeps/flow-crit/1.0.0/boot.md",
            LinkType::Inline,
            "flow:crit",
        )]);
        let written = write_boot_artifacts(ws.path(), ws.path(), &b).unwrap();
        assert!(written.inline.is_some());
        assert!(ws.path().join("spec/boot/INLINE.md").is_file());
    }

    #[test]
    fn write_boot_artifacts_removes_a_stale_inline() {
        let ws = TempDir::new().unwrap();
        let crit = ws.path().join("vibedeps/flow-crit/1.0.0/boot.md");
        fs::create_dir_all(crit.parent().unwrap()).unwrap();
        fs::write(&crit, "# discipline").unwrap();

        // First generation has an inline contribution.
        let with_inline = boot(vec![entry(
            "vibedeps/flow-crit/1.0.0/boot.md",
            LinkType::Inline,
            "flow:crit",
        )]);
        write_boot_artifacts(ws.path(), ws.path(), &with_inline).unwrap();
        assert!(ws.path().join("spec/boot/INLINE.md").exists());

        // A later generation has none — the stale INLINE.md must go.
        let without = boot(vec![entry("spec/boot/00-core.md", LinkType::Static, ".")]);
        let written = write_boot_artifacts(ws.path(), ws.path(), &without).unwrap();
        assert!(written.inline.is_none());
        assert!(!ws.path().join("spec/boot/INLINE.md").exists());
    }

    // ----- the managed <vibevm> block (PROP-012) -----

    #[test]
    fn locate_block_absent_when_no_markers() {
        assert_eq!(
            locate_block("# just a file\n\nno markers here"),
            BlockLocation::Absent
        );
        assert_eq!(locate_block(""), BlockLocation::Absent);
    }

    #[test]
    #[verifies("spec://vibevm/modules/vibe-workspace/PROP-012#markers", r = 1)]
    fn locate_block_well_formed_pair() {
        let content = "before\n<vibevm>\nbody\n</vibevm>\nafter\n";
        match locate_block(content) {
            BlockLocation::Present { start, end } => {
                assert_eq!(&content[start..end], "<vibevm>\nbody\n</vibevm>\n");
            }
            other => panic!("expected Present, got {other:?}"),
        }
    }

    #[test]
    #[verifies("spec://vibevm/modules/vibe-workspace/PROP-012#markers", r = 1)]
    fn locate_block_two_openers_is_malformed() {
        let content = "<vibevm>\na\n</vibevm>\n<vibevm>\nb\n</vibevm>\n";
        assert!(matches!(locate_block(content), BlockLocation::Malformed(_)));
    }

    #[test]
    fn locate_block_unbalanced_is_malformed() {
        assert!(matches!(
            locate_block("<vibevm>\nbody\n"),
            BlockLocation::Malformed(_)
        ));
        assert!(matches!(
            locate_block("body\n</vibevm>\n"),
            BlockLocation::Malformed(_)
        ));
    }

    #[test]
    fn locate_block_close_before_open_is_malformed() {
        assert!(matches!(
            locate_block("</vibevm>\nbody\n<vibevm>\n"),
            BlockLocation::Malformed(_)
        ));
    }

    #[test]
    fn write_managed_block_creates_a_missing_file() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("CLAUDE.md");
        let written = write_managed_block(&path).unwrap();
        assert_eq!(written.as_deref(), Some(path.as_path()));
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("<vibevm>\n"));
        assert!(content.trim_end().ends_with("</vibevm>"));
        assert!(content.contains("spec/boot/INDEX.md"));
    }

    #[test]
    #[verifies("spec://vibevm/modules/vibe-workspace/PROP-012#create", r = 1)]
    fn write_managed_block_appends_preserving_co_tenant_content() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("CLAUDE.md");
        fs::write(&path, "# My own instructions\n\nKeep me.\n").unwrap();
        write_managed_block(&path).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        // The hand-authored content is preserved verbatim, ahead of the block.
        assert!(content.starts_with("# My own instructions\n\nKeep me.\n"));
        assert!(content.contains("<vibevm>") && content.contains("</vibevm>"));
        assert!(matches!(
            locate_block(&content),
            BlockLocation::Present { .. }
        ));
    }

    #[test]
    #[verifies("spec://vibevm/modules/vibe-workspace/PROP-012#create", r = 1)]
    fn write_managed_block_splices_in_place_preserving_surroundings() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("CLAUDE.md");
        fs::write(
            &path,
            "TOP — mine\n\n<vibevm>\nstale body\n</vibevm>\n\nBOTTOM — mine\n",
        )
        .unwrap();
        write_managed_block(&path).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        assert!(content.starts_with("TOP — mine\n\n"));
        assert!(content.trim_end().ends_with("BOTTOM — mine"));
        assert!(!content.contains("stale body"));
        assert!(content.contains("# Session boot"));
    }

    #[test]
    fn write_managed_block_migrates_the_old_whole_file_redirect() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("CLAUDE.md");
        // A file that is wholly the pre-PROP-012 generated redirect.
        fs::write(
            &path,
            format!("{OLD_GENERATED_HEADER}\n\n# Session boot\n\nold body\n"),
        )
        .unwrap();
        write_managed_block(&path).unwrap();
        let content = fs::read_to_string(&path).unwrap();
        // Reclaimed wholesale as a block — no leftover old body.
        assert!(content.starts_with("<vibevm>\n"));
        assert!(!content.contains("old body"));
        assert!(matches!(
            locate_block(&content),
            BlockLocation::Present { .. }
        ));
    }

    #[test]
    fn write_managed_block_is_a_noop_when_block_is_identical() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("CLAUDE.md");
        write_managed_block(&path).unwrap();
        // A second write finds a byte-identical block — nothing to do.
        assert!(write_managed_block(&path).unwrap().is_none());
    }

    #[test]
    fn write_managed_block_errors_on_a_malformed_block() {
        let dir = TempDir::new().unwrap();
        let path = dir.path().join("CLAUDE.md");
        fs::write(&path, "<vibevm>\na\n</vibevm>\n<vibevm>\nb\n</vibevm>\n").unwrap();
        let err = write_managed_block(&path).unwrap_err();
        assert!(
            matches!(err, WorkspaceError::MalformedRedirectBlock { .. }),
            "{err}"
        );
    }
}
