//! Whole-driver evidence that ordering composes with later domain binding.

use anyhow::Result;
use serde_json::json;

use crate::codegen::postproc::{StrictnessSource, rewrite_generated};
use crate::codegen::strictness::Strictness;
use crate::repo_root;

#[test]
fn ordering_survives_domain_struct_and_field_binding_and_import_cleanup() -> Result<()> {
    let temp = tempfile::tempdir()?;
    let generated = temp.path().join("mod.rs");
    let emitted = r#"// Code generated by jtd-codegen for Rust v0.2.1

use chrono::{DateTime, FixedOffset};
use serde::{Deserialize, Serialize};

pub type Timestamp = DateTime<FixedOffset>;

@DERIVE@
pub struct Holder {
    #[serde(rename = "label")]
    pub label: String,

    #[serde(rename = "row")]
    pub row: OrderedRow,
}

@DERIVE@
pub struct OrderedRow {
    #[serde(rename = "alpha")]
    pub alpha: String,

    #[serde(rename = "at")]
    pub at: Timestamp,

    #[serde(rename = "zeta")]
    pub zeta: String,
}
"#
    .replace("@DERIVE@", concat!("#", "[derive(Serialize, Deserialize)]"));
    assert_eq!(
        emitted
            .matches(concat!("#", "[derive(Serialize, Deserialize)]"))
            .count(),
        2,
        "the reconstructed fixture bytes retain both pinned derive lines"
    );
    assert!(!emitted.contains("@DERIVE@"));
    std::fs::write(&generated, emitted)?;
    let resolved = temp.path().join("holder.jtd.json");
    std::fs::write(
        &resolved,
        serde_json::to_vec_pretty(&json!({
            "metadata": {
                "x-wire-order": ["row", "label"],
                "x-rust-type": "Envelope"
            },
            "definitions": {
                "timestamp": {
                    "type": "timestamp",
                    "metadata": {"x-rust-type": "chrono::DateTime<chrono::Utc>"}
                },
                "ordered_row": {
                    "metadata": {
                        "x-wire-order": ["zeta", "at", "alpha"],
                        "x-rust-type": "DomainRow"
                    },
                    "properties": {
                        "alpha": {"type": "string"},
                        "at": {"ref": "timestamp"},
                        "zeta": {"type": "string"}
                    }
                }
            },
            "properties": {
                "label": {"type": "string"},
                "row": {"ref": "ordered_row"}
            }
        }))?,
    )?;
    let root = repo_root()?;
    let strictness = Strictness::load(&root)?;
    let authored = root.join("schemas/index/e1/by_purl.jtd.json");
    rewrite_generated(
        &generated,
        &resolved,
        &authored,
        StrictnessSource::Registry {
            registry: &strictness,
            projections: &[],
        },
    )?;
    let out = std::fs::read_to_string(&generated)?;

    let envelope = out.find("pub struct Envelope {").unwrap();
    let row_field = out[envelope..].find("pub row: DomainRow,").unwrap();
    let label_field = out[envelope..].find("pub label: String,").unwrap();
    assert!(
        row_field < label_field,
        "root wire order survives rename: {out}"
    );

    let row = out.find("pub struct DomainRow {").unwrap();
    let zeta = out[row..].find("pub zeta: String,").unwrap();
    let at = out[row..].find("pub at: Timestamp,").unwrap();
    let alpha = out[row..].find("pub alpha: String,").unwrap();
    assert!(
        zeta < at && at < alpha,
        "definition order survives rename: {out}"
    );
    assert!(out.contains("pub type Timestamp = chrono::DateTime<chrono::Utc>;"));
    assert!(!out.contains("use chrono::{DateTime, FixedOffset};"));
    assert!(!out.contains("OrderedRow"));
    Ok(())
}
