//! `discipline-typescript init` — bootstrap the six discipline
//! artifacts in their TypeScript shape (the `discipline-rust init`
//! twin): conform.toml with a `[typescript]` table, specmap.toml with
//! the discovered `[[external_specs]]`, both ratchet baselines, and
//! the two BROWNFIELD registries. Everything is written once (never
//! overwriting an owned policy) and round-tripped through the parsing
//! engines in this module's own test.

use std::path::{Path, PathBuf};

use anyhow::{Context, Result};

pub struct InitOptions {
    /// The spec:// namespace; defaults to the root directory's name.
    pub namespace: Option<String>,
    /// Overwrite existing artifacts (topology re-derivation).
    pub force: bool,
}

struct ExternalSpec {
    namespace: String,
    root: String,
}

/// Installed packages' spec trees under `vibedeps/`, for
/// `[[external_specs]]` resolution — same discovery walk as the Rust
/// init (slot layout: `vibedeps/<slot>/<version>/{vibe.toml,spec/}`).
fn discover_external_specs(root: &Path) -> Vec<ExternalSpec> {
    let mut out = Vec::new();
    let vibedeps = root.join("vibedeps");
    let Ok(slots) = std::fs::read_dir(&vibedeps) else {
        return out;
    };
    let mut slot_dirs: Vec<PathBuf> = slots
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.is_dir())
        .collect();
    slot_dirs.sort();
    for slot in slot_dirs {
        let Ok(versions) = std::fs::read_dir(&slot) else {
            continue;
        };
        let mut version_dirs: Vec<PathBuf> = versions
            .filter_map(Result::ok)
            .map(|e| e.path())
            .filter(|p| p.is_dir())
            .collect();
        version_dirs.sort();
        for vdir in version_dirs {
            if !vdir.join("spec").is_dir() {
                continue;
            }
            let Ok(manifest) = std::fs::read_to_string(vdir.join("vibe.toml")) else {
                continue;
            };
            let Ok(table) = manifest.parse::<toml::Table>() else {
                continue;
            };
            let Some(name) = table
                .get("package")
                .and_then(|p| p.get("name"))
                .and_then(|n| n.as_str())
            else {
                continue;
            };
            let rel = vdir.join("spec");
            let rel = rel.strip_prefix(root).unwrap_or(&rel);
            out.push(ExternalSpec {
                namespace: name.to_string(),
                root: rel.to_string_lossy().replace('\\', "/"),
            });
        }
    }
    out
}

fn write_once(path: &Path, body: &str, force: bool) -> Result<bool> {
    if path.exists() && !force {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)
            .with_context(|| format!("creating {}", parent.display()))?;
    }
    std::fs::write(path, body).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}

fn report(wrote: bool, rel: &str) {
    if wrote {
        eprintln!("  wrote {rel}");
    } else {
        eprintln!("  kept  {rel} (exists; --force overwrites)");
    }
}

pub fn run_init(root: &Path, opts: &InitOptions) -> Result<()> {
    let namespace = match &opts.namespace {
        Some(ns) => ns.clone(),
        None => root
            .canonicalize()
            .ok()
            .and_then(|p| p.file_name().map(|n| n.to_string_lossy().into_owned()))
            .unwrap_or_else(|| "project".to_string()),
    };
    let has_cells = root.join("src").join("cells").is_dir();
    let cells_line = if has_cells {
        "cells_dir = \"src/cells\"\n"
    } else {
        "# cells_dir = \"src/cells\"   # uncomment when the cell layout lands\n"
    };

    let conform = format!(
        "# conform.toml — this project's AI-Native discipline policy\n\
         # (ENGINE-CONFORM; generated by `discipline-typescript init`, then owned by you).\n\
         #\n\
         # The [typescript] table drives the ts-tsc structural gate\n\
         # (`conform-typescript`): the §8 unsafe-set ban, cell isolation over\n\
         # import specifiers, and the file-length budget. Rust-side keys stay\n\
         # at their defaults until Rust code joins the tree.\n\
         \n\
         roots = []\n\
         max_file_lines = 600\n\
         \n\
         [typescript]\n\
         roots = [\"src\"]\n\
         exclude_substrings = [\"/fixtures/\"]\n\
         {cells_line}\
         seam = \"index\"\n"
    );

    let externals = discover_external_specs(root);
    let mut specmap = format!(
        "# specmap.toml — this project's traceability policy\n\
         # (PROP-014; generated by `discipline-typescript init`, then owned by you).\n\
         \n\
         # The spec:// namespace this project's units are minted under.\n\
         namespace = \"{namespace}\"\n\
         \n\
         scan_roots = [\"src\"]\n\
         spec_roots = [\"spec\"]\n\
         root_spec_docs = []\n\
         exempt = []\n\
         dispositioned = []\n"
    );
    if externals.is_empty() {
        specmap.push_str(
            "\n# No installed packages with spec trees were found under vibedeps/.\n\
             # After `vibe install`, re-run `discipline-typescript init --force` (or add\n\
             # [[external_specs]] entries by hand) so cross-package citations resolve.\n",
        );
    } else {
        specmap.push_str(
            "\n# Installed packages' spec trees, read for URI RESOLUTION only\n\
             # (PROP-014 §7.1) — discovered from vibedeps/ at init time.\n",
        );
        for e in &externals {
            specmap.push_str(&format!(
                "[[external_specs]]\nnamespace = \"{}\"\nroot = \"{}\"\n\n",
                e.namespace, e.root
            ));
        }
    }

    let tests_baseline = "{ \"schema\": 1, \"entries\": [] }\n";
    let debt = "{ \"schema\": 1, \"entries\": [] }\n";
    let intent = "{ \"schema\": 1, \"entries\": [] }\n";
    let conform_baseline = "{\"schema\":1,\"findings\":[]}\n";

    eprintln!("discipline-typescript init: namespace `{namespace}`");
    report(
        write_once(&root.join("conform.toml"), &conform, opts.force)?,
        "conform.toml",
    );
    report(
        write_once(&root.join("specmap.toml"), &specmap, opts.force)?,
        "specmap.toml",
    );
    report(
        write_once(
            &root.join(conform_cli_typescript::DEFAULT_TS_BASELINE),
            conform_baseline,
            opts.force,
        )?,
        conform_cli_typescript::DEFAULT_TS_BASELINE,
    );
    report(
        write_once(
            &root.join(crate::DEFAULT_TESTS_BASELINE),
            tests_baseline,
            opts.force,
        )?,
        crate::DEFAULT_TESTS_BASELINE,
    );
    report(
        write_once(&root.join(crate::DEFAULT_DEBT_REGISTRY), debt, opts.force)?,
        crate::DEFAULT_DEBT_REGISTRY,
    );
    report(
        write_once(
            &root.join(crate::DEFAULT_INTENT_REGISTRY),
            intent,
            opts.force,
        )?,
        crate::DEFAULT_INTENT_REGISTRY,
    );

    eprintln!(
        "discipline-typescript init: done. Next steps:\n\
         \x20 1. `npm install -D typescript prettier eslint typescript-eslint` — the floor's\n\
         \x20    toolchain (tsc also feeds the ts-tsc structural gate)\n\
         \x20 2. write your first spec unit (spec/PROP-001.md with a {{#req-…}} anchor) and\n\
         \x20    tag the implementing export: /** @implements spec://{namespace}/PROP-001#req-… */\n\
         \x20 3. `discipline-typescript specmap` to mint the index, then `discipline-typescript floor`\n\
         \x20 4. adopt cell by cell; the sweep skill walks the recurring routine\n\
         (layout changed since init? re-run with --force to regenerate the topology-derived files)"
    );
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generates_the_six_artifacts_round_tripping_through_the_engines() {
        let tmp = tempfile::tempdir().expect("tempdir");
        let root = tmp.path();
        std::fs::create_dir_all(root.join("src/cells")).expect("cells");
        std::fs::create_dir_all(root.join("vibedeps/flow-some-core/0.4.0/spec")).expect("slot");
        std::fs::write(
            root.join("vibedeps/flow-some-core/0.4.0/vibe.toml"),
            "[package]\nname = \"some-core\"\n",
        )
        .expect("slot manifest");

        run_init(
            root,
            &InitOptions {
                namespace: Some("demo".into()),
                force: false,
            },
        )
        .expect("init");

        // conform.toml parses into the engine's Config with the TS table.
        let conform: conform_core::Config =
            toml::from_str(&std::fs::read_to_string(root.join("conform.toml")).expect("conform"))
                .expect("conform parses");
        assert_eq!(conform.typescript.roots, vec!["src".to_string()]);
        assert_eq!(conform.typescript.cells_dir.as_deref(), Some("src/cells"));

        // specmap.toml parses and carries the discovered external root.
        let specmap = specmap_core::config::Config::load(root)
            .expect("load")
            .expect("present");
        assert_eq!(specmap.namespace, "demo");
        let policy = std::fs::read_to_string(root.join("specmap.toml")).expect("policy");
        assert!(policy.contains("root = \"vibedeps/flow-some-core/0.4.0/spec\""));

        // The registries parse through the engines that consume them.
        let baseline =
            std::fs::read_to_string(root.join(crate::DEFAULT_TESTS_BASELINE)).expect("baseline");
        assert!(
            specmap_core::testgate::parse_baseline(&baseline)
                .expect("baseline parses")
                .is_empty()
        );
        let debt = std::fs::read_to_string(root.join(crate::DEFAULT_DEBT_REGISTRY)).expect("debt");
        assert!(
            specmap_core::tripwire::evaluate(&debt, &["src/x.ts".into()])
                .expect("debt parses")
                .is_empty()
        );

        // Idempotent: a hand-edited policy is never clobbered.
        std::fs::write(root.join("conform.toml"), "# my edited policy\n").expect("edit");
        run_init(
            root,
            &InitOptions {
                namespace: Some("demo".into()),
                force: false,
            },
        )
        .expect("re-init");
        let kept = std::fs::read_to_string(root.join("conform.toml")).expect("kept");
        assert_eq!(kept, "# my edited policy\n");
    }
}
