schema = 1
source_hash = "sha256:f64be9e70d1663f9744b3a9845050dcf1109d1d178912b98fe6b56fb1b46b721"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:2e3026aa40e2e21771500e3fddcc4c1ee4b220ecb406189572bb31328dc0c746"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"
