//! Unit tests for the ordered-maps pass — one per behaviour the pass
//! owes its callers: the import-plus-usages rewrite, the comment
//! pass-through, the file-wide no-map pass-through, the idempotency
//! that keeps `check-codegen` stable, and the loud refusals that keep a
//! moved generator pin from being absorbed silently. The samples quote
//! the pinned emission shape of jtd-codegen verbatim — the pass exists
//! to be exact about that shape, so the tests must be exact about it
//! too.

use super::ordered_maps;
use anyhow::Result;

/// The `features_entry` fragment as the snake_case pass leaves it (a
/// doc comment may say `HashMap` as a word — the last line of the doc
/// run is synthetic to pin that rule; the code lines are quoted
/// verbatim from the generated tree).
const FEATURES_ENTRY: &str = r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Feature table: feature names map to activation lists; `exclusive` is the at-
/// most-one-of named-group table. The word `HashMap` may appear in a comment.
#[derive(Serialize, Deserialize)]
pub struct FeaturesEntry {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclusive: Option<Box<HashMap<String, Vec<String>>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<HashMap<String, Vec<String>>>>,
}
"#;

/// The import line and every `HashMap<` in code lines rewrite together,
/// and nothing else so much as breathes: doc comments (even one saying
/// `HashMap` as a word), attributes, layout, line endings stay byte for
/// byte — or `check-codegen` would report drift that isn't ours.
#[test]
fn the_import_and_every_usage_rewrite_together() -> Result<()> {
    let out = ordered_maps(FEATURES_ENTRY, "journal/mod.rs")?;
    assert_eq!(
        out,
        r#"// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Feature table: feature names map to activation lists; `exclusive` is the at-
/// most-one-of named-group table. The word `HashMap` may appear in a comment.
#[derive(Serialize, Deserialize)]
pub struct FeaturesEntry {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub exclusive: Option<Box<BTreeMap<String, Vec<String>>>>,

    #[serde(skip_serializing_if = "Option::is_none")]
    pub features: Option<Box<BTreeMap<String, Vec<String>>>>,
}
"#
    );
    Ok(())
}

/// Two maps on one line both rewrite — the pass counts occurrences, not
/// lines, so a `HashMap<String, HashMap<String, String>>` (a shape the
/// `files`-style maps could grow into) leaves no half-rewritten type
/// behind.
#[test]
fn every_occurrence_on_one_line_rewrites() -> Result<()> {
    let src =
        "use std::collections::HashMap;\npub nested: HashMap<String, HashMap<String, String>>,\n";
    let out = ordered_maps(src, "nested/mod.rs")?;
    assert_eq!(
        out,
        "use std::collections::BTreeMap;\npub nested: BTreeMap<String, BTreeMap<String, String>>,\n"
    );
    Ok(())
}

/// A file with no map at all is the identity, byte for byte — most
/// generated files carry no `values` form, and the pass must not so
/// much as reorder their whitespace.
#[test]
fn a_file_without_maps_passes_through() -> Result<()> {
    let src = "// Code generated by jtd-codegen for Rust v0.2.1

use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize)]
pub struct RegistryPublishReport {
    pub schema_version: u32,
}
";
    assert_eq!(ordered_maps(src, "registry_publish_report/mod.rs")?, src);
    Ok(())
}

/// The second run over the pass's own output is the identity — the
/// import and the usages rewrote together, so no `HashMap` is left to
/// see and no mismatch can fire. This is what keeps `check-codegen`
/// from blinking on a file a `codegen` run just wrote.
#[test]
fn the_pass_is_idempotent() -> Result<()> {
    let once = ordered_maps(FEATURES_ENTRY, "journal/mod.rs")?;
    let twice = ordered_maps(&once, "journal/mod.rs")?;
    assert_eq!(once, twice);
    Ok(())
}

/// A `HashMap` word in a code line that `<` does not immediately follow
/// refuses loudly: the message names the file, the line, quotes the
/// offending line verbatim, and carries the recipe. The generator's
/// emission shape is pinned; a word in a new position means the pin
/// moved, and the one unacceptable answer is a silent partial rewrite.
#[test]
fn a_stray_hash_map_word_refuses() {
    let src = "use std::collections::HashMap;\n    let seen = HashMap::new();\n";
    let err = ordered_maps(src, "odd/mod.rs")
        .expect_err("a bare `HashMap::new()` call is not the pinned shape");
    let msg = err.to_string();
    assert!(msg.contains("odd/mod.rs:2"), "names file and line: {msg}");
    assert!(
        msg.contains("HashMap::new()"),
        "quotes the offending line: {msg}"
    );
    assert!(
        msg.contains("ordered_maps.rs") && msg.contains("cargo xtask codegen"),
        "says what to do: {msg}"
    );
}

/// Usages without the import refuse: the pinned generator emits the
/// import with the first map type, so a usage the import cannot explain
/// is a moved pin, not a type to rewrite half-blind.
#[test]
fn usages_without_the_import_refuse() {
    let src = "pub files: HashMap<String, RepomdFileEntry>,\n";
    let err = ordered_maps(src, "odd/mod.rs")
        .expect_err("`HashMap<` with no import line is not the pinned shape");
    let msg = err.to_string();
    assert!(
        msg.contains("odd/mod.rs") && msg.contains("no") && msg.contains("import"),
        "names the file and the missing half: {msg}"
    );
    assert!(
        msg.contains("cargo xtask codegen"),
        "says what to do: {msg}"
    );
}

/// The import without usages refuses too — the mirror contract. An
/// orphaned import is just as much a moved pin, and rewriting it while
/// leaving nothing behind would hide the drift behind a clean diff.
#[test]
fn the_import_without_usages_refuses() {
    let src = "use std::collections::HashMap;\npub entries: u32,\n";
    let err = ordered_maps(src, "odd/mod.rs")
        .expect_err("an import with no map usage is not the pinned shape");
    let msg = err.to_string();
    assert!(
        msg.contains("odd/mod.rs") && msg.contains("never writes"),
        "names the file and the orphaned half: {msg}"
    );
    assert!(
        msg.contains("cargo xtask codegen"),
        "says what to do: {msg}"
    );
}
