//! Differential wire-parity oracles for the two inverted-index schemas
//! (`schemas/index/e1/by_cap.jtd.json` →
//! `vibe_wire::generated::index::e1::by_cap`,
//! `schemas/index/e1/by_purl.jtd.json` →
//! `vibe_wire::generated::index::e1::by_purl`).
//!
//! Both files are neighbours in code (`index/inverted.rs`) and in
//! meaning — one line of `by-cap/<slug>.jsonl`, one line of
//! `by-purl/<slug>.jsonl` — so their oracles live together. The law is
//! the entry oracle's: the hand-written row and the JTD-generated one
//! differ as Rust types by design (`Group` / `semver::Version` /
//! `BindingSite` against `String` / `String` / a generated enum), but
//! the **wire** must not differ. Both rows are all-required, flat and
//! short, which is exactly why they need the guard: five or six obvious
//! fields invite transcription from memory, and a remembered field is a
//! misremembered field.

use semver::Version;

use vibe_index::index::inverted::{BindingSite, CapabilityRow, PurlRow};
use vibe_index::types::{Group, PackageKind};
use vibe_wire::generated::index::e1::by_cap::ByCap;
use vibe_wire::generated::index::e1::by_purl::ByPurl;

/// Every key a row puts on the wire — both schemas are all-required, so
/// this is also the exhaustive field census of the row. Declared as a
/// constant so a fixture that lost a field fails the count assert before
/// the round-trip can quietly pass.
const CAPABILITY_ROW_KEY_COUNT: usize = 5;
const PURL_ROW_KEY_COUNT: usize = 6;

fn fully_populated_capability_row() -> CapabilityRow {
    CapabilityRow {
        kind: PackageKind::Feat,
        group: Group::parse("org.vibevm").expect("group parses"),
        name: "welcome".to_string(),
        version: Version::parse("0.3.0").expect("version parses"),
        capability: "ui:landing-page@0.3.0".to_string(),
    }
}

fn fully_populated_purl_row() -> PurlRow {
    PurlRow {
        kind: PackageKind::Flow,
        group: Group::parse("org.vibevm").expect("group parses"),
        name: "sqlx-skin".to_string(),
        version: Version::parse("0.1.0").expect("version parses"),
        purl: "pkg:cargo/sqlx@0.8.0".to_string(),
        binding_site: BindingSite::Subskill,
    }
}

#[test]
fn capability_row_round_trips_through_the_generated_type() {
    let handwritten = fully_populated_capability_row();

    let j1 = serde_json::to_value(&handwritten).expect("the hand-written type serialises");
    assert_eq!(
        j1.as_object().map(|object| object.len()),
        Some(CAPABILITY_ROW_KEY_COUNT),
        "the fixture must exercise every field of the row"
    );

    let generated: ByCap =
        serde_json::from_value(j1.clone()).expect("the generated type parses the writer's output");
    let j2 = serde_json::to_value(&generated).expect("the generated type serialises");
    assert_eq!(
        j1, j2,
        "wire drift between the hand-written and the generated by-cap row — a \
         field the schema misses is silently dropped by the permissive reader"
    );
}

#[test]
fn purl_row_round_trips_through_the_generated_type() {
    let handwritten = fully_populated_purl_row();

    let j1 = serde_json::to_value(&handwritten).expect("the hand-written type serialises");
    assert_eq!(
        j1.as_object().map(|object| object.len()),
        Some(PURL_ROW_KEY_COUNT),
        "the fixture must exercise every field of the row"
    );
    // The writer's binding-site spelling is on the wire: `kebab-case`
    // over single-word variants, i.e. `subskill` here.
    assert_eq!(
        j1["binding_site"].as_str(),
        Some("subskill"),
        "the fixture must pin the binding-site wire string the writer emits"
    );

    let generated: ByPurl =
        serde_json::from_value(j1.clone()).expect("the generated type parses the writer's output");
    let j2 = serde_json::to_value(&generated).expect("the generated type serialises");
    assert_eq!(
        j1, j2,
        "wire drift between the hand-written and the generated by-purl row — a \
         field the schema misses is silently dropped by the permissive reader"
    );
}
