schema = 1
source_hash = "sha256:f8141eefd8e3eb76bff982065b66467cff5b7f306c8d600ba47275937153e901"
output_format = "xml"
converter_recipe = "specdoc/4"
derived_hash = "sha256:3b34d850b22c8140f84d0960dc2049f60505ee4eecbbb6a7136e0c46e2b58e0e"

[[file]]
source = "LICENSE.md"
output = "LICENSE.md"
disposition = "copied"

[[file]]
source = "README.md"
output = "README.xml"
disposition = "converted"

[[file]]
source = "vibe.toml"
output = "vibe.toml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/boot/45-flow-operating-modes.xml"
output = "vibevm/vibespecs/boot/45-flow-operating-modes.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
output = "vibevm/vibespecs/flows/operating-modes/OPERATING-MODES-PROTOCOL.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/operating-modes/mfbt-mode.xml"
output = "vibevm/vibespecs/flows/operating-modes/mfbt-mode.xml"
disposition = "copied"

[[file]]
source = "vibevm/vibespecs/flows/operating-modes/writing-a-codeword.xml"
output = "vibevm/vibespecs/flows/operating-modes/writing-a-codeword.xml"
disposition = "copied"
